// Validates translation files and writes them into the app and shared code.
//   npx tsx scripts/translations/importTranslations.ts <dir with <code>.json files> "<translator, e.g. Claude Sonnet 5.5>" [--check]
// Each <code>.json mirrors the file written by exportSource.ts. With --check nothing is written.
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { DEFAULT_LANGUAGE, LANGUAGES, isLanguageCode, type LanguageCode } from "../../shared/src/languages.ts";
import { SOURCE_TEXT } from "./sourceText.ts";
import { lineCount, validateTranslation, type ValidationResult } from "./validateTranslation.ts";

const SHARED_LOCALES = "shared/src/locales";
const MOBILE_LOCALES = "mobile/src/i18n/locales";
const HAND_WRITTEN: LanguageCode[] = [DEFAULT_LANGUAGE, "sw"];
const MAX_REJECTED_SHARE = 0.1;

const [dir, translator, flag] = process.argv.slice(2);
if (!dir || !translator) throw new Error('Usage: importTranslations.ts <dir> "<translator>" [--check]');
const checkOnly = flag === "--check";

function header(translatorName: string): string {
  const date = new Date().toISOString().slice(0, 10);
  return `// Machine translation by ${translatorName}, ${date}. No native speaker has checked it yet.\n// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.\n`;
}

const identifier = (code: string) => `${code}Text`;

function writeSharedModule(code: LanguageCode, advice: unknown, headerText: string) {
  const body = JSON.stringify(advice, null, 2);
  const source = `${headerText}import type { AdviceTranslation } from "../adviceText.ts";\n\nconst ${identifier(code)} = (): AdviceTranslation => (${body});\n\nexport default ${identifier(code)};\n`;
  writeFileSync(join(SHARED_LOCALES, `${code}.ts`), source);
}

function writeMobileModule(code: LanguageCode, ui: unknown, headerText: string) {
  const body = JSON.stringify(ui, null, 2);
  const source = `${headerText}import type { UiTranslation } from '../strings.ts';\n\nconst ${identifier(code)} = (): UiTranslation => (${body});\n\nexport default ${identifier(code)};\n`;
  writeFileSync(join(MOBILE_LOCALES, `${code}.ts`), source);
}

function presentCodes(directory: string): LanguageCode[] {
  return LANGUAGES.map(({ code }) => code).filter((code) => existsSync(join(directory, `${code}.ts`)));
}

function writeIndex(directory: string, typeImport: string, constName: string, typeName: string, quote: string) {
  const codes = presentCodes(directory);
  const imports = codes.map((code) => `import ${identifier(code)} from ${quote}./${code}.ts${quote};`).join("\n");
  const entries = codes.map((code) => `  ${code}: ${identifier(code)},`).join("\n");
  const languageImport = `import type { LanguageCode } from ${quote}${directory.startsWith("mobile") ? "../../../../shared/src/languages.ts" : "../languages.ts"}${quote};`;
  const source = `// Generated by scripts/translations/importTranslations.ts. Do not edit by hand.\n${languageImport}\n${typeImport}\n${imports}\n\nexport const ${constName}: Partial<Record<LanguageCode, () => ${typeName}>> = {\n${entries}\n};\n`;
  writeFileSync(join(directory, "index.ts"), source);
}

function report(code: string, result: ValidationResult): boolean {
  const total = lineCount(SOURCE_TEXT);
  const acceptable = result.untranslatedLines / total <= MAX_REJECTED_SHARE;
  const status = acceptable ? "ok" : "REFUSED";
  console.log(`${code}: ${status}, ${result.untranslatedLines} of ${total} lines stay English (${result.rejections.length} rejected, ${result.missing.length} missing)`);
  for (const rejection of result.rejections) console.log(`  ${rejection.path}: ${rejection.reason}`);
  if (result.missing.length) console.log(`  missing: ${result.missing.join(", ")}`);
  return acceptable;
}

function importOne(file: string, headerText: string): boolean {
  const code = file.replace(/\.json$/, "");
  if (!isLanguageCode(code) || HAND_WRITTEN.includes(code)) {
    console.log(`${file}: skipped, not a machine-translated language`);
    return false;
  }
  const result = validateTranslation(SOURCE_TEXT, JSON.parse(readFileSync(join(dir, file), "utf8")));
  if (!report(code, result) || checkOnly) return false;
  const kept = result.kept as { ui?: unknown; advice?: unknown };
  writeMobileModule(code, kept.ui ?? {}, headerText);
  writeSharedModule(code, kept.advice ?? {}, headerText);
  return true;
}

const headerText = header(translator);
const files = readdirSync(dir).filter((file) => file.endsWith(".json") && file !== "source.en.json");
const imported = files.filter((file) => importOne(file, headerText)).length;

if (!checkOnly) {
  writeIndex(SHARED_LOCALES, 'import type { AdviceTranslation } from "../adviceText.ts";', "ADVICE_TRANSLATIONS", "AdviceTranslation", '"');
  writeIndex(MOBILE_LOCALES, "import type { UiTranslation } from '../strings.ts';", "UI_TRANSLATIONS", "UiTranslation", "'");
}
console.log(`${checkOnly ? "Checked" : "Imported"} ${checkOnly ? files.length : imported} of ${files.length} files.`);
