// Generated by scripts/translations/importTranslations.ts. Do not edit by hand.
import type { LanguageCode } from '../../../../shared/src/languages.ts';
import type { UiTranslation } from '../strings.ts';
import afText from './af.ts';
import amText from './am.ts';
import arText from './ar.ts';
import hyText from './hy.ts';
import asText from './as.ts';
import astText from './ast.ts';
import azText from './az.ts';
import beText from './be.ts';
import bnText from './bn.ts';
import bsText from './bs.ts';
import bgText from './bg.ts';
import myText from './my.ts';
import yueText from './yue.ts';
import caText from './ca.ts';
import cebText from './ceb.ts';
import hrText from './hr.ts';
import csText from './cs.ts';
import daText from './da.ts';
import nlText from './nl.ts';
import etText from './et.ts';
import filText from './fil.ts';
import fiText from './fi.ts';
import frText from './fr.ts';
import glText from './gl.ts';
import kaText from './ka.ts';
import deText from './de.ts';
import elText from './el.ts';
import guText from './gu.ts';
import haText from './ha.ts';
import heText from './he.ts';
import hiText from './hi.ts';
import huText from './hu.ts';
import isText from './is.ts';
import idText from './id.ts';
import itText from './it.ts';
import jaText from './ja.ts';
import jvText from './jv.ts';
import knText from './kn.ts';
import kkText from './kk.ts';
import koText from './ko.ts';
import kyText from './ky.ts';
import loText from './lo.ts';
import lvText from './lv.ts';
import lnText from './ln.ts';
import ltText from './lt.ts';
import lgText from './lg.ts';
import lbText from './lb.ts';
import mkText from './mk.ts';
import msText from './ms.ts';
import mlText from './ml.ts';
import mtText from './mt.ts';
import zhText from './zh.ts';
import miText from './mi.ts';
import mrText from './mr.ts';
import mnText from './mn.ts';
import neText from './ne.ts';
import nbText from './nb.ts';
import ocText from './oc.ts';
import orText from './or.ts';
import psText from './ps.ts';
import faText from './fa.ts';
import plText from './pl.ts';
import ptText from './pt.ts';
import paText from './pa.ts';
import roText from './ro.ts';
import ruText from './ru.ts';
import srText from './sr.ts';
import snText from './sn.ts';
import sdText from './sd.ts';
import skText from './sk.ts';
import slText from './sl.ts';
import soText from './so.ts';
import ckbText from './ckb.ts';
import esText from './es.ts';
import svText from './sv.ts';
import tgText from './tg.ts';
import taText from './ta.ts';
import teText from './te.ts';
import thText from './th.ts';
import trText from './tr.ts';
import ukText from './uk.ts';
import urText from './ur.ts';
import uzText from './uz.ts';
import viText from './vi.ts';
import cyText from './cy.ts';
import woText from './wo.ts';
import zuText from './zu.ts';
import rwText from './rw.ts';
import rnText from './rn.ts';
import omText from './om.ts';
import tiText from './ti.ts';
import mgText from './mg.ts';
import tetText from './tet.ts';
import htText from './ht.ts';
import quText from './qu.ts';

export const UI_TRANSLATIONS: Partial<Record<LanguageCode, () => UiTranslation>> = {
  af: afText,
  am: amText,
  ar: arText,
  hy: hyText,
  as: asText,
  ast: astText,
  az: azText,
  be: beText,
  bn: bnText,
  bs: bsText,
  bg: bgText,
  my: myText,
  yue: yueText,
  ca: caText,
  ceb: cebText,
  hr: hrText,
  cs: csText,
  da: daText,
  nl: nlText,
  et: etText,
  fil: filText,
  fi: fiText,
  fr: frText,
  gl: glText,
  ka: kaText,
  de: deText,
  el: elText,
  gu: guText,
  ha: haText,
  he: heText,
  hi: hiText,
  hu: huText,
  is: isText,
  id: idText,
  it: itText,
  ja: jaText,
  jv: jvText,
  kn: knText,
  kk: kkText,
  ko: koText,
  ky: kyText,
  lo: loText,
  lv: lvText,
  ln: lnText,
  lt: ltText,
  lg: lgText,
  lb: lbText,
  mk: mkText,
  ms: msText,
  ml: mlText,
  mt: mtText,
  zh: zhText,
  mi: miText,
  mr: mrText,
  mn: mnText,
  ne: neText,
  nb: nbText,
  oc: ocText,
  or: orText,
  ps: psText,
  fa: faText,
  pl: plText,
  pt: ptText,
  pa: paText,
  ro: roText,
  ru: ruText,
  sr: srText,
  sn: snText,
  sd: sdText,
  sk: skText,
  sl: slText,
  so: soText,
  ckb: ckbText,
  es: esText,
  sv: svText,
  tg: tgText,
  ta: taText,
  te: teText,
  th: thText,
  tr: trText,
  uk: ukText,
  ur: urText,
  uz: uzText,
  vi: viText,
  cy: cyText,
  wo: woText,
  zu: zuText,
  rw: rwText,
  rn: rnText,
  om: omText,
  ti: tiText,
  mg: mgText,
  tet: tetText,
  ht: htText,
  qu: quText,
};
