// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const afText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Jou blare lyk gesond",
    "headlineSpray": "{name}: beskerm gesonde blare en maak skoon",
    "headlinePrune": "{name}: maak skoon en snoei",
    "headlineMonitor": "{name}: hou aan dopgehou",
    "headlineAskOfficer": "{name}: vra jou veldbeampte om te kyk",
    "headlineNotSure": "Die toep is nie seker nie. Wys hierdie blare vir jou veldbeampte",
    "headlineMightBe": "Dit kan {name} wees, maar dit is nie bevestig nie. Wys dit vir 'n veldbeampte",
    "headlineRetake": "Neem duideliker foto's van meer blare",
    "retakeDaylight": "Beweeg na daglig, nie diep skaduwee of direkte son nie.",
    "retakeSteady": "Hou die foon stil totdat die blaar skerp lyk.",
    "retakeFillFrame": "Vul die raam met een blaar.",
    "sendToOfficer": "Stuur hierdie geval per SMS aan jou koöperasie se veldbeampte, of wys die blare persoonlik.",
    "rainReason": "Dit het op {n} van die laaste 7 dae naby jou gereën ({source}). Nat weer laat roes vinniger versprei.",
    "labelRate": "Gebruik die dosis op die produketiket.",
    "elseBerryDisease": "Koffiebessiesiekte: kyk of die bessies donker ingesonke kolle het.",
    "elseBerryBorer": "Koffiebessieboorder: soek klein gaatjies in die bessies.",
    "elseWilt": "Koffiewelk: hele takke wat verwelk en doodgaan.",
    "elseNutrition": "Swak grond of voeding: vergeling oor die hele boom.",
    "smsDecisionSpray": "Besluit: beskerm gesonde blare met koper teen die etiketdosis en maak skoon. Kyk weer oor {days} dae.",
    "smsDecisionPrune": "Besluit: snoei en maak skoon. Kyk weer oor {days} dae.",
    "smsDecisionMonitor": "Besluit: hou aan dophou. Kyk weer oor {days} dae.",
    "smsDecisionCallOfficer": "Besluit: wys dit vir jou veldbeampte."
  },
  "diseases": {
    "cercospora": {
      "name": "Bruinoogvlek",
      "look": "Ronde bruin kolle, meestal bo-op die blaar, met 'n grys-wit middel en 'n donkerbruin ring, dikwels met 'n geel kring daarom. Kolle is 5 tot 15 mm breed en kan saamgroei tot groot dooie kolle. Bessies kry donker ingesonke vlekke en ryp te vroeg.",
      "tellApart": "Bruinoogvlek het droë bruin ringe met 'n bleek grys middel en geen oranje poeier nie, terwyl roes oranje poeier aan die onderkant het.",
      "actions": [
        "Voed die bome goed, veral stikstof en kalium. Goeie voeding beheer hierdie siekte dikwels.",
        "Hou ligte skaduwee, beheer onkruid en snoei sodat lug beweeg en blare droog word.",
        "Dra blare en bessies ná snoei weg of brand hulle. Moenie hulle teen die bome opstapel nie.",
        "In die kwekery, plant saailinge ver van mekaar en brand saailinge met bruin ringkolle.",
        "As dit erg is, kan 'n koperswamdoder gesonde blare beskerm. Vra eers jou voorligtingsbeampte."
      ],
      "urgencyReason": "Dit verswak hoofsaaklik bome onder druk en verbeter gewoonlik sodra voeding en skaduwee reggemaak is."
    },
    "healthy": {
      "name": "Gesonde koffieblaar",
      "look": "'n Gesonde blaar is blink, ovaal en puntig, egalig donkergroen, sonder kolle, poeier, gate of tonnels bo of onder.",
      "actions": [
        "Snoei en hou ligte skaduwee en onkruid laag sodat blare vinnig droog word.",
        "Voed bome met kompos of gebalanseerde kunsmis, veral stikstof en kalium.",
        "Kyk elke week of twee na blare en hul onderkante om roes of blaarmyner vroeg te vang."
      ]
    },
    "miner": {
      "name": "Koffieblaarmyner",
      "look": "Bleek geel kronkelende spore verskyn binne die blaar en word ongelyke bruin dooie kolle bo-op. As jy die blaar buig, skei die dun boonste vel oor die kol en jy kan 'n klein deurskynende maaiers binne vind. Erge aanvalle laat blare val.",
      "tellApart": "Mynerkolle is papierdun blase met 'n maaiers binne wat skei as hulle gebuig word, terwyl bruinoogvlek 'n netjiese ronde ring is wat nie skei nie.",
      "actions": [
        "Buig bruin kolle om na lewendige maaiers te soek, veral in die droë seisoen.",
        "Beskerm natuurlike vyande soos klein wespe en miere deur gemengde skaduwee te hou en onnodige spuit te vermy.",
        "Hou jong bome en kwekerye dop en verwyder die eerste kolle vroeg.",
        "As 'n insekdoder nodig is, vra jou voorligtingsbeampte watter produk wettig en veilig in jou land is."
      ],
      "urgencyReason": "Erge aanvalle laat blare val en verlaag die opbrengs, die ergste in droë warm tye."
    },
    "phoma": {
      "name": "Phoma-blaarvlek",
      "look": "Donkerbruin tot swart kolle tot 2 cm breed op ouer blare, met 'n ligter middel en donkerder rand. Die punte van jong lote word swart en droog uit, blomme kan doodgaan en bessies val af. Skade kan by die blaarpunt of rand begin.",
      "tellApart": "Phoma maak ook die punte van jong lote en blomme dood in koue, winderige hooglande, terwyl bruinoogvlek as ringkolle bly en nie lootpunte laat uitdroog nie.",
      "actions": [
        "Plant windskerms in winderige gebiede. Windskade laat die swam in.",
        "Snoei verdroogde lote en gemummifiseerde bessies af en vernietig hulle, en snoei sodat lug die blare kan droog maak.",
        "Voed die bome met gebalanseerde kunsmis, veral stikstof en kalium.",
        "In koue winderige seisoene, spuit 'n koperswamdoder voor die siekte verskyn. Vra jou voorligtingsbeampte oor die tydsberekening."
      ],
      "urgencyReason": "In koue winderige hooglande kan dit lote en blomme doodmaak en die opbrengs met 15 tot 43 persent verlaag."
    },
    "rust": {
      "name": "Koffieblaarroes",
      "look": "Klein bleek geel kolle wys bo-op die blaar. Aan die onderkant het elke kol 'n plek geel tot donkeroranje poeier wat aan jou vinger afvee. Ou kolle word bruin in die middel en die blare val vroeg af. Dit begin gewoonlik op die onderste blare van die boom.",
      "tellApart": "Roes het oranje poeier aan die onderkant van die blaar, terwyl bruinoogvlek droë bruin ringe met 'n grys-wit middel en geen poeier het nie.",
      "actions": [
        "Kyk gereeld na die onderkant van onderste blare. Om dit vroeg te vang is die belangrikste.",
        "Pluk blare en takke met oranje kolle af en brand of begrawe hulle.",
        "Snoei en maak skaduwee en onkruid dunner sodat lug beweeg en blare vinniger droog word.",
        "Voed die bome met kompos of gebalanseerde kunsmis. Swak bome word harder getref.",
        "Spuit 'n koperswamdoder soos koperhidroksied op die bo- en onderkante van blare terwyl minder as ongeveer 5 persent van die blare siek is. Koper beskerm gesonde blare maar genees nie siek blare nie. Vra jou voorligtingsbeampte oor die tydsberekening.",
        "Vir nuwe aanplanting, vra jou voorligtingsbeampte oor roesbestande variëteite soos Catimor- of Sarchimor-tipes."
      ],
      "urgencyReason": "Dit versprei vinnig tussen bome en plase, en verliese by vatbare variëteite kan 30 tot 80 persent bereik."
    },
    "mites": {
      "name": "Moontlike mytskade",
      "look": "Die beeld lyk soos koffieblare wat as mytskade benoem is. Soortgelyke merke kan ander oorsake hê, so dit is 'n moontlike ooreenkoms.",
      "actions": [
        "Vra 'n voorligtingsbeampte om albei kante van die blaar te ondersoek en die oorsaak te bevestig voordat jy 'n behandeling kies."
      ]
    },
    "weevil": {
      "name": "Moontlike skade deur blaarkouende plaag",
      "look": "Die blaar lyk soos beelde wat as coco- of kalanderskade benoem is. Hierdie foto kan nie die insekspesie identifiseer nie.",
      "actions": [
        "Vra 'n voorligtingsbeampte om die beskadigde blaar en enige insekte op die plant te ondersoek voordat jy 'n behandeling kies."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Soek die KEPHIS-sticker op die saadpakkie.",
    "stepScratch": "Krap die sticker om die kode te wys.",
    "stepText": "Stuur die kode per teks na {shortCode}. Dit is gratis.",
    "result": "KEPHIS antwoord om te sê of die saad egte saad is. 'n Egte kode bewys nie dat die saad goed gestoor is nie.",
    "coverage": "Dit werk vir gesertifiseerde saad wat in pakkies verkoop word. Kwekerysaailinge het gewoonlik geen sticker nie, so vra jou veldbeampte daaroor.",
    "noContact": "Vra jou veldbeampte hoe om te kyk of 'n saadpakkie eg is."
  },
  "phoneGreeting": "Hallo, dit is Leaf Doctor. Ek help met siek koffieplante, en jy kan in jou eie taal met my praat. Wat sien jy op jou koffieblare?"
});

export default afText;
