// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const astText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Les sos fueyes paecen sanes",
    "headlineSpray": "{name}: protexa les fueyes sanes y llimpie",
    "headlinePrune": "{name}: llimpie y pode",
    "headlineMonitor": "{name}: siga vixilando",
    "headlineAskOfficer": "{name}: pida al so téunicu de campu que lo revise",
    "headlineNotSure": "L'aplicación nun ta segura. Enseñe estes fueyes al so téunicu de campu",
    "headlineMightBe": "Podría ser {name}, pero nun ta confirmao. Enseñe-yos a un téunicu de campu",
    "headlineRetake": "Faiga semeyes más clares de más fueyes",
    "retakeDaylight": "Vaya a la lluz del día, non a sombra fonda nin a sol direutu.",
    "retakeSteady": "Mantenga'l teléfonu quietu hasta que la fueya se vea nítida.",
    "retakeFillFrame": "Enllene'l marcu con una sola fueya.",
    "sendToOfficer": "Unvie esti casu per SMS al téunicu de campu de la so cooperativa, o enseñe les fueyes en persona.",
    "rainReason": "Llovió {n} de los últimos 7 díes cerca d'usté ({source}). El tiempu húmedu fai que la roya s'espardia más rápido.",
    "labelRate": "Use la dosis de la etiqueta del productu.",
    "elseBerryDisease": "Enfermedá de la cereza del café: mire si les cereces tienen manches escures y fundíes.",
    "elseBerryBorer": "Barrenador de la cereza del café: busque furacos pequeños nes cereces.",
    "elseWilt": "Marchitamientu del café: ramas enteres marchitándose y muriendo.",
    "elseNutrition": "Suelu probe o mala nutrición: amarellamientu en tol árbol.",
    "smsDecisionSpray": "Decisión: protexa les fueyes sanes con cobre na dosis de la etiqueta y llimpie. Revise otra vegada en {days} díes.",
    "smsDecisionPrune": "Decisión: pode y llimpie. Revise otra vegada en {days} díes.",
    "smsDecisionMonitor": "Decisión: siga vixilando. Revise otra vegada en {days} díes.",
    "smsDecisionCallOfficer": "Decisión: enseñe-ylo al so téunicu de campu."
  },
  "diseases": {
    "cercospora": {
      "name": "Manches de güeyu marrón",
      "look": "Manches marrones redondes, sobre too na cara de riba de la fueya, con centru gris blancu y un aniellu marrón escuru, a menudo con una aureola mariella. Les manches miden de 5 a 15 mm d'anchu y pueden xuntase en grandes zones muertes. Les cereces tienen manches escures y fundíes y maduren demasiao pronto.",
      "tellApart": "Les manches de güeyu marrón tienen anielles marrones seques con centru gris pálidu y ensin polvu naranxa, mientres que la roya tien polvu naranxa debaxo.",
      "actions": [
        "Nutra bien los árboles, sobre too con nitróxenu y potasiu. Una bona nutrición suel controlar esta enfermedá.",
        "Mantenga sombra lleve, controle les yerbes y pode pa que l'aire se mueva y les fueyes se sequen.",
        "Dempués de podar, llévese o queme les fueyes y les cereces. Nun les amonte contra los árboles.",
        "Nel viveru, separe les plántules y queme les que tengan manches marrones con anielles.",
        "Si ta mal, un fungicida de cobre pue protexer les fueyes sanes. Pregunte primero al so téunicu d'estensión."
      ],
      "urgencyReason": "Débilita sobre too los árboles estresaos y suel meyorar cuando se igüen la nutrición y la sombra."
    },
    "healthy": {
      "name": "Fueya de café sana",
      "look": "Una fueya sana ye brillante, ovalada y puntiaguda, d'un verde escuru uniforme, ensin manches, polvu, furacos nin túneles por riba nin por debaxo.",
      "actions": [
        "Pode y mantenga sombra lleve y poques yerbes pa que les fueyes se sequen rápido.",
        "Nutra los árboles con estiércol o abonu equilibráu, sobre too con nitróxenu y potasiu.",
        "Revise les fueyes y el envés cada selmana o dos pa atopar la roya o el minador enantes."
      ]
    },
    "miner": {
      "name": "Minador de la fueya del café",
      "look": "Dientro de la fueya apaecen camberos mariellos pálidos que se tornen en manches muertes marrones irregulares na cara de riba. Si dobla la fueya, la piel fina de riba de la mancha desprendi y pue atopar dientro una larva pequeña transparente. Los ataques fuertes faen que les fueyes caigan.",
      "tellApart": "Les manches del minador son ampolles como papel con una larva dientro que se desprenden al doblar, mientres que la mancha de güeyu marrón ye un aniellu redondu y ordenáu que nun se desprendi.",
      "actions": [
        "Dobre les manches marrones pa buscar larves vives, sobre too na estación seca.",
        "Protexa los enemigos naturales, como les avispes pequeñes y les fumes, mantiendo sombra variada y evitando fumigar de más.",
        "Vixile de cerca los árboles nuevos y los viveros y quite enantes les primeres manches.",
        "Si fai falta un insecticida, pregunte al so téunicu d'estensión qué productu ye llegal y seguru nel so país."
      ],
      "urgencyReason": "Los ataques fuertes faen cayer les fueyes y baxen la producción, y son peores nes seques calentes."
    },
    "phoma": {
      "name": "Mancha de la fueya por Phoma",
      "look": "Manches marrones escures a negres d'hasta 2 cm d'anchu en fueyes más vieyes, con centru más claru y borde más escuru. Les puntes de los brotes nuevos vuélvense negres y sécase, les flores puen morrer y les cereces caen. El dañu pue entamar na punta o nel borde de la fueya.",
      "tellApart": "Phoma tamién mata les puntes de los brotes nuevos y les flores nes tierres altes fríes y ventoses, mientres que la mancha de güeyu marrón queda como manches con anielles y nun seca les puntes de los brotes.",
      "actions": [
        "Plante barreres contra'l vientu nes zones ventoses. El dañu del vientu dexa entrar al fungu.",
        "Pode y destruya los brotes secos y les cereces momificaes, y pode pa que l'aire seque les fueyes.",
        "Nutra los árboles con abonu equilibráu, sobre too con nitróxenu y potasiu.",
        "Nes estaciones fríes y ventoses, fumigue un fungicida de cobre enantes de que apaeza la enfermedá. Pregunte al so téunicu d'estensión pol momentu."
      ],
      "urgencyReason": "Nes tierres altes fríes y ventoses pue matar brotes y flores y baxar la producción del 15 al 43 por cientu."
    },
    "rust": {
      "name": "Roya de la fueya del café",
      "look": "Na cara de riba de la fueya apaecen manches pequeñes mariellu pálidu. Debaxo, cada mancha tien un parche de polvu de mariellu a naranxa escuru que se pega al deu. Les manches vieyes tornen marrones nel mediu y les fueyes caen enantes. Suel entamar poles fueyes baxes del árbol.",
      "tellApart": "La roya tien polvu naranxa nel envés de la fueya, mientres que la mancha de güeyu marrón tien anielles marrones seques con centru gris blancu y ensin polvu.",
      "actions": [
        "Revise a menudo l'envés de les fueyes baxes. Atopala enantes ye lo más importante.",
        "Arranque y queme o entierre les fueyes y les ramas con manches naranxa.",
        "Pode y aclare la sombra y les yerbes pa que l'aire se mueva y les fueyes se sequen más rápido.",
        "Nutra los árboles con estiércol o abonu equilibráu. Los árboles débiles padecen más.",
        "Fumigue un fungicida de cobre, como l'hidróxidu de cobre, na cara de riba y l'envés de les fueyes mientres menos d'un 5 por cientu de les fueyes tean enfermes. El cobre protexe les fueyes sanes pero nun cura les enfermes. Pregunte al so téunicu d'estensión pol momentu.",
        "Pa plantaciones nueves, pregunte al so téunicu d'estensión por variedaes resistentes a la roya, como les de tipu Catimor o Sarchimor."
      ],
      "urgencyReason": "S'espardia rápido ente árboles y finques, y les perdes en variedaes susceptibles puen llegar del 30 al 80 por cientu."
    },
    "mites": {
      "name": "Posible dañu por ácaros",
      "look": "La imaxe se paez a fueyes de café etiquetaes con dañu por ácaros. Marques asemeyaes puen tener otres causes, polo que ye una posible coincidencia.",
      "actions": [
        "Pida a un téunicu d'estensión qu'inspeccione dambes cares de la fueya y confirme la causa enantes d'escoyer un tratamientu."
      ]
    },
    "weevil": {
      "name": "Posible dañu por una plaga que mastia la fueya",
      "look": "La fueya paez a imáxenes etiquetaes como dañu de coco o gorgojo. Esta semeya nun pue identificar la especie d'inseutu.",
      "actions": [
        "Pida a un téunicu d'estensión qu'inspeccione la fueya dañada y los inseutos de la planta enantes d'escoyer un tratamientu."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Atope la pegatina de KEPHIS nel sobre de granes.",
    "stepScratch": "Rasque la pegatina pa ver el códigu.",
    "stepText": "Unvie el códigu per testu a {shortCode}. Ye de baldre.",
    "result": "KEPHIS responde pa dicir si la grana ye xenuina. Un códigu xenuinu nun prueba que la grana se guardara bien.",
    "coverage": "Esto vale pa granes certificaes que se vienden en sobres. Les plántules de viveru normalmente nun tienen pegatina, polo que pregunte al so téunicu de campu por elles.",
    "noContact": "Pregunte al so téunicu de campu cómo comprobar si un sobre de granes ye xenuinu."
  },
  "phoneGreeting": "Hola, soi Leaf Doctor. Ayudo con plantes de café enfermes, y pue falame na so llingua. ¿Qué ve nes fueyes del so café?"
});

export default astText;
