// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const azText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Yarpaqlarınız sağlam görünür",
    "headlineSpray": "{name}: sağlam yarpaqları qoruyun və təmizləyin",
    "headlinePrune": "{name}: təmizləyin və budayın",
    "headlineMonitor": "{name}: izləməyə davam edin",
    "headlineAskOfficer": "{name}: sahə mütəxəssisinizdən yoxlamasını xahiş edin",
    "headlineNotSure": "Tətbiq əmin deyil. Bu yarpaqları sahə mütəxəssisinizə göstərin",
    "headlineMightBe": "Bu, {name} ola bilər, lakin təsdiqlənməyib. Sahə mütəxəssisinə göstərin",
    "headlineRetake": "Daha çox yarpağın daha aydın şəkillərini çəkin",
    "retakeDaylight": "Gün işığına keçin, dərin kölgəyə və ya birbaşa günəşə yox.",
    "retakeSteady": "Yarpaq aydın görünənə qədər telefonu tərpətmədən tutun.",
    "retakeFillFrame": "Kadrı bir yarpaqla doldurun.",
    "sendToOfficer": "Bu halı kooperativinizin sahə mütəxəssisinə SMS ilə göndərin və ya yarpaqları şəxsən göstərin.",
    "rainReason": "Yaxınlığınızda son 7 gündən {n} gün yağış yağıb ({source}). Yaş hava pasın daha tez yayılmasına səbəb olur.",
    "labelRate": "Məhsulun etiketindəki dozadan istifadə edin.",
    "elseBerryDisease": "Qəhvə giləsi xəstəliyi: gilələrdə qara, çökük ləkələrə baxın.",
    "elseBerryBorer": "Qəhvə giləsi qurdu: gilələrdə kiçik dəliklər axtarın.",
    "elseWilt": "Qəhvənin solması: bütün budaqların solması və ölməsi.",
    "elseNutrition": "Zəif torpaq və ya qidalanma: bütün ağac boyu saralma.",
    "smsDecisionSpray": "Qərar: sağlam yarpaqları etiketdəki dozada mislə qoruyun və təmizləyin. {days} gündən sonra yenidən yoxlayın.",
    "smsDecisionPrune": "Qərar: budayın və təmizləyin. {days} gündən sonra yenidən yoxlayın.",
    "smsDecisionMonitor": "Qərar: izləməyə davam edin. {days} gündən sonra yenidən yoxlayın.",
    "smsDecisionCallOfficer": "Qərar: sahə mütəxəssisinizə göstərin."
  },
  "diseases": {
    "cercospora": {
      "name": "Qəhvəyi göz ləkəsi",
      "look": "Dəyirmi qəhvəyi ləkələr, əsasən yarpağın üst tərəfində, boz-ağ mərkəzli və tünd qəhvəyi halqalı, tez-tez sarı haşiyəli. Ləkələrin eni 5 ilə 15 mm arasındadır və birləşib böyük ölü sahələr yarada bilər. Gilələrdə tünd çökük ləkələr əmələ gəlir və çox tez yetişir.",
      "tellApart": "Qəhvəyi göz ləkəsində solğun boz mərkəzli quru qəhvəyi halqalar var və narıncı toz yoxdur, pasın isə altında narıncı toz olur.",
      "actions": [
        "Ağacları yaxşı qidalandırın, xüsusilə azot və kaliumla. Yaxşı qidalanma bu xəstəliyi tez-tez nəzarətdə saxlayır.",
        "Yüngül kölgə saxlayın, alaq otlarına nəzarət edin və budayın ki, hava hərəkət etsin və yarpaqlar qurusun.",
        "Budamadan sonra yarpaqları və gilələri aparın və ya yandırın. Onları ağacların yanında yığmayın.",
        "Tinglikdə şitilləri bir-birindən aralı əkin və halqalı qəhvəyi ləkəsi olan şitilləri yandırın.",
        "Ağırdırsa, mis fungisidi sağlam yarpaqları qoruya bilər. Əvvəlcə əkinçilik məsləhətçinizdən soruşun."
      ],
      "urgencyReason": "O, əsasən stress altındakı ağacları zəiflədir və qidalanma ilə kölgə düzəldikdən sonra adətən yaxşılaşır."
    },
    "healthy": {
      "name": "Sağlam qəhvə yarpağı",
      "look": "Sağlam yarpaq parlaq, oval və uclu, bərabər tünd yaşıl olur; üstündə və altında ləkə, toz, dəlik və ya tunel olmur.",
      "actions": [
        "Yarpaqlar tez qurusun deyə budayın, yüngül kölgə saxlayın və alaq otlarını azaldın.",
        "Ağacları peyin və ya balanslaşdırılmış gübrə ilə qidalandırın, xüsusilə azot və kaliumla.",
        "Pası və ya yarpaq qazanı erkən tutmaq üçün hər həftə və ya iki həftədən bir yarpaqlara və onların alt tərəfinə baxın."
      ]
    },
    "miner": {
      "name": "Qəhvə yarpaq qazanı",
      "look": "Yarpağın içində solğun sarı qıvrım yollar görünür və üst tərəfdə hamar olmayan qəhvəyi ölü sahələrə çevrilir. Yarpağı büksəniz, ləkənin üstündəki nazik qabıq ayrılır və içərisində kiçik şəffaf sürfə tapa bilərsiniz. Güclü hücumlar yarpaqların tökülməsinə səbəb olur.",
      "tellApart": "Qazan ləkələri içərisində sürfə olan kağız kimi qabarcıqlardır və bükəndə ayrılır, qəhvəyi göz ləkəsi isə səliqəli dəyirmi halqadır və ayrılmır.",
      "actions": [
        "Canlı sürfələri axtarmaq üçün qəhvəyi ləkələri bükün, xüsusilə quraq mövsümdə.",
        "Qarışıq kölgə saxlayaraq və lazımsız çiləmədən çəkinərək kiçik arılar və qarışqalar kimi təbii düşmənləri qoruyun.",
        "Cavan ağaclara və tinglikləri diqqətlə izləyin və ilk ləkələri erkən götürün.",
        "Həşərat dərmanı lazımdırsa, ölkənizdə hansı məhsulun qanuni və təhlükəsiz olduğunu əkinçilik məsləhətçinizdən soruşun."
      ],
      "urgencyReason": "Güclü hücumlar yarpaq tökülməsinə və məhsulun azalmasına səbəb olur, quru isti dövrlərdə daha pisdir."
    },
    "phoma": {
      "name": "Foma yarpaq ləkəsi",
      "look": "Köhnə yarpaqlarda eni 2 sm-ə qədər tünd qəhvəyidən qaraya qədər ləkələr, mərkəzi daha açıq və kənarı daha tünd. Cavan zoğların ucları qaralır və quruyur, çiçəklər ölə bilər və gilələr tökülür. Zərər yarpağın ucundan və ya kənarından başlaya bilər.",
      "tellApart": "Foma soyuq, küləkli dağlıqlarda cavan zoğların və çiçəklərin ucunu da öldürür, qəhvəyi göz ləkəsi isə halqalı ləkə olaraq qalır və zoğ uclarını qurutmur.",
      "actions": [
        "Küləkli ərazilərdə külək tutan cərgələr əkin. Külək zədəsi göbələyin içəri girməsinə imkan verir.",
        "Qurumuş zoğları və mumiyalaşmış gilələri kəsib məhv edin və budayın ki, hava yarpaqları qurutsun.",
        "Ağacları balanslaşdırılmış gübrə ilə qidalandırın, xüsusilə azot və kaliumla.",
        "Soyuq küləkli mövsümlərdə xəstəlik görünməzdən əvvəl mis fungisidi çiləyin. Vaxt barədə əkinçilik məsləhətçinizdən soruşun."
      ],
      "urgencyReason": "Soyuq küləkli dağlıqlarda zoğları və çiçəkləri öldürə və məhsulu 15 ilə 43 faiz azalda bilər."
    },
    "rust": {
      "name": "Qəhvə yarpağı pası",
      "look": "Yarpağın üst tərəfində kiçik solğun sarı ləkələr görünür. Altda hər ləkədə barmağınıza yapışan sarıdan tünd narıncıya qədər toz sahəsi olur. Köhnə ləkələr ortada qəhvəyiləşir və yarpaqlar tez tökülür. Adətən ağacın alt yarpaqlarından başlayır.",
      "tellApart": "Pasın yarpağın alt tərəfində narıncı tozu var, qəhvəyi göz ləkəsində isə boz-ağ mərkəzli quru qəhvəyi halqalar var və toz yoxdur.",
      "actions": [
        "Alt yarpaqların alt tərəfini tez-tez yoxlayın. Erkən tutmaq ən vacibdir.",
        "Narıncı ləkəli yarpaqları və budaqları qoparıb yandırın və ya basdırın.",
        "Hava hərəkət etsin və yarpaqlar daha tez qurusun deyə kölgəni və alaq otlarını budayıb seyrəldin.",
        "Ağacları peyin və ya balanslaşdırılmış gübrə ilə qidalandırın. Zəif ağaclar daha ağır zərbə alır.",
        "Yarpaqların təxminən 5 faizindən azı xəstə olduqda yarpaqların üst və alt tərəfinə mis hidroksid kimi mis fungisidi çiləyin. Mis sağlam yarpaqları qoruyur, lakin xəstə yarpaqları sağaltmır. Vaxt barədə əkinçilik məsləhətçinizdən soruşun.",
        "Yeni əkin üçün əkinçilik məsləhətçinizdən Catimor və ya Sarchimor tipli pasa davamlı sortlar barədə soruşun."
      ],
      "urgencyReason": "Ağaclar və təsərrüfatlar arasında tez yayılır və həssas sortlarda itkilər 30 ilə 80 faizə çata bilər."
    },
    "mites": {
      "name": "Mümkün gənə zərəri",
      "look": "Şəkil gənə zərəri kimi qeyd olunmuş qəhvə yarpaqlarına bənzəyir. Oxşar izlərin başqa səbəbləri də ola bilər, ona görə bu, mümkün uyğunluqdur.",
      "actions": [
        "Müalicə seçməzdən əvvəl əkinçilik məsləhətçisindən yarpağın hər iki tərəfini yoxlamasını və səbəbi təsdiqləməsini xahiş edin."
      ]
    },
    "weevil": {
      "name": "Yarpaq gəmirən zərərvericinin mümkün zərəri",
      "look": "Yarpaq koko və ya uzunburun böcək zərəri kimi qeyd olunmuş şəkillərə bənzəyir. Bu şəkil həşərat növünü müəyyən edə bilməz.",
      "actions": [
        "Müalicə seçməzdən əvvəl əkinçilik məsləhətçisindən zədələnmiş yarpağı və bitkidəki həşəratları yoxlamasını xahiş edin."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Toxum paketində KEPHIS stikerini tapın.",
    "stepScratch": "Kodu görmək üçün stikeri cızın.",
    "stepText": "Kodu mətnlə {shortCode} nömrəsinə göndərin. Pulsuzdur.",
    "result": "KEPHIS toxumun əsl olub-olmadığını bildirmək üçün cavab verir. Əsl kod toxumun yaxşı saxlandığını sübut etmir.",
    "coverage": "Bu, paketlərdə satılan sertifikatlı toxum üçün işləyir. Tinglik şitillərində adətən stiker olmur, ona görə onlar barədə sahə mütəxəssisinizdən soruşun.",
    "noContact": "Toxum paketinin əsl olub-olmadığını necə yoxlamaq barədə sahə mütəxəssisinizdən soruşun."
  },
  "phoneGreeting": "Salam, mən Leaf Doctor-am. Xəstə qəhvə bitkilərinə kömək edirəm və mənimlə öz dilinizdə danışa bilərsiniz. Qəhvə yarpaqlarında nə görürsünüz?"
});

export default azText;
