// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const bsText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Vaši listovi izgledaju zdravo",
    "headlineSpray": "{name}: zaštitite zdrave listove i očistite",
    "headlinePrune": "{name}: očistite i orežite",
    "headlineMonitor": "{name}: nastavite posmatrati",
    "headlineAskOfficer": "{name}: zamolite svog terenskog službenika da provjeri",
    "headlineNotSure": "Aplikacija nije sigurna. Pokažite ove listove svom terenskom službeniku",
    "headlineMightBe": "Moglo bi biti {name}, ali nije potvrđeno. Pokažite terenskom službeniku",
    "headlineRetake": "Napravite jasnije fotografije više listova",
    "retakeDaylight": "Prijeđite na dnevno svjetlo, ne u gustu sjenu ni na direktno sunce.",
    "retakeSteady": "Držite telefon mirno dok list ne bude oštar.",
    "retakeFillFrame": "Ispunite kadar jednim listom.",
    "sendToOfficer": "Pošaljite ovaj slučaj SMS-om terenskom službeniku vaše zadruge ili pokažite listove lično.",
    "rainReason": "Kod vas je padala kiša {n} od posljednjih 7 dana ({source}). Vlažno vrijeme ubrzava širenje rđe.",
    "labelRate": "Koristite količinu s etikete proizvoda.",
    "elseBerryDisease": "Bolest bobica kafe: pogledajte imaju li bobice tamne udubljene mrlje.",
    "elseBerryBorer": "Bušač bobica kafe: tražite sitne rupice na bobicama.",
    "elseWilt": "Venuće kafe: cijele grane venu i odumiru.",
    "elseNutrition": "Slabo tlo ili ishrana: žućenje po cijelom stablu.",
    "smsDecisionSpray": "Odluka: zaštitite zdrave listove bakrom u količini s etikete i očistite. Provjerite ponovo za {days} dana.",
    "smsDecisionPrune": "Odluka: orežite i očistite. Provjerite ponovo za {days} dana.",
    "smsDecisionMonitor": "Odluka: nastavite posmatrati. Provjerite ponovo za {days} dana.",
    "smsDecisionCallOfficer": "Odluka: pokažite svom terenskom službeniku."
  },
  "diseases": {
    "cercospora": {
      "name": "Smeđa pjega u obliku oka",
      "look": "Okrugle smeđe pjege, uglavnom na gornjoj strani lista, sa sivo-bijelim središtem i tamnosmeđim prstenom, često sa žutim oreolom. Pjege su široke 5 do 15 mm i mogu se spojiti u velike mrtve površine. Bobice dobiju tamne udubljene mrlje i prerano sazriju.",
      "tellApart": "Smeđa pjega u obliku oka ima suhe smeđe prstenove sa blijedosivim središtem i bez narandžastog praha, dok rđa ima narandžasti prah s donje strane.",
      "actions": [
        "Dobro hranite stabla, posebno azotom i kalijem. Dobra ishrana često kontroliše ovu bolest.",
        "Držite laganu sjenu, kontrolišite korov i orežite da zrak struji i listovi se suše.",
        "Poslije rezidbe odnesite ili spalite listove i bobice. Ne slažite ih uz stabla.",
        "U rasadniku sadnice držite razmaknute i spalite sadnice sa smeđim prstenastim pjegama.",
        "Ako je jako, bakarni fungicid može zaštititi zdrave listove. Prvo pitajte svog savjetnika za poljoprivredu."
      ],
      "urgencyReason": "Uglavnom slabi stabla pod stresom i obično se popravi kad se ishrana i sjena srede."
    },
    "healthy": {
      "name": "Zdrav list kafe",
      "look": "Zdrav list je sjajan, ovalan i šiljast, ujednačeno tamnozelen, bez mrlja, praha, rupa ili tunela odozgo i odozdo.",
      "actions": [
        "Orežite i držite laganu sjenu i malo korova da se listovi brzo suše.",
        "Hranite stabla stajskim đubrivom ili uravnoteženim đubrivom, posebno azotom i kalijem.",
        "Provjeravajte listove i njihovu donju stranu svake sedmice ili dvije da rano uhvatite rđu ili miner lista."
      ]
    },
    "miner": {
      "name": "Miner lista kafe",
      "look": "Unutar lista pojave se blijedožute vijugave pruge koje se pretvore u neravne smeđe mrtve površine odozgo. Ako savijete list, tanka gornja kožica preko mrlje se odvoji i unutra možete naći sitnu prozirnu larvu. Jaki napadi uzrokuju opadanje listova.",
      "tellApart": "Mrlje od minera su papirnati mjehurići s larvom unutra koji se odvoje kad se savije, dok je smeđa pjega u obliku oka uredan okrugli prsten koji se ne odvaja.",
      "actions": [
        "Savijte smeđe mrlje da tražite žive larve, posebno u sušnoj sezoni.",
        "Zaštitite prirodne neprijatelje kao što su sitne ose i mravi tako što ćete držati miješanu sjenu i izbjegavati nepotrebno prskanje.",
        "Pomno pratite mlada stabla i rasadnike i rano uklonite prve mrlje.",
        "Ako je potreban insekticid, pitajte svog savjetnika za poljoprivredu koji je proizvod zakonit i siguran u vašoj državi."
      ],
      "urgencyReason": "Jaki napadi uzrokuju opadanje listova i manji prinos, najgore u sušnim vrućim periodima."
    },
    "phoma": {
      "name": "Pjegavost lista uzrokovana gljivom Phoma",
      "look": "Tamnosmeđe do crne pjege široke do 2 cm na starijim listovima, sa svjetlijim središtem i tamnijim rubom. Vrhovi mladih izdanaka pocrne i osuše se, cvjetovi mogu odumrijeti, a bobice opadaju. Oštećenje može početi na vrhu ili rubu lista.",
      "tellApart": "Phoma također ubija vrhove mladih izdanaka i cvjetove u hladnim, vjetrovitim visoravnima, dok smeđa pjega u obliku oka ostaje prstenasta pjega i ne suši vrhove izdanaka.",
      "actions": [
        "Sadite vjetrozaštitne pojaseve u vjetrovitim područjima. Oštećenje od vjetra pušta gljivu unutra.",
        "Orežite i uništite osušene izdanke i mumificirane bobice, i orežite tako da zrak može osušiti listove.",
        "Hranite stabla uravnoteženim đubrivom, posebno azotom i kalijem.",
        "U hladnim vjetrovitim sezonama prskajte bakarnim fungicidom prije pojave bolesti. Pitajte svog savjetnika za poljoprivredu za vrijeme."
      ],
      "urgencyReason": "U hladnim vjetrovitim visoravnima može ubiti izdanke i cvjetove i smanjiti prinos za 15 do 43 posto."
    },
    "rust": {
      "name": "Rđa lista kafe",
      "look": "Sitne blijedožute pjege pojave se na gornjoj strani lista. S donje strane svaka pjega ima površinu žutog do tamnonarandžastog praha koji se briše na prst. Stare pjege u sredini posmeđe, a listovi rano opadaju. Obično počinje na donjim listovima stabla.",
      "tellApart": "Rđa ima narandžasti prah na donjoj strani lista, dok smeđa pjega u obliku oka ima suhe smeđe prstenove sa sivo-bijelim središtem i bez praha.",
      "actions": [
        "Često provjeravajte donju stranu donjih listova. Rano otkrivanje je najvažnije.",
        "Poberite i spalite ili zakopajte listove i grane s narandžastim pjegama.",
        "Orežite i prorijedite sjenu i korov da zrak struji i listovi se brže suše.",
        "Hranite stabla stajskim đubrivom ili uravnoteženim đubrivom. Slaba stabla jače stradaju.",
        "Prskajte bakarnim fungicidom kao što je bakar hidroksid po gornjoj i donjoj strani listova dok je manje od oko 5 posto listova bolesno. Bakar štiti zdrave listove, ali ne liječi bolesne. Pitajte svog savjetnika za poljoprivredu za vrijeme.",
        "Za novu sadnju pitajte svog savjetnika za poljoprivredu o sortama otpornim na rđu kao što su tipovi Catimor ili Sarchimor."
      ],
      "urgencyReason": "Brzo se širi među stablima i farmama, a gubici na osjetljivim sortama mogu doseći 30 do 80 posto."
    },
    "mites": {
      "name": "Moguća šteta od grinja",
      "look": "Slika liči na listove kafe označene kao oštećene grinjama. Slični tragovi mogu imati druge uzroke, pa je ovo moguće podudaranje.",
      "actions": [
        "Zamolite savjetnika za poljoprivredu da pregleda obje strane lista i potvrdi uzrok prije odabira liječenja."
      ]
    },
    "weevil": {
      "name": "Moguća šteta od štetočine koja grize listove",
      "look": "List liči na slike označene kao šteta od koka ili surlaša. Ova fotografija ne može odrediti vrstu insekta.",
      "actions": [
        "Zamolite savjetnika za poljoprivredu da pregleda oštećeni list i sve insekte na biljci prije odabira liječenja."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Pronađite KEPHIS naljepnicu na paketiću sjemena.",
    "stepScratch": "Stružite naljepnicu da se vidi kod.",
    "stepText": "Pošaljite kod tekstom na {shortCode}. Besplatno je.",
    "result": "KEPHIS odgovara i kaže je li sjeme originalno. Originalan kod ne dokazuje da je sjeme dobro čuvano.",
    "coverage": "Ovo radi za certificirano sjeme koje se prodaje u paketićima. Sadnice iz rasadnika obično nemaju naljepnicu, pa o njima pitajte svog terenskog službenika.",
    "noContact": "Pitajte svog terenskog službenika kako provjeriti je li paketić sjemena originalan."
  },
  "phoneGreeting": "Zdravo, ovdje Leaf Doctor. Pomažem kod bolesnih biljaka kafe, a sa mnom možete razgovarati na svom jeziku. Šta vidite na listovima kafe?"
});

export default bsText;
