// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const caText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Les vostres fulles semblen sanes",
    "headlineSpray": "{name}: protegiu les fulles sanes i netegeu",
    "headlinePrune": "{name}: netegeu i podeu",
    "headlineMonitor": "{name}: continueu vigilant",
    "headlineAskOfficer": "{name}: demaneu al vostre agent de camp que ho comprovi",
    "headlineNotSure": "L'aplicació no n'està segura. Ensenyeu aquestes fulles al vostre agent de camp",
    "headlineMightBe": "Podria ser {name}, però no està confirmat. Ensenyeu-ho a un agent de camp",
    "headlineRetake": "Feu fotos més clares de més fulles",
    "retakeDaylight": "Aneu a la llum del dia, no a l'ombra fosca ni al sol directe.",
    "retakeSteady": "Mantingueu el telèfon quiet fins que la fulla es vegi nítida.",
    "retakeFillFrame": "Ompliu el requadre amb una sola fulla.",
    "sendToOfficer": "Envieu aquest cas per SMS a l'agent de camp de la vostra cooperativa, o ensenyeu-li les fulles en persona.",
    "rainReason": "Ha plogut {n} dels darrers 7 dies a prop vostre ({source}). El temps humit fa que la roya s'escampi més de pressa.",
    "labelRate": "Feu servir la dosi de l'etiqueta del producte.",
    "elseBerryDisease": "Malaltia de la baia del cafè: mireu si les baies tenen taques fosques i enfonsades.",
    "elseBerryBorer": "Barrinador de la baia del cafè: busqueu forats petits a les baies.",
    "elseWilt": "Marciment del cafè: branques senceres que s'assequen i moren.",
    "elseNutrition": "Sòl pobre o falta de nutrients: groguenc a tot l'arbre.",
    "smsDecisionSpray": "Decisió: protegiu les fulles sanes amb coure a la dosi de l'etiqueta i netegeu. Torneu a comprovar d'aquí a {days} dies.",
    "smsDecisionPrune": "Decisió: podeu i netegeu. Torneu a comprovar d'aquí a {days} dies.",
    "smsDecisionMonitor": "Decisió: continueu vigilant. Torneu a comprovar d'aquí a {days} dies.",
    "smsDecisionCallOfficer": "Decisió: ensenyeu-ho al vostre agent de camp."
  },
  "diseases": {
    "cercospora": {
      "name": "Taca d'ull marró",
      "look": "Taques marrons rodones, sobretot a la cara de dalt de la fulla, amb el centre gris blanquinós i un anell marró fosc, sovint amb un halo groc. Les taques fan de 5 a 15 mm d'ample i es poden unir en grans zones mortes. Les baies tenen taques fosques i enfonsades i maduren massa aviat.",
      "tellApart": "La taca d'ull marró té anells marrons secs amb el centre gris pàl·lid i no té pols taronja, mentre que la roya té pols taronja per sota.",
      "actions": [
        "Alimenteu bé els arbres, sobretot amb nitrogen i potassi. Una bona nutrició sovint controla aquesta malaltia.",
        "Mantingueu una ombra lleugera, controleu les males herbes i podeu perquè l'aire circuli i les fulles s'eixuguin.",
        "Després de podar, retireu o cremeu les fulles i les baies. No les apileu contra els arbres.",
        "Al viver, separeu les plàntules i cremeu les que tinguin taques marrons amb anells.",
        "Si és greu, un fungicida de coure pot protegir les fulles sanes. Pregunteu primer al vostre tècnic d'extensió agrària."
      ],
      "urgencyReason": "Sobretot debilita els arbres estressats i sol millorar quan es corregeix la nutrició i l'ombra."
    },
    "healthy": {
      "name": "Fulla de cafè sana",
      "look": "Una fulla sana és brillant, ovalada i punxeguda, d'un verd fosc uniforme, sense taques, pols, forats ni túnels per damunt ni per sota.",
      "actions": [
        "Podeu i mantingueu una ombra lleugera i les males herbes baixes perquè les fulles s'eixuguin de pressa.",
        "Alimenteu els arbres amb fems o fertilitzant equilibrat, sobretot nitrogen i potassi.",
        "Mireu les fulles i el revers cada una o dues setmanes per detectar aviat la roya o el minador."
      ]
    },
    "miner": {
      "name": "Minador de la fulla del cafè",
      "look": "Dins la fulla apareixen camins sinuosos de color groc pàl·lid que es converteixen en zones mortes marrons irregulars per damunt. Si doblegueu la fulla, la pell fina de sobre la zona es separa i hi podeu trobar una larva minúscula i transparent. Els atacs forts fan caure les fulles.",
      "tellApart": "Les zones del minador són butllofes primes com paper amb una larva a dins, que es separen en doblegar-les, mentre que la taca d'ull marró és un anell rodó i net que no es separa.",
      "actions": [
        "Doblegueu les zones marrons per buscar larves vives, sobretot a l'estació seca.",
        "Protegiu els enemics naturals, com les vespes petites i les formigues, mantenint ombra variada i evitant ruixar sense necessitat.",
        "Vigileu de prop els arbres joves i els viveres i traieu aviat les primeres zones afectades.",
        "Si cal un insecticida, pregunteu al vostre tècnic d'extensió agrària quin producte és legal i segur al vostre país."
      ],
      "urgencyReason": "Els atacs forts fan caure les fulles i baixen la collita, sobretot en períodes secs i calorosos."
    },
    "phoma": {
      "name": "Taca foliar per Phoma",
      "look": "Taques marrons fosques a negres de fins a 2 cm d'ample a les fulles velles, amb el centre més clar i la vora més fosca. Les puntes dels brots joves es tornen negres i s'assequen, les flors poden morir i les baies cauen. El dany pot començar a la punta o a la vora de la fulla.",
      "tellApart": "Phoma també mata les puntes dels brots joves i les flors a les terres altes fredes i ventoses, mentre que la taca d'ull marró queda com a taques amb anells i no asseca les puntes dels brots.",
      "actions": [
        "Planteu tallavents a les zones ventoses. El dany del vent deixa entrar el fong.",
        "Talleu i destruïu els brots secs i les baies momificades, i podeu perquè l'aire pugui eixugar les fulles.",
        "Alimenteu els arbres amb fertilitzant equilibrat, sobretot nitrogen i potassi.",
        "En temporades fredes i ventoses, ruixeu un fungicida de coure abans que aparegui la malaltia. Pregunteu al vostre tècnic d'extensió agrària quan fer-ho."
      ],
      "urgencyReason": "A les terres altes fredes i ventoses pot matar brots i flors i reduir la collita entre el 15 i el 43 per cent."
    },
    "rust": {
      "name": "Roya de la fulla del cafè",
      "look": "A la cara de dalt de la fulla surten taquetes groc pàl·lid. Per sota, cada taca té una zona de pols de groga a taronja fosca que es queda als dits si la fregueu. Les taques velles es tornen marrons pel mig i les fulles cauen aviat. Sol començar a les fulles de baix de l'arbre.",
      "tellApart": "La roya té pols taronja al revers de la fulla, mentre que la taca d'ull marró té anells marrons secs amb el centre gris blanquinós i no té pols.",
      "actions": [
        "Mireu sovint el revers de les fulles de baix. El més important és detectar-la aviat.",
        "Arrenqueu i cremeu o enterreu les fulles i les branques amb taques taronges.",
        "Podeu i aclariu l'ombra i les males herbes perquè l'aire circuli i les fulles s'eixuguin més de pressa.",
        "Alimenteu els arbres amb fems o fertilitzant equilibrat. Els arbres febles pateixen més.",
        "Ruixeu un fungicida de coure, com l'hidròxid de coure, per damunt i per sota de les fulles mentre menys del 5 per cent de les fulles estiguin malaltes. El coure protegeix les fulles sanes però no cura les malaltes. Pregunteu al vostre tècnic d'extensió agrària quan fer-ho.",
        "Per a una plantació nova, pregunteu al vostre tècnic d'extensió agrària per varietats resistents a la roya, com els tipus Catimor o Sarchimor."
      ],
      "urgencyReason": "S'escampa de pressa entre arbres i finques, i en varietats sensibles les pèrdues poden arribar al 30 i el 80 per cent."
    },
    "mites": {
      "name": "Possible dany per àcars",
      "look": "La imatge s'assembla a fulles de cafè etiquetades amb dany per àcars. Marques semblants poden tenir altres causes, així que és una possible coincidència.",
      "actions": [
        "Demaneu a un tècnic d'extensió agrària que inspeccioni les dues cares de la fulla i confirmi la causa abans d'escollir un tractament."
      ]
    },
    "weevil": {
      "name": "Possible dany per una plaga que rosega les fulles",
      "look": "La fulla s'assembla a imatges etiquetades com a dany de coco o de corc. Aquesta foto no pot identificar l'espècie d'insecte.",
      "actions": [
        "Demaneu a un tècnic d'extensió agrària que inspeccioni la fulla danyada i els insectes de la planta abans d'escollir un tractament."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Busqueu l'adhesiu de KEPHIS al paquet de llavors.",
    "stepScratch": "Ratlleu l'adhesiu per mostrar el codi.",
    "stepText": "Envieu el codi per SMS al {shortCode}. És gratuït.",
    "result": "KEPHIS respon per dir si la llavor és autèntica. Un codi autèntic no demostra que la llavor s'hagi guardat bé.",
    "coverage": "Això serveix per a llavor certificada venuda en paquets. Les plàntules de viver normalment no porten adhesiu, així que pregunteu-ho al vostre agent de camp.",
    "noContact": "Pregunteu al vostre agent de camp com comprovar si un paquet de llavors és autèntic."
  },
  "phoneGreeting": "Hola, sóc Leaf Doctor. Ajudo amb les plantes de cafè malaltes, i podeu parlar-me en el vostre idioma. Què veieu a les fulles del cafè?"
});

export default caText;
