// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const cebText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Himsog tan-awon ang imong mga dahon",
    "headlineSpray": "{name}: panalipdi ang himsog nga mga dahon ug limpyohi",
    "headlinePrune": "{name}: limpyohi ug putlia ang sanga",
    "headlineMonitor": "{name}: padayon nga bantayi",
    "headlineAskOfficer": "{name}: pasusiha sa imong opisyal sa umahan",
    "headlineNotSure": "Dili sigurado ang app. Ipakita kini nga mga dahon sa imong opisyal sa umahan",
    "headlineMightBe": "Mahimong {name}, apan wala pa makumpirma. Ipakita sa opisyal sa umahan",
    "headlineRetake": "Kuhaa ug mas klaro nga mga litrato sa mas daghang dahon",
    "retakeDaylight": "Lakaw ngadto sa kahayag sa adlaw, dili sa madulom nga landong o direktang init sa adlaw.",
    "retakeSteady": "Ayaw pagpalihok sa telepono hangtod mahait tan-awon ang dahon.",
    "retakeFillFrame": "Pun-a ang frame sa usa ka dahon.",
    "sendToOfficer": "Ipadala kini nga kaso sa opisyal sa umahan sa imong kooperatiba pinaagi sa SMS, o ipakita ang mga dahon personal.",
    "rainReason": "Nag-ulan sa {n} sa miaging 7 ka adlaw duol kanimo ({source}). Ang basa nga panahon nagpaayo sa kadali sa pagkaylap sa rust.",
    "labelRate": "Gamita ang gidaghanon nga gisulat sa label sa produkto.",
    "elseBerryDisease": "Sakit sa bunga sa kape: tan-awa ang mga bunga kung adunay ngitngit ug lunop nga mga lugar.",
    "elseBerryBorer": "Insekto nga mohaluk sa bunga sa kape: pangitaa ang gagmay nga lungag sa mga bunga.",
    "elseWilt": "Pagkalaya sa kape: tibuok nga mga sanga nagkalaya ug nangamatay.",
    "elseNutrition": "Dili maayo nga yuta o kakulang sa sustansya: nagdilaw ang tibuok kahoy.",
    "smsDecisionSpray": "Desisyon: panalipdi ang himsog nga mga dahon gamit ang copper sumala sa gidaghanon sa label ug limpyohi. Susiha pag usab sa {days} ka adlaw.",
    "smsDecisionPrune": "Desisyon: putlia ang sanga ug limpyohi. Susiha pag usab sa {days} ka adlaw.",
    "smsDecisionMonitor": "Desisyon: padayon nga bantayi. Susiha pag usab sa {days} ka adlaw.",
    "smsDecisionCallOfficer": "Desisyon: ipakita sa imong opisyal sa umahan."
  },
  "diseases": {
    "cercospora": {
      "name": "Brown nga lugar sama sa mata",
      "look": "Lingin nga brown nga mga tulbok, kasagaran sa ibabaw nga bahin sa dahon, nga abo-puti ang sentro ug ngitngit nga brown nga ring, kasagaran adunay dilaw nga libot. Ang mga tulbok 5 hangtod 15 mm ang gilapdon ug mahimong magkahiusa nga mahimong dagkong patay nga lugar. Ang mga bunga adunay ngitngit ug lunop nga mga lugar ug mahinog ug sayo ra kaayo.",
      "tellApart": "Ang brown nga lugar sama sa mata adunay uga nga brown nga mga ring nga luspad nga abo ang sentro ug walay orange nga abog, samtang ang rust adunay orange nga abog sa ilawom.",
      "actions": [
        "Pakan-a pag-ayo ang mga kahoy, labi na ug nitrogen ug potassium. Ang maayong pagpakaon kasagaran makakontrol niining sakita.",
        "Pabilini ang gaan nga landong, kontrola ang sagbot, ug putlia ang mga sanga aron makalusot ang hangin ug mauga ang mga dahon.",
        "Human sa pagputol, dad-a o sunoga ang mga dahon ug bunga. Ayaw ipundok sa tapad sa mga kahoy.",
        "Sa nursery, pag-ugma-ugmaa ang pagtanom sa mga lunang ug sunoga ang mga lunang nga adunay brown nga tulbok nga adunay ring.",
        "Kung grabe, ang copper nga fungicide makapanalipod sa himsog nga mga dahon. Pangutana una sa imong extension officer."
      ],
      "urgencyReason": "Kasagaran gihuyang niini ang mga kahoy nga gipaningkamutan ug kasagaran mouswag kung maayo na ang pagpakaon ug landong."
    },
    "healthy": {
      "name": "Himsog nga dahon sa kape",
      "look": "Ang himsog nga dahon masilaw, oval ug tulis, parehas ang ngitngit nga berde, walay tulbok, abog, lungag o tunel sa ibabaw ug ilawom.",
      "actions": [
        "Putlia ang mga sanga ug pabilini ang gaan nga landong ug ubos nga sagbot aron dali mauga ang mga dahon.",
        "Pakan-a ang mga kahoy ug abono o balanse nga pataba, labi na ug nitrogen ug potassium.",
        "Susiha ang mga dahon ug ilawom niini matag usa o duha ka semana aron maagahan ang rust o leaf miner."
      ]
    },
    "miner": {
      "name": "Coffee leaf miner",
      "look": "Ang luspad nga dilaw nga mga lukot nga agianan makita sa sulod sa dahon ug mahimong dili patas nga brown nga patay nga mga lugar sa ibabaw. Kung ibaluktot nimo ang dahon, ang nipis nga panit sa ibabaw sa lugar mabuka ug makakita ka ug gamay nga ulod nga matin-aw ang lawas sa sulod. Ang grabeng pag-atake maghimo sa mga dahon nga mahulog.",
      "tellApart": "Ang mga lugar sa miner sama sa nipis nga papel nga bukol nga adunay ulod sa sulod nga mabuka kung ibaluktot, samtang ang brown nga lugar sama sa mata usa ka limpyo nga lingin nga ring nga dili mabuka.",
      "actions": [
        "Ibaluktot ang brown nga mga lugar aron pangitaon ang buhi nga mga ulod, labi na sa uga nga panahon.",
        "Panalipdi ang natural nga mga kaaway sama sa gagmayng putyukan ug hulmigas pinaagi sa pagpabilin sa sagol nga landong ug pagpugong sa wala kinahanglana nga pag-spray.",
        "Bantayi pag-ayo ang bag-ong mga kahoy ug nursery ug tangtanga dayon ang unang mga lugar.",
        "Kung kinahanglan ang insecticide, pangutana sa imong extension officer kung unsang produkto ang legal ug luwas sa imong nasud."
      ],
      "urgencyReason": "Ang grabeng pag-atake hinungdan sa pagkahulog sa dahon ug pagkunhod sa ani, labing grabe sa uga ug init nga panahon."
    },
    "phoma": {
      "name": "Phoma nga lugar sa dahon",
      "look": "Ngitngit nga brown hangtod itom nga mga tulbok nga hangtod 2 cm ang gilapdon sa tigulang nga mga dahon, nga mas gaan ang sentro ug mas ngitngit ang ngilit. Ang tumoy sa batan-ong mga saha mangitom ug mauga, ang mga bulak mahimong mamatay, ug ang mga bunga mahulog. Ang kadaot mahimong magsugod sa tumoy o ngilit sa dahon.",
      "tellApart": "Ang Phoma nagpatay usab sa tumoy sa batan-ong mga saha ug mga bulak sa bugnaw ug mahangin nga kabukiran, samtang ang brown nga lugar sama sa mata nagpabilin nga mga tulbok nga adunay ring ug wala magpauga sa tumoy sa mga saha.",
      "actions": [
        "Tanoma ug babag sa hangin ang mahangin nga mga dapit. Ang kadaot sa hangin nagtugot sa fungus nga mosulod.",
        "Putla ug gub-a ang uga nga mga saha ug nangauga nga mga bunga, ug putlia ang mga sanga aron mauga sa hangin ang mga dahon.",
        "Pakan-a ang mga kahoy ug balanse nga pataba, labi na ug nitrogen ug potassium.",
        "Sa bugnaw ug mahangin nga panahon, i-spray ang copper nga fungicide sa dili pa mogawas ang sakit. Pangutana sa imong extension officer kung kanus-a."
      ],
      "urgencyReason": "Sa bugnaw ug mahangin nga kabukiran mahimo niyang mapatay ang mga saha ug bulak ug makunhod ang ani sa 15 hangtod 43 porsyento."
    },
    "rust": {
      "name": "Coffee leaf rust",
      "look": "Gagmay nga luspad nga dilaw nga mga tulbok makita sa ibabaw sa dahon. Sa ilawom, ang matag tulbok adunay lugar nga dilaw hangtod ngitngit nga orange nga abog nga mahilis sa imong tudlo. Ang tigulang nga mga tulbok mahimong brown sa tunga ug ang mga dahon mahulog sayo. Kasagaran magsugod sa ubos nga mga dahon sa kahoy.",
      "tellApart": "Ang rust adunay orange nga abog sa ilawom sa dahon, samtang ang brown nga lugar sama sa mata adunay uga nga brown nga mga ring nga abo-puti ang sentro ug walay abog.",
      "actions": [
        "Kanunayng susiha ang ilawom sa ubos nga mga dahon. Ang labing importante mao ang maagahan kini.",
        "Pamutla ug sunoga o ilubong ang mga dahon ug sanga nga adunay orange nga tulbok.",
        "Putlia ug hanggi ang landong ug sagbot aron makalusot ang hangin ug mas paspas mauga ang mga dahon.",
        "Pakan-a ang mga kahoy ug abono o balanse nga pataba. Ang huyang nga mga kahoy mas grabe ang tama.",
        "I-spray ang copper nga fungicide sama sa copper hydroxide sa ibabaw ug ilawom sa mga dahon samtang ubos pa sa mga 5 porsyento sa mga dahon ang masakiton. Ang copper nagpanalipod sa himsog nga mga dahon apan dili makaayo sa masakiton. Pangutana sa imong extension officer kung kanus-a.",
        "Alang sa bag-ong tanum, pangutana sa imong extension officer bahin sa mga klase nga makasukol sa rust sama sa Catimor o Sarchimor nga mga tipo."
      ],
      "urgencyReason": "Paspas kini mokaylap taliwala sa mga kahoy ug umahan, ug ang pagkawala sa dali nga madaot nga mga klase mahimong moabot sa 30 hangtod 80 porsyento."
    },
    "mites": {
      "name": "Posibleng kadaot sa mite",
      "look": "Ang hulagway susama sa mga dahon sa kape nga gimarkahan nga adunay kadaot sa mite. Ang susamang mga marka mahimong adunay ubang hinungdan, busa kini posibleng tugma.",
      "actions": [
        "Pasusiha sa extension officer ang duha ka kilid sa dahon ug kumpirmaha ang hinungdan sa dili pa pagpili ug tambal."
      ]
    },
    "weevil": {
      "name": "Posibleng kadaot sa peste nga mokaon sa dahon",
      "look": "Ang dahon susama sa mga hulagway nga gimarkahan nga kadaot sa coco o weevil. Kini nga litrato dili makaila sa klase sa insekto.",
      "actions": [
        "Pasusiha sa extension officer ang nadaot nga dahon ug ang bisan unsang insekto sa tanom sa dili pa pagpili ug tambal."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Pangitaa ang KEPHIS nga sticker sa putos sa binhi.",
    "stepScratch": "Kiskisa ang sticker aron makita ang code.",
    "stepText": "I-text ang code sa {shortCode}. Libre kini.",
    "result": "Motubag ang KEPHIS kung tinuod ba ang binhi. Ang tinuod nga code dili pamatuod nga maayo ang pagtipig sa binhi.",
    "coverage": "Kini mogana alang sa gisertipikahan nga binhi nga gibaligya sa putos. Ang mga lunang sa nursery kasagaran walay sticker, busa pangutana sa imong opisyal sa umahan bahin niini.",
    "noContact": "Pangutana sa imong opisyal sa umahan kung unsaon pagsusi kung tinuod ba ang putos sa binhi."
  },
  "phoneGreeting": "Kumusta, kini ang Leaf Doctor. Motabang ko sa masakiton nga tanom nga kape, ug makigsulti ka nako sa imong kaugalingong pinulongan. Unsa ang imong nakita sa dahon sa imong kape?"
});

export default cebText;
