// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const csText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Vaše listy vypadají zdravě",
    "headlineSpray": "{name}: chraňte zdravé listy a uklízejte",
    "headlinePrune": "{name}: uklízejte a ořezávejte",
    "headlineMonitor": "{name}: dál sledujte",
    "headlineAskOfficer": "{name}: požádejte svého terenního poradce o kontrolu",
    "headlineNotSure": "Aplikace si není jistá. Ukažte tyto listy svému terennímu poradci",
    "headlineMightBe": "Může to být: {name}, ale není to potvrzeno. Ukažte to terennímu poradci",
    "headlineRetake": "Pořiďte zřetelnější fotky více listů",
    "retakeDaylight": "Jděte na denní světlo, ne do hlubokého stínu ani na přímé slunce.",
    "retakeSteady": "Držte telefon v klidu, dokud list není ostrý.",
    "retakeFillFrame": "Zaplňte záběr jedním listem.",
    "sendToOfficer": "Pošlete tento případ SMS terennímu poradci svého družstva, nebo mu listy ukažte osobně.",
    "rainReason": "U vás pršelo {n} z posledních 7 dní ({source}). Vlhké počasí urychluje šíření rzi.",
    "labelRate": "Použijte dávku z etikety přípravku.",
    "elseBerryDisease": "Choroba plodů kávovníku: hledejte na plodech tmavé propadlé skvrny.",
    "elseBerryBorer": "Kávovníkový klikoroh: hledejte na plodech malé dírky.",
    "elseWilt": "Vadnutí kávovníku: vadnou a odumírají celé větve.",
    "elseNutrition": "Špatná půda nebo málo živin: žloutnutí celého stromu.",
    "smsDecisionSpray": "Rozhodnutí: chraňte zdravé listy mědí v dávce z etikety a uklízejte. Zkontrolujte znovu za {days} dní.",
    "smsDecisionPrune": "Rozhodnutí: ořezávejte a uklízejte. Zkontrolujte znovu za {days} dní.",
    "smsDecisionMonitor": "Rozhodnutí: dál sledujte. Zkontrolujte znovu za {days} dní.",
    "smsDecisionCallOfficer": "Rozhodnutí: ukažte to svému terennímu poradci."
  },
  "diseases": {
    "cercospora": {
      "name": "Hnědá skvrnitost listů (žabí oko)",
      "look": "Kulaté hnědé skvrny, hlavně na horní straně listu, se šedobílým středem a tmavohnědým kroužkem, často se žlutým lemem. Skvrny jsou 5 až 15 mm široké a mohou splynout ve velké odumřelé plochy. Plody dostanou tmavé propadlé skvrny a dozrávají příliš brzy.",
      "tellApart": "Hnědá skvrnitost má suché hnědé kroužky se světle šedým středem a žádný oranžový prášek, zatímco rez má dole oranžový prášek.",
      "actions": [
        "Dobře stromy hnojte, hlavně dusíkem a draslíkem. Dobrá výživa tuto nemoc často zvládne.",
        "Udržujte lehký stín, hubte plevel a ořezávejte tak, aby proudil vzduch a listy osychaly.",
        "Po ořezu listy a plody odneste nebo spalte. Nenechávejte je na hromadě u stromů.",
        "Ve školce sazenice sázejte s odstupem a sazenice s hnědými kroužkovitými skvrnami spalte.",
        "Je-li to vážné, měďnatý fungicid může chránit zdravé listy. Nejdřív se zeptejte svého zemědělského poradce."
      ],
      "urgencyReason": "Oslabuje hlavně stromy ve stresu a obvykle se zlepší, když se opraví výživa a stín."
    },
    "healthy": {
      "name": "Zdravý list kávovníku",
      "look": "Zdravý list je lesklý, oválný a špičatý, rovnoměrně tmavě zelený, bez skvrn, prášku, děr nebo chodbiček nahoře i dole.",
      "actions": [
        "Ořezávejte a držte lehký stín a nízký plevel, aby listy rychle osychaly.",
        "Stromy hnojte chlévskou mrvou nebo vyváženým hnojivem, hlavně dusíkem a draslíkem.",
        "Kontrolujte listy a jejich spodní strany každý týden nebo dva, abyste včas zachytili rez nebo škůdce minujícího listy."
      ]
    },
    "miner": {
      "name": "Škůdce minující listy kávovníku",
      "look": "Uvnitř listu se objeví světle žluté křivolaké stopy, které nahoře přejdou v nerovné hnědé odumřelé plochy. Když list ohnete, tenká horní slupka nad plochou se rozlepí a uvnitř můžete najít drobnou průhlednou larvu. Silné napadení způsobí opad listů.",
      "tellApart": "Plochy po minujícím škůdci jsou papírové puchýře s larvou uvnitř, které se při ohnutí rozlepí, zatímco hnědá skvrnitost je úhledný kulatý kroužek, který se nerozlepí.",
      "actions": [
        "Ohýbejte hnědé plochy a hledejte živé larvy, hlavně v období sucha.",
        "Chraňte přirozené nepřátele, jako jsou malé vosičky a mravenci, udržováním smíšeného stínu a vyhýbáním se zbytečnému postřiku.",
        "Pozorně sledujte mladé stromy a školky a první napadené plochy včas odstraňte.",
        "Je-li potřeba insekticid, zeptejte se svého zemědělského poradce, který přípravek je ve vaší zemi povolený a bezpečný."
      ],
      "urgencyReason": "Silné napadení způsobuje opad listů a nižší úrodu, nejhorší je v suchých horkých obdobích."
    },
    "phoma": {
      "name": "Skvrnitost listů způsobená houbou Phoma",
      "look": "Tmavohnědé až černé skvrny široké až 2 cm na starších listech, se světlejším středem a tmavším okrajem. Špičky mladých výhonků zčernají a uschnou, květy mohou odumřít a plody opadávají. Poškození může začít na špičce nebo okraji listu.",
      "tellApart": "Phoma ve studených větrných vysočinách zabíjí také špičky mladých výhonků a květy, zatímco hnědá skvrnitost zůstává jen kroužkovitými skvrnami a špičky výhonků nevysušuje.",
      "actions": [
        "Ve větrných oblastech vysaďte větrolamy. Poškození větrem pouští houbu dovnitř.",
        "Uschlé výhony a zmumifikované plody odřízněte a zničte a ořezávejte tak, aby vzduch mohl listy osušit.",
        "Stromy hnojte vyváženým hnojivem, hlavně dusíkem a draslíkem.",
        "Ve studených větrných obdobích postříkejte měďnatým fungicidem dřív, než se nemoc objeví. O načasování se zeptejte svého zemědělského poradce."
      ],
      "urgencyReason": "Ve studených větrných vysočinách může zabít výhony a květy a snížit úrodu o 15 až 43 procent."
    },
    "rust": {
      "name": "Rez kávovníku",
      "look": "Na horní straně listu se objevují malé světle žluté skvrny. Dole má každá skvrna plošku žlutého až tmavě oranžového prášku, který se otírá o prst. Staré skvrny uprostřed zhnědnou a listy brzy opadávají. Obvykle začíná na spodních listech stromu.",
      "tellApart": "Rez má oranžový prášek na spodní straně listu, zatímco hnědá skvrnitost má suché hnědé kroužky se šedobílým středem a žádný prášek.",
      "actions": [
        "Často kontrolujte spodní stranu spodních listů. Nejdůležitější je zachytit ji včas.",
        "Listy a větve s oranžovými skvrnami otrhejte a spalte nebo zakopejte.",
        "Ořezávejte a prořeďte stín a plevel, aby proudil vzduch a listy osychaly rychleji.",
        "Stromy hnojte chlévskou mrvou nebo vyváženým hnojivem. Slabé stromy rez postihuje víc.",
        "Postříkejte měďnatým fungicidem, například hydroxidem měďnatým, vršky i spodky listů, dokud je nemocných méně než asi 5 procent listů. Měď chrání zdravé listy, ale nevyléčí nemocné. O načasování se zeptejte svého zemědělského poradce.",
        "Pro novou výsadbu se zeptejte svého zemědělského poradce na odrůdy odolné proti rzi, například typy Catimor nebo Sarchimor."
      ],
      "urgencyReason": "Rychle se šíří mezi stromy i farmami a ztráty na náchylných odrůdách mohou dosáhnout 30 až 80 procent."
    },
    "mites": {
      "name": "Možné poškození roztoči",
      "look": "Obrázek připomíná listy kávovníku označené jako poškozené roztoči. Podobné stopy mohou mít jiné příčiny, takže jde o možnou shodu.",
      "actions": [
        "Požádejte zemědělského poradce, aby prohlédl obě strany listu a potvrdil příčinu, než zvolíte léčbu."
      ]
    },
    "weevil": {
      "name": "Možné poškození škůdcem, který žere listy",
      "look": "List připomíná obrázky označené jako poškození kokosem nebo nosatcem. Tato fotka nemůže určit druh hmyzu.",
      "actions": [
        "Požádejte zemědělského poradce, aby prohlédl poškozený list a jakýkoli hmyz na rostlině, než zvolíte léčbu."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Najděte nálepku KEPHIS na sáčku se semeny.",
    "stepScratch": "Setřete nálepku, aby se ukázal kód.",
    "stepText": "Pošlete kód zprávou na číslo {shortCode}. Je to zdarma.",
    "result": "KEPHIS odpoví, jestli jsou semena pravá. Pravý kód nedokazuje, že byla semena dobře uložena.",
    "coverage": "Platí to pro certifikovaná semena prodávaná v sáčcích. Sazenice ze školky obvykle nálepku nemají, proto se na ně zeptejte svého terenního poradce.",
    "noContact": "Zeptejte se svého terenního poradce, jak zjistit, jestli je sáček se semeny pravý."
  },
  "phoneGreeting": "Dobrý den, tady Leaf Doctor. Pomáhám s nemocnými kávovníky a můžete se mnou mluvit ve svém jazyce. Co vidíte na listech svého kávovníku?"
});

export default csText;
