// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const deText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Ihre Blätter sehen gesund aus",
    "headlineSpray": "{name}: gesunde Blätter schützen und aufräumen",
    "headlinePrune": "{name}: aufräumen und beschneiden",
    "headlineMonitor": "{name}: weiter beobachten",
    "headlineAskOfficer": "{name}: Lassen Sie Ihren Feldberater prüfen",
    "headlineNotSure": "Die App ist nicht sicher. Zeigen Sie diese Blätter Ihrem Feldberater",
    "headlineMightBe": "Es könnte {name} sein, ist aber nicht bestätigt. Zeigen Sie es einem Feldberater",
    "headlineRetake": "Machen Sie deutlichere Fotos von mehr Blättern",
    "retakeDaylight": "Gehen Sie ins Tageslicht, nicht in tiefen Schatten und nicht in direkte Sonne.",
    "retakeSteady": "Halten Sie das Telefon ruhig, bis das Blatt scharf aussieht.",
    "retakeFillFrame": "Füllen Sie das Bild mit einem Blatt.",
    "sendToOfficer": "Senden Sie diesen Fall per SMS an den Feldberater Ihrer Genossenschaft oder zeigen Sie die Blätter persönlich.",
    "rainReason": "Es hat in Ihrer Nähe an {n} der letzten 7 Tage geregnet ({source}). Feuchtes Wetter lässt den Rost sich schneller ausbreiten.",
    "labelRate": "Verwenden Sie die Menge, die auf dem Etikett steht.",
    "elseBerryDisease": "Kaffeebeeren-Krankheit: Schauen Sie, ob die Beeren dunkle, eingesunkene Flecken haben.",
    "elseBerryBorer": "Kaffeekirschenkäfer: Suchen Sie nach kleinen Löchern in den Beeren.",
    "elseWilt": "Kaffeewelke: ganze Äste welken und sterben ab.",
    "elseNutrition": "Schlechter Boden oder Nährstoffmangel: Der ganze Baum wird gelb.",
    "smsDecisionSpray": "Entscheidung: Gesunde Blätter mit Kupfer in der Menge vom Etikett schützen und aufräumen. In {days} Tagen erneut prüfen.",
    "smsDecisionPrune": "Entscheidung: beschneiden und aufräumen. In {days} Tagen erneut prüfen.",
    "smsDecisionMonitor": "Entscheidung: weiter beobachten. In {days} Tagen erneut prüfen.",
    "smsDecisionCallOfficer": "Entscheidung: Ihrem Feldberater zeigen."
  },
  "diseases": {
    "cercospora": {
      "name": "Braune Augenfleckenkrankheit",
      "look": "Runde braune Flecken, meist auf der Blattoberseite, mit grauweißer Mitte und dunkelbraunem Ring, oft mit gelbem Hof. Die Flecken sind 5 bis 15 mm breit und können zu großen abgestorbenen Stellen zusammenwachsen. Die Beeren bekommen dunkle, eingesunkene Flecken und reifen zu früh.",
      "tellApart": "Die braune Augenfleckenkrankheit hat trockene braune Ringe mit hellgrauer Mitte und kein orangefarbenes Pulver, während Rost unten orangefarbenes Pulver hat.",
      "actions": [
        "Düngen Sie die Bäume gut, besonders mit Stickstoff und Kalium. Gute Düngung hält diese Krankheit oft in Schach.",
        "Halten Sie leichten Schatten, kontrollieren Sie Unkraut und schneiden Sie, damit Luft durchzieht und die Blätter trocknen.",
        "Tragen Sie nach dem Schneiden Blätter und Beeren weg oder verbrennen Sie sie. Häufen Sie sie nicht an den Bäumen auf.",
        "Setzen Sie in der Baumschule die Setzlinge mit Abstand und verbrennen Sie Setzlinge mit braunen Ringflecken.",
        "Wenn es schlimm ist, kann ein Kupferfungizid gesunde Blätter schützen. Fragen Sie zuerst Ihren Beratungsdienst."
      ],
      "urgencyReason": "Sie schwächt vor allem gestresste Bäume und wird meist besser, wenn Düngung und Schatten stimmen."
    },
    "healthy": {
      "name": "Gesundes Kaffeeblatt",
      "look": "Ein gesundes Blatt ist glänzend, oval und spitz, gleichmäßig dunkelgrün, ohne Flecken, Pulver, Löcher oder Gänge, oben wie unten.",
      "actions": [
        "Schneiden Sie und halten Sie leichten Schatten und wenig Unkraut, damit die Blätter schnell trocknen.",
        "Düngen Sie die Bäume mit Mist oder ausgewogenem Dünger, besonders mit Stickstoff und Kalium.",
        "Prüfen Sie Blätter und ihre Unterseiten alle ein bis zwei Wochen, um Rost oder Minierfliegen früh zu erkennen."
      ]
    },
    "miner": {
      "name": "Kaffeeblattminierer",
      "look": "Im Blatt erscheinen hellgelbe, gewundene Gänge, die oben zu unregelmäßigen braunen abgestorbenen Stellen werden. Wenn Sie das Blatt biegen, löst sich die dünne obere Haut über der Stelle und innen finden Sie eine winzige durchsichtige Larve. Starker Befall lässt die Blätter abfallen.",
      "tellApart": "Minierstellen sind papierartige Blasen mit einer Larve darin, die sich beim Biegen lösen, während die braune Augenfleckenkrankheit ein sauberer runder Ring ist, der sich nicht löst.",
      "actions": [
        "Biegen Sie braune Stellen und suchen Sie nach lebenden Larven, besonders in der Trockenzeit.",
        "Schützen Sie natürliche Feinde wie kleine Wespen und Ameisen, indem Sie gemischten Schatten halten und unnötiges Spritzen vermeiden.",
        "Beobachten Sie junge Bäume und Baumschulen genau und entfernen Sie die ersten Stellen früh.",
        "Wenn ein Insektizid nötig ist, fragen Sie Ihren Beratungsdienst, welches Mittel in Ihrem Land erlaubt und sicher ist."
      ],
      "urgencyReason": "Starker Befall führt zu Blattfall und geringerem Ertrag, am schlimmsten in trockenen, heißen Phasen."
    },
    "phoma": {
      "name": "Phoma-Blattfleckenkrankheit",
      "look": "Dunkelbraune bis schwarze Flecken bis 2 cm Breite auf älteren Blättern, mit hellerer Mitte und dunklerem Rand. Die Spitzen junger Triebe werden schwarz und trocknen aus, Blüten können absterben und Beeren fallen ab. Der Schaden kann an der Blattspitze oder am Blattrand beginnen.",
      "tellApart": "Phoma tötet in kalten, windigen Hochlagen auch die Spitzen junger Triebe und die Blüten, während die braune Augenfleckenkrankheit bei Ringflecken bleibt und Triebspitzen nicht austrocknet.",
      "actions": [
        "Pflanzen Sie in windigen Gegenden Windschutzhecken. Windschäden lassen den Pilz eindringen.",
        "Schneiden Sie vertrocknete Triebe und vertrocknete Beeren ab und vernichten Sie sie, und schneiden Sie so, dass die Luft die Blätter trocknen kann.",
        "Düngen Sie die Bäume mit ausgewogenem Dünger, besonders mit Stickstoff und Kalium.",
        "Spritzen Sie in kalten, windigen Jahreszeiten ein Kupferfungizid, bevor die Krankheit auftritt. Fragen Sie Ihren Beratungsdienst nach dem richtigen Zeitpunkt."
      ],
      "urgencyReason": "In kalten, windigen Hochlagen kann sie Triebe und Blüten töten und den Ertrag um 15 bis 43 Prozent senken."
    },
    "rust": {
      "name": "Kaffeeblattrost",
      "look": "Kleine hellgelbe Flecken erscheinen auf der Blattoberseite. Unten hat jeder Fleck eine Stelle mit gelbem bis dunkelorangem Pulver, das am Finger abfärbt. Alte Flecken werden in der Mitte braun und die Blätter fallen früh ab. Er beginnt meist an den unteren Blättern des Baums.",
      "tellApart": "Rost hat orangefarbenes Pulver auf der Blattunterseite, während die braune Augenfleckenkrankheit trockene braune Ringe mit grauweißer Mitte und kein Pulver hat.",
      "actions": [
        "Prüfen Sie oft die Unterseite der unteren Blätter. Frühes Erkennen ist am wichtigsten.",
        "Pflücken Sie Blätter und Äste mit orangefarbenen Flecken ab und verbrennen oder vergraben Sie sie.",
        "Schneiden Sie und lichten Sie Schatten und Unkraut aus, damit Luft durchzieht und die Blätter schneller trocknen.",
        "Düngen Sie die Bäume mit Mist oder ausgewogenem Dünger. Schwache Bäume trifft es härter.",
        "Spritzen Sie ein Kupferfungizid wie Kupferhydroxid auf Ober- und Unterseiten der Blätter, solange weniger als etwa 5 Prozent der Blätter krank sind. Kupfer schützt gesunde Blätter, heilt aber keine kranken. Fragen Sie Ihren Beratungsdienst nach dem richtigen Zeitpunkt.",
        "Fragen Sie für Neupflanzungen Ihren Beratungsdienst nach rostresistenten Sorten wie den Typen Catimor oder Sarchimor."
      ],
      "urgencyReason": "Er breitet sich schnell zwischen Bäumen und Farmen aus, und die Verluste bei anfälligen Sorten können 30 bis 80 Prozent erreichen."
    },
    "mites": {
      "name": "Möglicher Milbenschaden",
      "look": "Das Bild ähnelt Kaffeeblättern, die als Milbenschaden gekennzeichnet sind. Ähnliche Spuren können andere Ursachen haben, daher ist dies nur eine mögliche Übereinstimmung.",
      "actions": [
        "Bitten Sie den Beratungsdienst, beide Blattseiten anzusehen und die Ursache zu bestätigen, bevor Sie eine Behandlung wählen."
      ]
    },
    "weevil": {
      "name": "Möglicher Schaden durch blattfressende Schädlinge",
      "look": "Das Blatt ähnelt Bildern, die als Coco- oder Rüsselkäferschaden gekennzeichnet sind. Dieses Foto kann die Insektenart nicht bestimmen.",
      "actions": [
        "Bitten Sie den Beratungsdienst, das beschädigte Blatt und alle Insekten an der Pflanze anzusehen, bevor Sie eine Behandlung wählen."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Suchen Sie den KEPHIS-Aufkleber auf der Saatgutpackung.",
    "stepScratch": "Rubbeln Sie den Aufkleber frei, damit der Code sichtbar wird.",
    "stepText": "Senden Sie den Code per SMS an {shortCode}. Das ist kostenlos.",
    "result": "KEPHIS antwortet, ob das Saatgut echt ist. Ein echter Code beweist nicht, dass das Saatgut gut gelagert wurde.",
    "coverage": "Das funktioniert für zertifiziertes Saatgut, das in Packungen verkauft wird. Setzlinge aus der Baumschule haben meist keinen Aufkleber, fragen Sie dazu Ihren Feldberater.",
    "noContact": "Fragen Sie Ihren Feldberater, wie Sie prüfen können, ob eine Saatgutpackung echt ist."
  },
  "phoneGreeting": "Hallo, hier ist Leaf Doctor. Ich helfe bei kranken Kaffeepflanzen, und Sie können in Ihrer eigenen Sprache mit mir sprechen. Was sehen Sie auf Ihren Kaffeeblättern?"
});

export default deText;
