// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const esText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Sus hojas se ven sanas",
    "headlineSpray": "{name}: proteja las hojas sanas y limpie",
    "headlinePrune": "{name}: limpie y pode",
    "headlineMonitor": "{name}: siga vigilando",
    "headlineAskOfficer": "{name}: pida a su técnico de campo que revise",
    "headlineNotSure": "La app no está segura. Muestre estas hojas a su técnico de campo",
    "headlineMightBe": "Podría ser {name}, pero no está confirmado. Muestre las hojas a un técnico de campo",
    "headlineRetake": "Tome fotos más claras de más hojas",
    "retakeDaylight": "Pase a la luz del día, no a la sombra profunda ni al sol directo.",
    "retakeSteady": "Sostenga firme el teléfono hasta que la hoja se vea nítida.",
    "retakeFillFrame": "Llene el cuadro con una sola hoja.",
    "sendToOfficer": "Envíe este caso por mensaje de texto al técnico de campo de su cooperativa, o muestre las hojas en persona.",
    "rainReason": "Llovió {n} de los últimos 7 días cerca de usted ({source}). El clima húmedo hace que la roya se propague más rápido.",
    "labelRate": "Use la dosis que indica la etiqueta del producto.",
    "elseBerryDisease": "Antracnosis del fruto del café: mire si los frutos tienen manchas oscuras hundidas.",
    "elseBerryBorer": "Broca del café: busque agujeros pequeños en los frutos.",
    "elseWilt": "Marchitez del café: ramas enteras que se marchitan y mueren.",
    "elseNutrition": "Suelo pobre o falta de nutrientes: amarillamiento en todo el árbol.",
    "smsDecisionSpray": "Decisión: proteger las hojas sanas con cobre a la dosis de la etiqueta y limpiar. Revisar de nuevo en {days} días.",
    "smsDecisionPrune": "Decisión: podar y limpiar. Revisar de nuevo en {days} días.",
    "smsDecisionMonitor": "Decisión: seguir vigilando. Revisar de nuevo en {days} días.",
    "smsDecisionCallOfficer": "Decisión: mostrar las hojas a su técnico de campo."
  },
  "diseases": {
    "cercospora": {
      "name": "Mancha de ojo pardo",
      "look": "Manchas redondas color café, sobre todo en el haz de la hoja, con el centro gris blanquecino y un anillo café oscuro, muchas veces con un halo amarillo. Las manchas miden de 5 a 15 mm de ancho y pueden unirse en grandes zonas muertas. Los frutos tienen manchas oscuras hundidas y maduran demasiado pronto.",
      "tellApart": "La mancha de ojo pardo tiene anillos café secos con el centro gris pálido y no tiene polvo anaranjado, mientras que la roya tiene polvo anaranjado por debajo.",
      "actions": [
        "Alimente bien los árboles, sobre todo con nitrógeno y potasio. Una buena nutrición muchas veces controla esta enfermedad.",
        "Mantenga sombra ligera, controle las malezas y pode para que el aire circule y las hojas se sequen.",
        "Después de podar, saque o queme las hojas y los frutos. No los amontone junto a los árboles.",
        "En el vivero, deje espacio entre las plántulas y queme las que tengan manchas café con anillos.",
        "Si está muy grave, un fungicida de cobre puede proteger las hojas sanas. Antes pregunte a su técnico de extensión."
      ],
      "urgencyReason": "Debilita sobre todo a los árboles con estrés y por lo general mejora cuando se corrigen la nutrición y la sombra."
    },
    "healthy": {
      "name": "Hoja de café sana",
      "look": "Una hoja sana es brillante, ovalada y con punta, de un verde oscuro parejo, sin manchas, polvo, agujeros ni túneles por arriba ni por debajo.",
      "actions": [
        "Pode y mantenga sombra ligera y pocas malezas para que las hojas se sequen rápido.",
        "Alimente los árboles con abono orgánico o fertilizante balanceado, sobre todo con nitrógeno y potasio.",
        "Revise las hojas y su parte de abajo cada una o dos semanas para detectar a tiempo la roya o el minador."
      ]
    },
    "miner": {
      "name": "Minador de la hoja del café",
      "look": "Aparecen caminos sinuosos de color amarillo pálido dentro de la hoja, que se vuelven manchas muertas de color café y forma despareja en el haz. Si dobla la hoja, la piel delgada sobre la mancha se despega y adentro se ve una larva diminuta y transparente. Los ataques fuertes hacen caer las hojas.",
      "tellApart": "Las manchas del minador son ampollas como papel con una larva adentro que se despegan al doblarlas, mientras que la mancha de ojo pardo es un anillo redondo y parejo que no se despega.",
      "actions": [
        "Doble las manchas café para buscar larvas vivas, sobre todo en la época seca.",
        "Proteja a los enemigos naturales, como las avispas pequeñas y las hormigas, manteniendo sombra mixta y evitando fumigar sin necesidad.",
        "Vigile de cerca los árboles jóvenes y los viveros y quite pronto las primeras manchas.",
        "Si hace falta un insecticida, pregunte a su técnico de extensión qué producto es legal y seguro en su país."
      ],
      "urgencyReason": "Los ataques fuertes hacen caer las hojas y bajan la cosecha, sobre todo en períodos secos y calurosos."
    },
    "phoma": {
      "name": "Mancha foliar por Phoma",
      "look": "Manchas de color café oscuro a negro, de hasta 2 cm de ancho, en las hojas más viejas, con el centro más claro y el borde más oscuro. Las puntas de los brotes jóvenes se ponen negras y se secan, las flores pueden morir y los frutos se caen. El daño puede empezar en la punta o en el borde de la hoja.",
      "tellApart": "La Phoma también mata las puntas de los brotes jóvenes y las flores en zonas altas, frías y ventosas, mientras que la mancha de ojo pardo se queda en manchas con anillos y no seca las puntas de los brotes.",
      "actions": [
        "Siembre barreras contra el viento en zonas ventosas. El daño del viento deja entrar al hongo.",
        "Pode y destruya los brotes secos y los frutos momificados, y pode para que el aire seque las hojas.",
        "Alimente los árboles con fertilizante balanceado, sobre todo con nitrógeno y potasio.",
        "En las épocas frías y ventosas, aplique un fungicida de cobre antes de que aparezca la enfermedad. Pregunte a su técnico de extensión cuándo hacerlo."
      ],
      "urgencyReason": "En zonas altas, frías y ventosas puede matar brotes y flores y reducir la cosecha entre 15 y 43 por ciento."
    },
    "rust": {
      "name": "Roya del café",
      "look": "En el haz de la hoja aparecen manchas pequeñas de color amarillo pálido. Por debajo, cada mancha tiene un polvo de color amarillo a naranja oscuro que se pega al dedo al frotarlo. Las manchas viejas se ponen cafés en el centro y las hojas se caen antes de tiempo. Casi siempre empieza en las hojas de abajo del árbol.",
      "tellApart": "La roya tiene polvo anaranjado por debajo de la hoja, mientras que la mancha de ojo pardo tiene anillos café secos con el centro gris blanquecino y no tiene polvo.",
      "actions": [
        "Revise seguido la parte de abajo de las hojas bajas. Lo más importante es detectarla temprano.",
        "Arranque y queme o entierre las hojas y ramas con manchas anaranjadas.",
        "Pode y reduzca la sombra y las malezas para que el aire circule y las hojas se sequen más rápido.",
        "Alimente los árboles con abono orgánico o fertilizante balanceado. Los árboles débiles sufren más.",
        "Aplique un fungicida de cobre, como el hidróxido de cobre, en el haz y el envés de las hojas mientras menos de 5 por ciento de las hojas estén enfermas. El cobre protege las hojas sanas pero no cura las enfermas. Pregunte a su técnico de extensión cuándo hacerlo.",
        "Para sembrar de nuevo, pregunte a su técnico de extensión por variedades resistentes a la roya, como los tipos Catimor o Sarchimor."
      ],
      "urgencyReason": "Se propaga rápido entre árboles y fincas, y en las variedades susceptibles las pérdidas pueden llegar de 30 a 80 por ciento."
    },
    "mites": {
      "name": "Posible daño por ácaros",
      "look": "La imagen se parece a hojas de café marcadas con daño por ácaros. Marcas parecidas pueden tener otras causas, así que esto es una posible coincidencia.",
      "actions": [
        "Pida a un técnico de extensión que revise ambos lados de la hoja y confirme la causa antes de elegir un tratamiento."
      ]
    },
    "weevil": {
      "name": "Posible daño por plaga que come hojas",
      "look": "La hoja se parece a imágenes marcadas con daño de coco o de gorgojo. Esta foto no puede identificar la especie del insecto.",
      "actions": [
        "Pida a un técnico de extensión que revise la hoja dañada y los insectos que haya en la planta antes de elegir un tratamiento."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Busque la etiqueta adhesiva de KEPHIS en el paquete de semillas.",
    "stepScratch": "Raspe la etiqueta para ver el código.",
    "stepText": "Envíe el código por mensaje de texto a {shortCode}. Es gratis.",
    "result": "KEPHIS responde para decir si la semilla es genuina. Un código genuino no prueba que la semilla se haya guardado bien.",
    "coverage": "Esto sirve para semilla certificada que se vende en paquetes. Las plántulas de vivero casi nunca tienen etiqueta, así que pregunte por ellas a su técnico de campo.",
    "noContact": "Pregunte a su técnico de campo cómo revisar si un paquete de semillas es genuino."
  },
  "phoneGreeting": "Hola, le habla Leaf Doctor. Ayudo con las plantas de café enfermas, y puede hablar conmigo en su propio idioma. ¿Qué ve en las hojas de su café?"
});

export default esText;
