// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const etText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Teie lehed näevad terved välja",
    "headlineSpray": "{name}: kaitske terveid lehti ja koristage",
    "headlinePrune": "{name}: koristage ja lõigake oksi",
    "headlineMonitor": "{name}: jälgige edasi",
    "headlineAskOfficer": "{name}: paluge oma välinõustajal kontrollida",
    "headlineNotSure": "Rakendus pole kindel. Näidake neid lehti oma välinõustajale",
    "headlineMightBe": "See võib olla {name}, kuid see pole kinnitatud. Näidake välinõustajale",
    "headlineRetake": "Tehke rohkematest lehtedest selgemaid fotosid",
    "retakeDaylight": "Minge päevavalgusesse, mitte sügavasse varju ega otsesesse päikesesse.",
    "retakeSteady": "Hoidke telefoni paigal, kuni leht on terav.",
    "retakeFillFrame": "Täitke kaader ühe lehega.",
    "sendToOfficer": "Saatke see juhtum SMS-iga oma ühistu välinõustajale või näidake lehti isiklikult.",
    "rainReason": "Teie lähedal sadas viimasest 7 päevast {n} päeval ({source}). Märg ilm paneb rooste kiiremini levima.",
    "labelRate": "Kasutage toote etiketil olevat kogust.",
    "elseBerryDisease": "Kohvimarjade haigus: vaadake, kas marjadel on tumedaid sissevajunud laike.",
    "elseBerryBorer": "Kohvimarjakoi: otsige marjadelt väikseid auke.",
    "elseWilt": "Kohvi närbumine: terved oksad närbuvad ja surevad.",
    "elseNutrition": "Vaene muld või toitainete puudus: kogu puu kolletab.",
    "smsDecisionSpray": "Otsus: kaitske terveid lehti vasega etiketil oleva koguse järgi ja koristage. Kontrollige uuesti {days} päeva pärast.",
    "smsDecisionPrune": "Otsus: lõigake oksi ja koristage. Kontrollige uuesti {days} päeva pärast.",
    "smsDecisionMonitor": "Otsus: jälgige edasi. Kontrollige uuesti {days} päeva pärast.",
    "smsDecisionCallOfficer": "Otsus: näidake oma välinõustajale."
  },
  "diseases": {
    "cercospora": {
      "name": "Pruun silmlaik",
      "look": "Ümmargused pruunid laigud, enamasti lehe pealmisel poolel, halli-valge keskosa ja tumepruuni rõngaga, sageli kollase äärisega. Laigud on 5 kuni 15 mm laiad ja võivad kokku kasvada suurteks surnud aladeks. Marjadele tekivad tumedad sissevajunud laigud ja need valmivad liiga vara.",
      "tellApart": "Pruunil silmlaigul on kuivad pruunid rõngad heleda hallika keskosaga ja oranži pulbrit pole, rooste puhul on aga all oranž pulber.",
      "actions": [
        "Toitke puid hästi, eriti lämmastiku ja kaaliumiga. Hea toitmine tavaliselt ohjab seda haigust.",
        "Hoidke kerget varju, tõrjuge umbrohtu ja lõigake oksi nii, et õhk liiguks ja lehed kuivaksid.",
        "Pärast lõikamist viige lehed ja marjad ära või põletage. Ärge kuhjake neid puude vastu.",
        "Puukoolis istutage tõusmed hõredalt ja põletage tõusmed, millel on rõngastega pruunid laigud.",
        "Kui see on tõsine, võib vaseseenetõrjevahend kaitsta terveid lehti. Küsige kõigepealt oma põllumajandusnõustajalt."
      ],
      "urgencyReason": "See nõrgestab peamiselt stressis puid ja paraneb tavaliselt, kui toitmine ja vari korda saavad."
    },
    "healthy": {
      "name": "Terve kohvipuu leht",
      "look": "Terve leht on läikiv, ovaalne ja teravatipuline, ühtlaselt tumeroheline, ilma laikude, pulbri, aukude või käikudeta pealt ja alt.",
      "actions": [
        "Lõigake oksi ning hoidke kerget varju ja madalat umbrohtu, et lehed kiiresti kuivaksid.",
        "Toitke puid sõnniku või tasakaalustatud väetisega, eriti lämmastiku ja kaaliumiga.",
        "Kontrollige lehti ja nende alumisi külgi iga nädal või kahe tagant, et rooste või lehemineerijat varakult märgata."
      ]
    },
    "miner": {
      "name": "Kohvipuu lehemineerija",
      "look": "Lehe sees ilmuvad kahvatukollased looklevad jäljed, mis muutuvad pealt ebaühtlasteks pruunideks surnud aladeks. Kui lehte painutada, rebeneb ala kohal olev õhuke pealmine nahk lahti ja seest võib leida pisikese läbipaistva röövika. Tugev kahjustus paneb lehed varisema.",
      "tellApart": "Mineerija alad on paberõhukesed villid, mille sees on röövik ja mis painutamisel rebenevad, pruun silmlaik on aga korralik ümmargune rõngas, mis ei rebene.",
      "actions": [
        "Painutage pruune alasid, et otsida elusaid röövikuid, eriti kuival aastaajal.",
        "Kaitske looduslikke vaenlasi, näiteks väikesi herilasi ja sipelgaid, hoides segavarju ja vältides tarbetut pritsimist.",
        "Jälgige noori puid ja puukoole tähelepanelikult ning eemaldage esimesed alad varakult.",
        "Kui putukamürki on vaja, küsige oma põllumajandusnõustajalt, milline toode on teie riigis seaduslik ja ohutu."
      ],
      "urgencyReason": "Tugev kahjustus põhjustab lehtede varisemist ja madalamat saaki, kõige hullem on see kuivadel kuumadel perioodidel."
    },
    "phoma": {
      "name": "Phoma lehelaik",
      "look": "Tumepruunid kuni mustad laigud, kuni 2 cm laiad, vanematel lehtedel, heledama keskosa ja tumedama äärega. Noorte võrsete tipud lähevad mustaks ja kuivavad, õied võivad surra ja marjad varisevad. Kahjustus võib alata lehe tipust või servast.",
      "tellApart": "Phoma tapab külmades tuulistes mägimaades ka noorte võrsete tipud ja õied, pruun silmlaik jääb aga rõngastega laikudeks ega kuivata võrsetippe.",
      "actions": [
        "Istutage tuulistes kohtades tuulekaitset. Tuulekahjustus lubab seenel sisse pääseda.",
        "Lõigake kuivanud võrsed ja mumifitseerunud marjad ära ning hävitage need, ja lõigake oksi nii, et õhk saaks lehti kuivatada.",
        "Toitke puid tasakaalustatud väetisega, eriti lämmastiku ja kaaliumiga.",
        "Külmadel tuulistel aastaaegadel pritsige vaseseenetõrjevahendit enne, kui haigus ilmub. Küsige õige aja kohta oma põllumajandusnõustajalt."
      ],
      "urgencyReason": "Külmades tuulistes mägimaades võib see tappa võrseid ja õisi ning vähendada saaki 15 kuni 43 protsenti."
    },
    "rust": {
      "name": "Kohvipuu lehemrooste",
      "look": "Lehe pealmisele poolele tekivad väikesed kahvatukollased laigud. All on igal laigul kollasest tumeoranžini pulbriplekk, mis jääb sõrme külge. Vanad laigud muutuvad keskelt pruuniks ja lehed varisevad vara. Tavaliselt algab see puu alumistelt lehtedelt.",
      "tellApart": "Roostel on lehe alumisel poolel oranž pulber, pruunil silmlaigul on aga kuivad pruunid rõngad halli-valge keskosaga ja pulbrit pole.",
      "actions": [
        "Kontrollige sageli alumiste lehtede alumist poolt. Kõige tähtsam on see varakult märgata.",
        "Noppige oranžide laikudega lehed ja oksad ära ning põletage või matke need.",
        "Lõigake oksi ning harvendage varju ja umbrohtu, et õhk liiguks ja lehed kuivaksid kiiremini.",
        "Toitke puid sõnniku või tasakaalustatud väetisega. Nõrgad puud saavad tugevamini kannatada.",
        "Pritsige vaseseenetõrjevahendit, näiteks vaskhüdroksiidi, lehtede pealt ja alt, kuni haigeid on alla umbes 5 protsendi lehtedest. Vask kaitseb terveid lehti, kuid ei ravi haigeid. Küsige õige aja kohta oma põllumajandusnõustajalt.",
        "Uue istutuse jaoks küsige oma põllumajandusnõustajalt roostekindlate sortide kohta, näiteks Catimori või Sarchimori tüüpi."
      ],
      "urgencyReason": "See levib kiiresti puude ja talude vahel ning vastuvõtlike sortide kaotused võivad ulatuda 30 kuni 80 protsendini."
    },
    "mites": {
      "name": "Võimalik lestakahjustus",
      "look": "Pilt sarnaneb kohvilehtedele, mis on märgitud lestakahjustusega. Sarnastel jälgedel võivad olla muud põhjused, seega on see võimalik vaste.",
      "actions": [
        "Paluge põllumajandusnõustajal vaadata lehe mõlemat külge ja kinnitada põhjus, enne kui valite ravi."
      ]
    },
    "weevil": {
      "name": "Võimalik lehti närivate kahjurite kahjustus",
      "look": "Leht sarnaneb piltidele, mis on märgitud kookose- või üraskahjustusega. See foto ei suuda putukaliiki kindlaks teha.",
      "actions": [
        "Paluge põllumajandusnõustajal vaadata kahjustatud lehte ja taimel olevaid putukaid, enne kui valite ravi."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Leidke seemnepakendilt KEPHIS-i kleebis.",
    "stepScratch": "Kraapige kleebis lahti, et kood nähtavale tuleks.",
    "stepText": "Saatke kood sõnumiga numbrile {shortCode}. See on tasuta.",
    "result": "KEPHIS vastab, kas seeme on ehtne. Ehtne kood ei tõesta, et seemet on hästi hoitud.",
    "coverage": "See toimib pakendites müüdava sertifitseeritud seemne puhul. Puukooli tõusmetel pole tavaliselt kleebist, seega küsige nende kohta oma välinõustajalt.",
    "noContact": "Küsige oma välinõustajalt, kuidas kontrollida, kas seemnepakend on ehtne."
  },
  "phoneGreeting": "Tere, siin on Leaf Doctor. Aitan haigete kohvitaimedega ja minuga võite rääkida oma keeles. Mida te oma kohvilehtedel näete?"
});

export default etText;
