// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const fiText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Lehtesi näyttävät terveiltä",
    "headlineSpray": "{name}: suojaa terveet lehdet ja siivoa",
    "headlinePrune": "{name}: siivoa ja leikkaa",
    "headlineMonitor": "{name}: seuraa tilannetta",
    "headlineAskOfficer": "{name}: pyydä neuvojaa tarkistamaan",
    "headlineNotSure": "Sovellus ei ole varma. Näytä nämä lehdet neuvojalle",
    "headlineMightBe": "Se voi olla {name}, mutta sitä ei ole varmistettu. Näytä neuvojalle",
    "headlineRetake": "Ota selkeämpiä kuvia useammasta lehdestä",
    "retakeDaylight": "Siirry päivänvaloon, älä syvään varjoon tai suoraan auringonpaisteeseen.",
    "retakeSteady": "Pidä puhelin vakaana, kunnes lehti näkyy terävänä.",
    "retakeFillFrame": "Täytä kuva yhdellä lehdellä.",
    "sendToOfficer": "Lähetä tämä tapaus osuuskuntasi neuvojalle tekstiviestillä tai näytä lehdet henkilökohtaisesti.",
    "rainReason": "Lähelläsi satoi {n} viimeisestä 7 päivästä ({source}). Märkä sää levittää ruostetta nopeammin.",
    "labelRate": "Käytä tuotteen pakkauksessa ilmoitettua annosta.",
    "elseBerryDisease": "Kahvimarjatauti: tarkista marjoista tummat painuneet läikät.",
    "elseBerryBorer": "Kahvimarjan kuoriainen: etsi marjoista pieniä reikiä.",
    "elseWilt": "Kahvin kuihtumistauti: kokonaiset oksat kuihtuvat ja kuolevat.",
    "elseNutrition": "Heikko maa tai ravinteiden puute: koko puu keltaistuu.",
    "smsDecisionSpray": "Päätös: suojaa terveet lehdet kuparilla pakkauksen annoksella ja siivoa. Tarkista uudelleen {days} päivän kuluttua.",
    "smsDecisionPrune": "Päätös: leikkaa ja siivoa. Tarkista uudelleen {days} päivän kuluttua.",
    "smsDecisionMonitor": "Päätös: seuraa tilannetta. Tarkista uudelleen {days} päivän kuluttua.",
    "smsDecisionCallOfficer": "Päätös: näytä neuvojalle."
  },
  "diseases": {
    "cercospora": {
      "name": "Ruskea silmälaikku",
      "look": "Pyöreitä ruskeita laikkuja, enimmäkseen lehden yläpinnalla. Keskusta on harmaanvalkoinen ja reuna tummanruskea rengas, usein keltaisen vyöhykkeen ympäröimänä. Laikut ovat 5–15 mm leveitä ja voivat yhtyä suuriksi kuolleiksi alueiksi. Marjoihin tulee tummia painuneita läiskiä, ja ne kypsyvät liian aikaisin.",
      "tellApart": "Ruskeassa silmälaikussa on kuivia ruskeita renkaita ja vaalean harmaa keskusta, eikä oranssia jauhetta ole, kun taas ruosteessa on oranssia jauhetta lehden alapinnalla.",
      "actions": [
        "Lannoita puut hyvin, erityisesti typellä ja kaliumilla. Hyvä lannoitus usein pitää taudin kurissa.",
        "Pidä kevyt varjostus, torju rikkaruohot ja leikkaa puita, jotta ilma liikkuu ja lehdet kuivuvat.",
        "Leikkaamisen jälkeen vie pois tai polta lehdet ja marjat. Älä kasaa niitä puiden viereen.",
        "Taimitarhassa pidä taimet erillään ja polta taimet, joissa on renkaallisia ruskeita laikkuja.",
        "Jos tauti on paha, kuparipohjainen sienitautien torjunta-aine voi suojata terveet lehdet. Kysy ensin neuvojalta."
      ],
      "urgencyReason": "Se heikentää lähinnä stressaantuneita puita ja yleensä paranee, kun lannoitus ja varjostus saadaan kuntoon."
    },
    "healthy": {
      "name": "Terve kahvin lehti",
      "look": "Terve lehti on kiiltävä, soikea ja suippo, tasaisen tummanvihreä, eikä siinä ole laikkuja, jauhetta, reikiä tai käytäviä ylä- tai alapinnalla.",
      "actions": [
        "Leikkaa puita ja pidä varjostus kevyenä ja rikkaruohot vähissä, jotta lehdet kuivuvat nopeasti.",
        "Lannoita puut lannalla tai tasapainoisella lannoitteella, erityisesti typellä ja kaliumilla.",
        "Tarkista lehdet ja niiden alapinnat viikon tai kahden välein, jotta huomaat ruosteen tai lehtikaivajan ajoissa."
      ]
    },
    "miner": {
      "name": "Kahvin lehtikaivaja",
      "look": "Lehden sisään ilmestyy vaaleankeltaisia mutkittelevia käytäviä, jotka muuttuvat epätasaisiksi ruskeiksi kuolleiksi laikuiksi yläpinnalla. Kun taivutat lehteä, laikun päällä oleva ohut yläkalvo repeää auki, ja sisältä löytyy pieni läpinäkyvä toukka. Vakavat hyökkäykset saavat lehdet putoamaan.",
      "tellApart": "Kaivajan laikut ovat paperimaisia rakkuloita, joiden sisällä on toukka ja jotka repeävät taivutettaessa, kun taas ruskea silmälaikku on siisti pyöreä rengas, joka ei repeä.",
      "actions": [
        "Taivuta ruskeita laikkuja ja etsi eläviä toukkia, erityisesti kuivana aikana.",
        "Suojele luonnollisia vihollisia, kuten pieniä ampiaisia ja muurahaisia, pitämällä sekavarjostus ja välttämällä turhaa ruiskutusta.",
        "Seuraa nuoria puita ja taimitarhoja tarkasti ja poista ensimmäiset laikut ajoissa.",
        "Jos hyönteismyrkkyä tarvitaan, kysy neuvojalta, mikä valmiste on laillinen ja turvallinen maassasi."
      ],
      "urgencyReason": "Vakavat hyökkäykset aiheuttavat lehtien putoamista ja pienentävät satoa, pahiten kuivina ja kuumina jaksoina."
    },
    "phoma": {
      "name": "Phoma-lehtilaikku",
      "look": "Tummanruskeita tai mustia, jopa 2 cm leveitä laikkuja vanhemmilla lehdillä. Keskusta on vaaleampi ja reuna tummempi. Nuorten versojen kärjet mustuvat ja kuivuvat, kukat voivat kuolla ja marjat putoavat. Vaurio voi alkaa lehden kärjestä tai reunasta.",
      "tellApart": "Phoma tappaa myös nuorten versojen kärjet ja kukat kylmillä, tuulisilla ylängöillä, kun taas ruskea silmälaikku pysyy renkaallisina laikkuina eikä kuivata verson kärkiä.",
      "actions": [
        "Istuta tuulensuojia tuulisille alueille. Tuulen aiheuttama vaurio päästää sienen sisään.",
        "Leikkaa pois ja tuhoa kuivuneet versot ja kuivettuneet marjat sekä leikkaa puita, jotta ilma kuivattaa lehdet.",
        "Lannoita puut tasapainoisella lannoitteella, erityisesti typellä ja kaliumilla.",
        "Kylminä tuulisina kausina ruiskuta kuparipohjaista sienitautien torjunta-ainetta ennen taudin ilmestymistä. Kysy neuvojalta ajoituksesta."
      ],
      "urgencyReason": "Kylmillä tuulisilla ylängöillä se voi tappaa versoja ja kukkia ja vähentää satoa 15–43 prosenttia."
    },
    "rust": {
      "name": "Kahvin lehtiruoste",
      "look": "Lehden yläpinnalle ilmestyy pieniä vaaleankeltaisia laikkuja. Alapinnalla jokaisessa laikussa on keltaisesta tummanoranssiin vaihtelevaa jauhetta, joka tarttuu sormeen. Vanhojen laikkujen keskusta muuttuu ruskeaksi ja lehdet putoavat ennenaikaisesti. Tauti alkaa yleensä puun alimmista lehdistä.",
      "tellApart": "Ruosteessa on oranssia jauhetta lehden alapinnalla, kun taas ruskeassa silmälaikussa on kuivia ruskeita renkaita, harmaanvalkoinen keskusta ja ei jauhetta.",
      "actions": [
        "Tarkista alimpien lehtien alapinnat usein. Varhainen havaitseminen on tärkeintä.",
        "Poimi ja polta tai hautaa lehdet ja oksat, joissa on oransseja laikkuja.",
        "Leikkaa ja harvenna varjostusta ja rikkaruohoja, jotta ilma liikkuu ja lehdet kuivuvat nopeammin.",
        "Lannoita puut lannalla tai tasapainoisella lannoitteella. Heikkoihin puihin tauti iskee kovemmin.",
        "Ruiskuta kuparipohjaista sienitautien torjunta-ainetta, kuten kuparihydroksidia, lehtien ylä- ja alapinnoille, kun alle noin 5 prosenttia lehdistä on sairaita. Kupari suojaa terveitä lehtiä mutta ei paranna sairaita. Kysy neuvojalta ajoituksesta.",
        "Uutta istutusta varten kysy neuvojalta ruosteenkestävistä lajikkeista, kuten Catimor- tai Sarchimor-tyypeistä."
      ],
      "urgencyReason": "Se leviää nopeasti puiden ja tilojen välillä, ja alttiilla lajikkeilla tappiot voivat nousta 30–80 prosenttiin."
    },
    "mites": {
      "name": "Mahdollinen punkkivaurio",
      "look": "Kuva muistuttaa kahvin lehtiä, jotka on merkitty punkkivaurioiksi. Samanlaisilla jäljillä voi olla muitakin syitä, joten tämä on vain mahdollinen vastaavuus.",
      "actions": [
        "Pyydä neuvojaa tarkistamaan lehden molemmat puolet ja varmistamaan syy ennen hoidon valintaa."
      ]
    },
    "weevil": {
      "name": "Mahdollinen lehtiä syövän tuholaisen vaurio",
      "look": "Lehti muistuttaa kuvia, jotka on merkitty coco- tai kärsäkäsvaurioiksi. Tämä kuva ei pysty tunnistamaan hyönteislajia.",
      "actions": [
        "Pyydä neuvojaa tarkistamaan vahingoittunut lehti ja kasvilla olevat hyönteiset ennen hoidon valintaa."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Etsi KEPHIS-tarra siemenpakkauksesta.",
    "stepScratch": "Raaputa tarra, niin koodi tulee näkyviin.",
    "stepText": "Lähetä koodi tekstiviestillä numeroon {shortCode}. Se on ilmaista.",
    "result": "KEPHIS vastaa ja kertoo, onko siemen aito. Aito koodi ei todista, että siemen on säilytetty hyvin.",
    "coverage": "Tämä toimii pakkauksissa myytävälle sertifioidulle siemenelle. Taimitarhan taimissa ei yleensä ole tarraa, joten kysy niistä neuvojalta.",
    "noContact": "Kysy neuvojalta, miten voit tarkistaa, onko siemenpakkaus aito."
  },
  "phoneGreeting": "Hei, tässä on Leaf Doctor. Autan sairaiden kahvikasvien kanssa, ja voit puhua minulle omalla kielelläsi. Mitä näet kahvin lehdissäsi?"
});

export default fiText;
