// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const filText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Mukhang malusog ang mga dahon mo",
    "headlineSpray": "{name}: protektahan ang malulusog na dahon at maglinis",
    "headlinePrune": "{name}: maglinis at magputol ng sanga",
    "headlineMonitor": "{name}: patuloy na bantayan",
    "headlineAskOfficer": "{name}: ipasuri sa opisyal mo sa bukid",
    "headlineNotSure": "Hindi tiyak ang app. Ipakita ang mga dahong ito sa opisyal mo sa bukid",
    "headlineMightBe": "Maaaring ito ay {name}, pero hindi pa kumpirmado. Ipakita sa opisyal sa bukid",
    "headlineRetake": "Kumuha ng mas malilinaw na litrato ng mas maraming dahon",
    "retakeDaylight": "Lumipat sa liwanag ng araw, hindi sa napakadilim na lilim o direktang araw.",
    "retakeSteady": "Hawakan nang matatag ang telepono hanggang maging malinaw ang dahon.",
    "retakeFillFrame": "Punuin ang frame ng isang dahon.",
    "sendToOfficer": "Ipadala ang kasong ito sa opisyal sa bukid ng kooperatiba mo sa pamamagitan ng SMS, o ipakita nang personal ang mga dahon.",
    "rainReason": "Umulan sa {n} sa nakaraang 7 araw malapit sa iyo ({source}). Mas mabilis kumalat ang kalawang kapag basa ang panahon.",
    "labelRate": "Gamitin ang dami na nakasulat sa label ng produkto.",
    "elseBerryDisease": "Sakit ng bunga ng kape: tingnan sa mga bunga ang madidilim at lubog na batik.",
    "elseBerryBorer": "Mga uod sa bunga ng kape: hanapin ang maliliit na butas sa mga bunga.",
    "elseWilt": "Pagkalanta ng kape: nalalanta at namamatay ang buong sanga.",
    "elseNutrition": "Mahinang lupa o kulang sa sustansya: nagdidilaw ang buong puno.",
    "smsDecisionSpray": "Desisyon: protektahan ang malulusog na dahon gamit ang tanso sa dami na nasa label at maglinis. Suriin ulit sa loob ng {days} araw.",
    "smsDecisionPrune": "Desisyon: magputol ng sanga at maglinis. Suriin ulit sa loob ng {days} araw.",
    "smsDecisionMonitor": "Desisyon: patuloy na bantayan. Suriin ulit sa loob ng {days} araw.",
    "smsDecisionCallOfficer": "Desisyon: ipakita sa opisyal mo sa bukid."
  },
  "diseases": {
    "cercospora": {
      "name": "Batik na parang mata na kayumanggi",
      "look": "Bilog na kayumangging batik, kadalasan sa ibabaw ng dahon, na may kulay abong-puting gitna at madilim na kayumangging singsing, madalas may dilaw na palibot. Ang mga batik ay 5 hanggang 15 mm ang lapad at maaaring magdugtong-dugtong at maging malalaking patay na bahagi. Ang mga bunga ay nagkakaroon ng madilim at lubog na mantsa at maagang humihinog.",
      "tellApart": "Ang batik na parang mata na kayumanggi ay may tuyong kayumangging singsing at maputlang kulay abong gitna at walang kulay kahel na pulbos, samantalang ang kalawang ay may kulay kahel na pulbos sa ilalim.",
      "actions": [
        "Pakainin nang mabuti ang mga puno, lalo na ng nitrogen at potassium. Madalas napipigilan ng mabuting pagpapakain ang sakit na ito.",
        "Panatilihin ang kaunting lilim, kontrolin ang damo, at magputol ng sanga para makagalaw ang hangin at matuyo ang mga dahon.",
        "Pagkatapos magputol, dalhin palayo o sunugin ang mga dahon at bunga. Huwag itambak sa tabi ng mga puno.",
        "Sa nursery, pagitan-pagitan ang mga punla at sunugin ang mga punlang may kayumangging singsing na batik.",
        "Kung malala, maaaring protektahan ng fungicide na tanso ang malulusog na dahon. Magtanong muna sa extension officer mo."
      ],
      "urgencyReason": "Pangunahing pinahihina nito ang mga punong stressed at kadalasang gumagaling kapag naayos ang pagpapakain at lilim."
    },
    "healthy": {
      "name": "Malusog na dahon ng kape",
      "look": "Ang malusog na dahon ay makintab, hugis-itlog at matulis, pantay ang kulay na madilim na berde, at walang batik, pulbos, butas o lagusan sa ibabaw o sa ilalim.",
      "actions": [
        "Magputol ng sanga at panatilihin ang kaunting lilim at mababang damo para mabilis matuyo ang mga dahon.",
        "Pakainin ang mga puno ng dumi ng hayop o balanseng pataba, lalo na ng nitrogen at potassium.",
        "Suriin ang mga dahon at ang ilalim nito tuwing isa o dalawang linggo para maagang mahuli ang kalawang o leaf miner."
      ]
    },
    "miner": {
      "name": "Leaf miner ng kape",
      "look": "Lumilitaw sa loob ng dahon ang maputlang dilaw na paliko-likong landas at nagiging hindi pantay na patay na kayumangging bahagi sa ibabaw. Kapag ibinaluktot mo ang dahon, naghihiwalay ang manipis na balat sa ibabaw ng bahaging iyon at makikita mo ang maliit na uod na halos transparent sa loob. Ang matinding atake ay nagpapalagas ng mga dahon.",
      "tellApart": "Ang mga bahagi ng miner ay parang papel na paltos na may uod sa loob at naghihiwalay kapag ibinaluktot, samantalang ang batik na parang mata na kayumanggi ay maayos na bilog na singsing na hindi naghihiwalay.",
      "actions": [
        "Ibaluktot ang mga kayumangging bahagi para hanapin ang buhay na uod, lalo na sa tag-init.",
        "Protektahan ang mga likas na kaaway nito tulad ng maliliit na putakti at langgam sa pamamagitan ng paggamit ng halu-halong lilim at pag-iwas sa hindi kailangang pag-spray.",
        "Bantayang mabuti ang mga batang puno at nursery at alisin nang maaga ang mga unang apektadong bahagi.",
        "Kung kailangan ng pamatay-insekto, magtanong sa extension officer mo kung aling produkto ang legal at ligtas sa bansa mo."
      ],
      "urgencyReason": "Ang matinding atake ay nagdudulot ng pagkalagas ng dahon at pagbaba ng ani, pinakamalala sa mainit at tuyong panahon."
    },
    "phoma": {
      "name": "Batik ng dahon na Phoma",
      "look": "Madilim na kayumanggi hanggang itim na batik na hanggang 2 cm ang lapad sa mas matatandang dahon, na may mas maliwanag na gitna at mas madilim na gilid. Ang dulo ng mga batang usbong ay nagiging itim at natutuyo, maaaring mamatay ang mga bulaklak, at nalalaglag ang mga bunga. Maaaring magsimula ang pinsala sa dulo o gilid ng dahon.",
      "tellApart": "Pinapatay din ng Phoma ang dulo ng mga batang usbong at mga bulaklak sa malamig at mahangin na kabundukan, samantalang ang batik na parang mata na kayumanggi ay nananatiling may singsing na batik at hindi tinutuyo ang dulo ng usbong.",
      "actions": [
        "Magtanim ng mga pananggalang sa hangin sa mahangin na lugar. Ang pinsala ng hangin ang nagpapapasok sa fungus.",
        "Putulin at sirain ang mga tuyong usbong at mummified na bunga, at magputol ng sanga para matuyo ng hangin ang mga dahon.",
        "Pakainin ang mga puno ng balanseng pataba, lalo na ng nitrogen at potassium.",
        "Sa malamig at mahangin na panahon, mag-spray ng fungicide na tanso bago lumitaw ang sakit. Magtanong sa extension officer mo tungkol sa tamang oras."
      ],
      "urgencyReason": "Sa malamig at mahangin na kabundukan, maaari nitong patayin ang mga usbong at bulaklak at bawasan ang ani ng 15 hanggang 43 porsiyento."
    },
    "rust": {
      "name": "Kalawang ng dahon ng kape",
      "look": "Lumilitaw ang maliliit na maputlang dilaw na batik sa ibabaw ng dahon. Sa ilalim, bawat batik ay may bahagi ng dilaw hanggang madilim na kahel na pulbos na nagkikiskis sa daliri mo. Ang mga lumang batik ay nagiging kayumanggi sa gitna at maagang nalalaglag ang mga dahon. Kadalasang nagsisimula ito sa mga mababang dahon ng puno.",
      "tellApart": "Ang kalawang ay may kulay kahel na pulbos sa ilalim ng dahon, samantalang ang batik na parang mata na kayumanggi ay may tuyong kayumangging singsing na may kulay abong-puting gitna at walang pulbos.",
      "actions": [
        "Madalas na tingnan ang ilalim ng mga mababang dahon. Pinakamahalaga ang maagang pagtuklas.",
        "Pitasin at sunugin o ilibing ang mga dahon at sanga na may kulay kahel na batik.",
        "Magputol ng sanga at bawasan ang lilim at damo para makagalaw ang hangin at mas mabilis matuyo ang mga dahon.",
        "Pakainin ang mga puno ng dumi ng hayop o balanseng pataba. Mas matindi ang tama sa mahihinang puno.",
        "Mag-spray ng fungicide na tanso tulad ng copper hydroxide sa ibabaw at ilalim ng mga dahon habang wala pang mga 5 porsiyento ng mga dahon ang may sakit. Pinoprotektahan ng tanso ang malulusog na dahon pero hindi nito pinagagaling ang may sakit. Magtanong sa extension officer mo tungkol sa tamang oras.",
        "Para sa bagong tanim, magtanong sa extension officer mo tungkol sa mga barayting lumalaban sa kalawang tulad ng uri ng Catimor o Sarchimor."
      ],
      "urgencyReason": "Mabilis itong kumakalat sa pagitan ng mga puno at sakahan, at ang pagkalugi sa mga barayting madaling tamaan ay maaaring umabot sa 30 hanggang 80 porsiyento."
    },
    "mites": {
      "name": "Posibleng pinsala ng mite",
      "look": "Kahawig ng larawan ang mga dahon ng kape na may markang pinsala ng mite. Maaaring may ibang sanhi ang magkakahawig na marka, kaya posibleng tugma lang ito.",
      "actions": [
        "Magpasuri sa extension officer ng magkabilang gilid ng dahon at ipakumpirma ang sanhi bago pumili ng gagamiting lunas."
      ]
    },
    "weevil": {
      "name": "Posibleng pinsala ng peste na ngumunguya ng dahon",
      "look": "Kahawig ng dahon ang mga larawang may markang pinsala ng coco o weevil. Hindi matukoy ng litratong ito ang uri ng insekto.",
      "actions": [
        "Magpasuri sa extension officer ng nasirang dahon at ng anumang insekto sa halaman bago pumili ng gagamiting lunas."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Hanapin ang sticker ng KEPHIS sa pakete ng binhi.",
    "stepScratch": "Kayurin ang sticker para lumabas ang code.",
    "stepText": "I-text ang code sa {shortCode}. Libre ito.",
    "result": "Sumasagot ang KEPHIS kung tunay ang binhi. Hindi patunay ang tunay na code na maayos na naitabi ang binhi.",
    "coverage": "Gumagana ito para sa sertipikadong binhing ibinebenta sa pakete. Kadalasang walang sticker ang mga punla sa nursery, kaya magtanong sa opisyal mo sa bukid tungkol sa mga ito.",
    "noContact": "Tanungin ang opisyal mo sa bukid kung paano malalaman kung tunay ang pakete ng binhi."
  },
  "phoneGreeting": "Magandang araw po, ito ang Leaf Doctor. Tumutulong ako sa mga may sakit na tanim na kape, at maaari ninyo akong kausapin sa sarili ninyong wika. Ano po ang nakikita ninyo sa mga dahon ng kape ninyo?"
});

export default filText;
