// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const frText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Vos feuilles ont l'air saines",
    "headlineSpray": "{name} : protégez les feuilles saines et nettoyez",
    "headlinePrune": "{name} : nettoyez et taillez",
    "headlineMonitor": "{name} : continuez à surveiller",
    "headlineAskOfficer": "{name} : demandez à votre conseiller de terrain de vérifier",
    "headlineNotSure": "L'application n'est pas sûre. Montrez ces feuilles à votre conseiller de terrain",
    "headlineMightBe": "Ce pourrait être {name}, mais ce n'est pas confirmé. Montrez-le à un conseiller de terrain",
    "headlineRetake": "Prenez des photos plus nettes de plus de feuilles",
    "retakeDaylight": "Allez à la lumière du jour, pas dans l'ombre épaisse ni en plein soleil.",
    "retakeSteady": "Tenez le téléphone immobile jusqu'à ce que la feuille soit nette.",
    "retakeFillFrame": "Remplissez le cadre avec une seule feuille.",
    "sendToOfficer": "Envoyez ce dossier par SMS au conseiller de terrain de votre coopérative, ou montrez-lui les feuilles en personne.",
    "rainReason": "Il a plu {n} jours sur les 7 derniers jours près de chez vous ({source}). Le temps humide fait se propager la rouille plus vite.",
    "labelRate": "Utilisez la dose indiquée sur l'étiquette du produit.",
    "elseBerryDisease": "Anthracnose des baies du caféier : regardez si les baies ont des taches sombres et enfoncées.",
    "elseBerryBorer": "Scolyte des baies du caféier : cherchez de petits trous dans les baies.",
    "elseWilt": "Flétrissement du caféier : des branches entières se flétrissent et meurent.",
    "elseNutrition": "Sol pauvre ou manque d'éléments nutritifs : jaunissement de tout l'arbre.",
    "smsDecisionSpray": "Décision : protéger les feuilles saines avec du cuivre à la dose de l'étiquette et nettoyer. Vérifier à nouveau dans {days} jours.",
    "smsDecisionPrune": "Décision : tailler et nettoyer. Vérifier à nouveau dans {days} jours.",
    "smsDecisionMonitor": "Décision : continuer à surveiller. Vérifier à nouveau dans {days} jours.",
    "smsDecisionCallOfficer": "Décision : montrer à votre conseiller de terrain."
  },
  "diseases": {
    "cercospora": {
      "name": "Tache brune en œil",
      "look": "Taches rondes brunes, surtout sur le dessus de la feuille, avec un centre gris-blanc et un anneau brun foncé, souvent entourées d'un halo jaune. Les taches font 5 à 15 mm de large et peuvent se rejoindre en grandes zones mortes. Les baies ont des taches sombres et enfoncées et mûrissent trop tôt.",
      "tellApart": "La tache brune en œil a des anneaux bruns secs avec un centre gris pâle et pas de poudre orange, alors que la rouille a de la poudre orange en dessous.",
      "actions": [
        "Nourrissez bien les arbres, surtout avec de l'azote et du potassium. Une bonne fertilisation maîtrise souvent cette maladie.",
        "Gardez une ombre légère, contrôlez les mauvaises herbes et taillez pour que l'air circule et que les feuilles sèchent.",
        "Après la taille, emportez ou brûlez les feuilles et les baies. Ne les entassez pas contre les arbres.",
        "En pépinière, espacez les plants et brûlez ceux qui ont des taches brunes en anneau.",
        "Si c'est grave, un fongicide à base de cuivre peut protéger les feuilles saines. Demandez d'abord à votre agent de vulgarisation."
      ],
      "urgencyReason": "Elle affaiblit surtout les arbres stressés et s'améliore en général quand la fertilisation et l'ombre sont corrigées."
    },
    "healthy": {
      "name": "Feuille de caféier saine",
      "look": "Une feuille saine est brillante, ovale et pointue, d'un vert foncé uniforme, sans taches, poudre, trous ni galeries, dessus comme dessous.",
      "actions": [
        "Taillez et gardez une ombre légère et peu de mauvaises herbes pour que les feuilles sèchent vite.",
        "Nourrissez les arbres avec du fumier ou un engrais équilibré, surtout riche en azote et en potassium.",
        "Examinez les feuilles et leur face du dessous chaque semaine ou toutes les deux semaines pour repérer tôt la rouille ou la mineuse."
      ]
    },
    "miner": {
      "name": "Mineuse des feuilles du caféier",
      "look": "Des galeries jaune pâle et sinueuses apparaissent à l'intérieur de la feuille et deviennent des zones brunes mortes et irrégulières sur le dessus. Si vous pliez la feuille, la fine peau au-dessus de la zone se décolle et vous pouvez trouver une minuscule larve transparente à l'intérieur. Les fortes attaques font tomber les feuilles.",
      "tellApart": "Les zones de mineuse sont des cloques comme du papier, avec une larve à l'intérieur, qui se décollent quand on plie, alors que la tache brune en œil est un anneau net et rond qui ne se décolle pas.",
      "actions": [
        "Pliez les zones brunes pour chercher des larves vivantes, surtout en saison sèche.",
        "Protégez les ennemis naturels comme les petites guêpes et les fourmis en gardant une ombre mélangée et en évitant les traitements inutiles.",
        "Surveillez de près les jeunes arbres et les pépinières et enlevez tôt les premières zones atteintes.",
        "Si un insecticide est nécessaire, demandez à votre agent de vulgarisation quel produit est légal et sûr dans votre pays."
      ],
      "urgencyReason": "Les fortes attaques font tomber les feuilles et baissent le rendement, surtout pendant les périodes sèches et chaudes."
    },
    "phoma": {
      "name": "Tache foliaire à Phoma",
      "look": "Taches brun foncé à noires, jusqu'à 2 cm de large, sur les feuilles plus âgées, avec un centre plus clair et un bord plus foncé. Le bout des jeunes pousses noircit et se dessèche, les fleurs peuvent mourir et les baies tombent. Les dégâts peuvent commencer par le bout ou le bord de la feuille.",
      "tellApart": "Le Phoma tue aussi le bout des jeunes pousses et les fleurs dans les hautes terres froides et venteuses, alors que la tache brune en œil reste en taches à anneaux et ne dessèche pas le bout des pousses.",
      "actions": [
        "Plantez des brise-vent dans les zones venteuses. Les dégâts du vent laissent entrer le champignon.",
        "Coupez et détruisez les pousses sèches et les baies momifiées, et taillez pour que l'air sèche les feuilles.",
        "Nourrissez les arbres avec un engrais équilibré, surtout riche en azote et en potassium.",
        "Pendant les saisons froides et venteuses, pulvérisez un fongicide à base de cuivre avant que la maladie n'apparaisse. Demandez le bon moment à votre agent de vulgarisation."
      ],
      "urgencyReason": "Dans les hautes terres froides et venteuses, elle peut tuer les pousses et les fleurs et réduire le rendement de 15 à 43 pour cent."
    },
    "rust": {
      "name": "Rouille du caféier",
      "look": "De petites taches jaune pâle apparaissent sur le dessus de la feuille. En dessous, chaque tache a une plaque de poudre jaune à orange foncé qui reste sur le doigt quand on frotte. Les vieilles taches deviennent brunes au milieu et les feuilles tombent tôt. Elle commence en général sur les feuilles du bas de l'arbre.",
      "tellApart": "La rouille a de la poudre orange sous la feuille, alors que la tache brune en œil a des anneaux bruns secs avec un centre gris-blanc et pas de poudre.",
      "actions": [
        "Regardez souvent le dessous des feuilles du bas. Repérer la maladie tôt est ce qui compte le plus.",
        "Cueillez et brûlez ou enterrez les feuilles et les branches qui ont des taches orange.",
        "Taillez et éclaircissez l'ombre et les mauvaises herbes pour que l'air circule et que les feuilles sèchent plus vite.",
        "Nourrissez les arbres avec du fumier ou un engrais équilibré. Les arbres faibles sont plus touchés.",
        "Pulvérisez un fongicide à base de cuivre, comme l'hydroxyde de cuivre, sur le dessus et le dessous des feuilles tant que moins d'environ 5 pour cent des feuilles sont malades. Le cuivre protège les feuilles saines mais ne guérit pas les feuilles malades. Demandez le bon moment à votre agent de vulgarisation.",
        "Pour une nouvelle plantation, demandez à votre agent de vulgarisation des variétés résistantes à la rouille, comme les types Catimor ou Sarchimor."
      ],
      "urgencyReason": "Elle se propage vite d'un arbre et d'une exploitation à l'autre, et les pertes sur les variétés sensibles peuvent atteindre 30 à 80 pour cent."
    },
    "mites": {
      "name": "Dégâts possibles d'acariens",
      "look": "L'image ressemble à des feuilles de caféier notées comme abîmées par des acariens. Des marques semblables peuvent avoir d'autres causes, donc c'est une correspondance possible.",
      "actions": [
        "Demandez à un agent de vulgarisation d'examiner les deux faces de la feuille et de confirmer la cause avant de choisir un traitement."
      ]
    },
    "weevil": {
      "name": "Dégâts possibles d'un ravageur qui ronge les feuilles",
      "look": "La feuille ressemble à des images notées comme des dégâts de coco ou de charançon. Cette photo ne permet pas d'identifier l'espèce d'insecte.",
      "actions": [
        "Demandez à un agent de vulgarisation d'examiner la feuille abîmée et les insectes présents sur la plante avant de choisir un traitement."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Trouvez l'autocollant KEPHIS sur le sachet de semences.",
    "stepScratch": "Grattez l'autocollant pour faire apparaître le code.",
    "stepText": "Envoyez le code par SMS au {shortCode}. C'est gratuit.",
    "result": "KEPHIS répond pour dire si la semence est authentique. Un code authentique ne prouve pas que la semence a été bien conservée.",
    "coverage": "Cela marche pour les semences certifiées vendues en sachets. Les plants de pépinière n'ont en général pas d'autocollant, alors demandez à votre conseiller de terrain.",
    "noContact": "Demandez à votre conseiller de terrain comment vérifier si un sachet de semences est authentique."
  },
  "phoneGreeting": "Bonjour, ici Leaf Doctor. J'aide pour les caféiers malades, et vous pouvez me parler dans votre langue. Que voyez-vous sur les feuilles de vos caféiers ?"
});

export default frText;
