// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const glText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "As túas follas parecen sas",
    "headlineSpray": "{name}: protexe as follas sas e limpa",
    "headlinePrune": "{name}: limpa e poda",
    "headlineMonitor": "{name}: segue vixiando",
    "headlineAskOfficer": "{name}: pídelle ao teu técnico de campo que o revise",
    "headlineNotSure": "A aplicación non está segura. Móstralle estas follas ao teu técnico de campo",
    "headlineMightBe": "Podería ser {name}, pero non está confirmado. Móstrallo a un técnico de campo",
    "headlineRetake": "Saca fotos máis claras de máis follas",
    "retakeDaylight": "Vai á luz do día, non á sombra profunda nin ao sol directo.",
    "retakeSteady": "Mantén o teléfono quieto ata que a folla se vexa nítida.",
    "retakeFillFrame": "Enche o cadro cunha soa folla.",
    "sendToOfficer": "Envía este caso por mensaxe de texto ao técnico de campo da túa cooperativa, ou móstralle as follas en persoa.",
    "rainReason": "Choveu {n} dos últimos 7 días preto de ti ({source}). O tempo húmido fai que a ferruxe se espalle máis rápido.",
    "labelRate": "Usa a dose que indica a etiqueta do produto.",
    "elseBerryDisease": "Enfermidade das bagas do café: mira se as bagas teñen manchas escuras e afundidas.",
    "elseBerryBorer": "Broca do café: busca pequenos buratos nas bagas.",
    "elseWilt": "Murchamento do café: ramas enteiras que murchan e morren.",
    "elseNutrition": "Solo pobre ou falta de nutrientes: amarelecemento de toda a árbore.",
    "smsDecisionSpray": "Decisión: protexer as follas sas con cobre na dose da etiqueta e limpar. Revisar de novo en {days} días.",
    "smsDecisionPrune": "Decisión: podar e limpar. Revisar de novo en {days} días.",
    "smsDecisionMonitor": "Decisión: seguir vixiando. Revisar de novo en {days} días.",
    "smsDecisionCallOfficer": "Decisión: mostrarllo ao técnico de campo."
  },
  "diseases": {
    "cercospora": {
      "name": "Mancha ollo de ra marrón",
      "look": "Manchas redondas marróns, sobre todo na cara de arriba da folla, cun centro gris esbrancuxado e un anel marrón escuro, a miúdo cun halo amarelo. As manchas miden de 5 a 15 mm de ancho e poden unirse en grandes zonas mortas. As bagas teñen manchas escuras e afundidas e maduran demasiado cedo.",
      "tellApart": "A mancha ollo de ra marrón ten aneis marróns secos cun centro gris claro e sen po laranxa, mentres que a ferruxe ten po laranxa por debaixo.",
      "actions": [
        "Aboa ben as árbores, sobre todo con nitróxeno e potasio. Unha boa adubación adoita controlar esta enfermidade.",
        "Mantén unha sombra lixeira, controla as malas herbas e poda para que circule o aire e as follas sequen.",
        "Despois de podar, leva lonxe ou queima as follas e as bagas. Non as amontoes xunto ás árbores.",
        "No viveiro, deixa espazo entre as plantas novas e queima as que teñan manchas marróns con aneis.",
        "Se é grave, un funxicida de cobre pode protexer as follas sas. Pregúntalle primeiro ao teu axente de extensión."
      ],
      "urgencyReason": "Debilita sobre todo as árbores con estrés e adoita mellorar cando se arranxan a adubación e a sombra."
    },
    "healthy": {
      "name": "Folla de café sa",
      "look": "Unha folla sa é brillante, oval e puntiaguda, dun verde escuro uniforme, sen manchas, po, buratos nin túneles por arriba nin por debaixo.",
      "actions": [
        "Poda e mantén unha sombra lixeira e poucas malas herbas para que as follas sequen axiña.",
        "Aboa as árbores con esterco ou un adubo equilibrado, sobre todo con nitróxeno e potasio.",
        "Revisa as follas e o seu envés cada semana ou cada dúas semanas para detectar a tempo a ferruxe ou o minador."
      ]
    },
    "miner": {
      "name": "Minador da folla do café",
      "look": "Aparecen galerías amarelas pálidas e sinuosas dentro da folla, que se converten en zonas marróns mortas e irregulares por arriba. Se dobras a folla, a pel fina que cobre a zona desprégase e podes atopar dentro unha larva minúscula e transparente. Os ataques fortes fan caer as follas.",
      "tellApart": "As zonas do minador son ampolas coma papel, cunha larva dentro, que se despregan ao dobrar, mentres que a mancha ollo de ra marrón é un anel limpo e redondo que non se despega.",
      "actions": [
        "Dobra as zonas marróns para buscar larvas vivas, sobre todo na estación seca.",
        "Protexe os inimigos naturais, como as avespas pequenas e as formigas, mantendo sombra mixta e evitando fumigar sen necesidade.",
        "Vixía de preto as árbores novas e os viveiros e quita cedo as primeiras zonas afectadas.",
        "Se fai falta un insecticida, pregúntalle ao teu axente de extensión que produto é legal e seguro no teu país."
      ],
      "urgencyReason": "Os ataques fortes fan caer as follas e baixan a colleita, sobre todo en períodos secos e quentes."
    },
    "phoma": {
      "name": "Mancha foliar por Phoma",
      "look": "Manchas marrón escuro a negras de ata 2 cm de ancho nas follas máis vellas, cun centro máis claro e o bordo máis escuro. As puntas dos brotes novos volven negras e secan, as flores poden morrer e as bagas caen. O dano pode comezar pola punta ou polo bordo da folla.",
      "tellApart": "O Phoma tamén mata as puntas dos brotes novos e as flores nas terras altas frías e ventosas, mentres que a mancha ollo de ra marrón queda en manchas con aneis e non seca as puntas dos brotes.",
      "actions": [
        "Planta cortaventos nas zonas ventosas. O dano do vento deixa entrar o fungo.",
        "Corta e destrúe os brotes secos e as bagas momificadas, e poda para que o aire seque as follas.",
        "Aboa as árbores cun adubo equilibrado, sobre todo con nitróxeno e potasio.",
        "Nas estacións frías e ventosas, fumiga un funxicida de cobre antes de que apareza a enfermidade. Pregúntalle ao teu axente de extensión polo momento axeitado."
      ],
      "urgencyReason": "Nas terras altas frías e ventosas pode matar brotes e flores e reducir a colleita entre un 15 e un 43 por cento."
    },
    "rust": {
      "name": "Ferruxe da folla do café",
      "look": "Aparecen pequenas manchas amarelas pálidas na cara de arriba da folla. Por debaixo, cada mancha ten unha placa de po amarelo a laranxa escuro que se pega ao dedo. As manchas vellas volven marróns no medio e as follas caen cedo. Adoita comezar polas follas de abaixo da árbore.",
      "tellApart": "A ferruxe ten po laranxa no envés da folla, mentres que a mancha ollo de ra marrón ten aneis marróns secos cun centro gris esbrancuxado e sen po.",
      "actions": [
        "Revisa a miúdo o envés das follas de abaixo. Detectala a tempo é o máis importante.",
        "Colle e queima ou enterra as follas e as ramas con manchas laranxas.",
        "Poda e aclara a sombra e as malas herbas para que circule o aire e as follas sequen máis rápido.",
        "Aboa as árbores con esterco ou un adubo equilibrado. As árbores débiles resultan máis afectadas.",
        "Fumiga un funxicida de cobre, como o hidróxido de cobre, polo anverso e o envés das follas mentres haxa menos duns 5 por cento de follas enfermas. O cobre protexe as follas sas pero non cura as enfermas. Pregúntalle ao teu axente de extensión polo momento axeitado.",
        "Para unha nova plantación, pregúntalle ao teu axente de extensión por variedades resistentes á ferruxe, como os tipos Catimor ou Sarchimor."
      ],
      "urgencyReason": "Espállase rápido entre árbores e fincas, e as perdas nas variedades sensibles poden chegar do 30 ao 80 por cento."
    },
    "mites": {
      "name": "Posible dano por ácaros",
      "look": "A imaxe parécese a follas de café marcadas con dano por ácaros. Marcas semellantes poden ter outras causas, así que é só unha posible coincidencia.",
      "actions": [
        "Pídelle a un axente de extensión que inspeccione os dous lados da folla e confirme a causa antes de escoller un tratamento."
      ]
    },
    "weevil": {
      "name": "Posible dano de pragas que mastigan follas",
      "look": "A folla parécese a imaxes marcadas como dano de coco ou de gorgullo. Esta foto non pode identificar a especie do insecto.",
      "actions": [
        "Pídelle a un axente de extensión que inspeccione a folla danada e os insectos da planta antes de escoller un tratamento."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Busca a etiqueta de KEPHIS no paquete de sementes.",
    "stepScratch": "Rasca a etiqueta para ver o código.",
    "stepText": "Envía o código por mensaxe ao {shortCode}. É gratis.",
    "result": "KEPHIS responde para dicir se a semente é auténtica. Un código auténtico non proba que a semente se gardase ben.",
    "coverage": "Isto serve para semente certificada que se vende en paquetes. As plantas de viveiro adoitan non ter etiqueta, así que pregúntalle ao teu técnico de campo por elas.",
    "noContact": "Pregúntalle ao teu técnico de campo como comprobar se un paquete de sementes é auténtico."
  },
  "phoneGreeting": "Ola, son Leaf Doctor. Axudo con cafeeiros enfermos e podes falar comigo na túa propia lingua. Que ves nas follas dos teus cafeeiros?"
});

export default glText;
