// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const haText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Ganyayenka suna da lafiya",
    "headlineSpray": "{name}: ka kare ganyaye masu lafiya ka kuma share",
    "headlinePrune": "{name}: ka share ka kuma yanke rassa",
    "headlineMonitor": "{name}: ci gaba da lura",
    "headlineAskOfficer": "{name}: ka nemi jami'in gonarka ya duba",
    "headlineNotSure": "Manhajar ba ta da tabbaci. Nuna waɗannan ganyaye ga jami'in gonarka",
    "headlineMightBe": "Mai yiwuwa {name} ne, amma ba a tabbatar ba. Nuna wa jami'in gona",
    "headlineRetake": "Ɗauki hotuna masu bayyana na ƙarin ganyaye",
    "retakeDaylight": "Matsa zuwa hasken rana, ba cikin inuwa mai kauri ko rana kai tsaye ba.",
    "retakeSteady": "Ka riƙe wayar a tsaye har ganyen ya bayyana sosai.",
    "retakeFillFrame": "Cika firam da ganye ɗaya.",
    "sendToOfficer": "Aika wannan batu ga jami'in gonar ƙungiyarku ta SMS, ko ka nuna masa ganyayen da kanka.",
    "rainReason": "An yi ruwan sama a kwanaki {n} cikin kwanaki 7 da suka wuce kusa da kai ({source}). Yanayi mai danshi yana sa tsatsa ta yaɗu da sauri.",
    "labelRate": "Yi amfani da adadin da aka rubuta a jikin samfurin.",
    "elseBerryDisease": "Cutar 'ya'yan kofi: duba 'ya'yan ko suna da tabo masu duhu da suka nutse.",
    "elseBerryBorer": "Kwarin 'ya'yan kofi: nemi ƙananan ramuka a cikin 'ya'yan.",
    "elseWilt": "Bushewar kofi: rassa gaba ɗaya suna bushewa suna mutuwa.",
    "elseNutrition": "Ƙasa mara kyau ko rashin abinci mai gina jiki: itace gaba ɗaya yana rawaya.",
    "smsDecisionSpray": "Shawara: kare ganyaye masu lafiya da ƙarfe jan ƙarfe bisa adadin jikin samfurin, ka kuma share. Sake dubawa nan da kwanaki {days}.",
    "smsDecisionPrune": "Shawara: yanke rassa ka share. Sake dubawa nan da kwanaki {days}.",
    "smsDecisionMonitor": "Shawara: ci gaba da lura. Sake dubawa nan da kwanaki {days}.",
    "smsDecisionCallOfficer": "Shawara: nuna wa jami'in gonarka."
  },
  "diseases": {
    "cercospora": {
      "name": "Tabon ido mai launin ruwan ƙasa",
      "look": "Tabo masu zagaye masu launin ruwan ƙasa, galibi a saman ganye, da tsakiya mai launin toka-fari da zobe mai duhun ruwan ƙasa, sau da yawa da rawaya a kewaye. Tabban faɗinsu 5 zuwa 15 mm kuma suna iya haɗewa su zama manyan wurare matattu. 'Ya'yan suna samun tabo masu duhu da suka nutse kuma suna nunawa da wuri.",
      "tellApart": "Tabon ido mai launin ruwan ƙasa yana da zobba busassu masu launin ruwan ƙasa da tsakiya mai launin toka mai haske kuma ba shi da garin lemu, yayin da tsatsa tana da garin lemu a ƙasa.",
      "actions": [
        "Ka ciyar da itatuwa sosai, musamman da nitrogen da potassium. Ciyarwa mai kyau tana sau da yawa shawo kan wannan cuta.",
        "Ka bar inuwa mai sauƙi, ka sarrafa ciyawa, ka kuma yanke rassa don iska ta shiga ganyaye su bushe.",
        "Bayan yanke rassa, ka ɗauke ganyaye da 'ya'ya ka kai nesa ko ka ƙone su. Kada ka tara su kusa da itatuwan.",
        "A gandun shuke-shuke, ka bar tazara tsakanin 'yan itatuwa ka ƙone waɗanda suke da tabo masu zobe masu launin ruwan ƙasa.",
        "Idan ta yi tsanani, maganin fungi na jan ƙarfe zai iya kare ganyaye masu lafiya. Ka fara tambayar jami'in faɗaɗa noma naka."
      ],
      "urgencyReason": "Tana raunana itatuwa masu damuwa galibi kuma yawanci tana ingantuwa idan an gyara ciyarwa da inuwa."
    },
    "healthy": {
      "name": "Ganyen kofi mai lafiya",
      "look": "Ganye mai lafiya yana walƙiya, siffarsa kamar ƙwai kuma mai tsini, kore mai duhu daidai, ba tare da tabo, gari, ramuka ko rami ba, a sama ko ƙasa.",
      "actions": [
        "Ka yanke rassa ka bar inuwa mai sauƙi da ciyawa kaɗan don ganyaye su bushe da sauri.",
        "Ka ciyar da itatuwa da taki ko takin zamani daidaitacce, musamman nitrogen da potassium.",
        "Ka duba ganyaye da ƙasan su kowane mako ɗaya ko biyu don kama tsatsa ko kwarin ganye da wuri."
      ]
    },
    "miner": {
      "name": "Kwarin haƙar ganyen kofi",
      "look": "Hanyoyi masu juyawa masu launin rawaya mai haske suna bayyana a cikin ganye kuma suna zama wurare matattu masu launin ruwan ƙasa marasa daidaito a sama. Idan ka lanƙwasa ganyen, fatar sama mai sirara a kan wurin tana rabuwa kuma za ka iya samun ƙaramin tsutsa mai gani ta ciki a ciki. Mummunan hari yana sa ganyaye su faɗi.",
      "tellApart": "Wuraren kwarin haƙar ganye kumburi ne masu sirara kamar takarda da tsutsa a ciki waɗanda suke rabuwa idan an lanƙwasa, yayin da tabon ido mai launin ruwan ƙasa zobe ne mai tsabta wanda ba ya rabuwa.",
      "actions": [
        "Ka lanƙwasa wurare masu launin ruwan ƙasa don neman tsutsotsi masu rai, musamman a lokacin rani.",
        "Ka kare maƙiyan halitta kamar ƙananan zuma-masu-harbi da tururuwa ta hanyar kiyaye inuwa gauraye da guje wa feshi mara amfani.",
        "Ka lura da ƙananan itatuwa da gandun shuke-shuke sosai ka cire wurare na farko da wuri.",
        "Idan ana buƙatar maganin kwari, ka tambayi jami'in faɗaɗa noma naka wane samfuri ne halal kuma lafiyayye a ƙasarka."
      ],
      "urgencyReason": "Mummunan hari yana sa ganyaye su faɗi kuma yana rage amfanin gona, mafi muni a lokutan bushewa da zafi."
    },
    "phoma": {
      "name": "Tabon ganye na Phoma",
      "look": "Tabo masu launin ruwan ƙasa mai duhu zuwa baƙi har faɗin 2 cm a tsofaffin ganyaye, da tsakiya mai haske da gefe mai duhu. Saman sabbin harbi yana baƙi ya bushe, furanni na iya mutuwa kuma 'ya'ya su faɗi. Lalacewar na iya farawa daga ƙarshen ganye ko gefensa.",
      "tellApart": "Phoma tana kashe saman sabbin harbi da furanni a tuddai masu sanyi da iska, yayin da tabon ido mai launin ruwan ƙasa yake zama tabo masu zobe kuma ba ya busar da saman harbi.",
      "actions": [
        "Ka dasa itatuwan hana iska a yankuna masu iska. Lalacewar iska tana barin naman gwari ya shiga.",
        "Ka yanke ka lalata busassun harbi da busassun 'ya'ya, ka kuma yanke rassa don iska ta busar da ganyaye.",
        "Ka ciyar da itatuwa da takin zamani daidaitacce, musamman nitrogen da potassium.",
        "A lokutan sanyi da iska, ka fesa maganin fungi na jan ƙarfe kafin cutar ta bayyana. Ka tambayi jami'in faɗaɗa noma naka game da lokaci."
      ],
      "urgencyReason": "A tuddai masu sanyi da iska tana iya kashe harbi da furanni ta rage amfanin gona da kashi 15 zuwa 43."
    },
    "rust": {
      "name": "Tsatsar ganyen kofi",
      "look": "Ƙananan tabo masu rawaya mai haske suna bayyana a saman ganye. A ƙasa, kowane tabo yana da gari mai launin rawaya zuwa lemu mai duhu wanda yake mannewa a yatsa. Tsofaffin tabo suna zama launin ruwan ƙasa a tsakiya kuma ganyaye suna faɗuwa da wuri. Yawanci tana farawa daga ƙananan ganyen itace.",
      "tellApart": "Tsatsa tana da garin lemu a ƙasan ganye, yayin da tabon ido mai launin ruwan ƙasa yake da zobba busassu masu launin ruwan ƙasa da tsakiya mai launin toka-fari kuma ba shi da gari.",
      "actions": [
        "Ka riƙa duba ƙasan ƙananan ganyaye akai-akai. Kama ta da wuri shi ne mafi muhimmanci.",
        "Ka ɗebo ka ƙone ko ka binne ganyaye da rassa masu tabo masu launin lemu.",
        "Ka yanke rassa ka rage inuwa da ciyawa don iska ta shiga ganyaye su bushe da sauri.",
        "Ka ciyar da itatuwa da taki ko takin zamani daidaitacce. Raunanan itatuwa suna shan wahala fiye.",
        "Ka fesa maganin fungi na jan ƙarfe kamar copper hydroxide a saman ganyaye da ƙasan su, muddin ƙasa da kusan kashi 5 na ganyayen suna da cuta. Jan ƙarfe yana kare ganyaye masu lafiya amma ba ya warkar da masu cuta. Ka tambayi jami'in faɗaɗa noma naka game da lokaci.",
        "Don sabon shuki, ka tambayi jami'in faɗaɗa noma naka game da nau'ukan da ke jure tsatsa kamar nau'in Catimor ko Sarchimor."
      ],
      "urgencyReason": "Tana yaɗuwa da sauri tsakanin itatuwa da gonaki, kuma asara a nau'ukan da ke saurin kamuwa na iya kaiwa kashi 30 zuwa 80."
    },
    "mites": {
      "name": "Yiwuwar lalacewar ƙwarin mite",
      "look": "Hoton yana kama da ganyen kofi da aka yi wa alama da lalacewar mite. Alamomi iri ɗaya na iya samun wasu dalilai, don haka wannan yiwuwar daidaito ce kawai.",
      "actions": [
        "Ka nemi jami'in faɗaɗa noma ya duba ɓangarorin ganyen biyu ya tabbatar da dalilin kafin ka zaɓi magani."
      ]
    },
    "weevil": {
      "name": "Yiwuwar lalacewar kwari masu cin ganye",
      "look": "Ganyen yana kama da hotunan da aka yi wa alama da lalacewar coco ko weevil. Wannan hoto ba zai iya gane nau'in kwarin ba.",
      "actions": [
        "Ka nemi jami'in faɗaɗa noma ya duba ganyen da ya lalace da duk kwarin da ke kan shukar kafin ka zaɓi magani."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Nemo mannen KEPHIS a jikin fakitin iri.",
    "stepScratch": "Kankare mannen don lambar ta bayyana.",
    "stepText": "Aika lambar ta saƙo zuwa {shortCode}. Kyauta ne.",
    "result": "KEPHIS tana amsawa ta faɗi ko iri na asali ne. Lamba ta asali ba ta tabbatar an adana irin da kyau ba.",
    "coverage": "Wannan yana aiki ga iri mai takardar shaida da ake sayarwa a fakiti. 'Yan itatuwa na gandun shuke-shuke yawanci ba su da manne, don haka ka tambayi jami'in gonarka game da su.",
    "noContact": "Ka tambayi jami'in gonarka yadda za a duba ko fakitin iri na asali ne."
  },
  "phoneGreeting": "Sannu, ni ce Leaf Doctor. Ina taimakawa game da shuke-shuken kofi marasa lafiya, kuma za ka iya magana da ni da harshenka. Me kake gani a ganyen kofinka?"
});

export default haText;
