// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const hrText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Vaši listovi izgledaju zdravo",
    "headlineSpray": "{name}: zaštitite zdrave listove i očistite",
    "headlinePrune": "{name}: očistite i orezujte",
    "headlineMonitor": "{name}: nastavite pratiti",
    "headlineAskOfficer": "{name}: zamolite svog terenskog službenika da provjeri",
    "headlineNotSure": "Aplikacija nije sigurna. Pokažite ove listove svom terenskom službeniku",
    "headlineMightBe": "Moglo bi biti: {name}, ali nije potvrđeno. Pokažite terenskom službeniku",
    "headlineRetake": "Snimite jasnije fotografije više listova",
    "retakeDaylight": "Idite na dnevno svjetlo, ne u gustu sjenu ni na izravno sunce.",
    "retakeSteady": "Držite telefon mirno dok list ne bude oštar.",
    "retakeFillFrame": "Ispunite okvir jednim listom.",
    "sendToOfficer": "Pošaljite ovaj slučaj terenskom službeniku svoje zadruge SMS-om ili mu pokažite listove osobno.",
    "rainReason": "Kišilo je {n} od posljednjih 7 dana blizu vas ({source}). Vlažno vrijeme ubrzava širenje hrđe.",
    "labelRate": "Koristite količinu s etikete proizvoda.",
    "elseBerryDisease": "Bolest bobica kave: pogledajte imaju li bobice tamne udubljene mrlje.",
    "elseBerryBorer": "Kavin svrdlaš bobica: tražite male rupice na bobicama.",
    "elseWilt": "Uvenuće kave: cijele grane venu i odumiru.",
    "elseNutrition": "Siromašno tlo ili nedostatak hrane: žutilo po cijelom stablu.",
    "smsDecisionSpray": "Odluka: zaštitite zdrave listove bakrom u količini s etikete i očistite. Provjerite ponovno za {days} dana.",
    "smsDecisionPrune": "Odluka: orezujte i očistite. Provjerite ponovno za {days} dana.",
    "smsDecisionMonitor": "Odluka: nastavite pratiti. Provjerite ponovno za {days} dana.",
    "smsDecisionCallOfficer": "Odluka: pokažite svom terenskom službeniku."
  },
  "diseases": {
    "cercospora": {
      "name": "Smeđa pjegavost lista (oko žabe)",
      "look": "Okrugle smeđe pjege, uglavnom na gornjoj strani lista, sa sivo-bijelim središtem i tamnosmeđim prstenom, često sa žutim oreolom. Pjege su široke od 5 do 15 mm i mogu se spojiti u velike mrtve površine. Bobice dobiju tamne udubljene mrlje i prerano sazriju.",
      "tellApart": "Smeđa pjegavost ima suhe smeđe prstenove sa svijetlosivim središtem i nema narančastog praha, a hrđa ima narančasti prah odozdo.",
      "actions": [
        "Dobro prihranjujte stabla, osobito dušikom i kalijem. Dobra prehrana često suzbija ovu bolest.",
        "Održavajte laganu sjenu, suzbijajte korov i orezujte tako da zrak struji i listovi se suše.",
        "Nakon orezivanja odnesite ili spalite listove i bobice. Ne slažite ih uz stabla.",
        "U rasadniku sadnice posadite razmaknuto i spalite sadnice sa smeđim pjegama s prstenovima.",
        "Ako je jako, bakreni fungicid može zaštititi zdrave listove. Najprije pitajte svog poljoprivrednog savjetnika."
      ],
      "urgencyReason": "Uglavnom slabi stabla pod stresom i obično se popravi kad se ispravi prehrana i sjena."
    },
    "healthy": {
      "name": "Zdrav list kave",
      "look": "Zdrav list je sjajan, ovalan i šiljast, ujednačeno tamnozelen, bez pjega, praha, rupa ili tunela na gornjoj i donjoj strani.",
      "actions": [
        "Orezujte i održavajte laganu sjenu i nizak korov da se listovi brzo suše.",
        "Prihranjujte stabla stajskim gnojem ili uravnoteženim gnojivom, osobito dušikom i kalijem.",
        "Provjeravajte listove i njihove donje strane svaki tjedan ili dva da rano uočite hrđu ili miniranje lista."
      ]
    },
    "miner": {
      "name": "Kavin miner lista",
      "look": "Blijedožuti vijugavi tragovi pojavljuju se unutar lista i postaju neravne smeđe mrtve površine na gornjoj strani. Ako savijete list, tanka gornja kožica iznad površine se odvoji i unutra možete naći sitnu prozirnu ličinku. Jak napad uzrokuje opadanje listova.",
      "tellApart": "Površine od minera su papirnati mjehuri s ličinkom unutra koji se odvoje kad se savije, a smeđa pjegavost je uredan okrugli prsten koji se ne odvaja.",
      "actions": [
        "Savijte smeđe površine i tražite žive ličinke, osobito u sušnom razdoblju.",
        "Zaštitite prirodne neprijatelje poput malih osa i mrava održavanjem mješovite sjene i izbjegavanjem nepotrebnog prskanja.",
        "Pomno pratite mlada stabla i rasadnike i rano uklonite prve zahvaćene površine.",
        "Ako je potreban insekticid, pitajte svog poljoprivrednog savjetnika koji je proizvod zakonit i siguran u vašoj zemlji."
      ],
      "urgencyReason": "Jak napad uzrokuje opadanje listova i niži urod, najgore u suhim i vrućim razdobljima."
    },
    "phoma": {
      "name": "Pjegavost lista od gljive Phoma",
      "look": "Tamnosmeđe do crne pjege široke do 2 cm na starijim listovima, sa svjetlijim središtem i tamnijim rubom. Vrhovi mladih izdanaka pocrne i osuše se, cvjetovi mogu uginuti, a bobice otpadaju. Oštećenje može početi na vrhu ili rubu lista.",
      "tellApart": "Phoma također ubija vrhove mladih izdanaka i cvjetove u hladnim vjetrovitim visoravnima, a smeđa pjegavost ostaje samo prstenasta pjegavost i ne suši vrhove izdanaka.",
      "actions": [
        "Sadite vjetrobrane u vjetrovitim područjima. Oštećenje vjetrom pušta gljivu unutra.",
        "Odrežite i uništite osušene izdanke i mumificirane bobice te orezujte da zrak može sušiti listove.",
        "Prihranjujte stabla uravnoteženim gnojivom, osobito dušikom i kalijem.",
        "U hladnim vjetrovitim razdobljima prskajte bakrenim fungicidom prije nego se bolest pojavi. Pitajte svog poljoprivrednog savjetnika za vrijeme prskanja."
      ],
      "urgencyReason": "U hladnim vjetrovitim visoravnima može uništiti izdanke i cvjetove i smanjiti urod za 15 do 43 posto."
    },
    "rust": {
      "name": "Hrđa lista kave",
      "look": "Na gornjoj strani lista pojavljuju se male blijedožute pjege. S donje strane svaka pjega ima mrlju žutog do tamnonarančastog praha koji se briše prstom. Stare pjege u sredini posmeđe, a listovi rano otpadaju. Obično počinje na donjim listovima stabla.",
      "tellApart": "Hrđa ima narančasti prah na donjoj strani lista, a smeđa pjegavost ima suhe smeđe prstenove sa sivo-bijelim središtem i bez praha.",
      "actions": [
        "Često provjeravajte donju stranu donjih listova. Najvažnije je uhvatiti je rano.",
        "Poberite i spalite ili zakopajte listove i grane s narančastim pjegama.",
        "Orezujte i prorjeđujte sjenu i korov da zrak struji i listovi se brže suše.",
        "Prihranjujte stabla stajskim gnojem ili uravnoteženim gnojivom. Slaba stabla pogađa jače.",
        "Prskajte bakrenim fungicidom poput bakrenog hidroksida po gornjoj i donjoj strani listova dok je bolesno manje od otprilike 5 posto listova. Bakar štiti zdrave listove, ali ne liječi bolesne. Pitajte svog poljoprivrednog savjetnika za vrijeme prskanja.",
        "Za novu sadnju pitajte svog poljoprivrednog savjetnika o sortama otpornima na hrđu, poput tipova Catimor ili Sarchimor."
      ],
      "urgencyReason": "Brzo se širi između stabala i imanja, a gubici na osjetljivim sortama mogu doseći 30 do 80 posto."
    },
    "mites": {
      "name": "Moguća šteta od grinja",
      "look": "Slika sliči listovima kave označenima kao oštećeni grinjama. Slični tragovi mogu imati druge uzroke, pa je ovo moguće podudaranje.",
      "actions": [
        "Zamolite poljoprivrednog savjetnika da pregleda obje strane lista i potvrdi uzrok prije odabira liječenja."
      ]
    },
    "weevil": {
      "name": "Moguća šteta od štetnika koji grizu lišće",
      "look": "List sliči slikama označenima kao šteta od kokosa ili surlaša. Ova fotografija ne može odrediti vrstu kukca.",
      "actions": [
        "Zamolite poljoprivrednog savjetnika da pregleda oštećeni list i sve kukce na biljci prije odabira liječenja."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Pronađite KEPHIS naljepnicu na vrećici sjemena.",
    "stepScratch": "Ogrebite naljepnicu da se pokaže kôd.",
    "stepText": "Pošaljite kôd porukom na {shortCode}. Besplatno je.",
    "result": "KEPHIS odgovara je li sjeme pravo. Pravi kôd ne dokazuje da je sjeme dobro čuvano.",
    "coverage": "Ovo vrijedi za certificirano sjeme koje se prodaje u vrećicama. Sadnice iz rasadnika obično nemaju naljepnicu, pa o njima pitajte svog terenskog službenika.",
    "noContact": "Pitajte svog terenskog službenika kako provjeriti je li vrećica sjemena prava."
  },
  "phoneGreeting": "Dobar dan, ovdje Leaf Doctor. Pomažem kod bolesnih biljaka kave, a sa mnom možete razgovarati na svom jeziku. Što vidite na listovima svoje kave?"
});

export default hrText;
