// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const htText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Fèy ou yo sanble an sante",
    "headlineSpray": "{name}: pwoteje fèy ki an sante yo epi netwaye",
    "headlinePrune": "{name}: netwaye epi taye",
    "headlineMonitor": "{name}: kontinye veye",
    "headlineAskOfficer": "{name}: mande ajan teren ou an pou verifye",
    "headlineNotSure": "Aplikasyon an pa sèten. Montre fèy sa yo bay ajan teren ou an",
    "headlineMightBe": "Li kapab {name}, men sa pa konfime. Montre yon ajan teren",
    "headlineRetake": "Pran foto ki pi klè sou plis fèy",
    "retakeDaylight": "Ale nan limyè jou, pa nan fon lonbraj ni nan solèy dirèk.",
    "retakeSteady": "Kenbe telefòn nan fèm jiskaske fèy la parèt byen nèt.",
    "retakeFillFrame": "Ranpli ekran an ak yon sèl fèy.",
    "sendToOfficer": "Voye ka sa a bay ajan teren koperativ ou an pa SMS, oswa montre fèy yo an pèsòn.",
    "rainReason": "Lapli te tonbe sou {n} nan 7 dènye jou yo toupre ou ({source}). Move tan mouye fè wouy la gaye pi vit.",
    "labelRate": "Itilize dòz ki sou etikèt pwodwi a.",
    "elseBerryDisease": "Maladi grenn kafe: gade grenn yo pou wè tach nwa ki fonse anndan.",
    "elseBerryBorer": "Pèsè grenn kafe: chèche ti twou nan grenn yo.",
    "elseWilt": "Fletri kafe: branch antye ap fletri epi mouri.",
    "elseNutrition": "Move tè oswa mank manje: jonn sou tout pye a.",
    "smsDecisionSpray": "Desizyon: pwoteje fèy ki an sante yo ak kwiv selon dòz etikèt la epi netwaye. Verifye ankò nan {days} jou.",
    "smsDecisionPrune": "Desizyon: taye epi netwaye. Verifye ankò nan {days} jou.",
    "smsDecisionMonitor": "Desizyon: kontinye veye. Verifye ankò nan {days} jou.",
    "smsDecisionCallOfficer": "Desizyon: montre ajan teren ou an."
  },
  "diseases": {
    "cercospora": {
      "name": "Tach je mawon",
      "look": "Tach won mawon, sitou sou anlè fèy la, ak yon sant gri-blan ak yon bag mawon fonse, souvan ak yon alo jòn. Tach yo gen 5 a 15 mm lajè epi yo ka makonnen fè gwo plak mouri. Grenn yo gen tach fonse anndan epi yo mi twò bonè.",
      "tellApart": "Tach je mawon gen bag mawon sèk ak yon sant gri pal epi pa gen poud zoranj, men wouy gen poud zoranj anba fèy la.",
      "actions": [
        "Bay pye yo manje byen, sitou nitwojèn ak potasyòm. Bon manje souvan kontwole maladi sa a.",
        "Kenbe yon ti lonbraj, kontwole move zèb, epi taye pou lè a ka sikile epi fèy yo ka sèch.",
        "Apre ou fin taye, pote ale oswa boule fèy ak grenn yo. Pa fè pil ak yo kont pye yo.",
        "Nan pepinyè, kite espas ant jenn plan yo epi boule jenn plan ki gen tach mawon ak bag.",
        "Si li grav, yon fonjisid kwiv ka pwoteje fèy ki an sante yo. Mande ajan ekstansyon ou an anvan."
      ],
      "urgencyReason": "Li sitou febli pye ki estrese epi anjeneral li amelyore lè yo korije manje a ak lonbraj la."
    },
    "healthy": {
      "name": "Fèy kafe an sante",
      "look": "Yon fèy an sante klere, ovòl epi pwenti, vèt fonse egal, san tach, poud, twou oswa tinèl sou anlè ni anba.",
      "actions": [
        "Taye epi kenbe yon ti lonbraj ak move zèb ba pou fèy yo sèch vit.",
        "Bay pye yo fimye oswa angrè balanse, sitou nitwojèn ak potasyòm.",
        "Tcheke fèy yo ak anba yo chak semèn oswa chak de semèn pou jwenn wouy oswa ti vè fèy bonè."
      ]
    },
    "miner": {
      "name": "Ti vè ki fouye fèy kafe",
      "look": "Santye jòn pal k ap tòde parèt anndan fèy la epi vin tounen plak mawon mouri ki pa egal sou anlè. Si ou pliye fèy la, po mens anlè plak la dekole epi ou ka jwenn yon ti vè transparan anndan. Gwo atak fè fèy yo tonbe.",
      "tellApart": "Plak ti vè fouye yo se ti anpoul tankou papye ak yon vè anndan ki dekole lè yo pliye, men tach je mawon se yon bag won pwòp ki pa dekole.",
      "actions": [
        "Pliye plak mawon yo pou chèche vè vivan, sitou nan sezon sèk.",
        "Pwoteje lènmi natirèl tankou ti gèp ak foumi lè ou kenbe lonbraj melanje epi evite espreye san nesesite.",
        "Veye jenn pye yo ak pepinyè yo avèk atansyon epi retire premye plak yo bonè.",
        "Si yon ensektisid nesesè, mande ajan ekstansyon ou an ki pwodwi ki legal epi san danje nan peyi ou."
      ],
      "urgencyReason": "Gwo atak fè fèy tonbe epi bese rannman, sitou pi mal nan peryòd cho ak sèk."
    },
    "phoma": {
      "name": "Tach fèy Phoma",
      "look": "Tach mawon fonse jiska nwa ki rive 2 cm lajè sou fèy ki pi vye yo, ak yon sant pi klè ak yon bò pi fonse. Pwent jenn tij yo vin nwa epi sèch, flè yo ka mouri, epi grenn yo tonbe. Domaj la ka kòmanse nan pwent oswa bò fèy la.",
      "tellApart": "Phoma touye tou pwent jenn tij yo ak flè yo nan mòn frèt ak van, men tach je mawon rete tach ak bag epi pa seche pwent tij yo.",
      "actions": [
        "Plante bwa pou kase van nan zòn ki gen van. Domaj van kite chanpiyon an antre.",
        "Koupe epi detwi tij sèch yo ak grenn mimifye yo, epi taye pou lè a ka seche fèy yo.",
        "Bay pye yo angrè balanse, sitou nitwojèn ak potasyòm.",
        "Nan sezon frèt ak van, espreye yon fonjisid kwiv anvan maladi a parèt. Mande ajan ekstansyon ou an kilè pou fè sa."
      ],
      "urgencyReason": "Nan mòn frèt ak van li ka touye tij ak flè epi bese rannman pa 15 a 43 pousan."
    },
    "rust": {
      "name": "Wouy fèy kafe",
      "look": "Ti tach jòn pal parèt sou anlè fèy la. Anba, chak tach gen yon plak poud jòn rive zoranj fonse ki pase sou dwèt ou. Vye tach yo vin mawon nan mitan epi fèy yo tonbe bonè. Anjeneral li kòmanse sou fèy anba pye a.",
      "tellApart": "Wouy gen poud zoranj anba fèy la, men tach je mawon gen bag mawon sèk ak yon sant gri-blan epi pa gen poud.",
      "actions": [
        "Tcheke anba fèy ki anba yo souvan. Jwenn li bonè se sa ki pi enpòtan.",
        "Rache epi boule oswa antere fèy ak branch ki gen tach zoranj.",
        "Taye epi eklèsi lonbraj ak move zèb pou lè a sikile epi fèy yo seche pi vit.",
        "Bay pye yo fimye oswa angrè balanse. Pye ki fèb pran pi rèd.",
        "Espreye yon fonjisid kwiv tankou idroksid kwiv sou anlè ak anba fèy yo toutotan mwens pase anviwon 5 pousan fèy yo malad. Kwiv pwoteje fèy ki an sante men li pa geri sa ki malad yo. Mande ajan ekstansyon ou an kilè pou fè sa.",
        "Pou nouvo plantasyon, mande ajan ekstansyon ou an sou varyete ki reziste ak wouy tankou tip Catimor oswa Sarchimor."
      ],
      "urgencyReason": "Li gaye vit ant pye ak jaden, epi pèt sou varyete ki sansib yo ka rive 30 a 80 pousan."
    },
    "mites": {
      "name": "Domaj mit posib",
      "look": "Imaj la sanble ak fèy kafe yo make kòm domaj mit. Menm mak yo ka gen lòt kòz, donk sa se yon matche posib.",
      "actions": [
        "Mande yon ajan ekstansyon pou gade tou de bò fèy la epi konfime kòz la anvan ou chwazi yon tretman."
      ]
    },
    "weevil": {
      "name": "Domaj posib ensèk k ap manje fèy",
      "look": "Fèy la sanble ak imaj yo make kòm domaj koko oswa charanson. Foto sa a pa kapab idantifye espès ensèk la.",
      "actions": [
        "Mande yon ajan ekstansyon pou gade fèy ki domaje a ak nenpòt ensèk ki sou plant lan anvan ou chwazi yon tretman."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Jwenn otokolan KEPHIS la sou pake semans lan.",
    "stepScratch": "Grate otokolan an pou montre kòd la.",
    "stepText": "Voye kòd la pa tèks bay {shortCode}. Li gratis.",
    "result": "KEPHIS reponn pou di si semans lan orijinal. Yon kòd orijinal pa pwouve semans lan te byen kenbe.",
    "coverage": "Sa mache pou semans sètifye yo vann nan pake. Jenn plan pepinyè yo anjeneral pa gen otokolan, donk mande ajan teren ou an sou yo.",
    "noContact": "Mande ajan teren ou an ki jan pou verifye si yon pake semans orijinal."
  },
  "phoneGreeting": "Bonjou, se Leaf Doctor. Mwen ede ak plant kafe ki malad, epi ou ka pale avè m nan pwòp lang ou. Kisa ou wè sou fèy kafe ou yo?"
});

export default htText;
