// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const huText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "A levelei egészségesnek látszanak",
    "headlineSpray": "{name}: védje az egészséges leveleket, és takarítson",
    "headlinePrune": "{name}: takarítson és metsszen",
    "headlineMonitor": "{name}: figyelje tovább",
    "headlineAskOfficer": "{name}: kérje meg a terepi tanácsadót, hogy nézze meg",
    "headlineNotSure": "Az alkalmazás nem biztos benne. Mutassa meg ezeket a leveleket a terepi tanácsadónak",
    "headlineMightBe": "Lehet, hogy {name}, de nem igazolt. Mutassa meg egy terepi tanácsadónak",
    "headlineRetake": "Készítsen jobban látható fényképeket több levélről",
    "retakeDaylight": "Menjen nappali fényre, ne mély árnyékba és ne közvetlen napra.",
    "retakeSteady": "Tartsa mozdulatlanul a telefont, amíg a levél éles nem lesz.",
    "retakeFillFrame": "Egy levéllel töltse ki a képet.",
    "sendToOfficer": "Küldje el ezt az esetet SMS-ben a szövetkezet terepi tanácsadójának, vagy mutassa meg neki személyesen a leveleket.",
    "rainReason": "Az utolsó 7 napból {n} napon esett az eső az Ön közelében ({source}). A nedves idő gyorsabban terjeszti a rozsdát.",
    "labelRate": "A termék címkéjén megadott mennyiséget használja.",
    "elseBerryDisease": "Kávétermés-betegség: nézze meg a termést sötét, besüppedt foltok miatt.",
    "elseBerryBorer": "Kávétermés-fúrobogár: keressen apró lyukakat a termésen.",
    "elseWilt": "Kávéhervadás: egész ágak hervadnak és pusztulnak.",
    "elseNutrition": "Rossz talaj vagy tápanyaghiány: az egész fa sárgul.",
    "smsDecisionSpray": "Döntés: védje az egészséges leveleket rézzel a címkén megadott mennyiségben, és takarítson. Ellenőrizze újra {days} nap múlva.",
    "smsDecisionPrune": "Döntés: metsszen és takarítson. Ellenőrizze újra {days} nap múlva.",
    "smsDecisionMonitor": "Döntés: figyelje tovább. Ellenőrizze újra {days} nap múlva.",
    "smsDecisionCallOfficer": "Döntés: mutassa meg a terepi tanácsadónak."
  },
  "diseases": {
    "cercospora": {
      "name": "Barna szemfoltosság",
      "look": "Kerek barna foltok, többnyire a levél tetején, szürkésfehér közepükkel és sötétbarna gyűrűjükkel, gyakran sárga udvarral. A foltok 5-15 mm szélesek, és nagy elhalt foltokká folyhatnak össze. A termésen sötét, besüppedt foltok jelennek meg, és túl korán érik.",
      "tellApart": "A barna szemfoltosságnál száraz barna gyűrűk és halvány szürke közép van, narancssárga por nélkül, a rozsdánál viszont alul narancssárga por látszik.",
      "actions": [
        "Tápanyagozza jól a fákat, különösen nitrogénnel és káliummal. A jó tápanyag-ellátás gyakran megfékezi ezt a betegséget.",
        "Tartson könnyű árnyékot, irtsa a gyomot, és metsszen úgy, hogy a levegő átjárja a fát, és a levelek megszáradjanak.",
        "Metszés után vigye el vagy égesse el a leveleket és a termést. Ne halmozza őket a fák mellé.",
        "A csemetekertben hagyjon helyet a csemeték között, és égesse el a gyűrűs barna foltos csemetéket.",
        "Ha súlyos a helyzet, a rézalapú gombaölő szer megvédheti az egészséges leveleket. Előbb kérdezze meg a mezőgazdasági szaktanácsadót."
      ],
      "urgencyReason": "Főleg a stresszes fákat gyengíti, és általában javul, ha rendbe teszik a tápanyag-ellátást és az árnyékot."
    },
    "healthy": {
      "name": "Egészséges kávélevél",
      "look": "Az egészséges levél fényes, tojásdad és hegyes, egyenletesen sötétzöld, tetején és alján sincs folt, por, lyuk vagy járat.",
      "actions": [
        "Metsszen, tartson könnyű árnyékot, és tartsa alacsonyan a gyomot, hogy a levelek gyorsan megszáradjanak.",
        "Trágyával vagy kiegyensúlyozott műtrágyával tápanyagozza a fákat, különösen nitrogénnel és káliummal.",
        "Hetente vagy kéthetente nézze át a leveleket és az aljukat, hogy korán észrevegye a rozsdát vagy a levélaknázót."
      ]
    },
    "miner": {
      "name": "Kávélevél-aknázómoly",
      "look": "Halványsárga, kanyargós járatok jelennek meg a levélben, és a tetején egyenetlen, barna, elhalt foltokká válnak. Ha meghajlítja a levelet, a folt feletti vékony felső réteg szétválik, és bent egy apró, átlátszó lárvát találhat. Erős fertőzésnél a levelek lehullanak.",
      "tellApart": "Az aknázómoly foltjai papírszerű hólyagok, bennük lárvával, amelyek hajlításra szétválnak, a barna szemfoltosság viszont rendezett kerek gyűrű, amely nem válik szét.",
      "actions": [
        "Hajlítsa meg a barna foltokat, és keressen élő lárvákat, különösen a száraz évszakban.",
        "Védje a természetes ellenségeket, például a kis darazsakat és a hangyákat: tartson vegyes árnyékot, és kerülje a felesleges permetezést.",
        "Figyelje szorosan a fiatal fákat és a csemetekertet, és az első foltokat korán távolítsa el.",
        "Ha rovarölő szerre van szükség, kérdezze meg a mezőgazdasági szaktanácsadót, melyik termék törvényes és biztonságos az Ön országában."
      ],
      "urgencyReason": "Az erős fertőzés levélhullást okoz, és csökkenti a termést, leginkább száraz, forró időszakokban."
    },
    "phoma": {
      "name": "Phoma levélfoltosság",
      "look": "Sötétbarna, fekete foltok, legfeljebb 2 cm szélesek az idősebb leveleken, világosabb középpel és sötétebb széllel. A fiatal hajtások csúcsa megfeketedik és kiszárad, a virágok elpusztulhatnak, és a termés lehullik. A károsodás a levél csúcsán vagy szélén kezdődhet.",
      "tellApart": "A Phoma hideg, szeles hegyvidéken a fiatal hajtások csúcsát és a virágokat is elpusztítja, a barna szemfoltosság viszont gyűrűs folt marad, és nem szárítja ki a hajtáscsúcsokat.",
      "actions": [
        "Szeles területeken ültessen szélfogókat. A szél okozta sérülések utat nyitnak a gombának.",
        "Vágja le és semmisítse meg a kiszáradt hajtásokat és a beszáradt termést, és metsszen úgy, hogy a levegő megszárítsa a leveleket.",
        "Kiegyensúlyozott műtrágyával tápanyagozza a fákat, különösen nitrogénnel és káliummal.",
        "Hideg, szeles évszakokban permetezzen rézalapú gombaölő szerrel, mielőtt a betegség megjelenik. Az időzítésről kérdezze meg a mezőgazdasági szaktanácsadót."
      ],
      "urgencyReason": "Hideg, szeles hegyvidéken elpusztíthatja a hajtásokat és a virágokat, és 15-43 százalékkal csökkentheti a termést."
    },
    "rust": {
      "name": "Kávélevél-rozsda",
      "look": "Apró, halványsárga foltok jelennek meg a levél tetején. Alul minden folton sárgától sötét narancssárgáig terjedő por van, amely az ujjára is rátapad. A régi foltok közepe megbarnul, és a levelek korán lehullanak. Általában a fa alsó leveleinél kezdődik.",
      "tellApart": "A rozsdánál a levél alján narancssárga por van, a barna szemfoltosságnál viszont száraz barna gyűrűk és szürkésfehér közép van, por nélkül.",
      "actions": [
        "Gyakran nézze meg az alsó levelek fonákját. A korai felismerés a legfontosabb.",
        "Szedje le és égesse el vagy ássa el a narancssárga foltos leveleket és ágakat.",
        "Metsszen, és ritkítsa az árnyékot és a gyomot, hogy a levegő átjárja a fát, és a levelek gyorsabban száradjanak.",
        "Trágyával vagy kiegyensúlyozott műtrágyával tápanyagozza a fákat. A gyenge fákat jobban megviseli.",
        "Permetezzen rézalapú gombaölő szerrel, például réz-hidroxiddal (copper hydroxide) a levelek tetejét és fonákját, amíg a levelek körülbelül 5 százaléka alatt beteg. A réz védi az egészséges leveleket, de a beteget nem gyógyítja meg. Az időzítésről kérdezze meg a mezőgazdasági szaktanácsadót.",
        "Új ültetéshez kérdezze meg a mezőgazdasági szaktanácsadót a rozsdának ellenálló fajtákról, például a Catimor vagy Sarchimor típusokról."
      ],
      "urgencyReason": "Gyorsan terjed a fák és a gazdaságok között, és az érzékeny fajtákon a veszteség elérheti a 30-80 százalékot."
    },
    "mites": {
      "name": "Lehetséges atkakár",
      "look": "A kép olyan kávéleveleket idéz, amelyeket atkakárral jelöltek meg. Hasonló nyomokat más okok is okozhatnak, ezért ez csak lehetséges egyezés.",
      "actions": [
        "Kezelés választása előtt kérje meg a mezőgazdasági szaktanácsadót, hogy nézze meg a levél mindkét oldalát, és erősítse meg az okot."
      ]
    },
    "weevil": {
      "name": "Lehetséges levélrágó kártevő okozta kár",
      "look": "A levél olyan képekre hasonlít, amelyeket coco- vagy ormányosbogár-kárként jelöltek meg. Ez a fénykép nem tudja azonosítani a rovarfajt.",
      "actions": [
        "Kezelés választása előtt kérje meg a mezőgazdasági szaktanácsadót, hogy nézze meg a sérült levelet és a növényen lévő rovarokat."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Keresse meg a KEPHIS-matricát a vetőmagzacskón.",
    "stepScratch": "Kaparja le a matricát, hogy látszódjon a kód.",
    "stepText": "Küldje el a kódot üzenetben a(z) {shortCode} számra. Ingyenes.",
    "result": "A KEPHIS válaszol, hogy a vetőmag eredeti-e. Az eredeti kód nem bizonyítja, hogy a vetőmagot jól tárolták.",
    "coverage": "Ez a zacskóban árult, minősített vetőmagra működik. A csemetekerti csemetéken általában nincs matrica, ezért azokról kérdezze a terepi tanácsadót.",
    "noContact": "Kérdezze meg a terepi tanácsadót, hogyan ellenőrizheti, hogy a vetőmagzacskó eredeti-e."
  },
  "phoneGreeting": "Jó napot kívánok, a Leaf Doctor vagyok. Beteg kávénövényekben segítek, és a saját nyelvén beszélhet velem. Mit lát a kávélevelein?"
});

export default huText;
