// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const idText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Daun Anda tampak sehat",
    "headlineSpray": "{name}: lindungi daun yang sehat dan bersihkan kebun",
    "headlinePrune": "{name}: bersihkan dan pangkas",
    "headlineMonitor": "{name}: terus pantau",
    "headlineAskOfficer": "{name}: minta petugas lapangan Anda memeriksa",
    "headlineNotSure": "Aplikasi tidak yakin. Tunjukkan daun-daun ini kepada petugas lapangan Anda",
    "headlineMightBe": "Mungkin {name}, tetapi belum dipastikan. Tunjukkan kepada petugas lapangan",
    "headlineRetake": "Ambil foto yang lebih jelas dari lebih banyak daun",
    "retakeDaylight": "Pindah ke cahaya siang, jangan di bayangan gelap atau di bawah terik matahari.",
    "retakeSteady": "Pegang ponsel dengan stabil sampai daun tampak tajam.",
    "retakeFillFrame": "Penuhi bingkai dengan satu daun.",
    "sendToOfficer": "Kirim kasus ini lewat SMS ke petugas lapangan koperasi Anda, atau tunjukkan daunnya langsung.",
    "rainReason": "Hujan turun pada {n} dari 7 hari terakhir di dekat Anda ({source}). Cuaca basah membuat karat menyebar lebih cepat.",
    "labelRate": "Pakai takaran yang tertulis pada label produk.",
    "elseBerryDisease": "Penyakit buah kopi: periksa buahnya untuk melihat bercak gelap yang cekung.",
    "elseBerryBorer": "Penggerek buah kopi: cari lubang kecil pada buah.",
    "elseWilt": "Layu kopi: seluruh cabang layu dan mati.",
    "elseNutrition": "Tanah kurang baik atau kurang hara: menguning di seluruh pohon.",
    "smsDecisionSpray": "Keputusan: lindungi daun yang sehat dengan tembaga sesuai takaran label dan bersihkan kebun. Periksa lagi dalam {days} hari.",
    "smsDecisionPrune": "Keputusan: pangkas dan bersihkan kebun. Periksa lagi dalam {days} hari.",
    "smsDecisionMonitor": "Keputusan: terus pantau. Periksa lagi dalam {days} hari.",
    "smsDecisionCallOfficer": "Keputusan: tunjukkan kepada petugas lapangan Anda."
  },
  "diseases": {
    "cercospora": {
      "name": "Bercak mata coklat",
      "look": "Bercak coklat bulat, kebanyakan di sisi atas daun, dengan pusat abu-abu keputihan dan cincin coklat tua, sering dikelilingi lingkaran kuning. Lebar bercak 5 sampai 15 mm dan bisa menyatu menjadi bercak mati yang besar. Buah mendapat bercak gelap yang cekung dan masak terlalu cepat.",
      "tellApart": "Bercak mata coklat punya cincin coklat kering dengan pusat abu-abu pucat dan tanpa serbuk oranye, sedangkan karat punya serbuk oranye di bawah daun.",
      "actions": [
        "Beri pohon pupuk yang cukup, terutama nitrogen dan kalium. Pemupukan yang baik sering menekan penyakit ini.",
        "Jaga naungan tetap ringan, kendalikan gulma, dan pangkas supaya udara bergerak dan daun cepat kering.",
        "Setelah memangkas, bawa pergi atau bakar daun dan buahnya. Jangan menumpuknya di dekat pohon.",
        "Di pembibitan, beri jarak antar bibit dan bakar bibit yang punya bercak coklat bercincin.",
        "Jika parah, fungisida tembaga bisa melindungi daun yang sehat. Tanyakan dulu kepada penyuluh Anda."
      ],
      "urgencyReason": "Penyakit ini terutama melemahkan pohon yang stres dan biasanya membaik setelah pemupukan dan naungan diperbaiki."
    },
    "healthy": {
      "name": "Daun kopi sehat",
      "look": "Daun yang sehat mengilap, bulat telur dan runcing, hijau tua merata, tanpa bercak, serbuk, lubang, atau terowongan di atas maupun di bawah.",
      "actions": [
        "Pangkas dan jaga naungan tetap ringan serta gulma rendah supaya daun cepat kering.",
        "Beri pohon pupuk kandang atau pupuk berimbang, terutama nitrogen dan kalium.",
        "Periksa daun dan sisi bawahnya setiap satu atau dua minggu untuk menemukan karat atau penggorok daun sejak dini."
      ]
    },
    "miner": {
      "name": "Penggorok daun kopi",
      "look": "Jalur kuning pucat yang berkelok muncul di dalam daun dan berubah menjadi bercak mati coklat yang tidak rata di sisi atas. Jika daun ditekuk, kulit tipis di atas bercak terkelupas dan Anda bisa menemukan ulat kecil yang tembus pandang di dalamnya. Serangan berat membuat daun rontok.",
      "tellApart": "Bercak penggorok daun berupa lepuhan setipis kertas dengan ulat di dalamnya yang terkelupas saat ditekuk, sedangkan bercak mata coklat berupa cincin bulat rapi yang tidak terkelupas.",
      "actions": [
        "Tekuk bercak coklat untuk mencari ulat yang masih hidup, terutama pada musim kemarau.",
        "Lindungi musuh alami seperti tawon kecil dan semut dengan menjaga naungan campuran dan menghindari penyemprotan yang tidak perlu.",
        "Awasi pohon muda dan pembibitan dengan cermat dan buang bercak pertama sejak dini.",
        "Jika perlu insektisida, tanyakan kepada penyuluh Anda produk mana yang sah dan aman di negara Anda."
      ],
      "urgencyReason": "Serangan berat membuat daun rontok dan menurunkan hasil panen, paling parah saat cuaca kering dan panas."
    },
    "phoma": {
      "name": "Bercak daun Phoma",
      "look": "Bercak coklat tua sampai hitam selebar hingga 2 cm pada daun yang lebih tua, dengan pusat lebih terang dan tepi lebih gelap. Ujung tunas muda menjadi hitam dan mengering, bunga bisa mati, dan buah rontok. Kerusakan bisa dimulai dari ujung atau tepi daun.",
      "tellApart": "Phoma juga mematikan ujung tunas muda dan bunga di dataran tinggi yang dingin dan berangin, sedangkan bercak mata coklat tetap berupa bercak bercincin dan tidak mengeringkan ujung tunas.",
      "actions": [
        "Tanam pohon penahan angin di daerah berangin. Luka akibat angin memudahkan jamur masuk.",
        "Pangkas dan musnahkan tunas yang mengering dan buah yang mengering, dan pangkas supaya udara bisa mengeringkan daun.",
        "Beri pohon pupuk berimbang, terutama nitrogen dan kalium.",
        "Pada musim dingin yang berangin, semprot fungisida tembaga sebelum penyakit muncul. Tanyakan waktunya kepada penyuluh Anda."
      ],
      "urgencyReason": "Di dataran tinggi yang dingin dan berangin, penyakit ini bisa mematikan tunas dan bunga serta menurunkan hasil panen 15 sampai 43 persen."
    },
    "rust": {
      "name": "Karat daun kopi",
      "look": "Bercak kecil kuning pucat tampak di sisi atas daun. Di bawahnya, setiap bercak punya serbuk kuning sampai oranye tua yang menempel di jari. Bercak lama menjadi coklat di tengah dan daun rontok lebih awal. Biasanya mulai dari daun bagian bawah pohon.",
      "tellApart": "Karat punya serbuk oranye di sisi bawah daun, sedangkan bercak mata coklat punya cincin coklat kering dengan pusat abu-abu keputihan dan tanpa serbuk.",
      "actions": [
        "Periksa sisi bawah daun bagian bawah secara rutin. Menemukannya sejak dini paling penting.",
        "Petik dan bakar atau kubur daun dan cabang yang punya bercak oranye.",
        "Pangkas dan kurangi naungan serta gulma supaya udara bergerak dan daun lebih cepat kering.",
        "Beri pohon pupuk kandang atau pupuk berimbang. Pohon yang lemah terserang lebih parah.",
        "Semprot fungisida tembaga seperti tembaga hidroksida (copper hydroxide) pada sisi atas dan bawah daun selama daun yang sakit masih di bawah sekitar 5 persen. Tembaga melindungi daun yang sehat tetapi tidak menyembuhkan daun yang sakit. Tanyakan waktunya kepada penyuluh Anda.",
        "Untuk penanaman baru, tanyakan kepada penyuluh Anda tentang varietas tahan karat seperti jenis Catimor atau Sarchimor."
      ],
      "urgencyReason": "Penyakit ini menyebar cepat antar pohon dan antar kebun, dan kerugian pada varietas yang rentan bisa mencapai 30 sampai 80 persen."
    },
    "mites": {
      "name": "Kemungkinan kerusakan akibat tungau",
      "look": "Gambarnya mirip daun kopi yang diberi label kerusakan akibat tungau. Tanda yang mirip bisa punya penyebab lain, jadi ini baru kemungkinan.",
      "actions": [
        "Minta penyuluh memeriksa kedua sisi daun dan memastikan penyebabnya sebelum memilih pengobatan."
      ]
    },
    "weevil": {
      "name": "Kemungkinan kerusakan akibat hama pengunyah daun",
      "look": "Daun ini mirip gambar yang diberi label kerusakan akibat kumbang coco atau kumbang moncong. Foto ini tidak bisa menentukan jenis serangganya.",
      "actions": [
        "Minta penyuluh memeriksa daun yang rusak dan serangga di tanaman sebelum memilih pengobatan."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Cari stiker KEPHIS pada kemasan benih.",
    "stepScratch": "Gosok stikernya untuk menampilkan kode.",
    "stepText": "Kirim kode lewat pesan ke {shortCode}. Gratis.",
    "result": "KEPHIS membalas untuk memberi tahu apakah benihnya asli. Kode yang asli tidak membuktikan bahwa benih disimpan dengan baik.",
    "coverage": "Ini berlaku untuk benih bersertifikat yang dijual dalam kemasan. Bibit pembibitan biasanya tidak punya stiker, jadi tanyakan kepada petugas lapangan Anda tentang bibit itu.",
    "noContact": "Tanyakan kepada petugas lapangan Anda cara memeriksa apakah kemasan benih asli."
  },
  "phoneGreeting": "Halo, ini Leaf Doctor. Saya membantu soal tanaman kopi yang sakit, dan Anda bisa berbicara dengan saya dalam bahasa Anda sendiri. Apa yang Anda lihat pada daun kopi Anda?"
});

export default idText;
