// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const isText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Blöðin þín líta heilbrigð út",
    "headlineSpray": "{name}: verndaðu heilbrigð blöð og hreinsaðu til",
    "headlinePrune": "{name}: hreinsaðu til og klipptu",
    "headlineMonitor": "{name}: fylgstu áfram með",
    "headlineAskOfficer": "{name}: biddu ráðgjafann á vettvangi að skoða",
    "headlineNotSure": "Forritið er ekki visst. Sýndu ráðgjafanum á vettvangi þessi blöð",
    "headlineMightBe": "Þetta gæti verið {name} en það er ekki staðfest. Sýndu ráðgjafa á vettvangi",
    "headlineRetake": "Taktu skýrari myndir af fleiri blöðum",
    "retakeDaylight": "Farðu út í dagsbirtu, ekki í djúpan skugga eða beint sólarljós.",
    "retakeSteady": "Haltu símanum kyrrum þar til blaðið er skarpt.",
    "retakeFillFrame": "Fylltu rammann með einu blaði.",
    "sendToOfficer": "Sendu þetta mál með SMS til ráðgjafa samvinnufélagsins á vettvangi, eða sýndu honum blöðin í eigin persónu.",
    "rainReason": "Það rigndi {n} af síðustu 7 dögum nálægt þér ({source}). Blautt veður lætur ryð breiðast hraðar út.",
    "labelRate": "Notaðu skammtinn sem stendur á umbúðum vörunnar.",
    "elseBerryDisease": "Kaffiberjasjúkdómur: skoðaðu berin og leitaðu að dökkum, sokknum blettum.",
    "elseBerryBorer": "Kaffiberjabjalla: leitaðu að litlum götum á berjunum.",
    "elseWilt": "Kaffivisnun: heilar greinar visna og deyja.",
    "elseNutrition": "Léleg jörð eða næring: gulnun á öllu trénu.",
    "smsDecisionSpray": "Ákvörðun: verja heilbrigð blöð með kopar í skammtinum sem stendur á umbúðunum og hreinsa til. Athuga aftur eftir {days} daga.",
    "smsDecisionPrune": "Ákvörðun: klippa og hreinsa til. Athuga aftur eftir {days} daga.",
    "smsDecisionMonitor": "Ákvörðun: fylgjast áfram með. Athuga aftur eftir {days} daga.",
    "smsDecisionCallOfficer": "Ákvörðun: sýna ráðgjafanum á vettvangi."
  },
  "diseases": {
    "cercospora": {
      "name": "Brúnn augnblettur",
      "look": "Kringlóttir brúnir blettir, aðallega á efra borði blaðsins, með gráhvítri miðju og dökkbrúnum hring, oft með gulum bjarma. Blettirnir eru 5 til 15 mm breiðir og geta runnið saman í stóra dauða bletti. Á berjunum koma dökkir, sokknir blettir og þau þroskast of snemma.",
      "tellApart": "Brúnn augnblettur er með þurra brúna hringi og fölgráa miðju og engu appelsínugulu dufti, en ryð er með appelsínugult duft á neðra borðinu.",
      "actions": [
        "Gefðu trjánum góða næringu, sérstaklega köfnunarefni og kalí. Góð næring heldur þessum sjúkdómi oft í skefjum.",
        "Hafðu léttan skugga, haltu illgresi í skefjum og klipptu svo að loft nái að leika um og blöðin þorni.",
        "Eftir klippingu skaltu fara með blöðin og berin burt eða brenna þau. Ekki hrúga þeim upp við trén.",
        "Í gróðrarstöðinni skaltu hafa bil á milli plantna og brenna plöntur með hringjóttum brúnum blettum.",
        "Ef ástandið er slæmt getur koparsveppalyf varið heilbrigð blöð. Spyrðu ráðunautinn þinn fyrst."
      ],
      "urgencyReason": "Hann veikir aðallega streituplöguð tré og lagast yfirleitt þegar næring og skuggi eru löguð."
    },
    "healthy": {
      "name": "Heilbrigt kaffiblað",
      "look": "Heilbrigt blað er gljáandi, egglaga og oddhvasst, jafndökkgrænt, án bletta, dufts, gata eða ganga, bæði ofan og neðan.",
      "actions": [
        "Klipptu og haltu léttum skugga og illgresi í skefjum svo að blöðin þorni fljótt.",
        "Gefðu trjánum húsdýraáburð eða jafnvægisáburð, sérstaklega köfnunarefni og kalí.",
        "Skoðaðu blöðin og neðra borð þeirra í hverri viku eða aðra hverja viku til að finna ryð eða blaðnámufluguna snemma."
      ]
    },
    "miner": {
      "name": "Kaffiblaðnáma",
      "look": "Fölgulir, hlykkjóttir stígar birtast inni í blaðinu og breytast í ójafna, brúna, dauða bletti á efra borðinu. Ef þú beygir blaðið rifnar þunn húðin yfir blettinum í sundur og þú getur fundið örlitla gegnsæja lirfu inni í honum. Mikil sýking lætur blöðin falla.",
      "tellApart": "Blettir blaðnámunnar eru pappírsþunnar blöðrur með lirfu inni í sem rifna í sundur þegar þær eru beygðar, en brúnn augnblettur er snyrtilegur hringur sem rifnar ekki.",
      "actions": [
        "Beygðu brúna bletti til að leita að lifandi lirfum, sérstaklega á þurrkatímanum.",
        "Verndaðu náttúrulega óvini eins og litlar vespur og maura: hafðu blandaðan skugga og forðastu óþarfa úðun.",
        "Fylgstu vel með ungum trjám og gróðrarstöð og fjarlægðu fyrstu blettina snemma.",
        "Ef skordýraeitur þarf, spyrðu ráðunautinn þinn hvaða vara er lögleg og örugg í þínu landi."
      ],
      "urgencyReason": "Mikil sýking veldur laufföllum og minni uppskeru, verst í þurrum og heitum köflum."
    },
    "phoma": {
      "name": "Phoma-blaðblettur",
      "look": "Dökkbrúnir til svartir blettir, allt að 2 cm breiðir, á eldri blöðum, með ljósari miðju og dekkri brún. Oddar ungra sprota verða svartir og þorna, blóm geta drepist og ber falla. Skaðinn getur byrjað við blaðoddinn eða brúnina.",
      "tellApart": "Phoma drepur líka odda ungra sprota og blóm á köldum, vindasömum hálendum svæðum, en brúnn augnblettur helst sem hringjóttir blettir og þurrkar ekki sprotaodda.",
      "actions": [
        "Gróðursettu skjólbelti á vindasömum svæðum. Vindskemmdir hleypa sveppnum inn.",
        "Klipptu af og eyddu þurrum sprotum og skrælnuðum berjum, og klipptu svo að loft nái að þurrka blöðin.",
        "Gefðu trjánum jafnvægisáburð, sérstaklega köfnunarefni og kalí.",
        "Á köldum, vindasömum árstíðum skaltu úða koparsveppalyfi áður en sjúkdómurinn birtist. Spyrðu ráðunautinn þinn um tímasetningu."
      ],
      "urgencyReason": "Á köldum, vindasömum hálendum svæðum getur hann drepið sprota og blóm og dregið úr uppskeru um 15 til 43 prósent."
    },
    "rust": {
      "name": "Kaffiblaðaryð",
      "look": "Litlir fölgulir blettir birtast á efra borði blaðsins. Á neðra borðinu er á hverjum bletti duft, gult til dökkappelsínugult, sem smitast á fingurinn. Gamlir blettir verða brúnir í miðjunni og blöðin falla snemma. Það byrjar yfirleitt á neðri blöðum trésins.",
      "tellApart": "Ryð er með appelsínugult duft á neðra borði blaðsins, en brúnn augnblettur er með þurra brúna hringi með gráhvítri miðju og án dufts.",
      "actions": [
        "Skoðaðu neðra borð neðri blaða oft. Mestu skiptir að finna það snemma.",
        "Taktu af og brenndu eða grafðu blöð og greinar með appelsínugulum blettum.",
        "Klipptu og þynntu skugga og illgresi svo að loft nái að leika um og blöðin þorni hraðar.",
        "Gefðu trjánum húsdýraáburð eða jafnvægisáburð. Veik tré verða verr úti.",
        "Úðaðu koparsveppalyfi, svo sem koparhýdroxíði (copper hydroxide), á efra og neðra borð blaðanna á meðan færri en um 5 prósent blaða eru sjúk. Kopar ver heilbrigð blöð en læknar ekki sjúk. Spyrðu ráðunautinn þinn um tímasetningu.",
        "Fyrir nýja gróðursetningu skaltu spyrja ráðunautinn þinn um ryðþolin afbrigði, svo sem af gerðinni Catimor eða Sarchimor."
      ],
      "urgencyReason": "Það breiðist hratt út milli trjáa og bæja, og tap á næmum afbrigðum getur náð 30 til 80 prósentum."
    },
    "mites": {
      "name": "Hugsanlegur maurskaði",
      "look": "Myndin líkist kaffiblöðum sem eru merkt með maurskaða. Svipuð ummerki geta átt sér aðrar orsakir, svo þetta er hugsanleg samsvörun.",
      "actions": [
        "Biddu ráðunaut að skoða báðar hliðar blaðsins og staðfesta orsökina áður en meðferð er valin."
      ]
    },
    "weevil": {
      "name": "Hugsanlegur skaði af völdum blaðétandi meindýrs",
      "look": "Blaðið líkist myndum sem eru merktar sem coco- eða snýlubjölluskaði. Þessi mynd getur ekki greint tegund skordýrsins.",
      "actions": [
        "Biddu ráðunaut að skoða skemmda blaðið og skordýr á plöntunni áður en meðferð er valin."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Finndu KEPHIS-miðann á fræpokanum.",
    "stepScratch": "Skafðu miðann til að sýna kóðann.",
    "stepText": "Sendu kóðann í skilaboðum í {shortCode}. Það er ókeypis.",
    "result": "KEPHIS svarar og segir hvort fræið sé ósvikið. Ósvikinn kóði sannar ekki að fræið hafi verið vel geymt.",
    "coverage": "Þetta virkar fyrir vottað fræ sem selt er í pokum. Plöntur úr gróðrarstöð eru yfirleitt ekki með miða, svo spyrðu ráðgjafann á vettvangi um þær.",
    "noContact": "Spyrðu ráðgjafann á vettvangi hvernig á að athuga hvort fræpoki sé ósvikinn."
  },
  "phoneGreeting": "Góðan daginn, þetta er Leaf Doctor. Ég hjálpa með veikar kaffiplöntur og þú getur talað við mig á þínu eigin tungumáli. Hvað sérðu á kaffiblöðunum þínum?"
});

export default isText;
