// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const itText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Le sue foglie sembrano sane",
    "headlineSpray": "{name}: protegga le foglie sane e faccia pulizia",
    "headlinePrune": "{name}: faccia pulizia e poti",
    "headlineMonitor": "{name}: continui a osservare",
    "headlineAskOfficer": "{name}: chieda al suo tecnico di campo di controllare",
    "headlineNotSure": "L'app non è sicura. Mostri queste foglie al suo tecnico di campo",
    "headlineMightBe": "Potrebbe essere {name}, ma non è confermato. Lo mostri a un tecnico di campo",
    "headlineRetake": "Scatti foto più chiare di più foglie",
    "retakeDaylight": "Si sposti alla luce del giorno, non in ombra fitta né al sole diretto.",
    "retakeSteady": "Tenga fermo il telefono finché la foglia non appare nitida.",
    "retakeFillFrame": "Riempia l'inquadratura con una sola foglia.",
    "sendToOfficer": "Invii questo caso con un SMS al tecnico di campo della sua cooperativa, oppure gli mostri le foglie di persona.",
    "rainReason": "Ha piovuto in {n} degli ultimi 7 giorni vicino a lei ({source}). Il tempo umido fa diffondere la ruggine più in fretta.",
    "labelRate": "Usi la dose indicata sull'etichetta del prodotto.",
    "elseBerryDisease": "Malattia delle bacche del caffè: guardi le bacche per vedere macchie scure e infossate.",
    "elseBerryBorer": "Trivellatore delle bacche del caffè: cerchi piccoli fori nelle bacche.",
    "elseWilt": "Avvizzimento del caffè: rami interi che appassiscono e muoiono.",
    "elseNutrition": "Terreno povero o poco nutrimento: ingiallimento su tutto l'albero.",
    "smsDecisionSpray": "Decisione: proteggere le foglie sane con il rame alla dose indicata sull'etichetta e fare pulizia. Controllare di nuovo tra {days} giorni.",
    "smsDecisionPrune": "Decisione: potare e fare pulizia. Controllare di nuovo tra {days} giorni.",
    "smsDecisionMonitor": "Decisione: continuare a osservare. Controllare di nuovo tra {days} giorni.",
    "smsDecisionCallOfficer": "Decisione: mostrare al tecnico di campo."
  },
  "diseases": {
    "cercospora": {
      "name": "Macchia bruna a occhio",
      "look": "Macchie rotonde marroni, soprattutto sulla pagina superiore della foglia, con il centro grigio-bianco e un anello marrone scuro, spesso con un alone giallo. Le macchie sono larghe da 5 a 15 mm e possono unirsi in grandi chiazze morte. Le bacche hanno chiazze scure e infossate e maturano troppo presto.",
      "tellApart": "La macchia bruna a occhio ha anelli marroni secchi con il centro grigio chiaro e nessuna polvere arancione, mentre la ruggine ha polvere arancione sotto la foglia.",
      "actions": [
        "Nutra bene gli alberi, soprattutto con azoto e potassio. Una buona nutrizione spesso tiene sotto controllo questa malattia.",
        "Mantenga un'ombra leggera, controlli le erbacce e poti in modo che l'aria circoli e le foglie si asciughino.",
        "Dopo la potatura, porti via o bruci foglie e bacche. Non le accumuli vicino agli alberi.",
        "In vivaio, distanzi le piantine e bruci quelle con macchie marroni ad anello.",
        "Se la situazione è grave, un fungicida a base di rame può proteggere le foglie sane. Prima chieda al suo tecnico agricolo."
      ],
      "urgencyReason": "Indebolisce soprattutto gli alberi sotto stress e di solito migliora quando nutrizione e ombra vengono sistemate."
    },
    "healthy": {
      "name": "Foglia di caffè sana",
      "look": "Una foglia sana è lucida, ovale e appuntita, di un verde scuro uniforme, senza macchie, polvere, fori o gallerie né sopra né sotto.",
      "actions": [
        "Poti e mantenga un'ombra leggera e poche erbacce, così le foglie si asciugano in fretta.",
        "Nutra gli alberi con letame o concime bilanciato, soprattutto con azoto e potassio.",
        "Controlli le foglie e la loro pagina inferiore ogni settimana o due, per scoprire presto la ruggine o il minatore fogliare."
      ]
    },
    "miner": {
      "name": "Minatore fogliare del caffè",
      "look": "Sulla foglia compaiono sentieri giallo pallido e tortuosi all'interno, che diventano chiazze morte marroni e irregolari sopra. Se piega la foglia, la sottile pellicola superiore sopra la chiazza si stacca e dentro può trovare una minuscola larva trasparente. Gli attacchi forti fanno cadere le foglie.",
      "tellApart": "Le chiazze del minatore sono bolle sottili come carta con una larva dentro, che si staccano quando si piega la foglia, mentre la macchia bruna a occhio è un anello rotondo e netto che non si stacca.",
      "actions": [
        "Pieghi le chiazze marroni per cercare larve vive, soprattutto nella stagione secca.",
        "Protegga i nemici naturali, come le piccole vespe e le formiche, mantenendo ombra mista ed evitando trattamenti inutili.",
        "Osservi con attenzione gli alberi giovani e il vivaio e tolga presto le prime chiazze.",
        "Se serve un insetticida, chieda al suo tecnico agricolo quale prodotto è legale e sicuro nel suo paese."
      ],
      "urgencyReason": "Gli attacchi forti fanno cadere le foglie e riducono il raccolto, soprattutto nei periodi secchi e caldi."
    },
    "phoma": {
      "name": "Macchia fogliare da Phoma",
      "look": "Macchie da marrone scuro a nere, larghe fino a 2 cm, sulle foglie più vecchie, con il centro più chiaro e il bordo più scuro. Le punte dei germogli giovani diventano nere e seccano, i fiori possono morire e le bacche cadono. Il danno può iniziare dalla punta o dal bordo della foglia.",
      "tellApart": "La Phoma uccide anche le punte dei germogli giovani e i fiori negli altopiani freddi e ventosi, mentre la macchia bruna a occhio resta in macchie ad anello e non secca le punte dei germogli.",
      "actions": [
        "Pianti frangivento nelle zone ventose. I danni del vento fanno entrare il fungo.",
        "Tagli e distrugga i germogli secchi e le bacche mummificate, e poti in modo che l'aria possa asciugare le foglie.",
        "Nutra gli alberi con concime bilanciato, soprattutto con azoto e potassio.",
        "Nelle stagioni fredde e ventose, spruzzi un fungicida a base di rame prima che compaia la malattia. Chieda al suo tecnico agricolo quando farlo."
      ],
      "urgencyReason": "Negli altopiani freddi e ventosi può uccidere germogli e fiori e ridurre il raccolto dal 15 al 43 per cento."
    },
    "rust": {
      "name": "Ruggine del caffè",
      "look": "Piccole macchie giallo pallido compaiono sopra la foglia. Sotto, ogni macchia ha una chiazza di polvere da gialla ad arancione scuro che resta sul dito. Le macchie vecchie diventano marroni al centro e le foglie cadono presto. Di solito inizia dalle foglie basse dell'albero.",
      "tellApart": "La ruggine ha polvere arancione sulla pagina inferiore della foglia, mentre la macchia bruna a occhio ha anelli marroni secchi con il centro grigio-bianco e senza polvere.",
      "actions": [
        "Controlli spesso la pagina inferiore delle foglie basse. Scoprirla presto è la cosa più importante.",
        "Stacchi e bruci o sotterri le foglie e i rami con macchie arancioni.",
        "Poti e riduca ombra ed erbacce in modo che l'aria circoli e le foglie si asciughino più in fretta.",
        "Nutra gli alberi con letame o concime bilanciato. Gli alberi deboli sono colpiti più duramente.",
        "Spruzzi un fungicida a base di rame, come l'idrossido di rame (copper hydroxide), sopra e sotto le foglie finché sono malate meno del 5 per cento circa delle foglie. Il rame protegge le foglie sane ma non guarisce quelle malate. Chieda al suo tecnico agricolo quando farlo.",
        "Per un nuovo impianto, chieda al suo tecnico agricolo delle varietà resistenti alla ruggine, come i tipi Catimor o Sarchimor."
      ],
      "urgencyReason": "Si diffonde in fretta tra alberi e aziende, e le perdite sulle varietà sensibili possono arrivare dal 30 all'80 per cento."
    },
    "mites": {
      "name": "Possibile danno da acari",
      "look": "L'immagine somiglia a foglie di caffè etichettate con danno da acari. Segni simili possono avere altre cause, quindi questa è solo una possibile corrispondenza.",
      "actions": [
        "Chieda a un tecnico agricolo di controllare entrambi i lati della foglia e di confermare la causa prima di scegliere un trattamento."
      ]
    },
    "weevil": {
      "name": "Possibile danno da parassita che mangia le foglie",
      "look": "La foglia somiglia a immagini etichettate come danno da coco o da punteruolo. Questa foto non può identificare la specie dell'insetto.",
      "actions": [
        "Chieda a un tecnico agricolo di controllare la foglia danneggiata e gli insetti sulla pianta prima di scegliere un trattamento."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Trovi l'adesivo KEPHIS sulla confezione dei semi.",
    "stepScratch": "Gratti l'adesivo per far comparire il codice.",
    "stepText": "Invii il codice in un messaggio a {shortCode}. È gratuito.",
    "result": "KEPHIS risponde dicendo se il seme è autentico. Un codice autentico non prova che il seme sia stato conservato bene.",
    "coverage": "Funziona per i semi certificati venduti in confezione. Le piantine da vivaio di solito non hanno l'adesivo, quindi chieda informazioni al suo tecnico di campo.",
    "noContact": "Chieda al suo tecnico di campo come controllare se una confezione di semi è autentica."
  },
  "phoneGreeting": "Buongiorno, sono Leaf Doctor. Aiuto con le piante di caffè malate e lei può parlare con me nella sua lingua. Che cosa vede sulle foglie del suo caffè?"
});

export default itText;
