// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const jvText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Godhong panjenengan katon sehat",
    "headlineSpray": "{name}: lindhungi godhong sing sehat lan resik-resiken",
    "headlinePrune": "{name}: resik-resiken lan pangkas",
    "headlineMonitor": "{name}: terusna ngawasi",
    "headlineAskOfficer": "{name}: nyuwuna petugas lapangan panjenengan mriksa",
    "headlineNotSure": "Aplikasi ora yakin. Tuduhna godhong-godhong iki marang petugas lapangan panjenengan",
    "headlineMightBe": "Bisa uga {name}, nanging durung dipesthekake. Tuduhna marang petugas lapangan",
    "headlineRetake": "Jupuk foto sing luwih cetha saka luwih akeh godhong",
    "retakeDaylight": "Pindhaha menyang cahya awan, aja ing wewayangan peteng utawa ing panase srengenge langsung.",
    "retakeSteady": "Cekelen ponsel kanthi ajeg nganti godhonge katon cetha.",
    "retakeFillFrame": "Kebakna pigura nganggo godhong siji.",
    "sendToOfficer": "Kirimen kasus iki liwat SMS marang petugas lapangan koperasi panjenengan, utawa tuduhna godhonge langsung.",
    "rainReason": "Udan ing {n} saka 7 dina pungkasan ing cedhak panjenengan ({source}). Cuaca teles ndadekake karat nyebar luwih cepet.",
    "labelRate": "Gunakna takeran sing ana ing label produk.",
    "elseBerryDisease": "Penyakit woh kopi: delengen wohe, goleka bintik peteng sing amblong.",
    "elseBerryBorer": "Hama pengerek woh kopi: goleka bolongan cilik ing woh.",
    "elseWilt": "Layu kopi: pang-pang kabeh layu lan mati.",
    "elseNutrition": "Lemah elek utawa kurang pangan: kabeh wit dadi kuning.",
    "smsDecisionSpray": "Kaputusan: lindhungi godhong sing sehat nganggo tembaga miturut takeran label lan resik-resiken. Priksa maneh ing {days} dina.",
    "smsDecisionPrune": "Kaputusan: pangkas lan resik-resiken. Priksa maneh ing {days} dina.",
    "smsDecisionMonitor": "Kaputusan: terusna ngawasi. Priksa maneh ing {days} dina.",
    "smsDecisionCallOfficer": "Kaputusan: tuduhna marang petugas lapangan panjenengan."
  },
  "diseases": {
    "cercospora": {
      "name": "Bintik mripat coklat",
      "look": "Bintik coklat bunder, biasane ing sisih ndhuwur godhong, kanthi tengah abu-abu putih lan bunderan coklat tuwa, kerep ana lingkaran kuning ing sakubenge. Bintik jembare 5 nganti 15 mm lan bisa nyawiji dadi bagean mati sing gedhe. Woh-wohan oleh bintik peteng sing amblong lan mateng kecepeten.",
      "tellApart": "Bintik mripat coklat nduweni bunderan coklat garing kanthi tengah abu-abu pucet lan ora ana bubuk oranye, dene karat nduweni bubuk oranye ing sangisore godhong.",
      "actions": [
        "Wenehana pupuk sing cukup marang wit, utamane nitrogen lan kalium. Pupuk sing apik kerep bisa ngendhalekake penyakit iki.",
        "Jaganen ayom sing entheng, kendhalekna suket, lan pangkasen supaya hawa bisa mlaku lan godhong garing.",
        "Sawise mangkas, gawanen adoh utawa obongen godhong lan wohe. Aja ditumpuk cedhak wit.",
        "Ing pawinihan, wenehana jarak antarane winih lan obongen winih sing nduweni bintik coklat sing bunder.",
        "Yen parah, fungisida tembaga bisa nglindhungi godhong sing sehat. Takon disik marang penyuluh panjenengan."
      ],
      "urgencyReason": "Penyakit iki utamane nyilakakake wit sing ringkih lan biasane dadi apik yen pupuk lan ayome diatur."
    },
    "healthy": {
      "name": "Godhong kopi sehat",
      "look": "Godhong sing sehat mengkilap, bunder dowo lan lancip, ijo tuwa sing rata, tanpa bintik, bubuk, bolongan utawa trowongan ing ndhuwur utawa ing ngisor.",
      "actions": [
        "Pangkasen lan jaganen ayom sing entheng lan suket sing sethithik supaya godhong cepet garing.",
        "Wenehana pupuk kandhang utawa pupuk imbang marang wit, utamane nitrogen lan kalium.",
        "Priksanen godhong lan sisih ngisore saben minggu utawa rong minggu supaya karat utawa hama penggorok godhong ketemu luwih awal."
      ]
    },
    "miner": {
      "name": "Hama penggorok godhong kopi",
      "look": "Dalan kuning pucet sing ngliku-liku katon ing njero godhong lan malih dadi bagean mati coklat sing ora rata ing sisih ndhuwur. Yen godhonge ditekuk, kulit tipis ing ndhuwur bagean kuwi mlethek lan ing njero bisa ditemokake ulat cilik sing bening. Serangan abot ndadekake godhong rontog.",
      "tellApart": "Bagean penggorok godhong iku lepuh tipis kaya kertas kanthi ulat ing njero sing mlethek yen ditekuk, dene bintik mripat coklat iku bunderan bunder sing rapi lan ora mlethek.",
      "actions": [
        "Tekuken bagean coklat kanggo nggoleki ulat sing isih urip, utamane ing mangsa ketiga.",
        "Lindhungana mungsuh alami kayata tawon cilik lan semut kanthi njaga ayom campuran lan ngindhari nyemprot sing ora perlu.",
        "Awasana wit enom lan pawinihan kanthi tliti lan copoten bintik pisanan luwih awal.",
        "Yen perlu insektisida, takon marang penyuluh panjenengan produk endi sing sah lan aman ing negara panjenengan."
      ],
      "urgencyReason": "Serangan abot ndadekake godhong rontog lan nyuda asil panen, paling parah ing mangsa garing lan panas."
    },
    "phoma": {
      "name": "Bintik godhong Phoma",
      "look": "Bintik coklat tuwa nganti ireng jembare nganti 2 cm ing godhong sing luwih tuwa, kanthi tengah sing luwih padhang lan pinggir sing luwih peteng. Pucuk pang enom dadi ireng lan garing, kembang bisa mati, lan woh rontog. Karusakan bisa diwiwiti saka pucuk utawa pinggiring godhong.",
      "tellApart": "Phoma uga mateni pucuk pang enom lan kembang ing dhataran dhuwur sing adhem lan akeh angin, dene bintik mripat coklat tetep dadi bintik sing bunder lan ora ngeringake pucuk pang.",
      "actions": [
        "Tanduren wit panahan angin ing wilayah sing akeh angine. Karusakan amarga angin ndadekake jamur bisa mlebu.",
        "Pangkasen lan musnahna pang sing garing lan woh sing garing, lan pangkasen supaya hawa bisa ngeringake godhong.",
        "Wenehana pupuk imbang marang wit, utamane nitrogen lan kalium.",
        "Ing mangsa adhem lan akeh angin, semprotna fungisida tembaga sadurunge penyakit katon. Takon marang penyuluh panjenengan babagan wektune."
      ],
      "urgencyReason": "Ing dhataran dhuwur sing adhem lan akeh angin, penyakit iki bisa mateni pang lan kembang lan nyuda asil panen 15 nganti 43 persen."
    },
    "rust": {
      "name": "Karat godhong kopi",
      "look": "Bintik cilik kuning pucet katon ing sisih ndhuwur godhong. Ing sangisore, saben bintik nduweni bubuk kuning nganti oranye tuwa sing lengket ing driji. Bintik lawas dadi coklat ing tengah lan godhong rontog luwih awal. Biasane diwiwiti saka godhong ngisor ing wit.",
      "tellApart": "Karat nduweni bubuk oranye ing sisih ngisor godhong, dene bintik mripat coklat nduweni bunderan coklat garing kanthi tengah abu-abu putih lan ora ana bubuk.",
      "actions": [
        "Kerep-kerep priksanen sisih ngisor godhong sing ana ing ngisor. Ngerteni luwih awal iku sing paling penting.",
        "Petiken lan obongen utawa pendhemen godhong lan pang sing nduweni bintik oranye.",
        "Pangkasen lan kurangana ayom lan suket supaya hawa bisa mlaku lan godhong luwih cepet garing.",
        "Wenehana pupuk kandhang utawa pupuk imbang marang wit. Wit sing ringkih luwih parah kena.",
        "Semprotna fungisida tembaga kayata tembaga hidroksida (copper hydroxide) ing sisih ndhuwur lan ngisor godhong salawase kurang saka kira-kira 5 persen godhong sing lara. Tembaga nglindhungi godhong sing sehat nanging ora nyembuhake sing lara. Takon marang penyuluh panjenengan babagan wektune.",
        "Kanggo nandur anyar, takon marang penyuluh panjenengan babagan varietas sing tahan karat kayata jinis Catimor utawa Sarchimor."
      ],
      "urgencyReason": "Penyakit iki nyebar cepet antarane wit lan kebon, lan kerugian ing varietas sing gampang kena bisa tekan 30 nganti 80 persen."
    },
    "mites": {
      "name": "Kamungkinan karusakan amarga tungau",
      "look": "Gambare padha karo godhong kopi sing diwenehi label karusakan amarga tungau. Tandha sing meh padha bisa duwe panyebab liyane, dadi iki mung kamungkinan.",
      "actions": [
        "Nyuwuna penyuluh mriksa loro-lorone sisih godhong lan mesthekake panyebabe sadurunge milih pangobatan."
      ]
    },
    "weevil": {
      "name": "Kamungkinan karusakan amarga hama sing nggragoti godhong",
      "look": "Godhonge padha karo gambar sing diwenehi label karusakan amarga kumbang coco utawa kumbang moncong. Foto iki ora bisa nemtokake jinis seranggane.",
      "actions": [
        "Nyuwuna penyuluh mriksa godhong sing rusak lan serangga ing tanduran sadurunge milih pangobatan."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Goleki stiker KEPHIS ing bungkus wiji.",
    "stepScratch": "Gosoken stikere supaya kode katon.",
    "stepText": "Kirimen kode menyang {shortCode} nganggo pesen. Gratis.",
    "result": "KEPHIS mbales kanggo ngandhani apa wijine asli. Kode sing asli ora mbuktekake yen wijine disimpen kanthi becik.",
    "coverage": "Iki bisa dienggo kanggo wiji sing wis disertifikasi lan didol ing bungkus. Winih pawinihan biasane ora duwe stiker, mula takonna petugas lapangan panjenengan.",
    "noContact": "Takon marang petugas lapangan panjenengan carane mriksa apa bungkus wiji iku asli."
  },
  "phoneGreeting": "Sugeng, niki Leaf Doctor. Kula mbiyantu bab tanduran kopi ingkang sakit, lan panjenengan saged rembugan kaliyan kula nganggo basa panjenengan piyambak. Panjenengan ningali menapa wonten ing godhong kopi panjenengan?"
});

export default jvText;
