// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const lbText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Är Bläter gesinn gesond aus",
    "headlineSpray": "{name}: gesond Bläter schützen an opraumen",
    "headlinePrune": "{name}: opraumen a schneiden",
    "headlineMonitor": "{name}: weider beobachten",
    "headlineAskOfficer": "{name}: Äre Feldberoder bieden ze kucken",
    "headlineNotSure": "D'App ass sech net sécher. Weist dës Bläter Ärem Feldberoder",
    "headlineMightBe": "Et kéint {name} sinn, awer et ass net bestätegt. Weist et engem Feldberoder",
    "headlineRetake": "Maacht méi kloer Fotoen vu méi Bläter",
    "retakeDaylight": "Gitt an d'Dagesliicht, net an déifen Schiet an net an direkt Sonn.",
    "retakeSteady": "Hält den Telefon roueg, bis d'Blat schaarf ausgesäit.",
    "retakeFillFrame": "Fëllt de Bild mat engem Blat.",
    "sendToOfficer": "Schéckt dëse Fall per SMS un de Feldberoder vun Ärer Kooperativ oder weist d'Bläter perséinlech.",
    "rainReason": "Bei Iech huet et an {n} vun de leschte 7 Deeg gereent ({source}). Naass Wieder léisst d'Roscht méi séier verbreeden.",
    "labelRate": "Benotzt d'Dosis, déi um Etikett vum Produit steet.",
    "elseBerryDisease": "Kaffisbier-Krankheet: kuckt, ob d'Bieren donkel agesonk Flecke hunn.",
    "elseBerryBorer": "Kaffisbier-Burer: sicht no klenge Lächer an de Bieren.",
    "elseWilt": "Kaffis-Welk: ganz Äscht verwelken a stierwen of.",
    "elseNutrition": "Schlecht Buedem oder Nährstoffmangel: de ganze Bam gëtt giel.",
    "smsDecisionSpray": "Entscheedung: gesond Bläter mat Kupfer no der Dosis um Etikett schützen an opraumen. Kontrolléiert a(n) {days} Deeg nach eng Kéier.",
    "smsDecisionPrune": "Entscheedung: schneiden an opraumen. Kontrolléiert a(n) {days} Deeg nach eng Kéier.",
    "smsDecisionMonitor": "Entscheedung: weider beobachten. Kontrolléiert a(n) {days} Deeg nach eng Kéier.",
    "smsDecisionCallOfficer": "Entscheedung: Ärem Feldberoder weisen."
  },
  "diseases": {
    "cercospora": {
      "name": "Brong Aenfleck-Krankheet",
      "look": "Ronn brong Flecken, meescht uewen um Blat, mat engem gro-wäisse Mëttelpunkt an engem donkelbrongen Rank, dacks mat engem giele Rand. D'Flecke sinn 5 bis 15 mm breet a kënne sech zu groussen doudege Plazen zesummeschléissen. D'Bieren kréie donkel agesonk Flecken a ginn ze fréi reif.",
      "tellApart": "D'Brong Aenfleck-Krankheet huet dréchen brong Réng mat engem hellgrauen Mëttelpunkt a kee orange Pudder, wärend d'Roscht orange Pudder ënnendrënner huet.",
      "actions": [
        "Ernärt d'Beem gutt, besonnesch mat Stickstoff a Kalium. Gutt Ernärung hält dës Krankheet dacks an der Kontroll.",
        "Haalt liichte Schiet, kontrolléiert d'Onkraut a schneit esou, datt d'Loft zirkuléiert an d'Bläter dréchnen.",
        "No dem Schneiden huelt d'Bläter a Bieren ewech oder verbrennt se. Stapelt se net bei de Beem.",
        "An der Baamschoul setzt d'Stiecher mat Ofstand a verbrennt Stiecher mat ringfërmege brongen Flecken.",
        "Wann et schlëmm ass, kann e Kupferfungizid déi gesond Bläter schützen. Freet fir d'éischt Äre Landwirtschaftsberoder."
      ],
      "urgencyReason": "Si schwächt haaptsächlech gestresste Beem a gëtt normalerweis besser, wann d'Ernärung an de Schiet an Uerdnung kommen."
    },
    "healthy": {
      "name": "Gesond Kaffisblat",
      "look": "E gesond Blat ass glänzend, oval a spëtz, gläichméisseg donkelgréng, ouni Flecken, Pudder, Lächer oder Tunnelen uewen an ënnen.",
      "actions": [
        "Schneit d'Beem a haalt liichte Schiet an d'Onkraut kuerz, fir datt d'Bläter séier dréchnen.",
        "Ernärt d'Beem mat Mëscht oder ausgeglächenem Dünger, besonnesch mat Stickstoff a Kalium.",
        "Kontrolléiert d'Bläter an hir Ënnersäit all eng oder zwou Wochen, fir Roscht oder Blatminéierer fréi ze fannen."
      ]
    },
    "miner": {
      "name": "Kaffisblat-Minéierer",
      "look": "Hellgiel, gewonne Gäng erschénge bannen am Blat a ginn uewen zu ongläiche brongen doudege Plazen. Wann Dir d'Blat biegt, geet déi dënn Haut iwwer der Plaz auserneen, a Dir fannt eng kleng duerchsiichteg Larv dobannen. Schwéier Befall léisst d'Bläter fale.",
      "tellApart": "D'Minéierer-Plaze si papierdënn Blosen mat enger Larv dobannen, déi beim Biege auserneeginn, wärend d'Brong Aenfleck-Krankheet e propperen ronnen Rank ass, deen net auserneegeet.",
      "actions": [
        "Biegt brong Plazen, fir lieweg Larven ze sichen, besonnesch an der Dréchenzäit.",
        "Schützt natierlech Feinde wéi kleng Wespen a Seechomessen, andeems Dir gemëscht Schiet halt an onnéideg Spritzen vermeit.",
        "Kuckt jonk Beem an d'Baamschoul genau un a mécht déi éischt Plazen fréi ewech.",
        "Wann en Insektizid néideg ass, freet Äre Landwirtschaftsberoder, wéi ee Produit an Ärem Land erlaabt a sécher ass."
      ],
      "urgencyReason": "Schwéier Befall verursaacht Blatfall a méngert den Ertrag, am schlëmmste bei waarmen, dréchenen Zäiten."
    },
    "phoma": {
      "name": "Phoma-Blatfleckenkrankheet",
      "look": "Donkelbrong bis schwaarz Flecken, bis zu 2 cm breet, op eelere Bläter, mat engem méi hellen Mëttelpunkt an engem méi donkele Rand. D'Spëtze vu jonke Triebe ginn schwaarz an dréchnen aus, Blummen kënne stierwen, an d'Bieren falen of. De Schued ka bei der Blatspëtz oder um Rand ufänken.",
      "tellApart": "Phoma täift och d'Spëtze vu jonke Triebe a Blummen an de kale, wandege Héichlagen of, wärend d'Brong Aenfleck-Krankheet bei de ringfërmege Flecke bleift an d'Triebspëtze net ausdréchent.",
      "actions": [
        "Planzt Wandschutzhecken an de wandege Géigenden. Wandschued léisst de Pilz eran.",
        "Schneit dréche Triebe a mumifizéiert Bieren of a vernicht se, a schneit esou, datt d'Loft d'Bläter dréche kann.",
        "Ernärt d'Beem mat ausgeglächenem Dünger, besonnesch mat Stickstoff a Kalium.",
        "A kale, wandege Saisonen spritzt e Kupferfungizid, éier d'Krankheet erscheint. Freet Äre Landwirtschaftsberoder no dem Timing."
      ],
      "urgencyReason": "A kale, wandege Héichlagen ka si Triebe a Blummen ëmbréngen an den Ertrag em 15 bis 43 Prozent ofsenken."
    },
    "rust": {
      "name": "Kaffisblat-Roscht",
      "look": "Kleng hellgiel Flecken erschénge uewen um Blat. Ënnendrënner huet all Fleck eng Schicht giel bis donkelorange Pudder, deen um Fanger hänke bleift. Al Flecken ginn an der Mëtt brong, an d'Bläter falen ze fréi of. Normalerweis fänkt et un de ënneschte Bläter vum Bam un.",
      "tellApart": "D'Roscht huet orange Pudder op der Ënnersäit vum Blat, wärend d'Brong Aenfleck-Krankheet dréche brong Réng mat gro-wäissem Mëttelpunkt a kee Pudder huet.",
      "actions": [
        "Kontrolléiert dacks d'Ënnersäit vun de ënneschte Bläter. Et fréi ze fannen ass am wichtegsten.",
        "Rappt Bläter an Äscht mat orange Flecken of a verbrennt oder begrabt se.",
        "Schneit an dënnt Schiet an Onkraut aus, fir datt d'Loft zirkuléiert an d'Bläter méi séier dréchnen.",
        "Ernärt d'Beem mat Mëscht oder ausgeglächenem Dünger. Schwaach Beem ginn méi schwéier getraff.",
        "Spritzt e Kupferfungizid wéi Kupferhydroxid op d'Uewer- an Ënnersäit vun de Bläter, solaang manner wéi ongeféier 5 Prozent vun de Bläter krank sinn. Kupfer schützt gesond Bläter, heelt awer keng kranker. Freet Äre Landwirtschaftsberoder no dem Timing.",
        "Fir nei Planzungen freet Äre Landwirtschaftsberoder no roschtresistente Sorten wéi Catimor oder Sarchimor."
      ],
      "urgencyReason": "Si verbreet sech séier tëscht Beem a Betriber, a bei ufällege Sorte kënne Verloschter 30 bis 80 Prozent erreechen."
    },
    "mites": {
      "name": "Méiglechen Milleschued",
      "look": "D'Bild gläicht Kaffisbläter, déi als Milleschued markéiert sinn. Ähnlech Zeechen kënnen aner Ursaache hunn, dofir ass dat nëmmen eng méiglech Iwwereneestëmmung.",
      "actions": [
        "Bitt e Landwirtschaftsberoder, béid Säite vum Blat unzekucken an d'Ursaach ze bestätegen, éier Dir eng Behandlung wielt."
      ]
    },
    "weevil": {
      "name": "Méiglechen Schued duerch blatfriessend Schädlinge",
      "look": "D'Blat gläicht Biller, déi als Coco- oder Rësselkäfer-Schued markéiert sinn. Dëst Foto kann d'Insektenaart net bestëmmen.",
      "actions": [
        "Bitt e Landwirtschaftsberoder, d'beschiedegt Blat an d'Insekten op der Planz unzekucken, éier Dir eng Behandlung wielt."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Sicht de KEPHIS-Autocollant um Som-Pak.",
    "stepScratch": "Rubbelt den Autocollant fräi, fir de Code ze gesinn.",
    "stepText": "Schéckt de Code per SMS un {shortCode}. Et ass gratis.",
    "result": "KEPHIS äntwert, fir ze soen, ob de Som echt ass. E richtege Code beweist net, datt de Som gutt gelagert gouf.",
    "coverage": "Dëst funktionéiert fir zertifizéierte Som, deen a Päck verkaaft gëtt. Stiecher aus der Baamschoul hunn normalerweis keen Autocollant, dofir freet Äre Feldberoder dozou.",
    "noContact": "Freet Äre Feldberoder, wéi Dir kënnt kontrolléieren, ob e Som-Pak echt ass."
  },
  "phoneGreeting": "Moien, hei ass Leaf Doctor. Ech hëllefe bei kranke Kaffisplanzen, an Dir kënnt an Ärer eegener Sprooch mat mir schwätzen. Wat gesitt Dir op Äre Kaffisbläter?"
});

export default lbText;
