// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const lnText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Mapaya na yo emonani malamu",
    "headlineSpray": "{name}: bátɛlema mapaya malamu mpe bongisa esika",
    "headlinePrune": "{name}: bongisa esika mpe bokata nzete",
    "headlineMonitor": "{name}: kokoba kotala",
    "headlineAskOfficer": "{name}: senga mosungi na yo ya elanga atala",
    "headlineNotSure": "Appli eyebi malamu te. Lakisa mapaya oyo na mosungi na yo ya elanga",
    "headlineMightBe": "Ekoki kozala {name}, kasi ezali pe ndimama te. Lakisa mosungi ya elanga",
    "headlineRetake": "Bɔtɔla bafoto polele koleka ya mapaya mingi",
    "retakeDaylight": "Kende na pole ya moi, na elilingi makasi te to na moi makasi te.",
    "retakeSteady": "Mema telefone na kolɛngɛ tii lipaya emonani malamu.",
    "retakeFillFrame": "Tondisa ekran na lipaya moko.",
    "sendToOfficer": "Tinda likambo oyo epai ya mosungi ya elanga ya koperatifi na SMS, to lakisa ye mapaya na miso.",
    "rainReason": "Mvula ebɛtaki mikolo {n} na mikolo 7 eleki pembeni na yo ({source}). Mbula mingi esalaka ete rouille etambola noki.",
    "labelRate": "Salela quantité oyo ekomami na étiquette ya produit.",
    "elseBerryDisease": "Bokono ya mbuma ya kafé: tala mbuma soki ezali na bilembo ya moindo oyo ekɔtɔ.",
    "elseBerryBorer": "Nzokande ya mbuma ya kafé: luka mabulu mike na mbuma.",
    "elseWilt": "Kopɔla ya kafé: bitape mobimba ekopɔla mpe ekufa.",
    "elseNutrition": "Mabele ya malamu te to bilei ya nzete ezali te: nzete mobimba ekómi na langi ya mayi ya mbwa.",
    "smsDecisionSpray": "Mokano: bátɛlema mapaya malamu na cuivre na quantité ya étiquette mpe bongisa esika. Tala lisusu sima ya mikolo {days}.",
    "smsDecisionPrune": "Mokano: bokata nzete mpe bongisa esika. Tala lisusu sima ya mikolo {days}.",
    "smsDecisionMonitor": "Mokano: kokoba kotala. Tala lisusu sima ya mikolo {days}.",
    "smsDecisionCallOfficer": "Mokano: lakisa mosungi ya elanga."
  },
  "diseases": {
    "cercospora": {
      "name": "Bokono ya bilembo ya liso ya moindo",
      "look": "Bilembo ya mabɔkɔ ya moindo-ngenge, mingi likolo ya lipaya, na katikati ya langi ya cendre mpe zɔnga ya moindo makasi, mbala mingi na zɔnga ya langi ya mayi ya mbwa. Bilembo ezali na bonene ya 5 tii 15 mm mpe ekoki kosangana mpo na kokóma bisika monene ya kufa. Mbuma ezwaka bilembo ya moindo oyo ekɔtɔ mpe ebulaka noki mingi.",
      "tellApart": "Bokono ya bilembo ya liso ya moindo ezali na bazɔnga ya moindo ya kokauka na katikati ya langi ya cendre pɛ mpe ezali na putulu ya langi ya orange te, kasi rouille ezali na putulu ya langi ya orange na nse ya lipaya.",
      "actions": [
        "Pesa nzete bilei malamu, mingi azote mpe potassium. Bilei malamu ekangaka bokono oyo mbala mingi.",
        "Tika elili moke, bɔkɔla matiti mabe, mpe bokata nzete mpo mopepe eleka mpe mapaya ekauka.",
        "Sima ya bokati, zwa mapaya mpe mbuma mpe kanisa yango to kokanga yango na moto. Kobwaka yango pembeni ya nzete te.",
        "Na lopango ya bilenge nzete, bakisa bilenge nzete na kati na kati mpe kanga bilenge nzete oyo ezali na bilembo ya moindo ya zɔnga.",
        "Soki ezali makasi, fungicide ya cuivre ekoki kobatela mapaya malamu. Tuna liboso agent ya agriculture na yo."
      ],
      "urgencyReason": "Ebebisaka mingi nzete oyo ezali ya molɔngɔ te mpe ebongaka mbala mingi soki bilei mpe elili ebongisami."
    },
    "healthy": {
      "name": "Lipaya ya kafé ya malamu",
      "look": "Lipaya ya malamu ezali na lumbu, ya lolenge ya lipwa mpe ezali na nsɔngɛ, langi ya mobesu makasi, na bilembo te, putulu te, mabulu te to nzela te likolo to na nse.",
      "actions": [
        "Bokata nzete mpe tika elili moke mpe kokata matiti mpo mapaya ekauka noki.",
        "Pesa nzete fumier to engrais ya malamu, mingi azote mpe potassium.",
        "Tala mapaya mpe nse na yango mbala moko to mibale na poso mpo na kozwa rouille to nzokande ya lipaya noki."
      ]
    },
    "miner": {
      "name": "Nzokande ya lipaya ya kafé",
      "look": "Banzela ya langi ya mayi ya mbwa ekende kokoma na kati ya lipaya mpe ekoma bisika ya kufa ya moindo-ngenge likolo. Soki obuki lipaya, ngenge ya mpɛmbɛ likolo ya esika yango ekabwani mpe okoki kozwa nzokande moke ya polele na kati. Mpiko makasi esalaka ete mapaya ekwea.",
      "tellApart": "Bisika ya nzokande ezali na ndenge ya papye, na nzokande moke na kati, mpe ekabwanaka soki obuki yango, kasi bokono ya bilembo ya liso ya moindo ezali zɔnga ya malamu ekabwanaka te.",
      "actions": [
        "Buka bisika ya moindo-ngenge mpo na koluka nzokande ya bomoi, mingi na eleko ya kokauka.",
        "Batela banguna ya bozalisi lokola nzoi mike mpe fourmis, na kotika elili ya ndenge na ndenge mpe kosalela bakemika ya ntina te.",
        "Tala bilenge nzete mpe lopango ya bilenge nzete malamu mpe longola bisika ya liboso noki.",
        "Soki ezali na ntina ya kosalela insecticide, tuna agent ya agriculture na yo produit nini ezali na nzela mpe ezali na libɔndisi na mboka na yo."
      ],
      "urgencyReason": "Mpiko makasi esalaka ete mapaya ekwea mpe bobotami ekita, mingi na ntango ya moi makasi mpe kokauka."
    },
    "phoma": {
      "name": "Bokono ya bilembo ya lipaya ya Phoma",
      "look": "Bilembo ya mabɔkɔ moindo-ngenge tii moindo, bonene tii 2 cm, na mapaya ya kala, na katikati ya pɛ mpe ndelo ya moindo makasi. Nsɔngɛ ya bilenge bitape ekómaka moindo mpe ekaukaka, bafololo ekoki kokufa, mpe mbuma ekwaka. Libebi ekoki kobanda na nsɔngɛ to na ndelo ya lipaya.",
      "tellApart": "Phoma ebomaka lisusu nsɔngɛ ya bilenge bitape mpe bafololo na bisika ya ngomba oyo ezali na malili mpe mopepe, kasi bilembo ya liso ya moindo etikalaka na bilembo ya zɔnga mpe ekaukisaka nsɔngɛ te.",
      "actions": [
        "Lona banzete ya kobatela mopepe na bisika ya mopepe makasi. Libebi ya mopepe esalaka ete fungus ekɔta.",
        "Kata mpe ebebisa bitape ya kokauka mpe mbuma ya kokauka, mpe bokata nzete mpo mopepe ekaukisa mapaya.",
        "Pesa nzete engrais ya malamu, mingi azote mpe potassium.",
        "Na bileko ya malili mpe mopepe, bɛta fungicide ya cuivre liboso ya bokono kobima. Tuna agent ya agriculture na yo ntango."
      ],
      "urgencyReason": "Na bisika ya ngomba ya malili mpe mopepe ekoki kobomba bitape mpe bafololo mpe kokitisa bobotami na 15 tii 43 pɔsanti."
    },
    "rust": {
      "name": "Rouille ya lipaya ya kafé",
      "look": "Bilembo mike ya langi ya mayi ya mbwa emonani likolo ya lipaya. Na nse, elembo nyonso ezali na putulu ya langi ya mayi ya mbwa tii orange makasi oyo ekɔtaka na mosapi soki ofinaki yango. Bilembo ya kala ekómaka moindo-ngenge na katikati mpe mapaya ekwaka noki. Mbala mingi ebandaka na mapaya ya nse ya nzete.",
      "tellApart": "Rouille ezali na putulu ya orange na nse ya lipaya, kasi bokono ya bilembo ya liso ya moindo ezali na bazɔnga ya moindo-ngenge ya kokauka, katikati ya putulu pɛ, mpe putulu te.",
      "actions": [
        "Tala nse ya mapaya ya nse mbala mingi. Kozwa yango noki ezali ntina mingi.",
        "Futa mapaya mpe bitape oyo ezali na bilembo ya orange mpe kanisa yango to boma yango na mabele.",
        "Bokata nzete mpe kitisa elili mpe matiti mpo mopepe eleka mpe mapaya ekauka noki.",
        "Pesa nzete fumier to engrais ya malamu. Nzete ya molɔngɔ te ebɛlaka mingi.",
        "Bɛta fungicide ya cuivre lokola hydroxyde de cuivre likolo mpe na nse ya mapaya ntango mapaya ya bokono eleki te pembeni ya 5 pɔsanti. Cuivre ebatelaka mapaya malamu kasi esalaka mapaya ya bokono malamu te. Tuna agent ya agriculture na yo ntango.",
        "Mpo na kolona ya sika, tuna agent ya agriculture na yo mpo na ndenge oyo ekoki rouille te lokola Catimor to Sarchimor."
      ],
      "urgencyReason": "Etambolaka noki na kati ya banzete mpe bilanga, mpe bobungi na ndenge oyo ekoki kokɔta bokono ekoki kokoma 30 tii 80 pɔsanti."
    },
    "mites": {
      "name": "Ekoki kozala libebi ya mite",
      "look": "Elilingi ekokani na mapaya ya kafé oyo batiaki elembo ya libebi ya mite. Bilembo oyo ekokani ekoki kozala na bantina mosusu, yango wana ezali kaka likambo oyo ekoki kozala.",
      "actions": [
        "Senga agent ya agriculture atala mibale ya lipaya mpe andimisa ntina liboso ya kopona mondɔli."
      ]
    },
    "weevil": {
      "name": "Ekoki kozala libebi ya nzokande oyo ekitaka mapaya",
      "look": "Lipaya ekokani na bilili oyo batiaki elembo ya libebi ya coco to weevil. Foto oyo ekoki koyebisa lolenge ya nzokande te.",
      "actions": [
        "Senga agent ya agriculture atala lipaya oyo ebebi mpe nzokande oyo ezali na nzete liboso ya kopona mondɔli."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Luka sticker ya KEPHIS na sachet ya mbuma.",
    "stepScratch": "Kɔtɔla sticker mpo na komona kode.",
    "stepText": "Tinda kode na {shortCode} na SMS. Ezali ofele.",
    "result": "KEPHIS ezongisaka eyano mpo na koyebisa soki mbuma ezali ya solo. Kode ya solo emonisi te ete mbuma ebombamaki malamu.",
    "coverage": "Esalaka mpo na mbuma ya certifié oyo esombami na sachet. Bilenge nzete na lopango ya bilenge nzete ezalaka mbala mingi na sticker te, yango wana tuna mosungi na yo ya elanga.",
    "noContact": "Tuna mosungi na yo ya elanga ndenge ya kotala soki sachet ya mbuma ezali ya solo."
  },
  "phoneGreeting": "Mbote, nazali Leaf Doctor. Nasungaka bango oyo bakomi na bokono ya nzete ya kafé, mpe okoki koloba na ngai na monɔkɔ na yo moko. Ozali komona nini na mapaya ya kafé na yo?"
});

export default lnText;
