// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const ltText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Jūsų lapai atrodo sveiki",
    "headlineSpray": "{name}: apsaugokite sveikus lapus ir sutvarkykite",
    "headlinePrune": "{name}: sutvarkykite ir genėkite",
    "headlineMonitor": "{name}: toliau stebėkite",
    "headlineAskOfficer": "{name}: paprašykite lauko konsultanto apžiūrėti",
    "headlineNotSure": "Programa nėra tikra. Parodykite šiuos lapus savo lauko konsultantui",
    "headlineMightBe": "Gali būti {name}, bet tai nepatvirtinta. Parodykite lauko konsultantui",
    "headlineRetake": "Nufotografuokite aiškiau ir daugiau lapų",
    "retakeDaylight": "Eikite į dienos šviesą, ne į gilų šešėlį ir ne į tiesioginę saulę.",
    "retakeSteady": "Laikykite telefoną nejudindami, kol lapas atrodys ryškus.",
    "retakeFillFrame": "Užpildykite kadrą vienu lapu.",
    "sendToOfficer": "Išsiųskite šį atvejį savo kooperatyvo lauko konsultantui SMS žinute arba parodykite lapus asmeniškai.",
    "rainReason": "Netoli jūsų per paskutines 7 dienas lijo {n} dienas ({source}). Drėgnas oras padeda rūdims plisti greičiau.",
    "labelRate": "Naudokite dozę, nurodytą ant produkto etiketės.",
    "elseBerryDisease": "Kavos uogų liga: pažiūrėkite, ar uogose nėra tamsių įdubusių dėmių.",
    "elseBerryBorer": "Kavos uogų grąžtinukas: ieškokite mažų skylučių uogose.",
    "elseWilt": "Kavos vytimas: vysta ir džiūsta ištisos šakos.",
    "elseNutrition": "Prasta dirva arba trūksta maisto medžiagų: pagelsta visas medis.",
    "smsDecisionSpray": "Sprendimas: apsaugoti sveikus lapus variu pagal etiketės dozę ir sutvarkyti. Patikrinkite dar kartą po {days} dienų.",
    "smsDecisionPrune": "Sprendimas: genėti ir sutvarkyti. Patikrinkite dar kartą po {days} dienų.",
    "smsDecisionMonitor": "Sprendimas: toliau stebėti. Patikrinkite dar kartą po {days} dienų.",
    "smsDecisionCallOfficer": "Sprendimas: parodyti lauko konsultantui."
  },
  "diseases": {
    "cercospora": {
      "name": "Rudoji akutė dėmėtligė",
      "look": "Apvalios rudos dėmės, daugiausia lapo viršuje, su pilkšvai baltu centru ir tamsiai rudu žiedu, dažnai su geltonu apvadu. Dėmės yra 5 iki 15 mm pločio ir gali susilieti į dideles negyvas plotus. Ant uogų atsiranda tamsių įdubusių dėmių, ir jos nunoksta per anksti.",
      "tellApart": "Rudosios akutės dėmėtligės žiedai sausi, rudi, su šviesiai pilku centru ir be oranžinių miltelių, o rūdys apačioje turi oranžinių miltelių.",
      "actions": [
        "Gerai tręškite medžius, ypač azotu ir kaliu. Gera mityba dažnai suvaldo šią ligą.",
        "Palikite lengvą pavėsį, naikinkite piktžoles ir genėkite, kad oras judėtų ir lapai išdžiūtų.",
        "Po genėjimo išneškite arba sudeginkite lapus ir uogas. Nekraukite jų prie medžių.",
        "Daigyne sodinkite daigus atokiau vienas nuo kito ir sudeginkite daigus su žieduotomis rudomis dėmėmis.",
        "Jei liga stipri, vario fungicidas gali apsaugoti sveikus lapus. Pirmiausia paklauskite savo žemės ūkio konsultanto."
      ],
      "urgencyReason": "Ji daugiausia silpnina pavargusius medžius ir paprastai sumažėja, kai sutvarkoma mityba ir pavėsis."
    },
    "healthy": {
      "name": "Sveikas kavos lapas",
      "look": "Sveikas lapas blizgus, ovalus ir smailus, tolygiai tamsiai žalias, be dėmių, miltelių, skylių ar takelių viršuje ir apačioje.",
      "actions": [
        "Genėkite medžius, palikite lengvą pavėsį ir naikinkite piktžoles, kad lapai greitai išdžiūtų.",
        "Tręškite medžius mėšlu arba subalansuotomis trąšomis, ypač azotu ir kaliu.",
        "Kas savaitę ar dvi apžiūrėkite lapus ir jų apačią, kad anksti pastebėtumėte rūdis ar minuotoją."
      ]
    },
    "miner": {
      "name": "Kavos lapų minuotojas",
      "look": "Lapo viduje atsiranda šviesiai geltoni vingiuoti takeliai, kurie viršuje virsta netaisyklingomis rudomis negyvomis dėmėmis. Sulenkus lapą, plona viršutinė oda virš dėmės atsiskiria, ir viduje galima rasti mažytę permatomą lervą. Stiprus užpuolimas sukelia lapų kritimą.",
      "tellApart": "Minuotojo dėmės yra popieriaus plonumo pūslės su lerva viduje, kurios sulenkus atsiskiria, o rudoji akutė dėmėtligė yra tvarkingas apvalus žiedas, kuris neatsiskiria.",
      "actions": [
        "Sulenkite rudas dėmes ir ieškokite gyvų lervų, ypač sausuoju metu.",
        "Saugokite natūralius priešus, tokius kaip smulkios širšelės ir skruzdėlės: palikite mišrų pavėsį ir nepurkškite be reikalo.",
        "Atidžiai stebėkite jaunus medžius ir daigyną ir anksti pašalinkite pirmąsias dėmes.",
        "Jei reikia insekticido, paklauskite savo žemės ūkio konsultanto, kuris produktas jūsų šalyje yra teisėtas ir saugus."
      ],
      "urgencyReason": "Stiprus užpuolimas sukelia lapų kritimą ir mažina derlių, blogiausiai karštu ir sausu oru."
    },
    "phoma": {
      "name": "Fomos lapų dėmėtligė",
      "look": "Tamsiai rudos iki juodos dėmės, iki 2 cm pločio, ant senesnių lapų, su šviesesniu centru ir tamsesniu kraštu. Jaunų ūglių galiukai pajuosta ir išdžiūsta, žiedai gali žūti, o uogos nukrenta. Pažeidimas gali prasidėti nuo lapo galiuko ar krašto.",
      "tellApart": "Foma šaltose ir vėjuotose aukštumose žudo ir jaunų ūglių galiukus bei žiedus, o rudoji akutė dėmėtligė lieka žieduotomis dėmėmis ir neišdžiovina ūglių galiukų.",
      "actions": [
        "Vėjuotose vietose sodinkite vėjosaugas. Vėjo padaryti pažeidimai praleidžia grybą.",
        "Nugenėkite ir sunaikinkite išdžiūvusius ūglius ir mumifikuotas uogas, o genėkite taip, kad oras išdžiovintų lapus.",
        "Tręškite medžius subalansuotomis trąšomis, ypač azotu ir kaliu.",
        "Šaltais vėjuotais sezonais purkškite vario fungicidu, kol liga dar nepasirodė. Dėl laiko paklauskite savo žemės ūkio konsultanto."
      ],
      "urgencyReason": "Šaltose vėjuotose aukštumose ji gali nužudyti ūglius ir žiedus ir sumažinti derlių 15 iki 43 procentų."
    },
    "rust": {
      "name": "Kavos lapų rūdys",
      "look": "Lapo viršuje matyti mažos šviesiai geltonos dėmės. Apačioje kiekviena dėmė turi geltonų iki tamsiai oranžinių miltelių sluoksnį, kuris nusitrina ant piršto. Senos dėmės viduryje parudonuoja, ir lapai anksti krenta. Paprastai ji prasideda nuo apatinių medžio lapų.",
      "tellApart": "Rūdys lapo apačioje turi oranžinių miltelių, o rudoji akutė dėmėtligė turi sausus rudus žiedus su pilkšvai baltu centru ir be miltelių.",
      "actions": [
        "Dažnai apžiūrėkite apatinių lapų apačią. Svarbiausia pastebėti anksti.",
        "Nuskinkite ir sudeginkite arba užkaskite lapus ir šakas su oranžinėmis dėmėmis.",
        "Genėkite ir retinkite pavėsį bei piktžoles, kad oras judėtų ir lapai greičiau išdžiūtų.",
        "Tręškite medžius mėšlu arba subalansuotomis trąšomis. Silpni medžiai nukenčia labiau.",
        "Purkškite lapų viršų ir apačią vario fungicidu, pavyzdžiui, vario hidroksidu, kol serga mažiau nei apie 5 procentai lapų. Varis apsaugo sveikus lapus, bet neišgydo sergančių. Dėl laiko paklauskite savo žemės ūkio konsultanto.",
        "Naujiems sodinimams paklauskite savo žemės ūkio konsultanto apie rūdims atsparias veisles, tokias kaip Catimor arba Sarchimor tipo."
      ],
      "urgencyReason": "Ji greitai plinta tarp medžių ir ūkių, o jautrioms veislėms nuostoliai gali siekti 30 iki 80 procentų."
    },
    "mites": {
      "name": "Galimas erkučių pažeidimas",
      "look": "Vaizdas panašus į kavos lapus, pažymėtus kaip pažeistus erkučių. Panašius požymius gali sukelti ir kitos priežastys, todėl tai tik galimas sutapimas.",
      "actions": [
        "Prieš renkantis gydymą, paprašykite žemės ūkio konsultanto apžiūrėti abi lapo puses ir patvirtinti priežastį."
      ]
    },
    "weevil": {
      "name": "Galimas lapus graužiančių kenkėjų pažeidimas",
      "look": "Lapas panašus į vaizdus, pažymėtus kaip koko ar straubliukų pažeidimas. Pagal šią nuotrauką vabzdžio rūšies nustatyti negalima.",
      "actions": [
        "Prieš renkantis gydymą, paprašykite žemės ūkio konsultanto apžiūrėti pažeistą lapą ir ant augalo esančius vabzdžius."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Raskite KEPHIS lipduką ant sėklų pakuotės.",
    "stepScratch": "Nusibraukite lipduką, kad pasimatytų kodas.",
    "stepText": "Išsiųskite kodą žinute numeriu {shortCode}. Tai nemokama.",
    "result": "KEPHIS atsako, ar sėklos tikros. Tikras kodas neįrodo, kad sėklos buvo gerai laikomos.",
    "coverage": "Tai tinka sertifikuotoms sėkloms, parduodamoms pakuotėse. Daigyno daigai paprastai lipduko neturi, todėl apie juos paklauskite savo lauko konsultanto.",
    "noContact": "Paklauskite savo lauko konsultanto, kaip patikrinti, ar sėklų pakuotė tikra."
  },
  "phoneGreeting": "Laba diena, čia Leaf Doctor. Padedu su sergančiais kavos augalais, ir galite kalbėti su manimi savo kalba. Ką matote ant savo kavos lapų?"
});

export default ltText;
