// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const lvText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Jūsu lapas izskatās veselas",
    "headlineSpray": "{name}: aizsargājiet veselās lapas un sakopiet",
    "headlinePrune": "{name}: sakopiet un apgrieziet",
    "headlineMonitor": "{name}: turpiniet vērot",
    "headlineAskOfficer": "{name}: palūdziet lauka konsultantam to apskatīt",
    "headlineNotSure": "Lietotne nav pārliecināta. Parādiet šīs lapas savam lauka konsultantam",
    "headlineMightBe": "Tā varētu būt: {name}, bet tas nav apstiprināts. Parādiet lauka konsultantam",
    "headlineRetake": "Uzņemiet skaidrākus foto ar vairāk lapām",
    "retakeDaylight": "Pārejiet dienasgaismā, ne dziļā ēnā un ne tiešā saulē.",
    "retakeSteady": "Turiet tālruni mierīgi, līdz lapa izskatās asa.",
    "retakeFillFrame": "Piepildiet kadru ar vienu lapu.",
    "sendToOfficer": "Nosūtiet šo gadījumu sava kooperatīva lauka konsultantam ar SMS vai parādiet lapas klātienē.",
    "rainReason": "Jūsu tuvumā pēdējās 7 dienās lietus bija {n} dienās ({source}). Mitrs laiks liek rūsai izplatīties ātrāk.",
    "labelRate": "Izmantojiet devu, kas norādīta uz produkta etiķetes.",
    "elseBerryDisease": "Kafijas ogu slimība: paskatieties, vai ogām nav tumšu iedobtu plankumu.",
    "elseBerryBorer": "Kafijas ogu urbējvabole: meklējiet sīkus caurumiņus ogās.",
    "elseWilt": "Kafijas vīšana: vīst un atmirst veseli zari.",
    "elseNutrition": "Slikta augsne vai barības trūkums: dzeltē viss koks.",
    "smsDecisionSpray": "Lēmums: aizsargāt veselās lapas ar varu atbilstoši etiķetes devai un sakopt. Pārbaudiet vēlreiz pēc {days} dienām.",
    "smsDecisionPrune": "Lēmums: apgriezt un sakopt. Pārbaudiet vēlreiz pēc {days} dienām.",
    "smsDecisionMonitor": "Lēmums: turpināt vērot. Pārbaudiet vēlreiz pēc {days} dienām.",
    "smsDecisionCallOfficer": "Lēmums: parādīt lauka konsultantam."
  },
  "diseases": {
    "cercospora": {
      "name": "Brūnā acveida plankumainība",
      "look": "Apaļi brūni plankumi, galvenokārt lapas augšpusē, ar pelēkbaltu vidu un tumšbrūnu apmali, bieži ar dzeltenu oreolu. Plankumi ir 5 līdz 15 mm plati un var saplūst lielos atmirušos laukumos. Ogām parādās tumši iedobti plankumi, un tās nogatavojas par agru.",
      "tellApart": "Brūnajai acveida plankumainībai ir sausi brūni gredzeni ar gaiši pelēku vidu un nav oranža pulvera, bet rūsai apakšpusē ir oranžs pulveris.",
      "actions": [
        "Labi barojiet kokus, īpaši ar slāpekli un kāliju. Laba barošana bieži apvalda šo slimību.",
        "Uzturiet vieglu ēnu, apkarojiet nezāles un apgrieziet kokus tā, lai gaiss cirkulē un lapas izžūst.",
        "Pēc apgriešanas aiznesiet prom vai sadedziniet lapas un ogas. Nekrāmējiet tās pie kokiem.",
        "Stādaudzētavā stādiet stādus ar atstarpēm un sadedziniet stādus ar gredzenveida brūniem plankumiem.",
        "Ja slimība ir smaga, vara fungicīds var aizsargāt veselās lapas. Vispirms pajautājiet savam lauksaimniecības konsultantam."
      ],
      "urgencyReason": "Tā galvenokārt novājina nospiestus kokus un parasti mazinās, kad tiek sakārtota barošana un ēna."
    },
    "healthy": {
      "name": "Vesela kafijas lapa",
      "look": "Veselai lapai ir spīdīga, ovāla un ass gala forma, vienmērīgi tumšzaļa krāsa, bez plankumiem, pulvera, caurumiem vai ejām augšpusē un apakšpusē.",
      "actions": [
        "Apgrieziet kokus, uzturiet vieglu ēnu un ierobežojiet nezāles, lai lapas ātri izžūtu.",
        "Barojiet kokus ar kūtsmēsliem vai sabalansētu mēslojumu, īpaši ar slāpekli un kāliju.",
        "Pārbaudiet lapas un to apakšpuses reizi vai divās nedēļās, lai agri pamanītu rūsu vai lapu mīnētāju."
      ]
    },
    "miner": {
      "name": "Kafijas lapu mīnētājs",
      "look": "Lapas iekšpusē parādās gaiši dzeltenas līkumotas ejas, kas augšpusē pārvēršas nevienmērīgos brūnos atmirušos plankumos. Ja lapu saliec, plānā augšējā āda virs plankuma atdalās, un iekšpusē var atrast sīku caurspīdīgu kāpuru. Spēcīgs uzbrukums liek lapām nobirt.",
      "tellApart": "Mīnētāja plankumi ir papīra plānumā pūslīši ar kāpuru iekšā, kas saliecot atdalās, bet brūnā acveida plankumainība ir kārtīgs apaļš gredzens, kas neatdalās.",
      "actions": [
        "Saliecot brūnos plankumus, meklējiet dzīvus kāpurus, īpaši sausajā sezonā.",
        "Sargājiet dabiskos ienaidniekus, piemēram, sīkās lapsenes un skudras: uzturiet jauktu ēnu un nesmidziniet bez vajadzības.",
        "Cieši vērojiet jaunos kokus un stādaudzētavu un agri noņemiet pirmos plankumus.",
        "Ja nepieciešams insekticīds, pajautājiet savam lauksaimniecības konsultantam, kurš produkts jūsu valstī ir atļauts un drošs."
      ],
      "urgencyReason": "Spēcīgs uzbrukums izraisa lapu nobiršanu un samazina ražu, visļaunāk karstos, sausos periodos."
    },
    "phoma": {
      "name": "Fomas lapu plankumainība",
      "look": "Tumši brūni līdz melni plankumi līdz 2 cm platumā uz vecākām lapām, ar gaišāku vidu un tumšāku malu. Jauno dzinumu gali kļūst melni un izžūst, ziedi var atmirt, un ogas nobirst. Bojājums var sākties lapas galā vai malā.",
      "tellApart": "Foma aukstos, vējainos augstkalnu apvidos nogalina arī jauno dzinumu galus un ziedus, bet brūnā acveida plankumainība paliek gredzenveida plankumos un neizžāvē dzinumu galus.",
      "actions": [
        "Vējainās vietās stādiet vēja aizsargjoslas. Vēja bojājumi ļauj sēnītei iekļūt.",
        "Nogrieziet un iznīciniet izkaltušos dzinumus un mumificējušās ogas un apgrieziet kokus tā, lai gaiss varētu izžāvēt lapas.",
        "Barojiet kokus ar sabalansētu mēslojumu, īpaši ar slāpekli un kāliju.",
        "Aukstās, vējainās sezonās apsmidziniet ar vara fungicīdu, pirms slimība parādās. Pajautājiet savam lauksaimniecības konsultantam par laiku."
      ],
      "urgencyReason": "Aukstos, vējainos augstkalnu apvidos tā var nogalināt dzinumus un ziedus un samazināt ražu par 15 līdz 43 procentiem."
    },
    "rust": {
      "name": "Kafijas lapu rūsa",
      "look": "Lapas augšpusē parādās sīki gaiši dzelteni plankumi. Apakšpusē katram plankumam ir dzeltena līdz tumši oranža pulvera kārta, kas paliek uz pirksta. Vecie plankumi vidū kļūst brūni, un lapas nobirst par agru. Parasti tā sākas koka apakšējās lapās.",
      "tellApart": "Rūsai lapas apakšpusē ir oranžs pulveris, bet brūnajai acveida plankumainībai ir sausi brūni gredzeni ar pelēkbaltu vidu un nav pulvera.",
      "actions": [
        "Bieži pārbaudiet apakšējo lapu apakšpusi. Vissvarīgākais ir pamanīt to agri.",
        "Noplūciet un sadedziniet vai aprociet lapas un zarus ar oranžiem plankumiem.",
        "Apgrieziet un izretiniet ēnu un nezāles, lai gaiss cirkulē un lapas izžūst ātrāk.",
        "Barojiet kokus ar kūtsmēsliem vai sabalansētu mēslojumu. Vāji koki cieš vairāk.",
        "Apsmidziniet lapu augšpusi un apakšpusi ar vara fungicīdu, piemēram, vara hidroksīdu, kamēr slimas ir mazāk nekā aptuveni 5 procenti lapu. Varš aizsargā veselās lapas, bet neizārstē slimās. Pajautājiet savam lauksaimniecības konsultantam par laiku.",
        "Jauniem stādījumiem pajautājiet savam lauksaimniecības konsultantam par rūsai izturīgām šķirnēm, piemēram, Catimor vai Sarchimor tipa šķirnēm."
      ],
      "urgencyReason": "Tā ātri izplatās starp kokiem un saimniecībām, un uzņēmīgām šķirnēm zaudējumi var sasniegt 30 līdz 80 procentus."
    },
    "mites": {
      "name": "Iespējams ērcīšu bojājums",
      "look": "Attēls atgādina kafijas lapas, kas atzīmētas kā ērcīšu bojātas. Līdzīgas pazīmes var radīt arī citi cēloņi, tāpēc tā ir iespējama atbilstība.",
      "actions": [
        "Pirms izvēlaties ārstēšanu, palūdziet lauksaimniecības konsultantam apskatīt abas lapas puses un apstiprināt cēloni."
      ]
    },
    "weevil": {
      "name": "Iespējams lapas grauzēju kaitēkļu bojājums",
      "look": "Lapa atgādina attēlus, kas atzīmēti kā koko vai smecernieku bojājums. Pēc šī foto nevar noteikt kukaiņa sugu.",
      "actions": [
        "Pirms izvēlaties ārstēšanu, palūdziet lauksaimniecības konsultantam apskatīt bojāto lapu un kukaiņus uz auga."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Atrodiet KEPHIS uzlīmi uz sēklu iepakojuma.",
    "stepScratch": "Nokasiet uzlīmi, lai parādītos kods.",
    "stepText": "Nosūtiet kodu īsziņā uz {shortCode}. Tas ir bez maksas.",
    "result": "KEPHIS atbild, vai sēklas ir īstas. Īsts kods neapliecina, ka sēklas ir labi uzglabātas.",
    "coverage": "Tas darbojas sertificētām sēklām, ko pārdod iepakojumos. Stādaudzētavas stādiem parasti nav uzlīmes, tāpēc pajautājiet par tiem savam lauka konsultantam.",
    "noContact": "Pajautājiet savam lauka konsultantam, kā pārbaudīt, vai sēklu iepakojums ir īsts."
  },
  "phoneGreeting": "Labdien, šeit Leaf Doctor. Es palīdzu ar slimiem kafijas augiem, un jūs varat runāt ar mani savā valodā. Ko jūs redzat uz savām kafijas lapām?"
});

export default lvText;
