// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const mgText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Toa salama ny ravinao",
    "headlineSpray": "{name}: arovy ny ravina salama ary diovy",
    "headlinePrune": "{name}: diovy ary tapaho ny sampana",
    "headlineMonitor": "{name}: tohizo ny fanaraha-maso",
    "headlineAskOfficer": "{name}: angataho ny mpanolotsaina eny an-tsaha hijery",
    "headlineNotSure": "Tsy azo antoka ny rindranasa. Asehoy ny mpanolotsaina eny an-tsaha ireto ravina ireto",
    "headlineMightBe": "Mety ho {name} izany, saingy tsy voamarina. Asehoy mpanolotsaina eny an-tsaha",
    "headlineRetake": "Alaivo sary mazava kokoa ny ravina maro kokoa",
    "retakeDaylight": "Mankanesa amin'ny mazava andro, fa tsy ao anaty aloka matevina na amin'ny masoandro mivantana.",
    "retakeSteady": "Tazomy tsy hihetsiketsika ny finday mandra-pahitan'ny ravina mazava.",
    "retakeFillFrame": "Ameno ny efijery amin'ny ravina iray.",
    "sendToOfficer": "Alefaso amin'ny SMS any amin'ny mpanolotsaina eny an-tsaha ao amin'ny kooperativa ity raharaha ity, na asehoy mivantana ny ravina.",
    "rainReason": "Nilatsaka ny orana tamin'ny andro {n} tamin'ireo andro 7 farany teo akaikinao ({source}). Ny toetrandro mando dia mahatonga ny harafesina hiparitaka haingana kokoa.",
    "labelRate": "Ampiasao ny fatra voasoratra eo amin'ny etikety.",
    "elseBerryDisease": "Aretin'ny voan-kafe: jereo raha misy tasy maizina lalina eo amin'ny voa.",
    "elseBerryBorer": "Bibikely mandavaka voan-kafe: jereo raha misy lavaka kely eo amin'ny voa.",
    "elseWilt": "Fahalazan'ny kafe: ny sampana manontolo malazo ary maty.",
    "elseNutrition": "Tany ratsy na tsy ampy sakafo: mivadika mavo ny hazo manontolo.",
    "smsDecisionSpray": "Fanapahan-kevitra: arovy ny ravina salama amin'ny varahina araka ny fatra eo amin'ny etikety ary diovy. Jereo indray afaka andro {days}.",
    "smsDecisionPrune": "Fanapahan-kevitra: tapaho ny sampana ary diovy. Jereo indray afaka andro {days}.",
    "smsDecisionMonitor": "Fanapahan-kevitra: tohizo ny fanaraha-maso. Jereo indray afaka andro {days}.",
    "smsDecisionCallOfficer": "Fanapahan-kevitra: asehoy ny mpanolotsaina eny an-tsahanao."
  },
  "diseases": {
    "cercospora": {
      "name": "Tasy volontany misy maso",
      "look": "Tasy boribory volontany, indrindra eo an-tampon'ny ravina, misy afovoany fotsy-hatsatra sy peratra volontany maizina, matetika misy fototra mavo manodidina. Ny tasy dia 5 ka hatramin'ny 15 mm ny sakany ary mety hiray ho sombin-paty lehibe. Ny voa dia misy tasy maizina lalina ary masaka aloha loatra.",
      "tellApart": "Ny tasy volontany misy maso dia misy peratra volontany maina sy afovoany hatsatra ary tsy misy vovoka voasary, fa ny harafesina kosa misy vovoka voasary eo ambanin'ny ravina.",
      "actions": [
        "Omeo sakafo tsara ny hazo, indrindra ny azota sy ny potasioma. Matetika ny fanomezana sakafo tsara no mamaha ity aretina ity.",
        "Tazomy ny aloka maivana, fehezo ny ahitra ary tapaho ny sampana mba hiditra ny rivotra ary hamaina ny ravina.",
        "Aorian'ny fanapahana, ento lavitra na may ny ravina sy ny voa. Aza atao antsinjarany eo akaikin'ny hazo.",
        "Ao amin'ny toeram-pamokarana zana-kafe, asio elanelana ny zana-kafe ary may ireo zana-kafe misy tasy volontany misy peratra.",
        "Raha mafy, ny fungicide varahina dia afaka miaro ny ravina salama. Anontanio aloha ny mpanolotsaina ara-pambolena."
      ],
      "urgencyReason": "Mampahalemy indrindra ny hazo sahirana izy ary matetika mihatsara rehefa voavaha ny sakafo sy ny aloka."
    },
    "healthy": {
      "name": "Ravin-kafe salama",
      "look": "Ny ravina salama dia manjelanjelatra, oval sy maranitra, maitso matroka mitovy, tsy misy tasy, vovoka, lavaka na tonelina eo an-tampony na eo ambaniny.",
      "actions": [
        "Tapaho ny sampana ary tazomy ny aloka maivana sy ny ahitra ambany mba hamaina haingana ny ravina.",
        "Omeo zezika biby na zezika voalanjalanja ny hazo, indrindra ny azota sy ny potasioma.",
        "Jereo isan-kerinandro na isaky ny roa herinandro ny ravina sy ny ambaniny mba hahitana aloha ny harafesina na ny bibikely mandavaka ravina."
      ]
    },
    "miner": {
      "name": "Bibikely mandavaka ravin-kafe",
      "look": "Làlana mivalampatra mavo maivana miseho ao anaty ravina ary lasa tasy maty volontany tsy mitovy eo an-tampony. Raha mamihina ny ravina ianao, ny hodi-manify eo ambonin'ny tasy dia misaraka ary mahita olitra kely mangarahara ao anatiny ianao. Ny fanafihana mafy dia mahatonga ny ravina ho latsaka.",
      "tellApart": "Ny tasy avy amin'ny bibikely dia vongan-taratasy misy olitra ao anatiny ary misaraka rehefa mamihina, fa ny tasy volontany misy maso dia peratra boribory madio tsy misaraka.",
      "actions": [
        "Mamihina ny tasy volontany mba hitady olitra velona, indrindra amin'ny vanim-potoana maina.",
        "Arovy ny fahavalo voajanahary toy ny ankamantatra kely sy ny vitsika amin'ny fitazonana aloka mifangaro sy fisorohana ny fanafazana tsy ilaina.",
        "Araho akaiky ny hazo tanora sy ny toeram-pamokarana zana-kafe ary esory aloha ny tasy voalohany.",
        "Raha ilaina ny fanafody famonoana bibikely, anontanio ny mpanolotsaina ara-pambolena hoe iza no ara-dalàna sy azo antoka any amin'ny fireneranao."
      ],
      "urgencyReason": "Ny fanafihana mafy dia mahatonga ravina latsaka sy fihenan'ny vokatra, indrindra amin'ny vanim-potoana mafana sy maina."
    },
    "phoma": {
      "name": "Tasy ravina Phoma",
      "look": "Tasy volontany maizina hatramin'ny mainty, hatramin'ny 2 cm ny sakany eo amin'ny ravina antitra, misy afovoany mazava kokoa sy sisiny maizina kokoa. Ny tendron'ny rantsana tanora dia mainty ary maina, mety maty ny voninkazo ary latsaka ny voa. Mety hanomboka eo amin'ny tendron'ny ravina na ny sisiny ny fahasimbana.",
      "tellApart": "Ny Phoma koa dia mamono ny tendron'ny rantsana tanora sy ny voninkazo any amin'ny tany avo mangatsiaka sy mafy rivotra, fa ny tasy volontany misy maso dia mijanona ho tasy misy peratra ary tsy mahamaina ny tendron'ny rantsana.",
      "actions": [
        "Mamboly hazo manakana ny rivotra any amin'ny faritra mafy rivotra. Ny fahasimban'ny rivotra no ahafahan'ny holatra miditra.",
        "Tapaho sy fofohy ny rantsana maina sy ny voa norotsorana, ary tapaho ny sampana mba hahafahan'ny rivotra mamaha ny ravina.",
        "Omeo zezika voalanjalanja ny hazo, indrindra ny azota sy ny potasioma.",
        "Amin'ny vanim-potoana mangatsiaka sy mafy rivotra, fafazo fungicide varahina alohan'ny hisehoan'ny aretina. Anontanio ny mpanolotsaina ara-pambolena ny fotoana."
      ],
      "urgencyReason": "Any amin'ny tany avo mangatsiaka sy mafy rivotra dia mety hamono ny rantsana sy ny voninkazo ary hampihena ny vokatra 15 ka hatramin'ny 43 isan-jato."
    },
    "rust": {
      "name": "Harafesin'ny ravin-kafe",
      "look": "Tasy mavo maivana kely miseho eo an-tampon'ny ravina. Eo ambany, ny tasy tsirairay dia misy vovoka mavo ka hatramin'ny voasary matroka izay mifafy eo amin'ny rantsan-tananao. Ny tasy tranainy dia lasa volontany eo afovoany ary latsaka aloha ny ravina. Matetika manomboka amin'ny ravina ambany amin'ny hazo izy.",
      "tellApart": "Ny harafesina dia misy vovoka voasary eo ambanin'ny ravina, fa ny tasy volontany misy maso kosa misy peratra volontany maina sy afovoany fotsy-hatsatra ary tsy misy vovoka.",
      "actions": [
        "Jereo matetika ny ambanin'ny ravina ambany. Ny fahitana aloha no zava-dehibe indrindra.",
        "Fantsiho ary may na alevina ny ravina sy ny rantsana misy tasy voasary.",
        "Tapaho ary ahenao ny aloka sy ny ahitra mba hiditra ny rivotra ary hamaina haingana ny ravina.",
        "Omeo zezika biby na zezika voalanjalanja ny hazo. Ny hazo malemy no tototry ny aretina mafy kokoa.",
        "Fafazo fungicide varahina toy ny copper hydroxide eo an-tampony sy eo ambanin'ny ravina raha mbola latsaky ny 5 isan-jato eo ho eo ny ravina marary. Miaro ny ravina salama ny varahina fa tsy manasitrana ny marary. Anontanio ny mpanolotsaina ara-pambolena ny fotoana.",
        "Raha hamboly vaovao, anontanio ny mpanolotsaina ara-pambolena ny karazana manohitra ny harafesina toy ny karazana Catimor na Sarchimor."
      ],
      "urgencyReason": "Miparitaka haingana eo amin'ny hazo sy ny toeram-pambolena izy, ary ny fahavoazana amin'ny karazana mora tohina dia mety hahatratra 30 ka hatramin'ny 80 isan-jato."
    },
    "mites": {
      "name": "Mety ho simban'ny mite",
      "look": "Mitovy amin'ny ravin-kafe voasoratra ho simban'ny mite ny sary. Mety hisy antony hafa ny marika mitovy, ka mety ho mitovy fotsiny ity.",
      "actions": [
        "Angataho ny mpanolotsaina ara-pambolena hijery ny lafiny roa amin'ny ravina ary hanamarina ny anton'izany alohan'ny hisafidianao fitsaboana."
      ]
    },
    "weevil": {
      "name": "Mety ho simban'ny bibikely mihinana ravina",
      "look": "Mitovy amin'ny sary voasoratra ho simban'ny bibikely mihinana ravina ny ravina. Tsy afaka mamantatra ny karazan'ny bibikely io sary io.",
      "actions": [
        "Angataho ny mpanolotsaina ara-pambolena hijery ny ravina simba sy ny bibikely rehetra eo amin'ny zavamaniry alohan'ny hisafidianao fitsaboana."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Mitadiava ny stikera KEPHIS eo amin'ny fonosan'ny voa.",
    "stepScratch": "Kosehy ny stikera mba hiseho ny kaody.",
    "stepText": "Alefaso any amin'ny {shortCode} ny kaody. Maimaim-poana izany.",
    "result": "Mamaly ny KEPHIS hilaza raha tena izy ny voa. Ny kaody tena izy dia tsy porofo fa voatahiry tsara ny voa.",
    "coverage": "Mihatra amin'ny voa voamarina amidy ao anaty fonosana izany. Matetika tsy misy stikera ny zana-kafe avy any amin'ny toeram-pamokarana, ka anontanio ny mpanolotsaina eny an-tsahanao.",
    "noContact": "Anontanio ny mpanolotsaina eny an-tsahanao ny fomba hijerena raha tena izy ny fonosan'ny voa."
  },
  "phoneGreeting": "Miarahaba, Leaf Doctor ity. Manampy amin'ny zavamaniry kafe marary aho, ary afaka miresaka amiko amin'ny tenin'ny tenanao ianao. Inona no hitanao eo amin'ny ravin-kafenao?"
});

export default mgText;
