// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const miText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "He hauora te āhua o ō rau",
    "headlineSpray": "{name}: tiakina ngā rau hauora, ka whakapaipai",
    "headlinePrune": "{name}: whakapaipai, ka tapahi",
    "headlineMonitor": "{name}: haere tonu te tirotiro",
    "headlineAskOfficer": "{name}: tonoa tō āpiha mara kia tirotiro",
    "headlineNotSure": "Kāore te taupānga i te tino mōhio. Whakaatuhia ēnei rau ki tō āpiha mara",
    "headlineMightBe": "Tērā pea ko {name}, engari kāore anō kia whakapūmautia. Whakaatuhia ki tētahi āpiha mara",
    "headlineRetake": "Tangohia he whakaahua mārama ake o ētahi atu rau",
    "retakeDaylight": "Neke ki te marama o te rā, kaua ki te taumarumaru hōhonu, ki te rā tika rānei.",
    "retakeSteady": "Puritia te waea kia noho tonu kia mārama ai te rau.",
    "retakeFillFrame": "Whakakīia te anga ki te rau kotahi.",
    "sendToOfficer": "Tukuna tēnei take ki te āpiha mara o tō kōtui mā te SMS, whakaatu rānei i ngā rau ā-tinana.",
    "rainReason": "I ua i te {n} o ngā rā 7 kua pahure ki tō takiwā ({source}). Ko te huarere makuku te take e tere ai te marara o te waikura.",
    "labelRate": "Whakamahia te rahinga i runga i te tohu o te hua.",
    "elseBerryDisease": "Te mate hua kawhe: tirohia ngā hua mō ngā tohu pango hohonu.",
    "elseBerryBorer": "Te ngārara kai hua kawhe: rapua he rua iti i ngā hua.",
    "elseWilt": "Te pāwhara kawhe: ka pāwhara, ka mate ngā manga katoa.",
    "elseNutrition": "Te oneone kino, te koretake o ngā matūkai rānei: te kōwhai puta noa i te rākau katoa.",
    "smsDecisionSpray": "Whakatau: tiakina ngā rau hauora ki te kapa i te rahinga o te tohu, ka whakapaipai. Tirohia anō i roto i te {days} rā.",
    "smsDecisionPrune": "Whakatau: tapahia, ka whakapaipai. Tirohia anō i roto i te {days} rā.",
    "smsDecisionMonitor": "Whakatau: haere tonu te tirotiro. Tirohia anō i roto i te {days} rā.",
    "smsDecisionCallOfficer": "Whakatau: whakaatuhia ki tō āpiha mara."
  },
  "diseases": {
    "cercospora": {
      "name": "Te tohu karu parauri",
      "look": "He tohu parauri porowhita, te nuinga kei runga i te rau, he waenganui hina-mā me te mowhiti parauri pōuri, he mowhiti kōwhai ōna i te nuinga o te wā. He 5 ki te 15 mm te whānui o ngā tohu, ka whakakotahi hei wāhi mate nui. Ka pā ngā hua ki ngā tohu pōuri hohonu, ka maoa wawe.",
      "tellApart": "Ko te tohu karu parauri he mowhiti parauri maroke me te waenganui hina kōmā, kāore he paura karaka, engari ko te waikura he paura karaka kei raro.",
      "actions": [
        "Whangaia pai ngā rākau, otirā ki te hauota me te pōtaha. Ka whakahaerehia e te whangai pai tēnei mate i te nuinga o te wā.",
        "Puritia he taumarumaru māmā, whakahaerehia ngā taru, ka tapahi kia rere te hau, kia maroke ai ngā rau.",
        "Whai muri i te tapahi, kawea atu, tahuna rānei ngā rau me ngā hua. Kaua e whakatōpū ki te taha o ngā rākau.",
        "I te whakatipu-tupu, wehea ngā tupu kia tawhiti, ka tahuna ngā tupu he tohu parauri mowhiti ōna.",
        "Mēnā he kino, ka taea e te patu harore kapa te tiaki i ngā rau hauora. Pātai tuatahi ki tō āpiha whakawhiti mātauranga."
      ],
      "urgencyReason": "Ko te nuinga ka whakangoikore i ngā rākau e pēhia ana, ā, ka pai ake i te wā ka whakatikahia te whangai me te taumarumaru."
    },
    "healthy": {
      "name": "He rau kawhe hauora",
      "look": "He kerekere, he hangarite, he koi te rau hauora, he kākāriki pōuri rite, kāore he tohu, he paura, he rua, he kauhanga rānei i runga, i raro rānei.",
      "actions": [
        "Tapahia, ā, puritia he taumarumaru māmā me te whakahaere i ngā taru kia tere te maroke o ngā rau.",
        "Whangaia ngā rākau ki te tāhuna, ki te wairākau taurite rānei, otirā ki te hauota me te pōtaha.",
        "Tirohia ngā rau me ō rātou taha o raro ia wiki, ia rua wiki rānei kia kitea wawe te waikura, te kai rau rānei."
      ]
    },
    "miner": {
      "name": "Te kai rau kawhe",
      "look": "Ka puta he ara kōwhai kōmā kōpikopiko ki roto i te rau, ka huri hei wāhi mate parauri ōrite kore ki runga. Mēnā ka whakapākia te rau, ka wetekina te kiri angiangi i runga i te wāhi, ā, ka kitea he ngārara iti kitea-mā ki roto. Ka pāngia nuitia, ka tō ngā rau.",
      "tellApart": "Ko ngā wāhi o te kai rau he pūkoro pepa me te ngārara ki roto, ka wete ina pākia, engari ko te tohu karu parauri he mowhiti porowhita tōtika kāore e wete.",
      "actions": [
        "Whakapākia ngā wāhi parauri kia kitea he ngārara ora, otirā i te wā maroke.",
        "Tiakina ngā hoariri māori pēnei i ngā tōpītipiti iti me ngā tōpīwai mā te pupuri i te taumarumaru tāwhaiwhai me te karo i te rehu kore take.",
        "Kia tūpato ki ngā rākau rangatahi me ngā whakatipu-tupu, tangohia wawe ngā wāhi tuatahi.",
        "Mēnā he rongoā ngārara e hiahiatia ana, pātai ki tō āpiha whakawhiti mātauranga mēnā ko tēhea hua e ture ana, e haumaru ana i tō whenua."
      ],
      "urgencyReason": "Ka pāngia nuitia ka tō ngā rau, ka heke te hua, ā, he kino rawa i ngā wā mahana maroke."
    },
    "phoma": {
      "name": "Te tohu rau Phoma",
      "look": "He tohu parauri pōuri ki te pango tae atu ki te 2 cm te whānui i runga i ngā rau tawhito, he waenganui māmā ake me te tapa pōuri ake. Ka pango, ka maroke ngā pito o ngā tupu hou, ka mate pea ngā puāwai, ā, ka tō ngā hua. Ka tīmata pea te pāmamae i te pito, i te tapa rānei o te rau.",
      "tellApart": "Ka whakamate hoki a Phoma i ngā pito o ngā tupu hou me ngā puāwai i ngā pae teitei makariri, hauhau, engari ko te tohu karu parauri he tohu mowhiti anake, kāore e whakamaroke i ngā pito tupu.",
      "actions": [
        "Whakatōngia he arai hau ki ngā wāhi hauhau. Ka tuwhera te harore ki roto i te pāmamae a te hau.",
        "Tapahia, ā, whakangaromia ngā tupu maroke me ngā hua kua maroke, ā, tapahia kia taea e te hau te whakamaroke i ngā rau.",
        "Whangaia ngā rākau ki te wairākau taurite, otirā ki te hauota me te pōtaha.",
        "I ngā wā makariri hauhau, ruia he patu harore kapa i mua i te puta o te mate. Pātai ki tō āpiha whakawhiti mātauranga mō te wā."
      ],
      "urgencyReason": "I ngā pae teitei makariri hauhau ka taea e ia te whakamate i ngā tupu me ngā puāwai, ā, ka whakaiti i te hua 15 ki te 43 ōrau."
    },
    "rust": {
      "name": "Te waikura rau kawhe",
      "look": "Ka kitea he tohu kōwhai kōmā iti i runga i te rau. I raro, he wāhi paura kōwhai ki te karaka pōuri kei ia tohu, ka heke ki tō matimati ina tāpirihia. Ka parauri te waenganui o ngā tohu tawhito, ā, ka tō wawe ngā rau. I te nuinga o te wā ka tīmata ki ngā rau o raro o te rākau.",
      "tellApart": "He paura karaka kei raro i te rau o te waikura, engari ko te tohu karu parauri he mowhiti parauri maroke me te waenganui hina-mā, kāore he paura.",
      "actions": [
        "Tirohia ngā taha o raro o ngā rau o raro i ngā wā katoa. Ko te kitenga wawe te mea nui rawa.",
        "Tīkina, tahuna, tanumia rānei ngā rau me ngā manga he tohu karaka.",
        "Tapahia, whakaitihia te taumarumaru me ngā taru kia rere te hau, kia tere te maroke o ngā rau.",
        "Whangaia ngā rākau ki te tāhuna, ki te wairākau taurite rānei. Ka kino ake te pā ki ngā rākau ngoikore.",
        "Ruia he patu harore kapa pēnei i te kapa hauwai ki runga me raro i ngā rau ina iti iho i te 5 ōrau o ngā rau e māuiui ana. Ka tiakina e te kapa ngā rau hauora, engari kāore e whakaora i ngā mea māuiui. Pātai ki tō āpiha whakawhiti mātauranga mō te wā.",
        "Mō te whakatō hōu, pātai ki tō āpiha whakawhiti mātauranga mō ngā momo atete ki te waikura pēnei i ngā momo Catimor, Sarchimor rānei."
      ],
      "urgencyReason": "Ka marara tere i waenga i ngā rākau me ngā pāmu, ā, ka taea e ngā ngaro i ngā momo ngoikore te eke ki te 30 ki te 80 ōrau."
    },
    "mites": {
      "name": "Pea he pāmamae mai i ngā mite",
      "look": "He rite te whakaahua ki ngā rau kawhe kua tapaina he pāmamae mite. Ka taea e ngā tohu rite te whai take kē, nō reira he ōrite pea tēnei.",
      "actions": [
        "Tonoa tētahi āpiha whakawhiti mātauranga kia tirotiro i ngā taha e rua o te rau, ā, kia whakapūmau i te take i mua i te kōwhiri rongoā."
      ]
    },
    "weevil": {
      "name": "Pea he pāmamae mai i te ngārara kai rau",
      "look": "He rite te rau ki ngā whakaahua kua tapaina he pāmamae kokonati, pūngārara rānei. Kāore e taea e tēnei whakaahua te tautuhi i te momo ngārara.",
      "actions": [
        "Tonoa tētahi āpiha whakawhiti mātauranga kia tirotiro i te rau kua pāmamae me ngā ngārara i runga i te tipu i mua i te kōwhiri rongoā."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Rapua te tīpoka KEPHIS i runga i te kōpaki purapura.",
    "stepScratch": "Waruhia te tīpoka kia kitea te waehere.",
    "stepText": "Tukuna te waehere ki {shortCode}. He koreutu.",
    "result": "Ka whakautu a KEPHIS ki te kī mēnā he pono te purapura. Ehara te waehere pono i te tohu he pai te rokiroki o te purapura.",
    "coverage": "Ka mahi tēnei mō ngā purapura kua whakamanatia e hokona ana ki ngā kōpaki. I te nuinga o te wā kāore he tīpoka i ngā tupu o te whakatipu-tupu, nō reira pātai ki tō āpiha mara mō ērā.",
    "noContact": "Pātai ki tō āpiha mara me pēhea te tirotiro mēnā he pono te kōpaki purapura."
  },
  "phoneGreeting": "Kia ora, ko Leaf Doctor tēnei. Ka āwhina au mō ngā tipu kawhe māuiui, ā, ka taea e koe te kōrero mai ki a au i tō ake reo. He aha tāu e kite ana i ō rau kawhe?"
});

export default miText;
