// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const msText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Daun anda kelihatan sihat",
    "headlineSpray": "{name}: lindungi daun yang sihat dan bersihkan",
    "headlinePrune": "{name}: bersihkan dan pangkas",
    "headlineMonitor": "{name}: terus perhatikan",
    "headlineAskOfficer": "{name}: minta pegawai lapangan anda memeriksa",
    "headlineNotSure": "Aplikasi tidak pasti. Tunjukkan daun-daun ini kepada pegawai lapangan anda",
    "headlineMightBe": "Mungkin {name}, tetapi belum disahkan. Tunjukkan kepada pegawai lapangan",
    "headlineRetake": "Ambil foto yang lebih jelas bagi lebih banyak daun",
    "retakeDaylight": "Pergi ke tempat bercahaya siang, bukan teduh gelap atau cahaya matahari terus.",
    "retakeSteady": "Pegang telefon dengan stabil sehingga daun kelihatan tajam.",
    "retakeFillFrame": "Penuhkan bingkai dengan satu daun.",
    "sendToOfficer": "Hantar kes ini kepada pegawai lapangan koperasi anda melalui SMS, atau tunjukkan daun itu secara terus.",
    "rainReason": "Hujan turun pada {n} daripada 7 hari lepas berhampiran anda ({source}). Cuaca basah menyebabkan karat merebak lebih cepat.",
    "labelRate": "Gunakan kadar pada label produk.",
    "elseBerryDisease": "Penyakit buah kopi: lihat buah untuk mencari tompok gelap yang cengkung.",
    "elseBerryBorer": "Pengorek buah kopi: cari lubang kecil pada buah.",
    "elseWilt": "Layu kopi: seluruh dahan layu dan mati.",
    "elseNutrition": "Tanah atau zat makanan yang kurang: kekuningan pada seluruh pokok.",
    "smsDecisionSpray": "Keputusan: lindungi daun yang sihat dengan kuprum pada kadar label dan bersihkan. Periksa semula dalam {days} hari.",
    "smsDecisionPrune": "Keputusan: pangkas dan bersihkan. Periksa semula dalam {days} hari.",
    "smsDecisionMonitor": "Keputusan: terus perhatikan. Periksa semula dalam {days} hari.",
    "smsDecisionCallOfficer": "Keputusan: tunjukkan kepada pegawai lapangan anda."
  },
  "diseases": {
    "cercospora": {
      "name": "Bintik mata coklat",
      "look": "Bintik coklat bulat, kebanyakannya di atas daun, dengan tengah kelabu keputihan dan cincin coklat tua, selalunya dengan lingkaran kuning. Bintik selebar 5 hingga 15 mm dan boleh bercantum menjadi tompok mati yang besar. Buah mendapat tompok gelap yang cengkung dan masak terlalu awal.",
      "tellApart": "Bintik mata coklat mempunyai cincin coklat kering dengan tengah kelabu pucat dan tiada serbuk jingga, manakala karat mempunyai serbuk jingga di bawah.",
      "actions": [
        "Bajai pokok dengan baik, terutamanya nitrogen dan kalium. Pembajaan yang baik selalunya mengawal penyakit ini.",
        "Kekalkan teduhan ringan, kawal rumpai, dan pangkas supaya udara bergerak dan daun cepat kering.",
        "Selepas memangkas, bawa pergi atau bakar daun dan buah. Jangan longgokkan di sebelah pokok.",
        "Di tapak semaian, jarakkan anak benih dan bakar anak benih yang mempunyai bintik coklat bercincin.",
        "Jika teruk, racun kulat kuprum boleh melindungi daun yang sihat. Tanya pegawai pengembangan anda dahulu."
      ],
      "urgencyReason": "Ia terutamanya melemahkan pokok yang tertekan dan biasanya bertambah baik apabila pembajaan dan teduhan dibetulkan."
    },
    "healthy": {
      "name": "Daun kopi yang sihat",
      "look": "Daun yang sihat berkilat, bujur dan runcing, hijau tua sekata, tanpa bintik, serbuk, lubang atau terowong di atas atau di bawah.",
      "actions": [
        "Pangkas dan kekalkan teduhan ringan serta rendahkan rumpai supaya daun cepat kering.",
        "Bajai pokok dengan baja kandang atau baja seimbang, terutamanya nitrogen dan kalium.",
        "Periksa daun dan bahagian bawahnya setiap seminggu atau dua minggu untuk mengesan karat atau pengorek daun lebih awal."
      ]
    },
    "miner": {
      "name": "Pengorek daun kopi",
      "look": "Alur kuning pucat yang berliku muncul di dalam daun dan bertukar menjadi tompok mati coklat yang tidak sekata di atas. Jika daun dilengkungkan, kulit nipis di atas tompok itu terkopek dan anda boleh menemui ulat kecil lut sinar di dalamnya. Serangan teruk menyebabkan daun gugur.",
      "tellApart": "Tompok pengorek ialah lepuh seperti kertas dengan ulat di dalam yang terkopek apabila dilengkungkan, manakala bintik mata coklat ialah cincin bulat kemas yang tidak terkopek.",
      "actions": [
        "Lengkungkan tompok coklat untuk mencari ulat yang hidup, terutamanya pada musim kemarau.",
        "Lindungi musuh semula jadi seperti tebuan kecil dan semut dengan mengekalkan teduhan campuran dan mengelak semburan yang tidak perlu.",
        "Perhatikan pokok muda dan tapak semaian dengan teliti dan buang tompok pertama lebih awal.",
        "Jika racun serangga diperlukan, tanya pegawai pengembangan anda produk mana yang sah dan selamat di negara anda."
      ],
      "urgencyReason": "Serangan teruk menyebabkan daun gugur dan hasil berkurang, paling teruk semasa cuaca kering dan panas."
    },
    "phoma": {
      "name": "Bintik daun Phoma",
      "look": "Bintik coklat tua hingga hitam selebar sehingga 2 cm pada daun yang lebih tua, dengan tengah yang lebih cerah dan tepi yang lebih gelap. Hujung pucuk muda menjadi hitam dan kering, bunga boleh mati, dan buah gugur. Kerosakan boleh bermula di hujung atau tepi daun.",
      "tellApart": "Phoma juga membunuh hujung pucuk muda dan bunga di tanah tinggi yang sejuk dan berangin, manakala bintik mata coklat kekal sebagai bintik bercincin dan tidak mengeringkan hujung pucuk.",
      "actions": [
        "Tanam penghadang angin di kawasan berangin. Kerosakan akibat angin membolehkan kulat masuk.",
        "Pangkas dan musnahkan pucuk kering dan buah yang menjadi mumia, dan pangkas supaya udara dapat mengeringkan daun.",
        "Bajai pokok dengan baja seimbang, terutamanya nitrogen dan kalium.",
        "Pada musim sejuk berangin, semburkan racun kulat kuprum sebelum penyakit muncul. Tanya pegawai pengembangan anda tentang waktunya."
      ],
      "urgencyReason": "Di tanah tinggi yang sejuk dan berangin, ia boleh membunuh pucuk dan bunga serta mengurangkan hasil sebanyak 15 hingga 43 peratus."
    },
    "rust": {
      "name": "Karat daun kopi",
      "look": "Bintik kuning pucat yang kecil muncul di atas daun. Di bawah, setiap bintik mempunyai tompok serbuk kuning hingga jingga tua yang melekat pada jari anda apabila digosok. Bintik lama menjadi coklat di tengah dan daun gugur awal. Ia biasanya bermula pada daun bawah pokok.",
      "tellApart": "Karat mempunyai serbuk jingga di bahagian bawah daun, manakala bintik mata coklat mempunyai cincin coklat kering dengan tengah kelabu keputihan dan tiada serbuk.",
      "actions": [
        "Periksa bahagian bawah daun yang rendah dengan kerap. Mengesannya lebih awal paling penting.",
        "Petik dan bakar atau tanam daun dan dahan yang mempunyai bintik jingga.",
        "Pangkas dan jarangkan teduhan serta rumpai supaya udara bergerak dan daun cepat kering.",
        "Bajai pokok dengan baja kandang atau baja seimbang. Pokok yang lemah lebih teruk diserang.",
        "Semburkan racun kulat kuprum seperti kuprum hidroksida pada bahagian atas dan bawah daun semasa kurang daripada kira-kira 5 peratus daun yang sakit. Kuprum melindungi daun yang sihat tetapi tidak menyembuhkan daun yang sakit. Tanya pegawai pengembangan anda tentang waktunya.",
        "Untuk tanaman baharu, tanya pegawai pengembangan anda tentang varieti tahan karat seperti jenis Catimor atau Sarchimor."
      ],
      "urgencyReason": "Ia merebak dengan cepat antara pokok dan ladang, dan kerugian pada varieti yang mudah diserang boleh mencapai 30 hingga 80 peratus."
    },
    "mites": {
      "name": "Kemungkinan kerosakan hama hawar",
      "look": "Imej ini menyerupai daun kopi yang dilabel mempunyai kerosakan hama hawar. Tanda yang serupa boleh disebabkan oleh perkara lain, jadi ini hanya kemungkinan padanan.",
      "actions": [
        "Minta pegawai pengembangan memeriksa kedua-dua belah daun dan mengesahkan puncanya sebelum memilih rawatan."
      ]
    },
    "weevil": {
      "name": "Kemungkinan kerosakan serangga pemakan daun",
      "look": "Daun ini menyerupai imej yang dilabel sebagai kerosakan kumbang gajah atau kumbang. Foto ini tidak dapat mengenal pasti spesies serangga itu.",
      "actions": [
        "Minta pegawai pengembangan memeriksa daun yang rosak dan sebarang serangga pada pokok sebelum memilih rawatan."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Cari pelekat KEPHIS pada bungkusan benih.",
    "stepScratch": "Calar pelekat untuk menunjukkan kod.",
    "stepText": "Hantar kod melalui mesej ke {shortCode}. Ia percuma.",
    "result": "KEPHIS membalas untuk memberitahu sama ada benih itu tulen. Kod yang tulen tidak membuktikan benih itu disimpan dengan baik.",
    "coverage": "Ini berfungsi untuk benih bersijil yang dijual dalam bungkusan. Anak benih tapak semaian biasanya tiada pelekat, jadi tanya pegawai lapangan anda tentangnya.",
    "noContact": "Tanya pegawai lapangan anda cara memeriksa sama ada bungkusan benih itu tulen."
  },
  "phoneGreeting": "Helo, ini Leaf Doctor. Saya membantu tentang pokok kopi yang sakit, dan anda boleh bercakap dengan saya dalam bahasa anda sendiri. Apa yang anda lihat pada daun kopi anda?"
});

export default msText;
