// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const nbText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Bladene dine ser friske ut",
    "headlineSpray": "{name}: beskytt friske blader og rydd opp",
    "headlinePrune": "{name}: rydd opp og beskjær",
    "headlineMonitor": "{name}: hold øye med det",
    "headlineAskOfficer": "{name}: be feltrådgiveren din se på det",
    "headlineNotSure": "Appen er usikker. Vis disse bladene til feltrådgiveren din",
    "headlineMightBe": "Det kan være {name}, men det er ikke bekreftet. Vis det til en feltrådgiver",
    "headlineRetake": "Ta tydeligere bilder av flere blader",
    "retakeDaylight": "Gå ut i dagslys, ikke i dyp skygge eller rett sol.",
    "retakeSteady": "Hold telefonen rolig til bladet ser skarpt ut.",
    "retakeFillFrame": "Fyll bildet med ett blad.",
    "sendToOfficer": "Send saken til feltrådgiveren i kooperativet ditt på SMS, eller vis bladene personlig.",
    "rainReason": "Det regnet {n} av de siste 7 dagene i nærheten av deg ({source}). Vått vær får rust til å spre seg raskere.",
    "labelRate": "Bruk dosen som står på produktetiketten.",
    "elseBerryDisease": "Kaffebærsykdom: se etter mørke, innsunkne flekker på bærene.",
    "elseBerryBorer": "Kaffebærborer: se etter små hull i bærene.",
    "elseWilt": "Kaffevisning: hele greiner visner og dør.",
    "elseNutrition": "Dårlig jord eller mangel på næring: gulning over hele treet.",
    "smsDecisionSpray": "Beslutning: beskytt friske blader med kobber i dosen på etiketten og rydd opp. Sjekk igjen om {days} dager.",
    "smsDecisionPrune": "Beslutning: beskjær og rydd opp. Sjekk igjen om {days} dager.",
    "smsDecisionMonitor": "Beslutning: hold øye med det. Sjekk igjen om {days} dager.",
    "smsDecisionCallOfficer": "Beslutning: vis det til feltrådgiveren din."
  },
  "diseases": {
    "cercospora": {
      "name": "Brunt øyeflekk",
      "look": "Runde brune flekker, mest på oversiden av bladet, med gråhvit midte og en mørkebrun ring, ofte med en gul krans. Flekkene er 5 til 15 mm brede og kan vokse sammen til store døde partier. Bærene får mørke, innsunkne flekker og modnes for tidlig.",
      "tellApart": "Brunt øyeflekk har tørre brune ringer med blekgrå midte og uten oransje pulver, mens rust har oransje pulver på undersiden.",
      "actions": [
        "Gjødsle trærne godt, særlig med nitrogen og kalium. God gjødsling holder ofte denne sykdommen nede.",
        "Hold lett skygge, hold ugress under kontroll og beskjær slik at lufta kommer til og bladene tørker.",
        "Etter beskjæring: frakt bort eller brenn blader og bær. Ikke legg dem i hauger inntil trærne.",
        "I planteskolen: sett småplantene med god avstand og brenn småplanter med ringformede brune flekker.",
        "Hvis det er ille, kan et kobberbasert soppmiddel beskytte friske blader. Spør rådgiveren din i landbruksveiledningen først."
      ],
      "urgencyReason": "Den svekker hovedsakelig stressede trær og blir vanligvis bedre når gjødsling og skygge er i orden."
    },
    "healthy": {
      "name": "Friskt kaffeblad",
      "look": "Et friskt blad er blankt, ovalt og spisst, jevnt mørkegrønt, uten flekker, pulver, hull eller ganger på oversiden eller undersiden.",
      "actions": [
        "Beskjær, hold lett skygge og hold ugresset nede slik at bladene tørker raskt.",
        "Gi trærne husdyrgjødsel eller balansert gjødsel, særlig med nitrogen og kalium.",
        "Sjekk bladene og undersiden deres hver uke eller annenhver uke for å oppdage rust eller bladminerer tidlig."
      ]
    },
    "miner": {
      "name": "Kaffebladminerer",
      "look": "Blekgule, slyngete ganger dukker opp inne i bladet og blir til ujevne brune, døde partier på oversiden. Hvis du bøyer bladet, løsner den tynne huden over partiet, og du kan finne en liten gjennomsiktig larve inni. Kraftige angrep får bladene til å falle av.",
      "tellApart": "Minererpartier er papiraktige blemmer med en larve inni som løsner når bladet bøyes, mens brunt øyeflekk er en ryddig rund ring som ikke løsner.",
      "actions": [
        "Bøy de brune partiene for å lete etter levende larver, særlig i tørketiden.",
        "Beskytt naturlige fiender som små veps og maur ved å holde blandet skygge og unngå unødvendig sprøyting.",
        "Følg nøye med på unge trær og planteskoler og fjern de første partiene tidlig.",
        "Hvis det trengs et insektmiddel, spør rådgiveren din i landbruksveiledningen hvilket produkt som er lovlig og trygt i landet ditt."
      ],
      "urgencyReason": "Kraftige angrep gir bladfall og lavere avling, verst i tørre, varme perioder."
    },
    "phoma": {
      "name": "Phoma bladflekk",
      "look": "Mørkebrune til svarte flekker på opptil 2 cm på eldre blader, med lysere midte og mørkere kant. Spissene på unge skudd blir svarte og tørker inn, blomster kan dø og bær faller av. Skaden kan starte ved bladspissen eller kanten.",
      "tellApart": "Phoma dreper også spissene på unge skudd og blomster i kalde, vindfulle høylandsstrøk, mens brunt øyeflekk blir værende som ringformede flekker og ikke tørker ut skuddspissene.",
      "actions": [
        "Plant vindskjermer i vindfulle områder. Vindskader slipper soppen inn.",
        "Beskjær bort og ødelegg tørkede skudd og mumifiserte bær, og beskjær slik at lufta kan tørke bladene.",
        "Gjødsle trærne med balansert gjødsel, særlig med nitrogen og kalium.",
        "I kalde, vindfulle sesonger: sprøyt et kobberbasert soppmiddel før sykdommen dukker opp. Spør rådgiveren din i landbruksveiledningen om tidspunktet."
      ],
      "urgencyReason": "I kalde, vindfulle høylandsstrøk kan den drepe skudd og blomster og redusere avlingen med 15 til 43 prosent."
    },
    "rust": {
      "name": "Kaffebladrust",
      "look": "Små blekgule flekker vises på oversiden av bladet. På undersiden har hver flekk et parti med gult til mørkeoransje pulver som smitter av på fingeren. Gamle flekker blir brune i midten, og bladene faller tidlig av. Den starter vanligvis på de nederste bladene på treet.",
      "tellApart": "Rust har oransje pulver på undersiden av bladet, mens brunt øyeflekk har tørre brune ringer med gråhvit midte og uten pulver.",
      "actions": [
        "Sjekk undersiden av de nederste bladene ofte. Det aller viktigste er å oppdage den tidlig.",
        "Plukk av og brenn eller grav ned blader og greiner med oransje flekker.",
        "Beskjær og tynn ut skygge og ugress slik at lufta kommer til og bladene tørker raskere.",
        "Gi trærne husdyrgjødsel eller balansert gjødsel. Svake trær blir hardere rammet.",
        "Sprøyt et kobberbasert soppmiddel som kobberhydroksid på over- og undersiden av bladene mens under omtrent 5 prosent av bladene er syke. Kobber beskytter friske blader, men kurerer ikke syke. Spør rådgiveren din i landbruksveiledningen om tidspunktet.",
        "Ved ny planting: spør rådgiveren din i landbruksveiledningen om rustresistente sorter, for eksempel Catimor- eller Sarchimor-typer."
      ],
      "urgencyReason": "Den sprer seg raskt mellom trær og gårder, og tapet på mottakelige sorter kan nå 30 til 80 prosent."
    },
    "mites": {
      "name": "Mulig midskade",
      "look": "Bildet ligner på kaffeblader merket med midskade. Lignende merker kan ha andre årsaker, så dette er et mulig samsvar.",
      "actions": [
        "Be en rådgiver i landbruksveiledningen se på begge sider av bladet og bekrefte årsaken før du velger behandling."
      ]
    },
    "weevil": {
      "name": "Mulig skade fra bladetende skadedyr",
      "look": "Bladet ligner på bilder merket med skade fra kokosbille eller snutebiller. Dette bildet kan ikke avgjøre hvilken insektart det er.",
      "actions": [
        "Be en rådgiver i landbruksveiledningen se på det skadde bladet og eventuelle insekter på planten før du velger behandling."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Finn KEPHIS-klistremerket på frøpakken.",
    "stepScratch": "Skrap av klistremerket for å vise koden.",
    "stepText": "Send koden som tekst til {shortCode}. Det er gratis.",
    "result": "KEPHIS svarer og sier om frøet er ekte. En ekte kode beviser ikke at frøet er oppbevart riktig.",
    "coverage": "Dette fungerer for sertifisert frø som selges i pakker. Småplanter fra planteskole har vanligvis ikke klistremerke, så spør feltrådgiveren din om dem.",
    "noContact": "Spør feltrådgiveren din hvordan du kan sjekke om en frøpakke er ekte."
  },
  "phoneGreeting": "Hei, dette er Leaf Doctor. Jeg hjelper med syke kaffeplanter, og du kan snakke med meg på ditt eget språk. Hva ser du på kaffebladene dine?"
});

export default nbText;
