// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const nlText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Uw bladeren zien er gezond uit",
    "headlineSpray": "{name}: bescherm gezonde bladeren en ruim op",
    "headlinePrune": "{name}: ruim op en snoei",
    "headlineMonitor": "{name}: blijf opletten",
    "headlineAskOfficer": "{name}: vraag uw veldadviseur om te controleren",
    "headlineNotSure": "De app is niet zeker. Laat deze bladeren aan uw veldadviseur zien",
    "headlineMightBe": "Het kan {name} zijn, maar dat is niet bevestigd. Laat het aan een veldadviseur zien",
    "headlineRetake": "Maak duidelijkere foto's van meer bladeren",
    "retakeDaylight": "Ga naar daglicht, niet in diepe schaduw of direct zonlicht.",
    "retakeSteady": "Houd de telefoon stil tot het blad scherp is.",
    "retakeFillFrame": "Vul het beeld met één blad.",
    "sendToOfficer": "Stuur deze zaak per sms naar de veldadviseur van uw coöperatie, of laat de bladeren persoonlijk zien.",
    "rainReason": "Het heeft bij u in de buurt {n} van de laatste 7 dagen geregend ({source}). Nat weer laat roest sneller verspreiden.",
    "labelRate": "Gebruik de dosis die op het etiket van het product staat.",
    "elseBerryDisease": "Koffiebesziekte: kijk of de bessen donkere, ingezonken plekken hebben.",
    "elseBerryBorer": "Koffiebessenboorder: zoek naar kleine gaatjes in de bessen.",
    "elseWilt": "Koffieverwelking: hele takken verwelken en sterven af.",
    "elseNutrition": "Arme grond of te weinig voeding: vergeling over de hele boom.",
    "smsDecisionSpray": "Besluit: bescherm gezonde bladeren met koper in de dosis van het etiket en ruim op. Controleer opnieuw over {days} dagen.",
    "smsDecisionPrune": "Besluit: snoei en ruim op. Controleer opnieuw over {days} dagen.",
    "smsDecisionMonitor": "Besluit: blijf opletten. Controleer opnieuw over {days} dagen.",
    "smsDecisionCallOfficer": "Besluit: laat het aan uw veldadviseur zien."
  },
  "diseases": {
    "cercospora": {
      "name": "Bruine oogvlek",
      "look": "Ronde bruine vlekken, vooral op de bovenkant van het blad, met een grijswit midden en een donkerbruine ring, vaak met een gele rand. De vlekken zijn 5 tot 15 mm breed en kunnen samenvloeien tot grote dode plekken. Bessen krijgen donkere, ingezonken vlekken en rijpen te vroeg.",
      "tellApart": "Bruine oogvlek heeft droge bruine ringen met een lichtgrijs midden en geen oranje poeder, terwijl roest oranje poeder aan de onderkant heeft.",
      "actions": [
        "Geef de bomen goede voeding, vooral stikstof en kalium. Goede voeding houdt deze ziekte vaak in toom.",
        "Houd lichte schaduw, bestrijd onkruid en snoei zodat de lucht kan bewegen en de bladeren drogen.",
        "Voer na het snoeien bladeren en bessen af of verbrand ze. Leg ze niet in hopen tegen de bomen.",
        "Plant in de kwekerij de zaailingen met ruimte ertussen en verbrand zaailingen met bruine vlekken met ringen.",
        "Als het erg is, kan een koperschimmelbestrijder gezonde bladeren beschermen. Vraag eerst uw landbouwadviseur."
      ],
      "urgencyReason": "Het verzwakt vooral bomen onder stress en wordt meestal beter als voeding en schaduw op orde zijn."
    },
    "healthy": {
      "name": "Gezond koffieblad",
      "look": "Een gezond blad is glanzend, ovaal en puntig, egaal donkergroen, zonder vlekken, poeder, gaten of gangen aan de boven- en onderkant.",
      "actions": [
        "Snoei en houd lichte schaduw en laag onkruid, zodat de bladeren snel drogen.",
        "Geef de bomen mest of evenwichtige kunstmest, vooral stikstof en kalium.",
        "Controleer elke week of twee weken de bladeren en hun onderkant, om roest of bladmineerders vroeg te vinden."
      ]
    },
    "miner": {
      "name": "Koffiebladmineerder",
      "look": "Bleekgele kronkelende sporen verschijnen in het blad en worden ongelijke bruine dode plekken aan de bovenkant. Als u het blad buigt, scheurt het dunne bovenvlies over de plek open en kunt u binnenin een kleine doorzichtige larve vinden. Zware aantasting laat bladeren vallen.",
      "tellApart": "Mineerplekken zijn papierdunne blaasjes met een larve erin, die openscheuren als ze worden gebogen, terwijl bruine oogvlek een nette ronde ring is die niet scheurt.",
      "actions": [
        "Buig bruine plekken om te zoeken naar levende larven, vooral in het droge seizoen.",
        "Bescherm natuurlijke vijanden zoals kleine wespen en mieren door gemengde schaduw te houden en onnodig spuiten te vermijden.",
        "Let goed op jonge bomen en kwekerijen en verwijder de eerste plekken vroeg.",
        "Als een insecticide nodig is, vraag dan uw landbouwadviseur welk product in uw land wettelijk is toegestaan en veilig is."
      ],
      "urgencyReason": "Zware aantasting veroorzaakt bladval en lagere opbrengst, het ergst in droge, hete periodes."
    },
    "phoma": {
      "name": "Phoma-bladvlek",
      "look": "Donkerbruine tot zwarte vlekken tot 2 cm breed op oudere bladeren, met een lichter midden en een donkerdere rand. De toppen van jonge scheuten worden zwart en drogen uit, bloemen kunnen afsterven en bessen vallen af. De schade kan beginnen aan de bladtop of de rand.",
      "tellApart": "Phoma doodt ook de toppen van jonge scheuten en bloemen in koude, winderige hooglanden, terwijl bruine oogvlek bij vlekken met ringen blijft en de scheuttoppen niet laat uitdrogen.",
      "actions": [
        "Plant windschermen in winderige gebieden. Windschade laat de schimmel binnen.",
        "Snijd verdroogde scheuten en gemummificeerde bessen af en vernietig ze, en snoei zodat de lucht de bladeren kan drogen.",
        "Geef de bomen evenwichtige kunstmest, vooral stikstof en kalium.",
        "Spuit in koude, winderige seizoenen een koperschimmelbestrijder voordat de ziekte verschijnt. Vraag uw landbouwadviseur naar het juiste moment."
      ],
      "urgencyReason": "In koude, winderige hooglanden kan het scheuten en bloemen doden en de opbrengst met 15 tot 43 procent verlagen."
    },
    "rust": {
      "name": "Koffiebladroest",
      "look": "Kleine bleekgele vlekken verschijnen op de bovenkant van het blad. Aan de onderkant heeft elke vlek een plek geel tot donkeroranje poeder dat op uw vinger afgeeft. Oude vlekken worden in het midden bruin en de bladeren vallen vroeg af. Het begint meestal aan de onderste bladeren van de boom.",
      "tellApart": "Roest heeft oranje poeder aan de onderkant van het blad, terwijl bruine oogvlek droge bruine ringen met een grijswit midden heeft en geen poeder.",
      "actions": [
        "Controleer vaak de onderkant van de onderste bladeren. Vroeg ontdekken is het belangrijkst.",
        "Pluk bladeren en takken met oranje vlekken af en verbrand of begraaf ze.",
        "Snoei en dun schaduw en onkruid uit, zodat de lucht kan bewegen en de bladeren sneller drogen.",
        "Geef de bomen mest of evenwichtige kunstmest. Zwakke bomen worden harder getroffen.",
        "Spuit een koperschimmelbestrijder zoals koperhydroxide op boven- en onderkant van de bladeren zolang minder dan ongeveer 5 procent van de bladeren ziek is. Koper beschermt gezonde bladeren maar geneest zieke niet. Vraag uw landbouwadviseur naar het juiste moment.",
        "Vraag voor nieuwe aanplant uw landbouwadviseur naar roestresistente rassen zoals Catimor- of Sarchimor-typen."
      ],
      "urgencyReason": "Het verspreidt zich snel tussen bomen en boerderijen, en verliezen op gevoelige rassen kunnen oplopen tot 30 tot 80 procent."
    },
    "mites": {
      "name": "Mogelijke schade door mijten",
      "look": "De afbeelding lijkt op koffiebladeren die als mijtschade zijn gelabeld. Vergelijkbare tekens kunnen andere oorzaken hebben, dus dit is een mogelijke overeenkomst.",
      "actions": [
        "Vraag een landbouwadviseur beide kanten van het blad te bekijken en de oorzaak te bevestigen voordat u een behandeling kiest."
      ]
    },
    "weevil": {
      "name": "Mogelijke schade door bladetende plaaginsecten",
      "look": "Het blad lijkt op afbeeldingen die als coco- of snuitkeverschade zijn gelabeld. Deze foto kan de insectensoort niet bepalen.",
      "actions": [
        "Vraag een landbouwadviseur het beschadigde blad en eventuele insecten op de plant te bekijken voordat u een behandeling kiest."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Zoek de KEPHIS-sticker op het zaadzakje.",
    "stepScratch": "Krab de sticker vrij om de code te tonen.",
    "stepText": "Stuur de code per sms naar {shortCode}. Het is gratis.",
    "result": "KEPHIS antwoordt of het zaad echt is. Een echte code bewijst niet dat het zaad goed is bewaard.",
    "coverage": "Dit werkt voor gecertificeerd zaad dat in zakjes wordt verkocht. Zaailingen uit de kwekerij hebben meestal geen sticker, dus vraag uw veldadviseur ernaar.",
    "noContact": "Vraag uw veldadviseur hoe u kunt controleren of een zaadzakje echt is."
  },
  "phoneGreeting": "Goedendag, dit is Leaf Doctor. Ik help bij zieke koffieplanten en u kunt met mij praten in uw eigen taal. Wat ziet u op uw koffiebladeren?"
});

export default nlText;
