// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const ocText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Vòstras fuèlhas semblan en santat",
    "headlineSpray": "{name} : protegissètz las fuèlhas sanas e netejatz",
    "headlinePrune": "{name} : netejatz e talhatz",
    "headlineMonitor": "{name} : contunhatz de sorvelhar",
    "headlineAskOfficer": "{name} : demandatz a vòstre agent de tèrra de verificar",
    "headlineNotSure": "L'aplicacion es pas segura. Mostratz aquestas fuèlhas a vòstre agent de tèrra",
    "headlineMightBe": "Poiriá èsser {name}, mas es pas confirmat. Mostratz-o a un agent de tèrra",
    "headlineRetake": "Prenètz de fòtos mai claras de mai de fuèlhas",
    "retakeDaylight": "Anatz a la lutz del jorn, pas a l'ombra espessa ni al solelh dirècte.",
    "retakeSteady": "Tenètz lo telefòn immobil fins que la fuèlha siá nèta.",
    "retakeFillFrame": "Emplenatz lo quadre amb una sola fuèlha.",
    "sendToOfficer": "Mandatz aqueste cas a l'agent de tèrra de vòstra cooperativa per SMS, o mostratz las fuèlhas en persona.",
    "rainReason": "A plogut {n} jorns sus los 7 darrièrs près de vos ({source}). Lo temps banhat fa espandir la rovilha mai vite.",
    "labelRate": "Utilizatz la dòsi indicada sus l'etiqueta del produch.",
    "elseBerryDisease": "Malautiá de la baia de cafè : agachatz las baias per de talhas escuras e afondradas.",
    "elseBerryBorer": "Perforaire de la baia de cafè : cercatz de pichons traucs dins las baias.",
    "elseWilt": "Marciment del cafè : de branquetas entièras que seccan e morisson.",
    "elseNutrition": "Sòl paure o manca de nutriments : jaunida sus tot l'arbre.",
    "smsDecisionSpray": "Decision : protegissètz las fuèlhas sanas amb de coire a la dòsi de l'etiqueta e netejatz. Verificatz tornar dins {days} jorns.",
    "smsDecisionPrune": "Decision : talhatz e netejatz. Verificatz tornar dins {days} jorns.",
    "smsDecisionMonitor": "Decision : contunhatz de sorvelhar. Verificatz tornar dins {days} jorns.",
    "smsDecisionCallOfficer": "Decision : mostratz-o a vòstre agent de tèrra."
  },
  "diseases": {
    "cercospora": {
      "name": "Taca d'uèlh bruna",
      "look": "Talhas redondas brunas, sustot sus la fàcia del dessús de la fuèlha, amb un centre gris-blanc e un anèl bruna escur, sovent amb un halo jaune. Las talhas fan de 5 a 15 mm de larg e se pòdon ajustar en grands espandis morts. Las baias an de talhas escuras e afondradas e maduran tròp d'ora.",
      "tellApart": "La taca d'uèlh bruna a d'anèls bruns secs amb un centre gris clar e cap de pols irange, mentre que la rovilha a de pols irange en dessús.",
      "actions": [
        "Nutrissètz plan los arbres, especialament en azòt e en potassi. Una bona fumada contraròtla sovent aquesta malautiá.",
        "Gardatz una ombra leugièra, contraròtlatz las marridas èrbas e talhatz per que l'aire passe e que las fuèlhas secan.",
        "Aprèp la talha, emportatz o brutlatz las fuèlhas e las baias. Los amassetz pas contra los arbres.",
        "Dins la pepiniera, espaciatz los plançons e brutlatz los plançons amb de talhas brunas en anèl.",
        "Se es grèu, un fongicida a basa de coire pòt protegir las fuèlhas sanas. Demandatz primièr a vòstre agent d'extension."
      ],
      "urgencyReason": "Afebliís subretot los arbres estressats e s'amelhora generalament un còp que la fumada e l'ombra son sistemadas."
    },
    "healthy": {
      "name": "Fuèlha de cafè en santat",
      "look": "Una fuèlha en santat es lusenta, ovala e puntuda, d'un verd escur uniforme, sens talhas, pols, traucs o galariás dessús o dessot.",
      "actions": [
        "Talhatz e gardatz una ombra leugièra e las marridas èrbas bassas per que las fuèlhas secan lèu.",
        "Fumatz los arbres amb de fems o un engraissat equilibrat, especialament en azòt e en potassi.",
        "Verificatz las fuèlhas e lor revèrs cada setmana o cada doas setmanas per trapar d'ora la rovilha o lo minaire de fuèlha."
      ]
    },
    "miner": {
      "name": "Minaire de las fuèlhas de cafè",
      "look": "De camins jaune clar sinuós apareisson dins la fuèlha e se transforman en espandis morts bruns irregulars dessús. Se plegatz la fuèlha, la pèl fina sus l'espandi se desparteís e podètz trobar un pichon verm transparent dedins. Las atacas fòrtas fan tombar las fuèlhas.",
      "tellApart": "Los espandis del minaire son de bofigas coma de papièr amb un verm dedins que se despartisson quand se plega, mentre que la taca d'uèlh bruna es un anèl redond net que se desparteís pas.",
      "actions": [
        "Plegatz los espandis bruns per cercar de vèrms vius, especialament en sason seca.",
        "Protegissètz los enemics naturals coma las pichonas vèspas e las formigas en gardant una ombra mesclada e en evitant de pulverizar sens besonh.",
        "Sorvelhatz de près los arbres joves e las pepinieras e levatz d'ora los primièrs espandis.",
        "Se un insecticida es necessari, demandatz a vòstre agent d'extension quin produch es legal e sens risc dins vòstre país."
      ],
      "urgencyReason": "Las atacas fòrtas fan tombar las fuèlhas e baisson lo rendement, pièger pendent los periòdes secs e caluts."
    },
    "phoma": {
      "name": "Taca de las fuèlhas per Phoma",
      "look": "De talhas bruna escur a negras de fins a 2 cm de larg sus las fuèlhas pus vièlhas, amb un centre mai clar e un bòrd mai escur. Las puntas dels jaiçons joves venon negras e secan, las flors pòdon morir e las baias tombar. Lo damnatge pòt començar a la ponta o al bòrd de la fuèlha.",
      "tellApart": "Phoma tua tanben las puntas dels jaiçons joves e las flors dins las nautas tèrras fregidas e ventosas, mentre que la taca d'uèlh bruna demòra de talhas en anèl e fa pas secar las puntas dels jaiçons.",
      "actions": [
        "Plantatz de rampars de vent dins las zònas ventosas. Los damnatges del vent daissan entrar lo fonge.",
        "Talhatz e destruïssètz los jaiçons secs e las baias mumificadas, e talhatz per que l'aire pòsca secar las fuèlhas.",
        "Nutrissètz los arbres amb un engraissat equilibrat, especialament en azòt e en potassi.",
        "Dins las sasons fregidas e ventosas, pulverizatz un fongicida a basa de coire abans que la malautiá aparesca. Demandatz a vòstre agent d'extension quand o far."
      ],
      "urgencyReason": "Dins las nautas tèrras fregidas e ventosas pòt tuar los jaiçons e las flors e reduire lo rendement de 15 a 43 per cent."
    },
    "rust": {
      "name": "Rovilha de las fuèlhas de cafè",
      "look": "De pichonas talhas jaune clar apareisson sus la fàcia del dessús de la fuèlha. Dessot, cada taca a un espandi de pols jaune a irange escur que se desprèn sul det. Las talhas vièlhas venon brunas al mitan e las fuèlhas tombon d'ora. Comença generalament per las fuèlhas del bas de l'arbre.",
      "tellApart": "La rovilha a de pols irange sul revèrs de la fuèlha, mentre que la taca d'uèlh bruna a d'anèls bruns secs amb un centre gris-blanc e cap de pols.",
      "actions": [
        "Verificatz sovent lo revèrs de las fuèlhas del bas. La causa mai importanta es de la trapar d'ora.",
        "Culhissètz e brutlatz o enterratz las fuèlhas e las branquetas amb de talhas irangesas.",
        "Talhatz e esclarzissètz l'ombra e las marridas èrbas per que l'aire passe e que las fuèlhas secan mai lèu.",
        "Fumatz los arbres amb de fems o un engraissat equilibrat. Los arbres febles son mai fòrt tocats.",
        "Pulverizatz un fongicida a basa de coire coma l'idroxid de coire sus lo dessús e lo dessot de las fuèlhas tant que mens de 5 per cent de las fuèlhas son malautas. Lo coire protegís las fuèlhas sanas mas garís pas las malautas. Demandatz a vòstre agent d'extension quand o far.",
        "Per una plantacion novèla, demandatz a vòstre agent d'extension de varietats resistentas a la rovilha coma los tipes Catimor o Sarchimor."
      ],
      "urgencyReason": "S'espandís vitament entre los arbres e las fermas, e las pèrdas sus las varietats sensiblas pòdon arribar a 30 a 80 per cent."
    },
    "mites": {
      "name": "Damnatge possible d'acaians",
      "look": "L'imatge sembla a de fuèlhas de cafè marcadas amb un damnatge d'acaians. De marcas semblablas pòdon aver d'autras causas, doncas es una correspondéncia possibla.",
      "actions": [
        "Demandatz a un agent d'extension d'agachar los dos costats de la fuèlha e de confirmar la causa abans de causir un tractament."
      ]
    },
    "weevil": {
      "name": "Damnatge possible d'un parasit que manja las fuèlhas",
      "look": "La fuèlha sembla a d'imatges marcats coma un damnatge de coco o de gorgolhon. Aquesta fòto pòt pas identificar l'espècia de l'insècte.",
      "actions": [
        "Demandatz a un agent d'extension d'agachar la fuèlha damnada e los insèctes eventuals sus la planta abans de causir un tractament."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Trobatz l'autocolant KEPHIS sul paquet de semenças.",
    "stepScratch": "Gratatz l'autocolant per far aparéisser lo còdi.",
    "stepText": "Mandatz lo còdi per messatge al {shortCode}. Es gratuit.",
    "result": "KEPHIS respond per dire se la semença es autentica. Un còdi autentic pròva pas que la semença siá estada plan gardada.",
    "coverage": "Aquò foncionarà per las semenças certificadas venudas en paquets. Los plançons de pepiniera an generalament pas d'autocolant, doncas demandatz a vòstre agent de tèrra.",
    "noContact": "Demandatz a vòstre agent de tèrra cossí verificar se un paquet de semenças es autentic."
  },
  "phoneGreeting": "Bonjorn, aquí Leaf Doctor. Ajudi amb las plantas de cafè malautas, e podètz me parlar dins vòstra lenga. Qué vesètz sus vòstras fuèlhas de cafè ?"
});

export default ocText;
