// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const omText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Baalonni kee fayyaa qabu fakkaatu",
    "headlineSpray": "{name}: baala fayyaa qabu eegii qulqulleessi",
    "headlinePrune": "{name}: qulqulleessii muka qori",
    "headlineMonitor": "{name}: hordofuu itti fufi",
    "headlineAskOfficer": "{name}: ogeessa dirree kee akka ilaalu gaafadhu",
    "headlineNotSure": "Appiin hin mirkanoofne. Baalota kana ogeessa dirree keetti agarsiisi",
    "headlineMightBe": "{name} ta'uu mala, garuu hin mirkanoofne. Ogeessa dirree agarsiisi",
    "headlineRetake": "Baala dabalataa suuraa ifaa ta'een kaasi",
    "retakeDaylight": "Ifa guyyaatti seeni, gaaddisa cimaa yookiin aduu dhiyeenyaa keessa hin ta'iin.",
    "retakeSteady": "Baalli ifaan hanga mul'atutti bilbila jabeessii qabi.",
    "retakeFillFrame": "Baala tokkoon iskiriinii guuti.",
    "sendToOfficer": "Ilaalcha kana ogeessa dirree koopparaatiivii keetiif SMS'n ergi, yookiin baalota ofiin agarsiisi.",
    "rainReason": "Naannoo keetti ({source}) guyyoota 7 darban keessaa {n} roobeera. Haala qilleensaa jiidhaan rust dafee babal'ata.",
    "labelRate": "Dhiyeessa maxxansa oomishaa irra jiru fayyadami.",
    "elseBerryDisease": "Dhukkuba firii bunaa: firii irratti iddoo gadi fagoo gurraacha ilaali.",
    "elseBerryBorer": "Raammoo firii bunaa: firii keessatti boolla xixiqqaa ilaali.",
    "elseWilt": "Bunni goguu: dameewwan guutuun goggoguu fi du'uu.",
    "elseNutrition": "Biyyee yookiin soorata hin gahne: muka guutuu irratti keelloo ta'uu.",
    "smsDecisionSpray": "Murtii: baala fayyaa qabu koopperii dhiyeessa maxxansaan eegi qulqulleessi. Guyyaa {days} booda irra deebi'ii ilaali.",
    "smsDecisionPrune": "Murtii: muka qorii qulqulleessi. Guyyaa {days} booda irra deebi'ii ilaali.",
    "smsDecisionMonitor": "Murtii: hordofuu itti fufi. Guyyaa {days} booda irra deebi'ii ilaali.",
    "smsDecisionCallOfficer": "Murtii: ogeessa dirree kee agarsiisi."
  },
  "diseases": {
    "cercospora": {
      "name": "Tuqaa ijaa halluu bunaa",
      "look": "Tuqaawwan geengoo halluu bunaa, baay'inaan baala gubbaa irratti, giddu isaanii adii-daalachaa fi marsaa halluu bunaa gurraacha qaban, yeroo baay'ee marsaa keelloo qabu. Tuqaawwan kun bal'ina 5 hanga 15 mm qabu, walitti makamuudhaan iddoo du'e guddaa ta'uu danda'u. Firiin iddoo gadi fagoo gurraacha argata, yeroo isaa dura bilchaata.",
      "tellApart": "Tuqaan ijaa halluu bunaa marsaa halluu bunaa gogaa fi giddu daalachaa qaba, daakuu burtukaanaa hin qabu; rust garuu baala jalatti daakuu burtukaanaa qaba.",
      "actions": [
        "Muka gaarii soorachisi, keessumaa naayitirojiniifi poozaasiyamiin. Soorata gaariin yeroo baay'ee dhukkuba kana to'ata.",
        "Gaaddisa salphaa qabadhu, margaa to'adhu, qorii qori; qilleensi naanna'ee baalli gogu.",
        "Erga qoranii booda baalaa fi firii baadhii fudhaa deemi yookiin gubi. Muka irratti hin tuulin.",
        "Naursarii keessatti biqiltuu addaan fageessi, biqiltuu tuqaa halluu bunaa marsaa qabu gubi.",
        "Yoo hamaa ta'e, qoricha dhukkuba fungasii koopperii baala fayyaa qabu eegu danda'a. Dursa ogeessa babal'insaa gaafadhu."
      ],
      "urgencyReason": "Kan hedduu mukkeen dhiphatan dadhabsiisa; yeroo soorataafi gaaddisni sirraa'u ni fooyya'a."
    },
    "healthy": {
      "name": "Baala bunaa fayyaa qabu",
      "look": "Baalli fayyaa qabu ifaa, ovaalii fi fiixee qabu, magariisa dukkanaa walqixa, gubbaa fi jalaan tuqaa, daakuu, boolla yookiin tuunnelii hin qabu.",
      "actions": [
        "Qorii qorii, gaaddisa salphaa fi margaa gadi qabi, baalli dafee akka gogu.",
        "Muka ittiin bu'aa yookiin xaa'oo madaalawaan soorachisi, keessumaa naayitirojiniifi poozaasiyamiin.",
        "Baalaafi jala isaanii torbaan hundaa yookiin torban lamaan ilaali, rust yookiin raammoo baalaa dafee argachuuf."
      ]
    },
    "miner": {
      "name": "Raammoo baala bunaa keessa isaa nyaatu",
      "look": "Karaa keelloo ifaa maraa'aa baala keessatti mul'ata, gubbaa irratti iddoo du'e halluu bunaa walqixa hin taane ta'a. Baala yoo maruu, gogaan lafee gubbaa tuqaa irra jiru bu'a, raammoo xiqqoo ifa ta'e keessa isaa argita. Weerarri cimaan baalli akka kufu godha.",
      "tellApart": "Tuqaan raammoo waraqaa fakkaata, raammoo keessa qaba, yoo maruu addaan bu'a; tuqaan ijaa halluu bunaa garuu marsaa geengoo qulqulluu dha, addaan hin bu'u.",
      "actions": [
        "Raammoo jiraataa barbaaduuf tuqaa halluu bunaa maruu, keessumaa yeroo gogaa.",
        "Diinota uumamaa kan akka warqalee xixiqqaa fi tuutaa gaaddisa makaa qabuudhaan fi facaasuu hin barbaachifne irraa of qusachuudhaan eegi.",
        "Mukkeen dargaggoo fi naursarii ciminaan hordofi, tuqaa jalqabaa dafee balleessi.",
        "Yoo qoricha ilbiisaa barbaachise, ogeessa babal'insaa biyya kee keessatti kan seera qabeessaafi nageenya qabu kam akka ta'e gaafadhu."
      ],
      "urgencyReason": "Weerarri cimaan baalli akka kufu godha, oomisha ni hir'isa, yeroo gogaa ho'aa keessatti hammaata."
    },
    "phoma": {
      "name": "Tuqaa baalaa Phoma",
      "look": "Tuqaa halluu bunaa gurraacha hanga gurraacha, bal'inni isaa hanga 2 cm, baala dullaa irratti, giddu isaa ifa fi daangaan isaa dukkana'aa. Fiixeen dameewwan dargaggoo gurraacha'a, ni goga, daraaraan ni du'a, firiin ni kufa. Miidhaan fiixee yookiin daangaa baalaa irraa jalqabuu danda'a.",
      "tellApart": "Phoma fiixee dameewwan dargaggoo fi daraaraa gaarreen qabbanaa'oo fi bubbee qabu keessatti ni ajjeesa; tuqaan ijaa halluu bunaa garuu tuqaa marsaa qabu ta'ee hafa, fiixee damee hin gogsu.",
      "actions": [
        "Naannoo bubbee qabu keessatti muka bubbee dhaabuuf dhaabi. Miidhaan bubbee fungasii akka seenu godha.",
        "Dameewwan gogaa fi firii goggogaa qorii balleessi, qilleensi baala akka gogsuuf qorii qori.",
        "Muka xaa'oo madaalawaan soorachisi, keessumaa naayitirojiniifi poozaasiyamiin.",
        "Yeroo qabbanaa'aa fi bubbee qabu, dhukkubni osoo hin mul'anne qoricha fungasii koopperii facaasi. Yeroo isaa ogeessa babal'insaa gaafadhu."
      ],
      "urgencyReason": "Gaarreen qabbanaa'oo fi bubbee qabu keessatti dameewwan fi daraaraa ajjeesuu, oomisha dhibbeentaa 15 hanga 43 hir'isuu danda'a."
    },
    "rust": {
      "name": "Rust baala bunaa",
      "look": "Tuqaawwan keelloo ifaa xixiqqaa baala gubbaa irratti mul'atu. Jalaan, tuqaan tokkoon tokkoon isaa daakuu keelloo hanga burtukaanaa dukkanaa qaba, quba keetiin ni baqa. Tuqaawwan dulloomanii giddu isaanii halluu bunaa ta'a, baalonnis dafanii kufu. Yeroo baay'ee baala gadi muka irraa jalqaba.",
      "tellApart": "Rust baala jalatti daakuu burtukaanaa qaba; tuqaan ijaa halluu bunaa garuu marsaa halluu bunaa gogaa fi giddu adii-daalachaa qaba, daakuu hin qabu.",
      "actions": [
        "Baala gadii jala yeroo baay'ee ilaali. Dafee argachuun isa guddaa dha.",
        "Baalaa fi damee tuqaa burtukaanaa qabu fuudhii gubi yookiin awwaali.",
        "Gaaddisaafi margaa qorii hiri, qilleensi naanna'ee baalli dafee akka gogu.",
        "Muka ittiin bu'aa yookiin xaa'oo madaalawaan soorachisi. Mukkeen dadhaboon cimsanii miidhamu.",
        "Qoricha fungasii koopperii kan akka copper hydroxide baala gubbaa fi jalatti facaasi, hanga baala dhukkubsate dhibbeentaa 5 gadi ta'etti. Koopperiin baala fayyaa qabu ni eega, kan dhukkubsate garuu hin fayyisu. Yeroo isaa ogeessa babal'insaa gaafadhu.",
        "Dhaabbii haaraaf, gosoota rust'tti dandamatan kan akka gosa Catimor yookiin Sarchimor ogeessa babal'insaa gaafadhu."
      ],
      "urgencyReason": "Muka fi qonna gidduutti dafee babal'ata, gosoota dandamachuu hin dandeenye irratti dhabamsiisni dhibbeentaa 30 hanga 80 gahuu danda'a."
    },
    "mites": {
      "name": "Miidhaa maayitii ta'uu danda'u",
      "look": "Fakkiin baala bunaa miidhaa maayitiitiin mallatteeffame fakkaata. Mallattooleen walfakkaatan sababoota biroo qabaachuu danda'u, kanaaf kun walsimuu danda'u.",
      "actions": [
        "Ogeessa babal'insaa gaafadhu, bakka lamaan baala ilaalee sababa mirkaneessuuf, osoo yaalii hin filatin."
      ]
    },
    "weevil": {
      "name": "Miidhaa raammoo baala nyaatu ta'uu danda'u",
      "look": "Baalli fakkiiwwan miidhaa raammootiin mallatteeffaman fakkaata. Suuraan kun gosa raammoo adda baasuu hin danda'u.",
      "actions": [
        "Ogeessa babal'insaa gaafadhu, baala miidhame fi raammoo biyyoo irra jiru ilaaluuf, osoo yaalii hin filatin."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Maxxansa KEPHIS bukkee sanyii irraa barbaadi.",
    "stepScratch": "Koodii agarsiisuuf maxxansa sana qoosi.",
    "stepText": "Koodii sana gara {shortCode} ergi. Bilisaan dha.",
    "result": "KEPHIS sanyiin sun dhugaa ta'uu fi dhiisuu deebisa. Koodiin dhugaan sanyiin sun gaariitti kuufame jechuu miti.",
    "coverage": "Kun sanyii mirkanaa'e bukkeen gurguramu irratti hojjeta. Biqiltuun naursarii yeroo baay'ee maxxansa hin qabu, kanaaf ogeessa dirree kee irraa gaafadhu.",
    "noContact": "Bukkeen sanyii dhugaa ta'uu isaa akkamitti ilaaluu akka dandeessu ogeessa dirree kee gaafadhu."
  },
  "phoneGreeting": "Akkam, Leaf Doctor dha. Ani biqiltuu bunaa dhukkubsate gargaara, afaan keetiin natti dubbachuu dandeessa. Baala bunaa kee irratti maal argita?"
});

export default omText;
