// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const plText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Twoje liście wyglądają zdrowo",
    "headlineSpray": "{name}: chroń zdrowe liście i posprzątaj",
    "headlinePrune": "{name}: posprzątaj i przytnij",
    "headlineMonitor": "{name}: obserwuj dalej",
    "headlineAskOfficer": "{name}: poproś doradcę terenowego o sprawdzenie",
    "headlineNotSure": "Aplikacja nie ma pewności. Pokaż te liście doradcy terenowemu",
    "headlineMightBe": "Może to być {name}, ale nie jest to potwierdzone. Pokaż doradcy terenowemu",
    "headlineRetake": "Zrób wyraźniejsze zdjęcia większej liczby liści",
    "retakeDaylight": "Przejdź na światło dzienne, nie w głęboki cień ani w ostre słońce.",
    "retakeSteady": "Trzymaj telefon nieruchomo, aż liść będzie ostry.",
    "retakeFillFrame": "Wypełnij kadr jednym liściem.",
    "sendToOfficer": "Wyślij tę sprawę SMS-em do doradcy terenowego w Twojej spółdzielni albo pokaż liście osobiście.",
    "rainReason": "W ciągu ostatnich 7 dni deszcz padał przez {n} dni w Twojej okolicy ({source}). Mokra pogoda sprawia, że rdza rozprzestrzenia się szybciej.",
    "labelRate": "Użyj dawki podanej na etykiecie produktu.",
    "elseBerryDisease": "Antraknoza jagód kawowca: sprawdź, czy na jagodach są ciemne, zapadnięte plamy.",
    "elseBerryBorer": "Kawowiec jagodowy (szkodnik): szukaj małych dziurek w jagodach.",
    "elseWilt": "Więdnięcie kawowca: więdną i usychają całe gałęzie.",
    "elseNutrition": "Uboga gleba lub niedobór składników: żółknięcie całego drzewa.",
    "smsDecisionSpray": "Decyzja: chroń zdrowe liście miedzią w dawce z etykiety i posprzątaj. Sprawdź ponownie za {days} dni.",
    "smsDecisionPrune": "Decyzja: przytnij i posprzątaj. Sprawdź ponownie za {days} dni.",
    "smsDecisionMonitor": "Decyzja: obserwuj dalej. Sprawdź ponownie za {days} dni.",
    "smsDecisionCallOfficer": "Decyzja: pokaż doradcy terenowemu."
  },
  "diseases": {
    "cercospora": {
      "name": "Brązowa plamistość oczkowa liści kawowca",
      "look": "Okrągłe brązowe plamy, głównie na górnej stronie liścia, z szarobiałym środkiem i ciemnobrązowym pierścieniem, często z żółtą obwódką. Plamy mają od 5 do 15 mm szerokości i mogą łączyć się w duże martwe obszary. Na jagodach pojawiają się ciemne zapadnięte plamy, a jagody dojrzewają za wcześnie.",
      "tellApart": "Brązowa plamistość oczkowa ma suche brązowe pierścienie z jasnoszarym środkiem i nie ma pomarańczowego proszku, a rdza ma pomarańczowy proszek na spodzie liścia.",
      "actions": [
        "Dobrze nawoź drzewa, zwłaszcza azotem i potasem. Dobre nawożenie często powstrzymuje tę chorobę.",
        "Utrzymuj lekki cień, zwalczaj chwasty i przycinaj drzewa tak, aby powietrze krążyło, a liście szybko wysychały.",
        "Po przycinaniu wynieś lub spal liście i jagody. Nie składaj ich w stosach przy drzewach.",
        "W szkółce sadź siewki w odstępach i spal siewki z brązowymi plamami z pierścieniami.",
        "Jeśli choroba jest silna, miedziowy środek grzybobójczy może ochronić zdrowe liście. Najpierw zapytaj swojego doradcę rolniczego."
      ],
      "urgencyReason": "Głównie osłabia drzewa pod wpływem stresu i zwykle ustępuje, gdy poprawi się nawożenie i cień."
    },
    "healthy": {
      "name": "Zdrowy liść kawowca",
      "look": "Zdrowy liść jest błyszczący, owalny i zaostrzony, równomiernie ciemnozielony, bez plam, proszku, dziur i tuneli na wierzchu i od spodu.",
      "actions": [
        "Przycinaj drzewa, utrzymuj lekki cień i ograniczaj chwasty, aby liście szybko wysychały.",
        "Nawoź drzewa obornikiem lub zrównoważonym nawozem, zwłaszcza azotem i potasem.",
        "Co tydzień lub dwa sprawdzaj liście i ich spód, aby wcześnie wykryć rdzę lub szrotówka kawowego."
      ]
    },
    "miner": {
      "name": "Szrotówek liściowy kawowca (minujący liście)",
      "look": "Wewnątrz liścia pojawiają się jasnożółte, kręte ścieżki, które zamieniają się w nierówne, brązowe, martwe plamy na wierzchu. Gdy zegniesz liść, cienka górna skórka nad plamą odchodzi i w środku można znaleźć malutką, przezroczystą larwę. Silny atak powoduje opadanie liści.",
      "tellApart": "Plamy po szrotówku są jak papierowe pęcherze z larwą w środku i odchodzą, gdy się je zegnie, a brązowa plamistość oczkowa to równy okrągły pierścień, który nie odchodzi.",
      "actions": [
        "Zginaj brązowe plamy i szukaj żywych larw, zwłaszcza w porze suchej.",
        "Chroń naturalnych wrogów, takich jak małe osy i mrówki: utrzymuj mieszany cień i unikaj niepotrzebnych oprysków.",
        "Uważnie obserwuj młode drzewa i szkółki i wcześnie usuwaj pierwsze plamy.",
        "Jeśli potrzebny jest środek owadobójczy, zapytaj swojego doradcę rolniczego, który produkt jest legalny i bezpieczny w Twoim kraju."
      ],
      "urgencyReason": "Silny atak powoduje opadanie liści i niższy plon, najgorzej w suchych, upalnych okresach."
    },
    "phoma": {
      "name": "Plamistość liści kawowca wywołana przez Phoma",
      "look": "Ciemnobrązowe do czarnych plamy do 2 cm szerokości na starszych liściach, z jaśniejszym środkiem i ciemniejszym brzegiem. Końce młodych pędów czernieją i usychają, kwiaty mogą obumierać, a jagody opadają. Uszkodzenie może zacząć się od czubka lub brzegu liścia.",
      "tellApart": "Phoma zabija też końce młodych pędów i kwiaty w zimnych, wietrznych górach, a brązowa plamistość oczkowa pozostaje plamami z pierścieniami i nie powoduje usychania końców pędów.",
      "actions": [
        "Sadź pasy osłonowe od wiatru na terenach wietrznych. Uszkodzenia od wiatru wpuszczają grzyba.",
        "Odcinaj i niszcz wyschnięte pędy i zmumifikowane jagody, a drzewa przycinaj tak, aby powietrze mogło osuszać liście.",
        "Nawoź drzewa zrównoważonym nawozem, zwłaszcza azotem i potasem.",
        "W zimnych, wietrznych porach roku opryskaj miedziowym środkiem grzybobójczym, zanim pojawi się choroba. Zapytaj swojego doradcę rolniczego o termin."
      ],
      "urgencyReason": "W zimnych, wietrznych górach może zabić pędy i kwiaty i zmniejszyć plon o 15 do 43 procent."
    },
    "rust": {
      "name": "Rdza liści kawowca",
      "look": "Na wierzchu liścia pojawiają się małe, jasnożółte plamki. Od spodu każda plamka ma skupisko żółtego do ciemnopomarańczowego proszku, który ściera się na palcu. Stare plamy brązowieją pośrodku, a liście opadają przedwcześnie. Zwykle zaczyna się na dolnych liściach drzewa.",
      "tellApart": "Rdza ma pomarańczowy proszek na spodzie liścia, a brązowa plamistość oczkowa ma suche brązowe pierścienie z szarobiałym środkiem i nie ma proszku.",
      "actions": [
        "Często sprawdzaj spód dolnych liści. Najważniejsze jest wczesne wykrycie.",
        "Zrywaj i pal lub zakopuj liście i gałęzie z pomarańczowymi plamami.",
        "Przycinaj i przerzedzaj cień oraz chwasty, aby powietrze krążyło, a liście szybciej wysychały.",
        "Nawoź drzewa obornikiem lub zrównoważonym nawozem. Osłabione drzewa chorują ciężej.",
        "Opryskaj miedziowym środkiem grzybobójczym, takim jak wodorotlenek miedzi, górę i spód liści, dopóki chorych jest mniej niż około 5 procent liści. Miedź chroni zdrowe liście, ale nie leczy chorych. Zapytaj swojego doradcę rolniczego o termin.",
        "Przy nowych nasadzeniach zapytaj swojego doradcę rolniczego o odmiany odporne na rdzę, takie jak typy Catimor lub Sarchimor."
      ],
      "urgencyReason": "Szybko rozprzestrzenia się między drzewami i plantacjami, a straty na podatnych odmianach mogą sięgać od 30 do 80 procent."
    },
    "mites": {
      "name": "Możliwe uszkodzenia przez roztocza",
      "look": "Obraz przypomina liście kawowca opisane jako uszkodzone przez roztocza. Podobne ślady mogą mieć inne przyczyny, więc to jest możliwe dopasowanie.",
      "actions": [
        "Poproś doradcę rolniczego, aby obejrzał obie strony liścia i potwierdził przyczynę, zanim wybierzesz sposób zwalczania."
      ]
    },
    "weevil": {
      "name": "Możliwe uszkodzenia przez szkodniki gryzące liście",
      "look": "Liść przypomina obrazy opisane jako uszkodzenia przez coco lub ryjkowce. Na podstawie tego zdjęcia nie można rozpoznać gatunku owada.",
      "actions": [
        "Poproś doradcę rolniczego, aby obejrzał uszkodzony liść i wszelkie owady na roślinie, zanim wybierzesz sposób zwalczania."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Znajdź naklejkę KEPHIS na opakowaniu z nasionami.",
    "stepScratch": "Zdrap naklejkę, aby odsłonić kod.",
    "stepText": "Wyślij kod SMS-em na numer {shortCode}. To jest bezpłatne.",
    "result": "KEPHIS odpisze, czy nasiona są oryginalne. Oryginalny kod nie dowodzi, że nasiona były dobrze przechowywane.",
    "coverage": "To działa dla nasion certyfikowanych sprzedawanych w opakowaniach. Sadzonki ze szkółki zwykle nie mają naklejki, więc zapytaj o nie doradcę terenowego.",
    "noContact": "Zapytaj doradcę terenowego, jak sprawdzić, czy opakowanie z nasionami jest oryginalne."
  },
  "phoneGreeting": "Dzień dobry, tu Leaf Doctor. Pomagam przy chorych krzewach kawy i może Pan lub Pani mówić do mnie w swoim języku. Co widać na liściach Pana lub Pani kawowców?"
});

export default plText;
