// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const ptText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Suas folhas parecem saudáveis",
    "headlineSpray": "{name}: proteja as folhas sadias e faça a limpeza",
    "headlinePrune": "{name}: faça a limpeza e a poda",
    "headlineMonitor": "{name}: continue observando",
    "headlineAskOfficer": "{name}: peça ao seu técnico de campo para verificar",
    "headlineNotSure": "O app não tem certeza. Mostre estas folhas ao seu técnico de campo",
    "headlineMightBe": "Pode ser {name}, mas não está confirmado. Mostre a um técnico de campo",
    "headlineRetake": "Tire fotos mais nítidas de mais folhas",
    "retakeDaylight": "Vá para a luz do dia, nem na sombra fechada nem no sol direto.",
    "retakeSteady": "Segure o celular firme até a folha ficar nítida.",
    "retakeFillFrame": "Encha a tela com uma folha só.",
    "sendToOfficer": "Envie este caso por SMS ao técnico de campo da sua cooperativa, ou mostre as folhas pessoalmente.",
    "rainReason": "Choveu em {n} dos últimos 7 dias perto de você ({source}). Tempo úmido faz a ferrugem se espalhar mais rápido.",
    "labelRate": "Use a dose indicada no rótulo do produto.",
    "elseBerryDisease": "Antracnose do fruto do café: olhe se os frutos têm manchas escuras e afundadas.",
    "elseBerryBorer": "Broca-do-café: procure furinhos nos frutos.",
    "elseWilt": "Murcha do café: galhos inteiros murchando e secando.",
    "elseNutrition": "Solo pobre ou falta de nutrientes: amarelecimento na planta toda.",
    "smsDecisionSpray": "Decisão: proteger as folhas sadias com cobre na dose do rótulo e fazer a limpeza. Verificar de novo em {days} dias.",
    "smsDecisionPrune": "Decisão: podar e fazer a limpeza. Verificar de novo em {days} dias.",
    "smsDecisionMonitor": "Decisão: continuar observando. Verificar de novo em {days} dias.",
    "smsDecisionCallOfficer": "Decisão: mostrar ao seu técnico de campo."
  },
  "diseases": {
    "cercospora": {
      "name": "Mancha-olho-pardo",
      "look": "Manchas marrons redondas, principalmente na parte de cima da folha, com o centro cinza-esbranquiçado e um anel marrom-escuro, muitas vezes com um halo amarelo. As manchas têm de 5 a 15 mm de largura e podem se juntar em grandes áreas mortas. Os frutos ganham manchas escuras e afundadas e amadurecem cedo demais.",
      "tellApart": "A mancha-olho-pardo tem anéis marrons secos com o centro cinza-claro e não tem pó alaranjado, já a ferrugem tem pó alaranjado por baixo.",
      "actions": [
        "Adube bem as plantas, principalmente com nitrogênio e potássio. Uma boa adubação muitas vezes controla esta doença.",
        "Mantenha sombra leve, controle o mato e pode as plantas para o ar circular e as folhas secarem.",
        "Depois da poda, leve embora ou queime as folhas e os frutos. Não deixe amontoados junto às plantas.",
        "No viveiro, deixe espaço entre as mudas e queime as mudas com manchas marrons em anel.",
        "Se estiver forte, um fungicida de cobre pode proteger as folhas sadias. Antes, pergunte ao seu extensionista."
      ],
      "urgencyReason": "Ela enfraquece principalmente as plantas estressadas e costuma melhorar quando a adubação e a sombra são corrigidas."
    },
    "healthy": {
      "name": "Folha de café saudável",
      "look": "Uma folha saudável é brilhante, oval e pontuda, de um verde-escuro uniforme, sem manchas, pó, furos ou túneis em cima nem por baixo.",
      "actions": [
        "Pode as plantas e mantenha sombra leve e pouco mato para as folhas secarem rápido.",
        "Adube as plantas com esterco ou adubo equilibrado, principalmente com nitrogênio e potássio.",
        "Confira as folhas e a parte de baixo delas a cada uma ou duas semanas para pegar cedo a ferrugem ou o bicho-mineiro."
      ]
    },
    "miner": {
      "name": "Bicho-mineiro do café",
      "look": "Aparecem trilhas tortas amarelo-claras dentro da folha, que viram manchas marrons mortas e irregulares em cima. Se você dobrar a folha, a pele fina de cima da mancha se solta e dá para achar uma larvinha transparente lá dentro. Ataques fortes fazem as folhas caírem.",
      "tellApart": "As manchas do bicho-mineiro são bolhas finas como papel, com uma larva dentro, que se soltam quando dobradas, já a mancha-olho-pardo é um anel redondo certinho que não se solta.",
      "actions": [
        "Dobre as manchas marrons para procurar larvas vivas, principalmente na época seca.",
        "Proteja os inimigos naturais, como vespinhas e formigas, mantendo sombra variada e evitando pulverizações desnecessárias.",
        "Observe de perto as plantas novas e os viveiros e tire as primeiras manchas cedo.",
        "Se precisar de inseticida, pergunte ao seu extensionista qual produto é permitido e seguro no seu país."
      ],
      "urgencyReason": "Ataques fortes causam queda de folhas e menos colheita, e é pior em períodos secos e quentes."
    },
    "phoma": {
      "name": "Mancha-de-phoma",
      "look": "Manchas marrom-escuras a pretas, de até 2 cm de largura, nas folhas mais velhas, com o centro mais claro e a borda mais escura. As pontas dos brotos novos ficam pretas e secam, as flores podem morrer e os frutos caem. O dano pode começar na ponta ou na borda da folha.",
      "tellApart": "A phoma também mata as pontas dos brotos novos e as flores em regiões altas, frias e ventosas, já a mancha-olho-pardo fica só como manchas em anel e não seca as pontas dos brotos.",
      "actions": [
        "Plante quebra-ventos em áreas ventosas. O dano do vento deixa o fungo entrar.",
        "Corte e destrua os brotos secos e os frutos mumificados, e pode para o ar secar as folhas.",
        "Adube as plantas com adubo equilibrado, principalmente com nitrogênio e potássio.",
        "Em épocas frias e ventosas, pulverize um fungicida de cobre antes de a doença aparecer. Pergunte ao seu extensionista qual é a hora certa."
      ],
      "urgencyReason": "Em regiões altas, frias e ventosas, ela pode matar brotos e flores e reduzir a colheita em 15 a 43 por cento."
    },
    "rust": {
      "name": "Ferrugem do cafeeiro",
      "look": "Pequenas manchas amarelo-claras aparecem na parte de cima da folha. Por baixo, cada mancha tem um pó amarelo a laranja-escuro que sai no dedo. As manchas velhas ficam marrons no meio e as folhas caem cedo. Em geral começa nas folhas de baixo da planta.",
      "tellApart": "A ferrugem tem pó alaranjado na parte de baixo da folha, já a mancha-olho-pardo tem anéis marrons secos com o centro cinza-esbranquiçado e sem pó.",
      "actions": [
        "Olhe a parte de baixo das folhas de baixo com frequência. Pegar cedo é o que mais importa.",
        "Tire e queime ou enterre as folhas e os galhos com manchas alaranjadas.",
        "Pode e abra a sombra e o mato para o ar circular e as folhas secarem mais rápido.",
        "Adube as plantas com esterco ou adubo equilibrado. Planta fraca sofre mais.",
        "Pulverize um fungicida de cobre, como hidróxido de cobre, em cima e embaixo das folhas enquanto menos de cerca de 5 por cento das folhas estiverem doentes. O cobre protege as folhas sadias, mas não cura as doentes. Pergunte ao seu extensionista qual é a hora certa.",
        "Para plantio novo, pergunte ao seu extensionista sobre variedades resistentes à ferrugem, como os tipos Catimor ou Sarchimor."
      ],
      "urgencyReason": "Ela se espalha rápido entre plantas e propriedades, e as perdas em variedades sensíveis podem chegar a 30 a 80 por cento."
    },
    "mites": {
      "name": "Possível dano de ácaros",
      "look": "A imagem lembra folhas de café marcadas como dano de ácaros. Marcas parecidas podem ter outras causas, por isso é só uma possibilidade.",
      "actions": [
        "Peça a um extensionista para olhar os dois lados da folha e confirmar a causa antes de escolher um tratamento."
      ]
    },
    "weevil": {
      "name": "Possível dano de praga que mastiga folhas",
      "look": "A folha lembra imagens marcadas como dano de coco ou de gorgulho. Esta foto não consegue dizer qual é o inseto.",
      "actions": [
        "Peça a um extensionista para olhar a folha danificada e os insetos na planta antes de escolher um tratamento."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Procure o adesivo da KEPHIS no pacote de sementes.",
    "stepScratch": "Raspe o adesivo para aparecer o código.",
    "stepText": "Envie o código por mensagem para {shortCode}. É grátis.",
    "result": "A KEPHIS responde dizendo se a semente é genuína. Um código genuíno não prova que a semente foi bem guardada.",
    "coverage": "Isto vale para semente certificada vendida em pacotes. Mudas de viveiro em geral não têm adesivo, então pergunte ao seu técnico de campo sobre elas.",
    "noContact": "Pergunte ao seu técnico de campo como conferir se um pacote de sementes é genuíno."
  },
  "phoneGreeting": "Olá, aqui é o Leaf Doctor. Eu ajudo com pés de café doentes, e o senhor ou a senhora pode falar comigo no seu idioma. O que está vendo nas folhas do seu café?"
});

export default ptText;
