// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const quText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Raphikunayki allin hina rikchakun",
    "headlineSpray": "{name}: allin raphikunata waqaychay, pichaytaq",
    "headlinePrune": "{name}: pichay, rutuytaq",
    "headlineMonitor": "{name}: qhawayta qatipay",
    "headlineAskOfficer": "{name}: chakra oficialniykita qhawananpaq mañakuy",
    "headlineNotSure": "App mana allintachu yachan. Kay raphikunata chakra oficialniykiman rikuchiy",
    "headlineMightBe": "Manaraqmi takyasqachu, ichá {name} kanman. Chakra oficialman rikuchiy",
    "headlineRetake": "Aswan raphikunamanta aswan sut'i fotokunata orqoy",
    "retakeDaylight": "P'unchaw k'anchaypi kay, mana ancha llantupi nitaq inti chiqappichu.",
    "retakeSteady": "Telefonota mana kuyuchispa hap'iy raphi sut'i rikhurinankama.",
    "retakeFillFrame": "Pantallata huk raphiwan junt'achiy.",
    "sendToOfficer": "Kay kasota cooperativaykipa chakra oficialninman SMS-wan apachiy, icha raphikunata kikin rikuchiy.",
    "rainReason": "Qayllaykipi ({source}) qhepa 7 p'unchawmanta {n} p'unchawpi paramurqan. Para pachaqa royata aswan utqaylla mast'arichin.",
    "labelRate": "Productopa etiquetanpi qillqasqa tupuyta llamk'achiy.",
    "elseBerryDisease": "Kafe muhu unquy: muhukunapi yana, ukhuman yaykuq manchakunata maskay.",
    "elseBerryBorer": "Kafe muhu t'ukuq kuru: muhukunapi huch'uy t'uqukunata maskay.",
    "elseWilt": "Kafe ch'akiy: tukuy k'allmakuna ch'akispa wañun.",
    "elseNutrition": "Mana allin allpa icha mikhuy pisi: tukuy mallki q'illuyan.",
    "smsDecisionSpray": "Decision: allin raphikunata cobrewan etiquetapi tupuywan waqaychay, pichaytaq. {days} p'unchaw qhepaman wakmanta qhaway.",
    "smsDecisionPrune": "Decision: pichay, rutuytaq. {days} p'unchaw qhepaman wakmanta qhaway.",
    "smsDecisionMonitor": "Decision: qhawayta qatipay. {days} p'unchaw qhepaman wakmanta qhaway.",
    "smsDecisionCallOfficer": "Decision: chakra oficialniykiman rikuchiy."
  },
  "diseases": {
    "cercospora": {
      "name": "Ch'umpi ñawi mancha",
      "look": "Muyu ch'umpi manchakuna, aswanpas raphipa hawanpi, chawpinpi uqi-yuraq, muyuriqninpiqa ch'umpi yana, sapa kutim q'illu muyurisqa. Manchakunaqa 5-manta 15 mm-kama anchoyoq, huñukuspam hatun wañusqa kanman. Muhukunapas ukhuman yaykuq yana manchakunata chaskin, ñawpaqtam puqunku.",
      "tellApart": "Ch'umpi ñawi manchaqa ch'aki ch'umpi muyuriqniyoq, uqi chawpiyoq, naranja polvoyuqpas mana; royaqa raphipa ukhunpi naranja polvoyuq.",
      "actions": [
        "Mallkikunata allinta mikhuchiy, aswanpas nitrogenowan potasiowan. Allin mikhuyqa sapa kutim kay unquyta kamachin.",
        "Pisi llantuta waqaychay, qura-qurata kamachiy, rutuytaq wayra yaykunanpaq raphikunapas ch'akinanpaq.",
        "Rutuyta tukuspa raphikunata muhukunatapas karunchaman apay icha ruphachiy. Mallkikunaq ladonpi ama huñuychu.",
        "Almaciguepi plantakunata sapaq sapaqta churay, ch'umpi muyurisqa manchayoq plantakunatapas ruphachiy.",
        "Sinchi kaptinqa cobre fungicidaqa allin raphikunata waqaychayta atin. Ñawpaqta extension oficialniykita tapuy."
      ],
      "urgencyReason": "Aswanta sasachasqa mallkikunata llakichin, mikhuyninpas llantunpas allinchasqa kaptinqa allinyaqmi."
    },
    "healthy": {
      "name": "Allin kafe raphi",
      "look": "Allin raphiqa llimp'iq, oval, ruphu, ch'amaq q'umir huk laya, manchayoq, polvoyoq, t'uquyoq nitaq tunelyoqpas hawapi urapipas mana.",
      "actions": [
        "Rutuy, pisi llantuta qura-qurata uchuyanchiy raphikuna usqhaylla ch'akinanpaq.",
        "Mallkikunata kuyuchisqa wanuwan icha allinchasqa abonowan mikhuchiy, aswanpas nitrogenowan potasiowan.",
        "Raphikunata uranwan sapa semana icha iskay semanapi qhaway, royata usqhaylla tarinaykipaq."
      ]
    },
    "miner": {
      "name": "Raphi ukhupi t'ukuq kuru",
      "actions": [
        "Ch'umpi manchakunata k'umuspa kawsaq kurukunata maskay, aswanpas ch'aki pachapi.",
        "Kay kurukunata mikhuq huch'uy kawsaykunata waqaychay, chaypaqmi sumaq llantuyuq kay, mana necesario fumigayta ama ruwaychu.",
        "Wiñaq mallkikunata almaciguekunatapas sumaqta qhaway, ñawpaq mancha rikhurimuptin pisichiy.",
        "Insecticida necesario kaptinqa, extension oficialniykita tapuy, ima productochus kay llaqtaykipi kamachikuywan allin hinaspa mana ñak'ariywan kasqanta."
      ],
      "urgencyReason": "Sinchi hap'iyqa raphikunata urmachin, mikhuytapas pisichin, aswanpas q'uñi ch'aki pachapi."
    },
    "phoma": {
      "name": "Phoma raphi mancha",
      "look": "Yana ch'umpimanta yanakama manchakuna, 2 cm-kama anchoyoq, machu raphikunapi, chawpin k'anchaq, ladonkunataq aswan yana. Mallkipa huch'uy k'allmaq tukukuynin yanayan ch'akin, t'ikakunapas wañunmanmi, muhukunapas urmanmi. Waqayqa raphipa tukukuyninmanta icha ladonmanta qallarinmanmi.",
      "tellApart": "Phomaqa chiri wayrayoq hatun orqokunapi huch'uy k'allmakunatapas t'ikakunatapas wañuchin, ch'umpi ñawi manchakunaqa ñawpaq hina muyuriqniyoq manchallam, k'allmakunaq tukukuyninta mana ch'akichinchu.",
      "actions": [
        "Wayra sinchi chaypi wayra harkana mallkikunata tarpuy. Wayra waqaymi hongo yaykunanpaq punkuta kichan.",
        "Ch'aki k'allmakunata ch'aki muhukunatapas rutuspa chinkachiy, wayra raphikunata ch'akichinanpaq rutuytapas.",
        "Mallkikunata allinchasqa abonowan mikhuchiy, aswanpas nitrogenowan potasiowan.",
        "Chiri wayra pachapi, unquy manaraq rikhuchkaptin cobre fungicidata ch'ujchiy. Pachanmanta extension oficialniykita tapuy."
      ],
      "urgencyReason": "Chiri wayrayoq hatun orqokunapi k'allmakunatapas t'ikakunatapas wañuchinmanmi, mikhuytapas 15-manta 43-kama por ciento pisichinmanmi."
    },
    "rust": {
      "name": "Kafe raphi roya",
      "look": "Huch'uy q'illu manchakuna raphipa hawanpi rikhurin. Ukhunpitaq sapa manchaqa q'illumanta ch'amaq naranjakama polvoyuq, makiykipi hap'ikuq. Machu manchakunaqa chawpinpi ch'umpiyan, raphikunataq ñawpaqta urmanku. Aswan sapa kutim mallkipa uran raphikunapi qallarin.",
      "tellApart": "Royaqa raphipa ukhunpi naranja polvoyuq, ch'umpi ñawi manchaqa ch'aki ch'umpi muyuriqniyoq, uqi-yuraq chawpiyoq, polvoyuqpas mana.",
      "actions": [
        "Uran raphikunapa ukhunta sapa kutilla qhaway. Ñawpaqta tariyqa aswan ancha.",
        "Naranja manchayoq raphikunata k'allmakunatapas qhaqospa ruphachiy icha p'ampay.",
        "Rutuspa llantutapas qura-qurata pisichispa wayra yaykuchun, raphikunapas usqhaylla ch'akichun.",
        "Mallkikunata kuyuchisqa wanuwan icha allinchasqa abonowan mikhuchiy. Pisi kallpayoq mallkikuna aswan sinchita ñak'arin.",
        "Cobre fungicidata, ejemplopaq copper hydroxide, raphipa hawanman ukhunmanpas ch'ujchiy, 5 por ciento pisi raphikuna unqusqa kaptin. Cobreqa allin raphikunata waqaychan, mana unqusqakunata hampinchu. Pachanmanta extension oficialniykita tapuy.",
        "Musuq tarpuypaq, royaman mana atipasqa rikch'aqkunamanta, ejemplopaq Catimor icha Sarchimor rikch'aqmanta, extension oficialniykita tapuy."
      ],
      "urgencyReason": "Mallkikuna chakrakunapa chawpinpi usqhaylla mast'arin, atipay atiq rikch'aqkunapi chinkaynin 30-manta 80-kama por ciento chayanmanmi."
    },
    "mites": {
      "name": "Ichá mite ruwasqa waqay",
      "look": "Rikch'aqqa kafe raphikunaman rikch'akun mite waqaywan señalasqa. Kay rikch'aq señalkunaqa huk ima ruwaqmanta kanmanmi, chayrayku kayqa ichá.",
      "actions": [
        "Extension oficialmanta mañakuy raphipa iskay ladonta qhawananpaq, hampinata akllanaykipaq ñawpaqta imarayku kasqanta takyachinanpaq."
      ]
    },
    "weevil": {
      "name": "Ichá raphi mikhuq kuru waqay",
      "look": "Raphiqa rikch'akun foto señalasqa kurupa waqayninman. Kay fotoqa mana yachachinmanchu ima kuruchus kasqanta.",
      "actions": [
        "Extension oficialmanta mañakuy waqasqa raphita, mallkipi kuruta qhawananpaq, hampinata akllanaykipaq ñawpaqta."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Muhu paquetepi KEPHIS stickerta maskay.",
    "stepScratch": "Stickerpa hawanta raspay codigota rikunaykipaq.",
    "stepText": "Codigota {shortCode}-man mensajepi apachiy. Mana qolqeyoq.",
    "result": "KEPHIS kutichin muhu cheqaq kasqanta. Cheqaq codigoqa mana ninchu muhuqa allin waqaychasqa kasqanta.",
    "coverage": "Kayqa paquetepi rantisqa certificado muhukunapaq llamk'an. Almaciguepi plantakunaqa aswanta mana stickeryoqchu, chayrayku chaykunamanta chakra oficialniykita tapuy.",
    "noContact": "Chakra oficialniykita tapuy muhu paquete cheqaq kasqanta imayna qhawanaykipaq."
  },
  "phoneGreeting": "Napaykullayki, ñuqaqa Leaf Doctor kani. Unqoq kafe mallkikunata yanapani, simiykipipas ñuqawan rimayta atinki. Ima rikunkitaq kafe raphikunaykipi?"
});

export default quText;
