// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const rnText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Ibibabi vyawe bisa n'ibifise ubuzima",
    "headlineSpray": "{name}: rinda ibibabi bifise ubuzima kandi usukure",
    "headlinePrune": "{name}: sukura kandi ukate",
    "headlineMonitor": "{name}: komeza ukurikirane",
    "headlineAskOfficer": "{name}: saba umukozi w'ubuhinzi wawe agenzure",
    "headlineNotSure": "Porogaramu ntiyizeye. Erekana ibi bibabi umukozi w'ubuhinzi wawe",
    "headlineMightBe": "Birashoboka ko ari {name}, ariko ntibyemejwe. Erekana umukozi w'ubuhinzi",
    "headlineRetake": "Fata amafoto yeruye y'ibibabi vyinshi",
    "retakeDaylight": "Va mu rumuri rw'umunsi, ntube mu mwijima mwinshi canke izuba ryinshi.",
    "retakeSteady": "Fata terefone idahungabana gushika ikibabi kigaragaye neza.",
    "retakeFillFrame": "Uzuza ecran n'ikibabi kimwe.",
    "sendToOfficer": "Tuma iki kibazo ku mukozi w'ubuhinzi w'ishirahamwe ryanyu mu SMS, canke werekane ibibabi imbonankubone.",
    "rainReason": "Imvura yaguye ku minsi {n} mu minsi 7 iheze hafi yawe ({source}). Ikirere gitose gituma ingese ikwira vuba.",
    "labelRate": "Koresha urugero ruri ku kimenyetso c'igicuruzwa.",
    "elseBerryDisease": "Indwara y'imbuto z'ikawa: raba imbuto urabe ahantu hirabura harenga.",
    "elseBerryBorer": "Agakoko gatobora imbuto z'ikawa: rondera imyobo mitoyi mu mbuto.",
    "elseWilt": "Gukuma kw'ikawa: amashami yose yumye agapfa.",
    "elseNutrition": "Ubutaka bubi canke kubura ifunguro: igiti cose gihindukira umuhondo.",
    "smsDecisionSpray": "Icemezo: rinda ibibabi bifise ubuzima n'umuringa ku rugero ruri ku kimenyetso kandi usukure. Ongera ugenzure mu minsi {days}.",
    "smsDecisionPrune": "Icemezo: kata kandi usukure. Ongera ugenzure mu minsi {days}.",
    "smsDecisionMonitor": "Icemezo: komeza ukurikirane. Ongera ugenzure mu minsi {days}.",
    "smsDecisionCallOfficer": "Icemezo: erekana umukozi w'ubuhinzi wawe."
  },
  "diseases": {
    "cercospora": {
      "name": "Ibibara bisa n'amaso (ibara ry'ubutaka)",
      "look": "Ibibara biziga bisa n'ubutaka, cane cane hejuru y'ikibabi, bifise hagati hera-hijimye n'uruziga rwirabura rusa n'ubutaka, kenshi bifise umuhondo bizengurutse. Ibibara bifise ubugari bwa 5 gushika 15 mm kandi birashobora kwishira hamwe bigahinduka ahapfuye hanini. Imbuto zirabona ibibara birabura bitobotse kandi zirera imburagihe.",
      "tellApart": "Ibibara bisa n'amaso bifise uruziga rwumutse rusa n'ubutaka n'ihagati hera-hijimye, nta fu ya orange, naho ingese ifise ifu ya orange munsi y'ikibabi.",
      "actions": [
        "Raga ibiti neza, cane cane n'azote na potasiyumu. Kuraga neza kenshi bigenzura iyi ndwara.",
        "Gumisha ubwugamo buke, wirinde ibivyatsi, kandi ukate kugira umuyaga ube mwinshi n'ibibabi vyume.",
        "Nyuma yo gukata, jana ibibabi n'imbuto kure canke ubitwike. Ntubirundanye ku biti.",
        "Mu bibaya vy'ingemwe, shira intera hagati y'ingemwe kandi utwike ingemwe zifise ibibara bifise uruziga.",
        "Nimba bikomeye, umuti wica ibihumyo w'umuringa urashobora kurinda ibibabi bifise ubuzima. Babaze mbere umukozi w'ubuhinzi."
      ],
      "urgencyReason": "Cane cane irananira ibiti bitaraguwe kandi ikunda gutera imbere iyo ifunguro n'ubwugamo vyakosowe."
    },
    "healthy": {
      "name": "Ikibabi c'ikawa gifise ubuzima",
      "look": "Ikibabi gifise ubuzima kirabagirana, kimeze nk'igi kandi gifise umutwe usongoye, kibisi cirabura kangana, nta bibara, ifu, imyobo canke imiyoboro hejuru canke munsi.",
      "actions": [
        "Kata kandi ugumishe ubwugamo buke n'ibivyatsi bike kugira ibibabi vyume vuba.",
        "Raga ibiti ifumbire y'amase canke ifumbire iringaniye, cane cane azote na potasiyumu.",
        "Genzura ibibabi n'ibiri munsi yavyo buri cumweru canke buri nyuma y'ibiri kugira ubone ingese hakiri kare."
      ]
    },
    "miner": {
      "name": "Agakoko gacukura mu kibabi c'ikawa",
      "actions": [
        "Hetaguza ahari ibara ry'ubutaka urondere ibikoko bikiri bizima, cane cane mu gihe c'impeshi.",
        "Rinda abansi kamere nk'inzuki ntoya n'ibimonyo ugumisha ubwugamo buvanze kandi wirinde gutera imiti idakenewe.",
        "Kurikirana ibiti bikiri bito n'ibibaya vy'ingemwe cane, uvaneho ahabanza hakiri kare.",
        "Nimba umuti wica udukoko ukenewe, baza umukozi w'ubuhinzi uwemewe n'uwizewe mu gihugu cawe."
      ],
      "urgencyReason": "Ugucumurwa gukomeye gutuma ibibabi bigwa n'umwero ukagabanuka, vyane mu gihe c'impeshi n'ubushuhe."
    },
    "phoma": {
      "name": "Ibibara vy'ikibabi vya Phoma",
      "look": "Ibibara by'ubutaka bwirabura gushika ku birabura bifise ubugari bugera kuri 2 cm ku bibabi bishaje, bifise hagati hera n'impande zirabura cane. Imitwe y'amashami mato ihinduka umukara kandi ikuma, indabyo zirashobora gupfa, kandi imbuto zirahonoka. Ibyononekaye birashobora gutangura ku mutwe canke ku nkengero z'ikibabi.",
      "tellApart": "Phoma kandi yica imitwe y'amashami mato n'indabyo mu misozi ikonje kandi irimwo umuyaga, naho ibibara bisa n'amaso birama ari uruziga kandi ntibikumya imitwe y'amashami.",
      "actions": [
        "Tera ibiti bikingira umuyaga mu turere dufise umuyaga mwinshi. Ibyononekaye biterwa n'umuyaga bituma igihumyo cinjira.",
        "Kata utwike amashami yumye n'imbuto zumye, kandi ukate kugira umuyaga wumishe ibibabi.",
        "Raga ibiti ifumbire iringaniye, cane cane azote na potasiyumu.",
        "Mu bihe bikonje birimwo umuyaga, tera umuti w'umuringa wica ibihumyo indwara itaraboneka. Baza umukozi w'ubuhinzi igihe."
      ],
      "urgencyReason": "Mu misozi ikonje irimwo umuyaga irashobora kwica amashami n'indabyo ikagabanya umwero kuva kuri 15 gushika kuri 43 ku ijana."
    },
    "rust": {
      "name": "Ingese y'ikibabi c'ikawa",
      "look": "Ibibara bitoyi bifise umuhondo ucisha bigaragara hejuru y'ikibabi. Munsi, buri kibara gifise ahari ifu y'umuhondo gushika orange yijimye ifata ku rutoki. Ibibara bishaje bihinduka ibara ry'ubutaka hagati kandi ibibabi bigwa imburagihe. Kenshi itangura ku bibabi biri hasi y'igiti.",
      "tellApart": "Ingese ifise ifu ya orange munsi y'ikibabi, naho ibibara bisa n'amaso bifise uruziga rwumutse rusa n'ubutaka n'ihagati hera-hijimye kandi nta fu.",
      "actions": [
        "Genzura munsi y'ibibabi vyo hasi kenshi. Kuyibona hakiri kare ni vyo vyihutirwa.",
        "Sasura utwike canke uhambe ibibabi n'amashami bifise ibibara bya orange.",
        "Kata kandi ugabanye ubwugamo n'ibivyatsi kugira umuyaga ube mwinshi n'ibibabi vyume vuba.",
        "Raga ibiti ifumbire y'amase canke ifumbire iringaniye. Ibiti bidakomeye birakubitwa cane.",
        "Tera umuti wica ibihumyo w'umuringa nka copper hydroxide hejuru no munsi y'ibibabi igihe ibibabi birwaye bikiri munsi ya 5 ku ijana. Umuringa urinda ibibabi bifise ubuzima ariko ntuvura ibirwaye. Baza umukozi w'ubuhinzi igihe.",
        "Ku gutera gushasha, baza umukozi w'ubuhinzi ubwoko bwihanganira ingese nka Catimor canke Sarchimor."
      ],
      "urgencyReason": "Ikwira vuba hagati y'ibiti n'imirima, kandi igihombo ku bwoko butihanganira kirashobora gushika kuri 30 gushika kuri 80 ku ijana."
    },
    "mites": {
      "name": "Ibyononekaye bishoboka bya mite",
      "look": "Ifoto isa n'ibibabi vy'ikawa vyanditswe ko vyononwe na mite. Ibimenyetso bisa birashobora kugira izindi mpamvu, ni co gituma ari ugusa gushoboka.",
      "actions": [
        "Saba umukozi w'ubuhinzi agenzure impande zombi z'ikibabi yemeze impamvu imbere yo guhitamwo ubuvuzi."
      ]
    },
    "weevil": {
      "name": "Ibyononekaye bishoboka biterwa n'udukoko turya ibibabi",
      "look": "Ikibabi gisa n'amafoto yanditswe ko yononwe n'udukoko. Iyi foto ntishobora kumenya ubwoko bw'agakoko.",
      "actions": [
        "Saba umukozi w'ubuhinzi agenzure ikibabi cononekaye n'udukoko tuboneka ku gihingwa imbere yo guhitamwo ubuvuzi."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Rondera agatike ka KEPHIS ku paki y'imbuto.",
    "stepScratch": "Kuraho igisate gitwikiriye ikode ku gatike kugira ikode igaragare.",
    "stepText": "Tuma ikode kuri {shortCode}. Ni ubuntu.",
    "result": "KEPHIS irasubiza ivuga ko imbuto ari iz'ukuri. Ikode y'ukuri ntisobanura ko imbuto zabitswe neza.",
    "coverage": "Ibi bikora ku mbuto zemejwe zigurishwa mu mapaki. Ingemwe zo mu bibaya ntizisanzwe zifise agatike, ni co gituma ubaza umukozi w'ubuhinzi wawe.",
    "noContact": "Baza umukozi w'ubuhinzi wawe uko wokwemeza ko ipaki y'imbuto ari iy'ukuri."
  },
  "phoneGreeting": "Mwaramutse, ndi Leaf Doctor. Mfasha ibihingwa vy'ikawa birwaye, kandi mushobora kuvugana nanje mu rurimi rwanyu. Murabona iki ku bibabi vy'ikawa vyanyu?"
});

export default rnText;
