// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const roText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Frunzele dvs. arată sănătos",
    "headlineSpray": "{name}: protejați frunzele sănătoase și curățați",
    "headlinePrune": "{name}: curățați și tăiați",
    "headlineMonitor": "{name}: continuați să urmăriți",
    "headlineAskOfficer": "{name}: rugați agentul de teren să verifice",
    "headlineNotSure": "Aplicația nu este sigură. Arătați aceste frunze agentului de teren",
    "headlineMightBe": "Ar putea fi {name}, dar nu este confirmat. Arătați unui agent de teren",
    "headlineRetake": "Faceți poze mai clare la mai multe frunze",
    "retakeDaylight": "Mergeți la lumina zilei, nu la umbră deasă și nici la soare direct.",
    "retakeSteady": "Țineți telefonul nemișcat până când frunza se vede clar.",
    "retakeFillFrame": "Umpleți cadrul cu o singură frunză.",
    "sendToOfficer": "Trimiteți acest caz prin SMS agentului de teren din cooperativa dvs. sau arătați frunzele personal.",
    "rainReason": "A plouat în {n} din ultimele 7 zile lângă dvs. ({source}). Vremea umedă face rugina să se răspândească mai repede.",
    "labelRate": "Folosiți doza de pe eticheta produsului.",
    "elseBerryDisease": "Boala fructelor de cafea: căutați pe fructe pete întunecate și adâncite.",
    "elseBerryBorer": "Găunarul fructelor de cafea: căutați găuri mici în fructe.",
    "elseWilt": "Ofilirea cafeului: ramuri întregi se ofilesc și mor.",
    "elseNutrition": "Sol sărac sau hrană slabă: îngălbenire pe tot pomul.",
    "smsDecisionSpray": "Decizie: protejați frunzele sănătoase cu cupru la doza de pe etichetă și curățați. Verificați din nou peste {days} zile.",
    "smsDecisionPrune": "Decizie: tăiați și curățați. Verificați din nou peste {days} zile.",
    "smsDecisionMonitor": "Decizie: continuați să urmăriți. Verificați din nou peste {days} zile.",
    "smsDecisionCallOfficer": "Decizie: arătați agentului dvs. de teren."
  },
  "diseases": {
    "cercospora": {
      "name": "Pata brună ca un ochi",
      "look": "Pete rotunde brune, mai ales pe partea de sus a frunzei, cu centrul gri-alb și un inel brun-închis, adesea cu o aureolă galbenă. Petele au 5 până la 15 mm lățime și se pot uni în zone mari moarte. Fructele au pete întunecate și adâncite și se coc prea devreme.",
      "tellApart": "Pata brună ca un ochi are inele brune uscate cu centrul gri-deschis și nu are praf portocaliu, în timp ce rugina are praf portocaliu pe dedesubt.",
      "actions": [
        "Hrăniți bine pomii, mai ales cu azot și potasiu. O hrănire bună oprește adesea această boală.",
        "Păstrați umbră ușoară, controlați buruienile și tăiați pomii ca să circule aerul și frunzele să se usuce.",
        "După tăiere, duceți sau ardeți frunzele și fructele. Nu le lăsați grămadă lângă pomi.",
        "În pepinieră, lăsați spațiu între răsaduri și ardeți răsadurile cu pete brune cu inele.",
        "Dacă boala este gravă, un fungicid cu cupru poate proteja frunzele sănătoase. Întrebați mai întâi agentul dvs. de extensie."
      ],
      "urgencyReason": "Slăbește mai ales pomii stresați și de obicei se ameliorează după ce hrănirea și umbra sunt îndreptate."
    },
    "healthy": {
      "name": "Frunză de cafea sănătoasă",
      "look": "O frunză sănătoasă este lucioasă, ovală și ascuțită, de un verde-închis uniform, fără pete, praf, găuri sau galerii deasupra sau dedesubt.",
      "actions": [
        "Tăiați pomii și păstrați umbră ușoară și puține buruieni, ca frunzele să se usuce repede.",
        "Hrăniți pomii cu gunoi de grajd sau îngrășământ echilibrat, mai ales cu azot și potasiu.",
        "Verificați frunzele și partea lor de jos o dată la una sau două săptămâni, ca să prindeți devreme rugina sau minierul frunzelor."
      ]
    },
    "miner": {
      "name": "Minierul frunzelor de cafea",
      "look": "În frunză apar urme galben-pal șerpuite, care devin pete moarte brune neregulate deasupra. Dacă îndoiți frunza, pielea subțire de deasupra petei se desprinde și înăuntru puteți găsi o larvă mică, transparentă. Atacurile puternice fac frunzele să cadă.",
      "tellApart": "Petele de miner sunt băsici subțiri ca hârtia, cu o larvă înăuntru, care se desprind când sunt îndoite, în timp ce pata brună ca un ochi este un inel rotund regulat care nu se desprinde.",
      "actions": [
        "Îndoiți petele brune ca să căutați larve vii, mai ales în sezonul uscat.",
        "Protejați dușmanii naturali, precum viespile mici și furnicile, păstrând umbră amestecată și evitând stropirile inutile.",
        "Urmăriți cu atenție pomii tineri și pepinierele și îndepărtați devreme primele pete.",
        "Dacă este nevoie de insecticid, întrebați agentul dvs. de extensie ce produs este permis și sigur în țara dvs."
      ],
      "urgencyReason": "Atacurile puternice duc la căderea frunzelor și la recolte mai mici, mai ales în perioadele uscate și fierbinți."
    },
    "phoma": {
      "name": "Pata frunzelor cauzată de Phoma",
      "look": "Pete brun-închis până la negre, late până la 2 cm, pe frunzele mai vechi, cu centrul mai deschis și marginea mai închisă. Vârfurile lăstarilor tineri se înnegresc și se usucă, florile pot muri, iar fructele cad. Stricăciunea poate începe de la vârful sau marginea frunzei.",
      "tellApart": "Phoma ucide și vârfurile lăstarilor tineri și florile în zonele înalte, reci și bătute de vânt, în timp ce pata brună ca un ochi rămâne doar pete cu inele și nu usucă vârfurile lăstarilor.",
      "actions": [
        "Plantați perdele de protecție împotriva vântului în zonele bătute de vânt. Rănile făcute de vânt lasă ciuperca să intre.",
        "Tăiați și distrugeți lăstarii uscați și fructele mumificate și tăiați pomii ca aerul să usuce frunzele.",
        "Hrăniți pomii cu îngrășământ echilibrat, mai ales cu azot și potasiu.",
        "În sezoanele reci și cu vânt, stropiți un fungicid cu cupru înainte să apară boala. Întrebați agentul dvs. de extensie când."
      ],
      "urgencyReason": "În zonele înalte, reci și cu vânt poate ucide lăstarii și florile și poate reduce recolta cu 15 până la 43 la sută."
    },
    "rust": {
      "name": "Rugina frunzelor de cafea",
      "look": "Pe partea de sus a frunzei apar pete mici galben-pal. Dedesubt, fiecare pată are un strat de praf galben până la portocaliu-închis, care se șterge pe deget. Petele vechi devin brune la mijloc și frunzele cad devreme. De obicei începe pe frunzele de jos ale pomului.",
      "tellApart": "Rugina are praf portocaliu pe partea de jos a frunzei, în timp ce pata brună ca un ochi are inele brune uscate cu centrul gri-alb și fără praf.",
      "actions": [
        "Verificați des partea de jos a frunzelor de jos. Cel mai important este să prindeți boala devreme.",
        "Culegeți și ardeți sau îngropați frunzele și ramurile cu pete portocalii.",
        "Tăiați și rărițiți umbra și buruienile ca aerul să circule și frunzele să se usuce mai repede.",
        "Hrăniți pomii cu gunoi de grajd sau îngrășământ echilibrat. Pomii slabi sunt loviți mai tare.",
        "Stropiți un fungicid cu cupru, de exemplu hidroxid de cupru, pe partea de sus și de jos a frunzelor cât timp sunt bolnave sub aproximativ 5 la sută din frunze. Cuprul protejează frunzele sănătoase, dar nu le vindecă pe cele bolnave. Întrebați agentul dvs. de extensie când.",
        "Pentru plantări noi, întrebați agentul dvs. de extensie despre soiuri rezistente la rugină, cum sunt tipurile Catimor sau Sarchimor."
      ],
      "urgencyReason": "Se răspândește repede între pomi și ferme, iar pierderile la soiurile sensibile pot ajunge la 30 până la 80 la sută."
    },
    "mites": {
      "name": "Posibile stricăciuni de la acarieni",
      "look": "Imaginea seamănă cu frunze de cafea marcate ca fiind stricate de acarieni. Semne asemănătoare pot avea alte cauze, deci este doar o posibilă potrivire.",
      "actions": [
        "Rugați un agent de extensie să se uite pe ambele fețe ale frunzei și să confirme cauza înainte de a alege un tratament."
      ]
    },
    "weevil": {
      "name": "Posibile stricăciuni de la un dăunător care roade frunzele",
      "look": "Frunza seamănă cu imagini marcate ca stricăciuni de coco sau de gărgăriță. Această poză nu poate spune ce insectă este.",
      "actions": [
        "Rugați un agent de extensie să se uite la frunza stricată și la insectele de pe plantă înainte de a alege un tratament."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Găsiți autocolantul KEPHIS pe pachetul cu semințe.",
    "stepScratch": "Răzuiți autocolantul ca să se vadă codul.",
    "stepText": "Trimiteți codul prin mesaj la {shortCode}. Este gratuit.",
    "result": "KEPHIS răspunde dacă semințele sunt autentice. Un cod autentic nu dovedește că semințele au fost bine păstrate.",
    "coverage": "Merge pentru semințe certificate vândute în pachete. Răsadurile din pepinieră de obicei nu au autocolant, deci întrebați agentul de teren despre ele.",
    "noContact": "Întrebați agentul dvs. de teren cum puteți verifica dacă un pachet de semințe este autentic."
  },
  "phoneGreeting": "Bună ziua, sunt Leaf Doctor. Ajut cu plantele de cafea bolnave și puteți vorbi cu mine în limba dvs. Ce vedeți pe frunzele de cafea?"
});

export default roText;
