// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const skText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Vaše listy vyzerajú zdravo",
    "headlineSpray": "{name}: chráňte zdravé listy a upracte",
    "headlinePrune": "{name}: upracte a orežte",
    "headlineMonitor": "{name}: ďalej sledujte",
    "headlineAskOfficer": "{name}: požiadajte svojho poradcu, aby to skontroloval",
    "headlineNotSure": "Aplikácia si nie je istá. Ukážte tieto listy svojmu poradcovi",
    "headlineMightBe": "Môže to byť {name}, ale nie je to potvrdené. Ukážte to poradcovi",
    "headlineRetake": "Odfoťte jasnejšie fotky viacerých listov",
    "retakeDaylight": "Presuňte sa na denné svetlo, nie do hlbokého tieňa ani na priame slnko.",
    "retakeSteady": "Držte telefón pokojne, kým list nebude ostrý.",
    "retakeFillFrame": "Vyplňte záber jedným listom.",
    "sendToOfficer": "Pošlite tento prípad SMS poradcovi vášho družstva alebo mu listy ukážte osobne.",
    "rainReason": "V okolí pršalo {n} z posledných 7 dní ({source}). Vlhké počasie urýchľuje šírenie hrdze.",
    "labelRate": "Použite dávku uvedenú na štítku výrobku.",
    "elseBerryDisease": "Choroba kávových bobúľ: pozrite, či majú bobule tmavé preliačené škvrny.",
    "elseBerryBorer": "Kávovníkový podkôrnik bobúľ: hľadajte malé dierky v bobuliach.",
    "elseWilt": "Vädnutie kávovníka: vädnú a odumierajú celé vetvy.",
    "elseNutrition": "Chudobná pôda alebo nedostatok živín: žltnutie celého stromu.",
    "smsDecisionSpray": "Rozhodnutie: chrániť zdravé listy meďou v dávke podľa štítku a upratať. Skontrolovať znova o {days} dní.",
    "smsDecisionPrune": "Rozhodnutie: orezať a upratať. Skontrolovať znova o {days} dní.",
    "smsDecisionMonitor": "Rozhodnutie: ďalej sledovať. Skontrolovať znova o {days} dní.",
    "smsDecisionCallOfficer": "Rozhodnutie: ukázať listy svojmu poradcovi."
  },
  "diseases": {
    "cercospora": {
      "name": "Hnedá okatá škvrnitosť",
      "look": "Okrúhle hnedé škvrny, najmä na vrchnej strane listu, so sivobielym stredom a tmavohnedým kruhom, často so žltým lemom. Škvrny sú široké 5 až 15 mm a môžu sa spojiť do veľkých odumretých plôch. Na bobuliach sú tmavé preliačené škvrny a dozrievajú príliš skoro.",
      "tellApart": "Hnedá okatá škvrnitosť má suché hnedé kruhy s bledosivým stredom a žiadny oranžový prášok, kým hrdza má oranžový prášok na spodnej strane.",
      "actions": [
        "Dobre stromy hnojte, najmä dusíkom a draslíkom. Dobré hnojenie často túto chorobu zvládne.",
        "Nechajte ľahký tieň, ničte buriny a stromy orežte tak, aby sa vzduch hýbal a listy schli.",
        "Po rezaní odneste alebo spáľte listy a bobule. Nehádžte ich na kopu pri stromoch.",
        "V škôlke dajte sadenice od seba a spáľte sadenice s hnedými kruhovými škvrnami.",
        "Ak je to zlé, medený fungicíd môže chrániť zdravé listy. Najprv sa opýtajte svojho poradcu."
      ],
      "urgencyReason": "Oslabuje hlavne stromy v strese a zvyčajne sa zlepší, keď sa opraví hnojenie a tieň."
    },
    "healthy": {
      "name": "Zdravý kávový list",
      "look": "Zdravý list je lesklý, vajcovitý a špicatý, rovnomerne tmavozelený, bez škvŕn, prášku, dier alebo chodbičiek na vrchnej aj spodnej strane.",
      "actions": [
        "Orežte stromy a udržiavajte ľahký tieň a málo burín, aby listy rýchlo schli.",
        "Hnojte stromy maštaľným hnojom alebo vyváženým hnojivom, najmä dusíkom a draslíkom.",
        "Každý týždeň alebo dva skontrolujte listy a ich spodnú stranu, aby ste včas zachytili hrdzu alebo listovníka."
      ]
    },
    "miner": {
      "name": "Listovník kávovníkový",
      "look": "Vo vnútri listu sa objavia bledožlté kľukaté chodbičky, ktoré sa na vrchnej strane menia na nerovnomerné hnedé odumreté plochy. Keď list ohnete, tenká vrchná kožička nad škvrnou sa odlúpne a vo vnútri nájdete drobnú priehľadnú larvu. Silný útok spôsobí opad listov.",
      "tellApart": "Škvrny od listovníka sú papierové pľuzgiere s larvou vo vnútri, ktoré sa pri ohnutí odlúpnu, kým hnedá okatá škvrnitosť je úhľadný okrúhly kruh, ktorý sa neodlupuje.",
      "actions": [
        "Ohýbajte hnedé škvrny a hľadajte živé larvy, najmä v období sucha.",
        "Chráňte prirodzených nepriateľov, ako sú malé osy a mravce, tým, že udržíte zmiešaný tieň a nebudete zbytočne striekať.",
        "Pozorne sledujte mladé stromy a škôlky a prvé škvrny včas odstráňte.",
        "Ak treba insekticíd, opýtajte sa svojho poradcu, ktorý výrobok je vo vašej krajine zákonný a bezpečný."
      ],
      "urgencyReason": "Silný útok spôsobí opad listov a nižšiu úrodu, najhoršie počas suchých horúcich období."
    },
    "phoma": {
      "name": "Škvrnitosť listov Phoma",
      "look": "Tmavohnedé až čierne škvrny široké do 2 cm na starších listoch, so svetlejším stredom a tmavším okrajom. Konce mladých výhonkov očiernejú a vyschnú, kvety môžu odumrieť a bobule opadávajú. Poškodenie môže začať na špičke alebo okraji listu.",
      "tellApart": "Phoma zabíja aj konce mladých výhonkov a kvety v studených veterných vysočinách, kým hnedá okatá škvrnitosť ostáva pri kruhových škvrnách a konce výhonkov nevysúša.",
      "actions": [
        "Vo veterných oblastiach vysaďte vetrolamy. Poškodenie vetrom pustí huby dnu.",
        "Odrežte a zničte vyschnuté výhonky a zmumifikované bobule a orežte stromy tak, aby vzduch sušil listy.",
        "Hnojte stromy vyváženým hnojivom, najmä dusíkom a draslíkom.",
        "V studených veterných obdobiach nastriekajte medený fungicíd skôr, ako sa choroba objaví. Opýtajte sa svojho poradcu na správny čas."
      ],
      "urgencyReason": "V studených veterných vysočinách môže zabiť výhonky a kvety a znížiť úrodu o 15 až 43 percent."
    },
    "rust": {
      "name": "Hrdza kávovníka",
      "look": "Na vrchnej strane listu sa objavia malé bledožlté škvrny. Na spodnej strane má každá škvrna kôpku žltého až tmavooranžového prášku, ktorý sa stiera na prste. Staré škvrny v strede zhnednú a listy predčasne opadnú. Zvyčajne to začína na spodných listoch stromu.",
      "tellApart": "Hrdza má oranžový prášok na spodnej strane listu, kým hnedá okatá škvrnitosť má suché hnedé kruhy so sivobielym stredom a žiadny prášok.",
      "actions": [
        "Často kontrolujte spodnú stranu spodných listov. Najdôležitejšie je zachytiť to včas.",
        "Oberte a spáľte alebo zahrabte listy a vetvy s oranžovými škvrnami.",
        "Orežte a presvetlite tieň a buriny, aby sa vzduch hýbal a listy schli rýchlejšie.",
        "Hnojte stromy maštaľným hnojom alebo vyváženým hnojivom. Slabé stromy chorobu zasiahne tvrdšie.",
        "Nastriekajte medený fungicíd, napríklad hydroxid meďnatý, na vrchnú aj spodnú stranu listov, kým je choré menej než 5 percent listov. Meď chráni zdravé listy, ale chorých nevylieči. Opýtajte sa svojho poradcu na správny čas.",
        "Pri novej výsadbe sa opýtajte svojho poradcu na odrody odolné voči hrdzi, napríklad typy Catimor alebo Sarchimor."
      ],
      "urgencyReason": "Šíri sa rýchlo medzi stromami a farmami a straty na náchylných odrodách môžu dosiahnuť 30 až 80 percent."
    },
    "mites": {
      "name": "Možné poškodenie roztočmi",
      "look": "Obrázok sa podobá na kávové listy označené ako poškodené roztočmi. Podobné znaky môžu mať iné príčiny, takže ide len o možnú zhodu.",
      "actions": [
        "Požiadajte poradcu, aby skontroloval obe strany listu a potvrdil príčinu skôr, ako vyberiete liečbu."
      ]
    },
    "weevil": {
      "name": "Možné poškodenie škodcom, ktorý hryzie listy",
      "look": "List sa podobá na obrázky označené ako poškodenie coco alebo nosánikom. Z tejto fotky sa nedá určiť druh hmyzu.",
      "actions": [
        "Požiadajte poradcu, aby skontroloval poškodený list a hmyz na rastline skôr, ako vyberiete liečbu."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Nájdite nálepku KEPHIS na balení semien.",
    "stepScratch": "Zotrite nálepku, aby sa ukázal kód.",
    "stepText": "Pošlite kód SMS na {shortCode}. Je to zadarmo.",
    "result": "KEPHIS odpovie, či je semeno pravé. Pravý kód nedokazuje, že semeno bolo dobre uskladnené.",
    "coverage": "Platí to pre certifikované semená predávané v baleniach. Sadenice zo škôlky zvyčajne nemajú nálepku, preto sa na ne opýtajte svojho poradcu.",
    "noContact": "Opýtajte sa svojho poradcu, ako skontrolovať, či je balenie semien pravé."
  },
  "phoneGreeting": "Dobrý deň, tu je Leaf Doctor. Pomáham pri chorých kávovníkoch a môžete so mnou hovoriť vo svojom jazyku. Čo vidíte na listoch svojich kávovníkov?"
});

export default skText;
