// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const snText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Makukwe enyu anoita akanaka",
    "headlineSpray": "{name}: dzivirirai makukwe akanaka uye mubvise zvakaipa",
    "headlinePrune": "{name}: bvisai zvakaipa uye mucheke matavi",
    "headlineMonitor": "{name}: enderera mberi uchitarisa",
    "headlineAskOfficer": "{name}: kumbirai mukuru wenyu wemunda kuti atarise",
    "headlineNotSure": "App haina chokwadi. Ratidzai makukwe aya mukuru wenyu wemunda",
    "headlineMightBe": "Zvingava {name}, asi hazvisati zvasimbiswa. Ratidzai mukuru wemunda",
    "headlineRetake": "Torai mifananidzo yakajeka yemakukwe akawanda",
    "retakeDaylight": "Enda muchiedza chemasikati, kwete mumumvuri wakakora kana zuva rakananga.",
    "retakeSteady": "Bata foni yakagara kudzamara rukukwe rwajeka.",
    "retakeFillFrame": "Dzadza firimu norukukwe rumwe.",
    "sendToOfficer": "Tumirai nyaya iyi neSMS kumukuru wemunda wekambani yenyu yekubatana, kana kuratidza makukwe pachiso.",
    "rainReason": "Mvura yanaya mazuva {n} pamazuva 7 apfuura padhuze nemi ({source}). Mamiriro ekunyorova anokonzera kuti ngura ipararire nokukurumidza.",
    "labelRate": "Shandisai huwandu hwakanyorwa palabel yechigadzirwa.",
    "elseBerryDisease": "Chirwere chembeu dzekofi: tarisai mbeu dzine mavanga matema akadzika.",
    "elseBerryBorer": "Chipuka chinopinda mumbeu dzekofi: tsvagai maburi madiki mumbeu.",
    "elseWilt": "Kuvhunduka kwekofi: matavi ose anovhunduka uye anofa.",
    "elseNutrition": "Ivhu rakashata kana kushaiwa kwezvokudya: kutsvukira mumuti wose.",
    "smsDecisionSpray": "Sarudzo: dzivirirai makukwe akanaka necopper huwandu hwelabel uye mubvise zvakaipa. Tarisazve mumazuva {days}.",
    "smsDecisionPrune": "Sarudzo: chekai matavi uye mubvise zvakaipa. Tarisazve mumazuva {days}.",
    "smsDecisionMonitor": "Sarudzo: enderera mberi uchitarisa. Tarisazve mumazuva {days}.",
    "smsDecisionCallOfficer": "Sarudzo: ratidzai mukuru wenyu wemunda."
  },
  "diseases": {
    "cercospora": {
      "name": "Vanga dzvuku-dzvuku rakaita seziso",
      "look": "Mavanga akatenderera dzvuku-dzvuku, kunyanya pamusoro perukukwe, ane pakati pakatsvukira-chena uye denderedzwa dzvuku-dzvuku rakasviba, kazhinji nedenderedzwa rizvuvu. Mavanga ari 5 kusvika 15 mm upamhi uye anogona kubatana ogadzira zvikamu zvikuru zvakafa. Mbeu dzinoita mavanga matema akadzika uye dzinibva nguva isati yakwana.",
      "tellApart": "Vanga dzvuku-dzvuku rakaita seziso rine madenderedzwa akaoma dzvuku-dzvuku ane pakati pakatsvukira uye harina upfu hwakatsvukira-orenji, asi ngura ine upfu hwakatsvukira-orenji pasi.",
      "actions": [
        "Dyisai miti zvakanaka, kunyanya nitrogen ne potassium. Kudya kwakanaka kazhinji kunodzora chirwere ichi.",
        "Chengetai mumvuri wakareruka, dzorai marara, uye chekai matavi kuti mhepo ifambe uye makukwe aome.",
        "Mushure mekucheka matavi, tsikirai kana kupisa makukwe nembeu. Musazvirunda pedyo nemiti.",
        "Munzvimbo yemiche, dyarai michero pakaparadzana uye mupise michero ine mavanga dzvuku-dzvuku ane madenderedzwa.",
        "Kana zvakaipa zvikuru, mushonga wecopper wekuuraya fungi unogona kudzivirira makukwe akanaka. Bvunzai mukuru wenyu wekuridzira kutanga."
      ],
      "urgencyReason": "Kunyanya chinoita kuti miti inenge yatambudzika isimbe uye kazhinji chinovandudzika kana kudya nemumvuri zvagadziriswa."
    },
    "healthy": {
      "name": "Rukukwe rwekofi rwakanaka",
      "look": "Rukukwe rwakanaka runopenya, rwakatenderera sezai uye rune pamucheto unorema, rune girini rakasviba rakaenzana, pasina mavanga, upfu, maburi kana mawere pamusoro kana pasi.",
      "actions": [
        "Chekai matavi uye muchengete mumvuri wakareruka nemarara mashoma kuti makukwe aome nokukurumidza.",
        "Dyisai miti nemadhodhi kana fetiraiza yakaenzana, kunyanya nitrogen ne potassium.",
        "Tarisai makukwe nepasi pawo vhiki rega rega kana mavhiki maviri kuti mubate ngura kana chipuka chinoruma makukwe nokukurumidza."
      ]
    },
    "miner": {
      "name": "Chipuka chinoruma makukwe ekofi",
      "look": "Mapazi akatsvukira-yero akakombama anooneka mukati merukukwe uye anoita mavanga akafa dzvuku-dzvuku asina kuenzana pamusoro. Kana ukakombamisa rukukwe, ganda rakaonda riri pamusoro pevanga rinoparuka uye mukati unogona kuwana mbozha diki inoonekwa kuburikidza. Kurwiswa kukuru kunoita kuti makukwe awire.",
      "tellApart": "Mavanga echipuka chinoruma makukwe akaita seburu repepa rine mbozha mukati uye anoparuka kana akakombamiswa, asi vanga dzvuku-dzvuku rakaita seziso idenderedzwa rakarongeka risingaparuki.",
      "actions": [
        "Kombamisai mavanga dzvuku-dzvuku kuti mutsvage mbozha dzipenyu, kunyanya mumwaka wakaoma.",
        "Chengetai vavengi vechisikirwo vakaita sezvipembenene zvidiki nembhesvu nokuchengeta mumvuri wakasanganiswa uye nokudzivisa kupfapfaidza kusingakoshi.",
        "Tarisai nokungwarira miti michena nemiche uye mubvise mavanga ekutanga nokukurumidza.",
        "Kana mushonga wezvipembenene uchidikanwa, bvunzai mukuru wenyu wekuridzira kuti chigadzirwa chipi chinobvumirwa uye chakachengeteka munyika yenyu."
      ],
      "urgencyReason": "Kurwiswa kukuru kunokonzera kuwa kwemakukwe uye kuderera kwemukobvu, kwakanyanya kuipa munguva dzakaoma nedzinopisa."
    },
    "phoma": {
      "name": "Vanga rerukukwe rePhoma",
      "look": "Mavanga dzvuku-dzvuku akasviba kusvika matema ane upamhi hwakasvika 2 cm pamakukwe akura, ane pakati pakareruka nemucheto wakasviba. Matiritiri emiti michena anosvibira uye anoomarara, maruva anogona kufa, uye mbeu dzinowira. Kukuvara kunogona kutanga pamucheto kana padivi perukukwe.",
      "tellApart": "Phoma inouraya zvakare matiritiri emiti michena nemaruva munzvimbo dzakakwirira dzine mhepo nechando, asi vanga dzvuku-dzvuku rakaita seziso rinongoramba riri mavanga ane madenderedzwa uye harioomesi matiritiri emiti.",
      "actions": [
        "Dyarai miti inodzivirira mhepo munzvimbo dzine mhepo. Kukuvara kwemhepo kunoita kuti fungi ipinde.",
        "Chekai uye muparadze matavi akaoma nembeu dzakaoma, uye chekai matavi kuti mhepo igone kuomesa makukwe.",
        "Dyisai miti nefetiraiza yakaenzana, kunyanya nitrogen ne potassium.",
        "Mumwaka une chando nemhepo, pfapfaidzai mushonga wecopper wekuuraya fungi chirwere chisati chaonekwa. Bvunzai mukuru wenyu wekuridzira nezvenguva."
      ],
      "urgencyReason": "Munzvimbo dzakakwirira dzine chando nemhepo, inogona kuuraya matavi nemaruva uye kudzikisa mukobvu ne15 kusvika 43 muzana."
    },
    "rust": {
      "name": "Ngura yemakukwe ekofi",
      "look": "Mavanga madiki akatsvukira-yero anooneka pamusoro perukukwe. Pasi, vanga rega rega rine upfu hwakatsvukira-yero kusvika orenji rakasviba hunoramba pachigunwe. Mavanga ekare anova dzvuku-dzvuku pakati uye makukwe anowira nguva isati yakwana. Kazhinji inotanga pamakukwe epasi emuti.",
      "tellApart": "Ngura ine upfu hwakatsvukira-orenji pasi perukukwe, asi vanga dzvuku-dzvuku rakaita seziso rine madenderedzwa akaoma dzvuku-dzvuku ane pakati pakatsvukira-chena uye harina upfu.",
      "actions": [
        "Tarisai kazhinji pasi pemakukwe epasi. Kubata nokukurumidza ndiko kwakakosha kwazvo.",
        "Pambai uye mupise kana kuviga makukwe nematavi ane mavanga orenji.",
        "Chekai matavi uye mudzikise mumvuri nemarara kuti mhepo ifambe uye makukwe aome nokukurumidza.",
        "Dyisai miti nemadhodhi kana fetiraiza yakaenzana. Miti isina simba inorwiswa zvikuru.",
        "Pfapfaidzai mushonga wecopper wekuuraya fungi wakaita secopper hydroxide pamusoro nepasi pemakukwe kana makukwe asingasviki 5 muzana ari kurwara. Copper inodzivirira makukwe akanaka asi haiporesi akarwara. Bvunzai mukuru wenyu wekuridzira nezvenguva.",
        "Pakudyara kutsva, bvunzai mukuru wenyu wekuridzira nezvemhando dzinomira ngura dzakaita seCatimor kana Sarchimor."
      ],
      "urgencyReason": "Inopararira nokukurumidza pakati pemiti nemapurazi, uye kurasikirwa pamhando dzinorwara nyore kunogona kusvika 30 kusvika 80 muzana."
    },
    "mites": {
      "name": "Kukuvara kunogona kuva kwemite",
      "look": "Mufananidzo unoita semakukwe ekofi akanzi akukuvadzwa nemite. Zviratidzo zvakafanana zvinogona kuva nezvimwe zvinokonzera, saka uku kungova kufanana kunogona.",
      "actions": [
        "Kumbirai mukuru wekuridzira kuti atarise mativi ose maviri erukukwe uye asimbise chikonzero tisati tasarudza kurapa."
      ]
    },
    "weevil": {
      "name": "Kukuvara kunogona kuva kwechipuka chinodya makukwe",
      "look": "Rukukwe runoita semifananidzo yakanzi yakukuvadzwa necoco kana weevil. Mufananidzo uyu haugoni kuziva rudzi rwechipembenene.",
      "actions": [
        "Kumbirai mukuru wekuridzira kuti atarise rukukwe rwakukuvara nezvipembenene zviri pachirimwa tisati tasarudza kurapa."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Tsvagai chimiro che KEPHIS pahari yembeu.",
    "stepScratch": "Kwenyai chimiro kuti muone kodhi.",
    "stepText": "Tumirai kodhi neSMS ku{shortCode}. Hazvidhuri.",
    "result": "KEPHIS inopindura kuti mbeu chaiyo here. Kodhi chaiyo haipi humbowo hwekuti mbeu yakachengetwa zvakanaka.",
    "coverage": "Izvi zvinoshanda pambeu dzakasimbiswa dzinotengeswa mumapaketi. Michero yemunzvimbo yemiche kazhinji haina chimiro, saka bvunzai mukuru wenyu wemunda nezvayo.",
    "noContact": "Bvunzai mukuru wenyu wemunda kuti mungaziva sei kuti paketi yembeu chaiyo."
  },
  "phoneGreeting": "Mhoro, ndini Leaf Doctor. Ndinobatsira nemiti yekofi yakarwara, uye munogona kutaura neni nemutauro wenyu. Munoona chii pamakukwe ekofi yenyu?"
});

export default snText;
