// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const soText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Caleemahaagu way caafimaad qabaan",
    "headlineSpray": "{name}: ilaali caleemaha caafimaadka qaba oo nadiifi",
    "headlinePrune": "{name}: nadiifi oo gooy",
    "headlineMonitor": "{name}: sii daawo",
    "headlineAskOfficer": "{name}: weydii sarkaalkaaga beeraha inuu hubiyo",
    "headlineNotSure": "Abku ma hubo. Caleemahan tus sarkaalkaaga beeraha",
    "headlineMightBe": "Waxaa laga yaabaa inuu yahay {name}, laakiin lama xaqiijin. U tus sarkaal beeraha",
    "headlineRetake": "Qaad sawirro ka cad oo caleemo badan ah",
    "retakeDaylight": "U dhaaf iftiinka maalinta, ma aha hooska aadka u dhuuban ama qorraxda tooska ah.",
    "retakeSteady": "Taleefanka degan hayso ilaa caleentu ay cadaato.",
    "retakeFillFrame": "Hal caleen ku buuxi sawirka.",
    "sendToOfficer": "Kiiskan u dir sarkaalka beeraha ee ururkaaga oo SMS ah, ama caleemaha ku tus si toos ah.",
    "rainReason": "Roob ayaa da'ay {n} ee 7-dii maalmood ee la soo dhaafay agtaada ({source}). Cimilada qoyan waxay ka dhigtaa bahda in ay si degdeg ah u fido.",
    "labelRate": "Isticmaal qadarka ku qoran sumadda alaabta.",
    "elseBerryDisease": "Cudurka midhaha bunka: eeg haddii midhuhu leeyihiin tabaryo madow oo hoos u dhacsan.",
    "elseBerryBorer": "Gooryaanka midhaha bunka: raadi god yaryar oo midhaha ku jira.",
    "elseWilt": "Engegidda bunka: laamo dhan oo engegaya oo dhimanaya.",
    "elseNutrition": "Ciid xun ama nafaqo la'aan: huruud geedka oo dhan ah.",
    "smsDecisionSpray": "Go'aan: ilaali caleemaha caafimaadka qaba oo isticmaal naxaas sida qadarka sumadda, oo nadiifi. Mar kale hubi {days} maalmood kadib.",
    "smsDecisionPrune": "Go'aan: gooy oo nadiifi. Mar kale hubi {days} maalmood kadib.",
    "smsDecisionMonitor": "Go'aan: sii daawo. Mar kale hubi {days} maalmood kadib.",
    "smsDecisionCallOfficer": "Go'aan: caleemaha tus sarkaalkaaga beeraha."
  },
  "diseases": {
    "cercospora": {
      "name": "Dhibcaha indhaha bunni",
      "look": "Dhibco goobaaban oo bunni ah, inta badan dusha sare ee caleenta, oo leh bartamaha cawlan-caddaan iyo giraan bunni madow ah, badanaa leh xaglo huruud ah. Dhibcuhu waa 5 ilaa 15 mm balac, waxayna isku soo biirin karaan tabaryo waaweyn oo dhintay. Midhuhu waxay yeeshaan tabaryo madow oo hoos u dhacsan, waxayna bislaadaan goor hore.",
      "tellApart": "Dhibcaha indhaha bunni waxay leeyihiin giraan bunni ah oo qalalan oo bartamaha cawlan leh, ma laha budo oranji ah, bahduna waxay leedahay budo oranji ah hoosteeda.",
      "actions": [
        "Geedaha si wanaagsan u quudi, gaar ahaan nitrogen iyo potassium. Quudin wanaagsan badanaa waxay xakamaysaa cudurkan.",
        "Dhig hooskaas yar, xakamee haramaha, oo gooy si hawadu u socoto oo caleemuhu u engegaan.",
        "Gooynta kadib, qaad ama dub caleemaha iyo midhaha. Ha ugu tuurin geedaha agtooda.",
        "Beerta nuurseriga, abuurka iska durki oo dub abuurka leh dhibco bunni ah oo giraan leh.",
        "Haddii uu xun yahay, fungicide naxaas ah ayaa ilaalin kara caleemaha caafimaadka qaba. Marka hore weydii sarkaalkaaga ballaarinta."
      ],
      "urgencyReason": "Inta badan waxay daciifisaa geedaha cadaadiska haysta, badanaa way fiicnaataa marka quudinta iyo hooska la hagaajiyo."
    },
    "healthy": {
      "name": "Caleen bun caafimaad qabta",
      "look": "Caleen caafimaad qabta waa dhalaalaysaa, ugxan-qaab ah oo af leh, cagaar madow oo isku mid ah, dusha sare iyo hoosteba dhibco, budo, god ama god-god la'aan.",
      "actions": [
        "Gooy oo dhig hooskaas yar iyo haramo yar si caleemuhu dhaqso ugu engegaan.",
        "Geedaha ku quudi digaag-bax ama bacriminta isku-dheelitiran, gaar ahaan nitrogen iyo potassium.",
        "Caleemaha iyo hoosta caleemaha hubi toddobaad kasta ama labadii toddobaad si aad goor hore u ogaato bahda ama caleen-ceyriyaha."
      ]
    },
    "miner": {
      "name": "Caleen-ceyriyaha bunka",
      "look": "Waddooyin jaalle ah oo qalloocan ayaa ka muuqda caleenta gudaheeda, waxayna isu beddelaan tabaryo bunni ah oo dhintay oo aan siman dusha sare. Haddii aad caleenta laabto, maqaarka khafiifka ah ee tabarta ka sarreeya ayaa kala go'a, waxaad gudaha ka heli kartaa gooryaan yar oo muuqda. Weerarro culus ayaa caleemaha ka dhigaya inay da'aan.",
      "tellApart": "Tabaryaha caleen-ceyriyuhu waa bokhsado waraaq u eg oo gooryaan ku jiro oo marka la laabo kala go'a, halka dhibcaha indhaha bunni ay yihiin giraan goobaaban oo nadiif ah oo aan kala go'in.",
      "actions": [
        "Tabaryaha bunni ah laab oo ka raadi gooryaan nool, gaar ahaan xilliga qalalan.",
        "Ilaali cadowga dabiiciga ah sida shumbureyaasha yaryar iyo quraanjada adigoo haynaya hooska isku dhafan oo iska ilaalinaya buufin aan loo baahnayn.",
        "Si dhow u daawo geedaha yar yar iyo nuurseriyada, oo tabaryaha hore goor hore ka saar.",
        "Haddii dawo cayayaan loo baahdo, weydii sarkaalkaaga ballaarinta waa kee alaab sharci ah oo ammaan ah dalkaaga."
      ],
      "urgencyReason": "Weerarro culus ayaa keena caleemo da'a oo hoos u dhiga dalagga, kuwa ugu xun waa xilliyada qalalan ee kulul."
    },
    "phoma": {
      "name": "Dhibcaha caleenta Phoma",
      "look": "Dhibco bunni madow ilaa madow ah oo ilaa 2 cm balac ah oo ku yaal caleemaha da'da weyn, oo bartamaha ka khafiifsan iyo cidhifka ka madow. Cidhifyada gaagaaban ee dhirta yar yar waa madoobaadaan oo qalalaan, ubaxyadu way dhiman karaan, midhuhuna way da'aan. Dhaawacu wuxuu ka bilaabmi karaa cidhifka ama dhinaca caleenta.",
      "tellApart": "Phoma sidoo kale waxay dishaa cidhifyada dhirta yar yar iyo ubaxyada meelaha sare ee qabow ee dabaysha leh, halka dhibcaha indhaha bunni ay ku hadhaan dhibco giraan leh oo aan cidhifyada engejin.",
      "actions": [
        "Meelaha dabaysha leh ku beer dabayl-celiyayaal. Dhaawaca dabayshu wuxuu gelinayaa fangas.",
        "Gooy oo burburi laamaha qalalan iyo midhaha engegay, oo gooy si hawadu caleemaha u engejiso.",
        "Geedaha ku quudi bacriminta isku-dheelitiran, gaar ahaan nitrogen iyo potassium.",
        "Xilliyada qabow ee dabaysha leh, ku buufi fungicide naxaas ah intaan cudurku soo muuqan. Waqtiga weydii sarkaalkaaga ballaarinta."
      ],
      "urgencyReason": "Meelaha sare ee qabow ee dabaysha leh waxay dili kartaa laamo iyo ubaxyo oo dhimi karta dalagga 15 ilaa 43 boqolkiiba."
    },
    "rust": {
      "name": "Bahda caleenta bunka",
      "look": "Dhibco yaryar oo jaalle khafiif ah ayaa ka muuqda dusha sare ee caleenta. Hoostooda, dhibic kastaa waxay leedahay budo jaalle ilaa oranji madow ah oo farta ku dhegta. Dhibcaha da'da weyn bartamahooda way bunni noqdaan caleemuhuna waxay da'aan goor hore. Badanaa wuxuu ka bilaabmaa caleemaha hoose ee geedka.",
      "tellApart": "Bahdu waxay leedahay budo oranji ah hoosta caleenta, halka dhibcaha indhaha bunni ay leeyihiin giraan bunni ah oo qalalan oo bartamaha cawlan-caddaan leh, budana ma laha.",
      "actions": [
        "Si joogto ah hubi hoosta caleemaha hoose. Goor hore ogaanshaha ayaa ugu muhiimsan.",
        "Ka jeex oo dub ama ku aaso caleemaha iyo laamaha leh dhibco oranji ah.",
        "Gooy oo yaree hooska iyo haramaha si hawadu u socoto oo caleemuhu si dhaqso ah u engegaan.",
        "Geedaha ku quudi digaag-bax ama bacriminta isku-dheelitiran. Geedaha daciifka ah ayaa si ka daran loo dhaawacaa.",
        "Ku buufi fungicide naxaas ah sida copper hydroxide dusha sare iyo hoosta caleemaha inta ka yar 5 boqolkiiba caleemaha ay buka. Naxaasku wuxuu ilaaliyaa caleemaha caafimaadka qaba laakiin ma bogsiiyo kuwa buka. Waqtiga weydii sarkaalkaaga ballaarinta.",
        "Beerid cusub, weydii sarkaalkaaga ballaarinta noocyada ka caabiya bahda sida noocyada Catimor ama Sarchimor."
      ],
      "urgencyReason": "Si degdeg ah ayay ugu fidaa geedaha iyo beeraha, khasaaruhuna noocyada u nugul waxay gaari karaan 30 ilaa 80 boqolkiiba."
    },
    "mites": {
      "name": "Dhaawac fiidmeer ee suurtagal ah",
      "look": "Sawirku wuxuu u eg yahay caleemo bun ah oo loo calaamadeeyay dhaawac fiidmeer. Calaamado la mid ah waxay yeelan karaan sababo kale, sidaas darteed kani waa isku dhac suurtagal ah.",
      "actions": [
        "Weydii sarkaalka ballaarinta inuu hubiyo labada dhinac ee caleenta oo xaqiijiyo sababta intaadan dawo dooran."
      ]
    },
    "weevil": {
      "name": "Dhaawac cayayaan caleemo cuna oo suurtagal ah",
      "look": "Caleentu waxay u eg tahay sawirro loo calaamadeeyay dhaawac coco ama weevil. Sawirkan ma garan karo nooca cayayaanka.",
      "actions": [
        "Weydii sarkaalka ballaarinta inuu hubiyo caleenta dhaawacantay iyo cayayaanka dhirta ku jira intaadan dawo dooran."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Ka raadi sumadda KEPHIS ee bakaylka abuurka.",
    "stepScratch": "Sumadda xoq si koodhka u muuqdo.",
    "stepText": "Koodhka u dir {shortCode} qoraal ahaan. Waa bilaash.",
    "result": "KEPHIS waxay ku jawaabtaa inay abuurku dhab yahay iyo in kale. Koodh dhab ah ma caddeeyo in abuurka si wanaagsan loo keydiyay.",
    "coverage": "Tani waxay ku shaqeysaa abuur la shahaadeeyay oo baakado lagu iibiyo. Abuurka nuurseriga badanaa sumad ma laha, sidaas darteed ka weydii sarkaalkaaga beeraha.",
    "noContact": "Weydii sarkaalkaaga beeraha sida loo hubiyo in bakaylka abuurku dhab yahay."
  },
  "phoneGreeting": "Salaan, waxaan ahay Leaf Doctor. Waxaan caawiyaa dhirta bunka ee buka, waxaadna kala hadli kartaa luqaddaada. Maxaad ku aragtaa caleemaha bunkaaga?"
});

export default soText;
