// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const svText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Dina blad ser friska ut",
    "headlineSpray": "{name}: skydda friska blad och städa",
    "headlinePrune": "{name}: städa och beskär",
    "headlineMonitor": "{name}: fortsätt att hålla uppsikt",
    "headlineAskOfficer": "{name}: be din rådgivare titta på det",
    "headlineNotSure": "Appen är inte säker. Visa de här bladen för din rådgivare",
    "headlineMightBe": "Det kan vara {name}, men det är inte bekräftat. Visa en rådgivare",
    "headlineRetake": "Ta tydligare foton av fler blad",
    "retakeDaylight": "Gå ut i dagsljus, inte i djup skugga eller starkt solljus.",
    "retakeSteady": "Håll telefonen stilla tills bladet ser skarpt ut.",
    "retakeFillFrame": "Fyll bilden med ett enda blad.",
    "sendToOfficer": "Skicka det här ärendet med sms till kooperativets rådgivare, eller visa bladen på plats.",
    "rainReason": "Det regnade {n} av de senaste 7 dagarna nära dig ({source}). Blött väder gör att rost sprids snabbare.",
    "labelRate": "Använd den dos som står på produktens etikett.",
    "elseBerryDisease": "Kaffebärssjuka: titta efter mörka insjunkna fläckar på bären.",
    "elseBerryBorer": "Kaffebärsborre: titta efter små hål i bären.",
    "elseWilt": "Kaffevissnesjuka: hela grenar som vissnar och dör.",
    "elseNutrition": "Dålig jord eller brist på näring: gulnande över hela trädet.",
    "smsDecisionSpray": "Beslut: skydda friska blad med koppar enligt dosen på etiketten och städa. Kontrollera igen om {days} dagar.",
    "smsDecisionPrune": "Beslut: beskär och städa. Kontrollera igen om {days} dagar.",
    "smsDecisionMonitor": "Beslut: fortsätt hålla uppsikt. Kontrollera igen om {days} dagar.",
    "smsDecisionCallOfficer": "Beslut: visa bladen för din rådgivare."
  },
  "diseases": {
    "cercospora": {
      "name": "Brunögonfläck",
      "look": "Runda bruna fläckar, mest på bladets ovansida, med gråvit mitt och en mörkbrun ring, ofta med en gul kant utanför. Fläckarna är 5 till 15 mm breda och kan växa ihop till stora döda partier. Bären får mörka insjunkna fläckar och mognar för tidigt.",
      "tellApart": "Brunögonfläck har torra bruna ringar med blekgrå mitt och inget orange pulver, medan rost har orange pulver på undersidan.",
      "actions": [
        "Göd träden väl, särskilt med kväve och kalium. God näring håller ofta sjukdomen i schack.",
        "Ha lätt skugga, håll efter ogräs och beskär så att luften rör sig och bladen torkar.",
        "Efter beskärning ska du bära bort eller bränna blad och bär. Lägg dem inte i hög mot träden.",
        "I plantskolan ska du ha plantorna med mellanrum och bränna plantor med bruna ringfläckar.",
        "Om det är illa kan ett kopparbaserat svampmedel skydda friska blad. Fråga först din rådgivare."
      ],
      "urgencyReason": "Den försvagar mest stressade träd och blir oftast bättre när näring och skugga är ordnade."
    },
    "healthy": {
      "name": "Friskt kaffeblad",
      "look": "Ett friskt blad är blankt, ovalt och spetsigt, jämnt mörkgrönt, utan fläckar, pulver, hål eller gångar på ovansidan eller undersidan.",
      "actions": [
        "Beskär och ha lätt skugga och lite ogräs så att bladen torkar snabbt.",
        "Göd träden med stallgödsel eller balanserat gödsel, särskilt med kväve och kalium.",
        "Titta på bladen och deras undersidor varje eller varannan vecka för att upptäcka rost eller bladminerare tidigt."
      ]
    },
    "miner": {
      "name": "Kaffebladminerare",
      "look": "Bleka gula slingrande gångar syns inne i bladet och blir ojämna bruna döda fläckar på ovansidan. Om du viker bladet lossnar det tunna ytskiktet över fläcken, och du kan hitta en liten genomskinlig larv inuti. Kraftiga angrepp får bladen att falla av.",
      "tellApart": "Minerarens fläckar är pappersliknande blåsor med en larv inuti som lossnar när man viker dem, medan brunögonfläck är en prydlig rund ring som inte lossnar.",
      "actions": [
        "Vik de bruna fläckarna och leta efter levande larver, särskilt under torrperioden.",
        "Skydda naturliga fiender som små steklar och myror genom att ha blandad skugga och undvika onödig besprutning.",
        "Håll noga uppsikt över unga träd och plantskolor och ta bort de första fläckarna tidigt.",
        "Om ett insektsmedel behövs, fråga din rådgivare vilken produkt som är lagligt och säker i ditt land."
      ],
      "urgencyReason": "Kraftiga angrepp gör att bladen faller och skörden minskar, värst under torra heta perioder."
    },
    "phoma": {
      "name": "Phoma-bladfläck",
      "look": "Mörkbruna till svarta fläckar upp till 2 cm breda på äldre blad, med ljusare mitt och mörkare kant. Spetsarna på unga skott blir svarta och torkar, blommor kan dö och bär faller av. Skadan kan börja vid bladspetsen eller bladkanten.",
      "tellApart": "Phoma dödar också spetsarna på unga skott och blommor i kalla, blåsiga högländer, medan brunögonfläck förblir ringfläckar och inte torkar ut skottspetsarna.",
      "actions": [
        "Plantera vindskydd där det blåser mycket. Vindskador släpper in svampen.",
        "Beskär bort och förstör torkade skott och intorkade bär, och beskär så att luften kan torka bladen.",
        "Göd träden med balanserat gödsel, särskilt med kväve och kalium.",
        "Under kalla blåsiga säsonger ska du spruta ett kopparbaserat svampmedel innan sjukdomen dyker upp. Fråga din rådgivare när det ska göras."
      ],
      "urgencyReason": "I kalla blåsiga högländer kan den döda skott och blommor och minska skörden med 15 till 43 procent."
    },
    "rust": {
      "name": "Kaffebladrost",
      "look": "Små bleka gula fläckar syns på bladets ovansida. På undersidan har varje fläck ett lager gult till mörkorange pulver som går att gnugga av med fingret. Gamla fläckar blir bruna i mitten och bladen faller av för tidigt. Det börjar oftast på trädets nedre blad.",
      "tellApart": "Rost har orange pulver på bladets undersida, medan brunögonfläck har torra bruna ringar med gråvit mitt och inget pulver.",
      "actions": [
        "Titta ofta på undersidan av de nedre bladen. Det är viktigast att upptäcka det tidigt.",
        "Plocka av och bränn eller gräv ner blad och grenar med orange fläckar.",
        "Beskär och gallra skugga och ogräs så att luften rör sig och bladen torkar fortare.",
        "Göd träden med stallgödsel eller balanserat gödsel. Svaga träd drabbas hårdare.",
        "Spruta ett kopparbaserat svampmedel som kopparhydroxid på bladens ovansida och undersida så länge färre än 5 procent av bladen är sjuka. Koppar skyddar friska blad men botar inte sjuka. Fråga din rådgivare när det ska göras.",
        "Vid nyplantering ska du fråga din rådgivare om rostresistenta sorter, till exempel av typen Catimor eller Sarchimor."
      ],
      "urgencyReason": "Den sprids snabbt mellan träd och gårdar, och förlusterna på mottagliga sorter kan nå 30 till 80 procent."
    },
    "mites": {
      "name": "Möjlig skada av kvalster",
      "look": "Bilden liknar kaffeblad som har märkts som kvalsterskadade. Liknande märken kan ha andra orsaker, så det här är en möjlig träff.",
      "actions": [
        "Be en rådgivare titta på båda sidorna av bladet och bekräfta orsaken innan du väljer behandling."
      ]
    },
    "weevil": {
      "name": "Möjlig skada av skadedjur som gnager på blad",
      "look": "Bladet liknar bilder som har märkts som skada av coco eller vivel. Det här fotot kan inte avgöra vilken insektsart det är.",
      "actions": [
        "Be en rådgivare titta på det skadade bladet och på insekter på plantan innan du väljer behandling."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Hitta KEPHIS-klistermärket på fröpåsen.",
    "stepScratch": "Skrapa på klistermärket så att koden syns.",
    "stepText": "Sms:a koden till {shortCode}. Det är gratis.",
    "result": "KEPHIS svarar och säger om fröet är äkta. En äkta kod bevisar inte att fröet har förvarats bra.",
    "coverage": "Det här fungerar för certifierat frö som säljs i påsar. Plantor från plantskola har oftast inget klistermärke, så fråga din rådgivare om dem.",
    "noContact": "Fråga din rådgivare hur du kontrollerar om en fröpåse är äkta."
  },
  "phoneGreeting": "Hej, det här är Leaf Doctor. Jag hjälper till med sjuka kaffeplantor, och du kan prata med mig på ditt eget språk. Vad ser du på dina kaffeblad?"
});

export default svText;
