// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const tetText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Ita-nia tahan sira haree saudavel",
    "headlineSpray": "{name}: proteje tahan saudavel no hamoos",
    "headlinePrune": "{name}: hamoos no tesi",
    "headlineMonitor": "{name}: kontinua haree",
    "headlineAskOfficer": "{name}: husu ofisiál terenu atu verifika",
    "headlineNotSure": "Aplikasaun la certu. Hatudu tahan sira ne'e ba ofisiál terenu",
    "headlineMightBe": "Karik {name}, maibé seidauk konfirma. Hatudu ba ofisiál terenu",
    "headlineRetake": "Foti retratu klaru liu husi tahan barak liu",
    "retakeDaylight": "Muda ba naroman loron nian, la'ós iha see todan ka loro-matan direta.",
    "retakeSteady": "Kaer telemovel hakmatek to'o tahan haree klaru.",
    "retakeFillFrame": "Kobre ekran ho tahan ida.",
    "sendToOfficer": "Haruka kazu ne'e ba ofisiál terenu kooperativa liu husi SMS, ka hatudu tahan sira ho pesoál.",
    "rainReason": "Udan monu iha loron {n} husi loron 7 ikus besik Ita ({source}). Udan halo ferrugem fahe lalais.",
    "labelRate": "Uza dozajen ne'ebé hakerek iha etiketa produtu.",
    "elseBerryDisease": "Moras fuan kafé: haree fuan atu hetan fatin nakukun ne'ebé tun ba laran.",
    "elseBerryBorer": "Hamlaha fuan kafé: buka kuak ki'ik iha fuan.",
    "elseWilt": "Kafé maran: ramin tomak maran no mate.",
    "elseNutrition": "Rai aat ka falta nutrisaun: ai-hun tomak sai kinur.",
    "smsDecisionSpray": "Desizaun: proteje tahan saudavel ho tembaga tuir dozajen etiketa no hamoos. Verifika fali iha loron {days}.",
    "smsDecisionPrune": "Desizaun: tesi no hamoos. Verifika fali iha loron {days}.",
    "smsDecisionMonitor": "Desizaun: kontinua haree. Verifika fali iha loron {days}.",
    "smsDecisionCallOfficer": "Desizaun: hatudu ba ofisiál terenu."
  },
  "diseases": {
    "cercospora": {
      "name": "Marka matan kór marrom",
      "look": "Marka kabuar kór marrom, liu-liu iha tahan leten, ho klaran kór sinza-mutin no kolar marrom nakukun, dala barak ho kinur iha liman. Marka ne'e luan 5 to'o 15 mm no bele hamutuk sai fatin mate boot. Fuan hetan marka nakukun ne'ebé tun ba laran no nuur molok tempu.",
      "tellApart": "Marka matan kór marrom iha sirkulu maran kór marrom ho klaran sinza kláru no la iha pó laranja, maibé ferrugem iha pó laranja iha tahan okos.",
      "actions": [
        "Fó han di'ak ba ai-hun sira, liu-liu nitrojéniu no potásiu. Han di'ak dala barak kontrola moras ne'e.",
        "Husik see kiik, kontrola ai-rai, no tesi atu anin pasa no tahan maran lalais.",
        "Hafoin tesi, lori tahan no fuan ba mesak ka sunu. Labele hatún hamutuk besik ai-hun.",
        "Iha viveiru, fahe di'ak ai-oan sira no sunu ai-oan ne'ebé iha marka marrom ho sirkulu.",
        "Se aat, fungisida tembaga bele proteje tahan saudavel. Husu uluk ba ofisiál extensaun."
      ],
      "urgencyReason": "Liu-liu hamamar ai-hun ne'ebé susar no normalmente di'ak liu bainhira han no see hadi'a."
    },
    "healthy": {
      "name": "Tahan kafé saudavel",
      "look": "Tahan saudavel nakdoko, oval no tarutu, matak nakukun hanesan, la iha marka, pó, kuak ka tunel iha leten no okos.",
      "actions": [
        "Tesi no husik see kiik no ai-rai ki'ik atu tahan maran lalais.",
        "Fó han ba ai-hun ho adubu animál ka adubu ne'ebé baruk, liu-liu nitrojéniu no potásiu.",
        "Verifika tahan no sira-nia okos kada semana ida ka rua atu hetan ferrugem sedu."
      ]
    },
    "miner": {
      "name": "Hamlaha tahan kafé nia laran",
      "actions": [
        "Dobra fatin marrom sira atu buka ulat moris, liu-liu iha tempu maran.",
        "Proteje inimigu naturál sira husi insetu ne'e liu husi mantein see ne'ebé mistura no la sprai la presiza.",
        "Haree didi'ak ai-hun foin moris no viveiru, no hasai marka dahuluk sedu.",
        "Se presiza insetisida, husu ofisiál extensaun produtu ida ne'ebé legál no seguru iha Ita-nia nasaun."
      ],
      "urgencyReason": "Ataka todan halo tahan monu no hamenus produsaun, aat liu iha tempu maran manas."
    },
    "phoma": {
      "name": "Marka tahan Phoma",
      "look": "Marka marrom nakukun to'o metan ne'ebé luan to'o 2 cm iha tahan tuan, ho klaran naroman liu no ninin nakukun liu. Ponta ramin foun sai metan no maran, funan bele mate, no fuan monu. Estragu bele hahú husi ponta ka ninin tahan.",
      "tellApart": "Phoma mós oho ponta ramin foun no funan iha foho malirin ho anin, maibé marka matan kór marrom hela hanesan marka ho sirkulu no la halo ponta ramin maran.",
      "actions": [
        "Kuda ai-hun atu taka anin iha fatin ne'ebé anin makaas. Estragu husi anin husik fungu tama.",
        "Tesi no sunu ramin maran no fuan maran, no tesi atu anin bele maran tahan.",
        "Fó han ba ai-hun ho adubu ne'ebé baruk, liu-liu nitrojéniu no potásiu.",
        "Iha tempu malirin ho anin, sprai fungisida tembaga molok moras mosu. Husu ofisiál extensaun kona-ba tempu."
      ],
      "urgencyReason": "Iha foho malirin ho anin bele oho ramin no funan no hamenus produsaun husi 15 to'o 43 persentu."
    },
    "rust": {
      "name": "Ferrugem tahan kafé",
      "look": "Marka kinur kláru ki'ik hatudu iha tahan leten. Iha okos, marka ida-idak iha pó kór kinur to'o laranja nakukun ne'ebé tuur iha liman. Marka tuan sai marrom iha klaran no tahan monu sedu. Dala barak hahú iha tahan sira iha ai-hun nia okos.",
      "tellApart": "Ferrugem iha pó laranja iha tahan okos, maibé marka matan kór marrom iha sirkulu marrom maran ho klaran sinza-mutin no la iha pó.",
      "actions": [
        "Verifika tahan okos nian okos dala barak. Hetan sedu importante liu.",
        "Hasai no sunu ka rai tahan no ramin ne'ebé iha marka laranja.",
        "Tesi no hamenus see no ai-rai atu anin pasa no tahan maran lalais.",
        "Fó han ba ai-hun ho adubu animál ka adubu ne'ebé baruk. Ai-hun fraku hetan kona makaas liu.",
        "Sprai fungisida tembaga hanesan copper hydroxide iha tahan leten no okos bainhira tahan moras seidauk to'o persentu 5. Tembaga proteje tahan saudavel maibé la hamoos ne'ebé moras ona. Husu ofisiál extensaun kona-ba tempu.",
        "Ba kuda foun, husu ofisiál extensaun kona-ba varietadi ne'ebé reziste ba ferrugem hanesan tipu Catimor ka Sarchimor."
      ],
      "urgencyReason": "Fahe lalais entre ai-hun no to'os, no perda ba varietadi ne'ebé sensível bele to'o persentu 30 to'o 80."
    },
    "mites": {
      "name": "Posivel estragu husi mite",
      "look": "Imajen ne'e hanesan tahan kafé ne'ebé marka ho estragu mite. Marka hanesan bele iha kauza seluk, tanba ne'e ida ne'e posivel de'it.",
      "actions": [
        "Husu ofisiál extensaun atu haree tahan sorin rua no konfirma kauza molok hili tratamentu."
      ]
    },
    "weevil": {
      "name": "Posivel estragu husi insetu han tahan",
      "look": "Tahan ne'e hanesan imajen ne'ebé marka ho estragu insetu. Retratu ida ne'e la bele hatene espésie insetu.",
      "actions": [
        "Husu ofisiál extensaun atu haree tahan ne'ebé estraga no insetu ruma iha ai-hun molok hili tratamentu."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Buka adezivu KEPHIS iha pakote fini.",
    "stepScratch": "Hasai kamada raspa iha adezivu atu hatudu kódigu.",
    "stepText": "Haruka kódigu ba {shortCode}. Gratis.",
    "result": "KEPHIS responde atu hatete se fini ne'e orijinál. Kódigu orijinál la prova katak fini rai di'ak.",
    "coverage": "Ida ne'e serbisu ba fini sertifikadu ne'ebé faan iha pakote. Ai-oan viveiru normalmente la iha adezivu, tanba ne'e husu ofisiál terenu kona-ba sira.",
    "noContact": "Husu ofisiál terenu oinsá atu verifika se pakote fini orijinál."
  },
  "phoneGreeting": "Bondia, ha'u Leaf Doctor. Ha'u ajuda ho ai-hun kafé moras, no Ita bele ko'alia ho ha'u iha Ita-nia lian rasik. Saida mak Ita haree iha tahan kafé?"
});

export default tetText;
