// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const trText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Yapraklarınız sağlıklı görünüyor",
    "headlineSpray": "{name}: sağlıklı yaprakları koruyun ve temizlik yapın",
    "headlinePrune": "{name}: temizlik yapın ve budayın",
    "headlineMonitor": "{name}: izlemeye devam edin",
    "headlineAskOfficer": "{name}: saha görevlinizden kontrol etmesini isteyin",
    "headlineNotSure": "Uygulama emin değil. Bu yaprakları saha görevlinize gösterin",
    "headlineMightBe": "{name} olabilir ama doğrulanmadı. Bir saha görevlisine gösterin",
    "headlineRetake": "Daha çok yaprağın daha net fotoğraflarını çekin",
    "retakeDaylight": "Koyu gölgeye ya da doğrudan güneşe değil, gün ışığına geçin.",
    "retakeSteady": "Yaprak net görünene kadar telefonu sabit tutun.",
    "retakeFillFrame": "Çerçeveyi tek bir yaprakla doldurun.",
    "sendToOfficer": "Bu kaydı kooperatifinizin saha görevlisine SMS ile gönderin ya da yaprakları yüz yüze gösterin.",
    "rainReason": "Yakınınızda son 7 günün {n} gününde yağmur yağdı ({source}). Yağışlı hava pası daha hızlı yayar.",
    "labelRate": "Ürün etiketindeki dozu kullanın.",
    "elseBerryDisease": "Kahve meyve hastalığı: meyvelerde koyu, çökük lekelere bakın.",
    "elseBerryBorer": "Kahve meyve kurdu: meyvelerde küçük deliklere bakın.",
    "elseWilt": "Kahve solgunluğu: bütün dalların solup ölmesi.",
    "elseNutrition": "Zayıf toprak veya beslenme: bütün ağaçta sararma.",
    "smsDecisionSpray": "Karar: sağlıklı yaprakları etiket dozunda bakırla koruyun ve temizlik yapın. {days} gün sonra yeniden kontrol edin.",
    "smsDecisionPrune": "Karar: budayın ve temizlik yapın. {days} gün sonra yeniden kontrol edin.",
    "smsDecisionMonitor": "Karar: izlemeye devam edin. {days} gün sonra yeniden kontrol edin.",
    "smsDecisionCallOfficer": "Karar: saha görevlinize gösterin."
  },
  "diseases": {
    "cercospora": {
      "name": "Kahverengi göz lekesi",
      "look": "Yuvarlak kahverengi lekeler; çoğunlukla yaprağın üst yüzünde, ortası gri-beyaz, çevresinde koyu kahverengi halka vardır ve sık sık sarı bir hale ile çevrilidir. Lekeler 5 ile 15 mm genişliğindedir ve birleşerek büyük ölü alanlar oluşturabilir. Meyvelerde koyu çökük lekeler olur ve meyveler çok erken olgunlaşır.",
      "tellApart": "Kahverengi göz lekesinde kuru kahverengi halkalar ve soluk gri bir orta vardır, turuncu toz yoktur; pasta ise altta turuncu toz bulunur.",
      "actions": [
        "Ağaçları iyi besleyin, özellikle azot ve potasyum verin. İyi beslenme bu hastalığı çoğu zaman kontrol altına alır.",
        "Hafif gölge bırakın, yabani otları temizleyin ve hava dolaşsın, yapraklar kurusun diye budayın.",
        "Budamadan sonra yaprakları ve meyveleri uzağa taşıyın veya yakın. Ağaçların dibine yığmayın.",
        "Fidanlıkta fidanları birbirinden uzak dikin ve halkalı kahverengi lekeli fidanları yakın.",
        "Hastalık ağırsa bakırlı bir mantar ilacı sağlıklı yaprakları koruyabilir. Önce ziraat danışmanınıza sorun."
      ],
      "urgencyReason": "Çoğunlukla stresli ağaçları zayıflatır ve beslenme ile gölge düzeltilince genellikle düzelir."
    },
    "healthy": {
      "name": "Sağlıklı kahve yaprağı",
      "look": "Sağlıklı yaprak parlak, oval ve sivri uçludur, rengi eşit koyu yeşildir; üstünde ve altında leke, toz, delik veya tünel yoktur.",
      "actions": [
        "Yaprakların çabuk kuruması için budayın, gölgeyi hafif tutun ve yabani otları bastırın.",
        "Ağaçları gübre veya dengeli bir gübre ile besleyin, özellikle azot ve potasyum verin.",
        "Pas veya yaprak galeri güvesini erken yakalamak için yaprakları ve alt yüzlerini bir iki haftada bir kontrol edin."
      ]
    },
    "miner": {
      "name": "Kahve yaprak galeri güvesi",
      "look": "Yaprağın içinde soluk sarı, kıvrımlı izler görünür ve üst yüzde düzensiz kahverengi ölü alanlara dönüşür. Yaprağı bükerseniz lekenin üstündeki ince üst deri soyulur ve içinde küçük, şeffaf bir kurt bulabilirsiniz. Ağır saldırılarda yapraklar dökülür.",
      "tellApart": "Galeri güvesi lekeleri içinde kurt olan, bükülünce soyulan kağıt gibi kabarcıklardır; kahverengi göz lekesi ise soyulmayan düzgün, yuvarlak bir halkadır.",
      "actions": [
        "Canlı kurt bulmak için kahverengi lekeleri bükün, özellikle kurak mevsimde.",
        "Karışık gölge tutarak ve gereksiz ilaçlamadan kaçınarak küçük yaban arıları ve karıncalar gibi doğal düşmanları koruyun.",
        "Genç ağaçları ve fidanlıkları yakından izleyin ve ilk lekeleri erken temizleyin.",
        "Böcek ilacı gerekirse ülkenizde hangi ürünün yasal ve güvenli olduğunu ziraat danışmanınıza sorun."
      ],
      "urgencyReason": "Ağır saldırılar yaprak dökülmesine ve verim kaybına yol açar, en kötüsü kurak sıcak dönemlerdedir."
    },
    "phoma": {
      "name": "Phoma yaprak lekesi",
      "look": "Yaşlı yapraklarda 2 cm genişliğe kadar koyu kahverengiden siyaha lekeler; ortası daha açık, kenarı daha koyudur. Genç sürgünlerin uçları kararır ve kurur, çiçekler ölebilir ve meyveler dökülür. Hasar yaprak ucundan veya kenarından başlayabilir.",
      "tellApart": "Phoma soğuk ve rüzgarlı yaylalarda genç sürgün uçlarını ve çiçekleri de öldürür; kahverengi göz lekesi ise halkalı lekeler olarak kalır ve sürgün uçlarını kurutmaz.",
      "actions": [
        "Rüzgarlı bölgelerde rüzgar perdesi dikin. Rüzgar hasarı mantarın girmesine yol açar.",
        "Kurumuş sürgünleri ve kuruyup büzülmüş meyveleri kesip yok edin ve hava yaprakları kurutsun diye budayın.",
        "Ağaçları dengeli gübre ile besleyin, özellikle azot ve potasyum verin.",
        "Soğuk ve rüzgarlı mevsimlerde hastalık görülmeden önce bakırlı bir mantar ilacı püskürtün. Zamanlama için ziraat danışmanınıza sorun."
      ],
      "urgencyReason": "Soğuk ve rüzgarlı yaylalarda sürgünleri ve çiçekleri öldürebilir ve verimi yüzde 15 ile 43 arasında düşürebilir."
    },
    "rust": {
      "name": "Kahve yaprak pası",
      "look": "Yaprağın üst yüzünde küçük soluk sarı lekeler görünür. Altta her lekede, parmağınıza bulaşan sarıdan koyu turuncuya bir toz tabakası vardır. Eski lekelerin ortası kahverengiye döner ve yapraklar erken dökülür. Genellikle ağacın alt yapraklarında başlar.",
      "tellApart": "Pasta yaprağın alt yüzünde turuncu toz vardır; kahverengi göz lekesinde ise kuru kahverengi halkalar ve gri-beyaz bir orta vardır, toz yoktur.",
      "actions": [
        "Alt yaprakların alt yüzünü sık sık kontrol edin. Erken yakalamak en önemlisidir.",
        "Turuncu lekeli yaprakları ve dalları toplayıp yakın veya gömün.",
        "Hava dolaşsın ve yapraklar daha çabuk kurusun diye gölgeyi ve yabani otları azaltıp budayın.",
        "Ağaçları gübre veya dengeli gübre ile besleyin. Zayıf ağaçlar daha ağır hasar görür.",
        "Yaprakların yüzde 5 kadarından azı hastayken, bakır hidroksit gibi bakırlı bir mantar ilacını yaprakların üst ve alt yüzlerine püskürtün. Bakır sağlıklı yaprakları korur ama hasta olanları iyileştirmez. Zamanlama için ziraat danışmanınıza sorun.",
        "Yeni dikim için pasa dayanıklı çeşitleri, örneğin Catimor veya Sarchimor tipleri hakkında ziraat danışmanınıza sorun."
      ],
      "urgencyReason": "Ağaçlar ve çiftlikler arasında hızla yayılır; hassas çeşitlerde kayıplar yüzde 30 ile 80'e ulaşabilir."
    },
    "mites": {
      "name": "Olası akar zararı",
      "look": "Görüntü, akar zararı olarak etiketlenmiş kahve yapraklarına benziyor. Benzer izlerin başka nedenleri olabilir, bu yüzden bu olası bir eşleşmedir.",
      "actions": [
        "Tedaviye karar vermeden önce bir ziraat danışmanından yaprağın her iki yüzünü incelemesini ve nedeni doğrulamasını isteyin."
      ]
    },
    "weevil": {
      "name": "Olası yaprak kemiren zararlı hasarı",
      "look": "Yaprak, koko veya hortumlu böcek zararı olarak etiketlenmiş görüntülere benziyor. Bu fotoğraf böcek türünü belirleyemez.",
      "actions": [
        "Tedaviye karar vermeden önce bir ziraat danışmanından zarar görmüş yaprağı ve bitkideki böcekleri incelemesini isteyin."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Tohum paketinde KEPHIS etiketini bulun.",
    "stepScratch": "Kodu görmek için etiketi kazıyın.",
    "stepText": "Kodu {shortCode} numarasına mesajla gönderin. Ücretsizdir.",
    "result": "KEPHIS tohumun orijinal olup olmadığını yanıtlar. Orijinal bir kod, tohumun iyi saklandığını kanıtlamaz.",
    "coverage": "Bu, paketlerde satılan sertifikalı tohum için çalışır. Fidanlık fidanlarında genellikle etiket olmaz, bu yüzden onları saha görevlinize sorun.",
    "noContact": "Bir tohum paketinin orijinal olup olmadığının nasıl kontrol edileceğini saha görevlinize sorun."
  },
  "phoneGreeting": "Merhaba, burası Leaf Doctor. Hasta kahve bitkilerinde yardımcı oluyorum ve benimle kendi dilinizde konuşabilirsiniz. Kahve yapraklarınızda ne görüyorsunuz?"
});

export default trText;
