// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const woText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Seeni xob dañu mel ni ñu wér",
    "headlineSpray": "{name}: aar xob yu wér te setal",
    "headlinePrune": "{name}: setal te gor garab yi",
    "headlineMonitor": "{name}: wéyal seetaan",
    "headlineAskOfficer": "{name}: laajal ofisye bu tool bi mu seet",
    "headlineNotSure": "App bi gëmul ko ci lu mat. Wone xob yii ofisye bu tool bi",
    "headlineMightBe": "Mën na doon {name}, waaye dëggal nañu ko ba tey. Wone ko ofisye bu tool",
    "headlineRetake": "Jël foto yu gën a leer ci xob yu gën a bari",
    "retakeDaylight": "Dem ci leeru bëccëg, du ci ker gu lëndëm walla naar bu ñuul.",
    "retakeSteady": "Jàppal telefon bi ba mu taxaw ba xob bi leer.",
    "retakeFillFrame": "Fees ekran bi ak benn xob.",
    "sendToOfficer": "Yónnee mbir mii ci ofisye bu tool bu koperatif bi ci SMS, wala wone xob yi ci gëstu.",
    "rainReason": "Taw na ci {n} ci 7 fan yu mujj ci seen wet ({source}). Jamono ju mouille day tax rust di law gën a gaaw.",
    "labelRate": "Jëfandikoo ñaata ñu bind ci etiket bu jumtukaay bi.",
    "elseBerryDisease": "Feebaru doomu kafe: seetal doom yi ndax am nañu tàcc yu ñuul yu suuxat.",
    "elseBerryBorer": "Bët-bët bu doomu kafe: wër pax yu ndaw ci doom yi.",
    "elseWilt": "Kafe bu lax: car yépp dañuy lax te dee.",
    "elseNutrition": "Suuf su bon wala ñam amul: garab bépp dafay mboq.",
    "smsDecisionSpray": "Dogal: aar xob yu wér ak kuwiwr ci ñaata ñu bind ci etiket bi te setal. Seetaat ci {days} fan.",
    "smsDecisionPrune": "Dogal: gor te setal. Seetaat ci {days} fan.",
    "smsDecisionMonitor": "Dogal: wéyal seetaan. Seetaat ci {days} fan.",
    "smsDecisionCallOfficer": "Dogal: wone ofisye bu tool bi."
  },
  "diseases": {
    "cercospora": {
      "name": "Tàcc bu xonq-ñuul bu mel ni bët",
      "look": "Tàcc yu wërsëg yu xonq-ñuul, ci kaw xob bi lu ëpp, ak digg bu wërëm-weex ak wërsëg bu ñuul-ñuul, bu bari am safara mboq. Tàcc yi yaatu nañu 5 ba 15 mm te mën nañu booloo ba di tàcc yu rëy yu dee. Doom yi am nañu tàcc yu ñuul yu suuxat te di ñor ci gaaw.",
      "tellApart": "Tàcc bu xonq-ñuul bu mel ni bët am wërsëg yu xonq-ñuul yu wow ak digg bu wërëm-weex te amul pudar bu soxor, waaye rust am pudar bu soxor ci suuf.",
      "actions": [
        "May garab yi ñam bu baax, rawatina nitrogène ak potasiyom. Ñam bu baax day yombal feebar bii.",
        "Bàyyi ker gu woyof, kontrole toxu ak gor garab yi ngir ngelaw dox te xob yi wow.",
        "Gannaaw gor, yóbbu xob yi ak doom yi ci kanam wala lakk leen. Bu ngeen leen tëral ci wetu garab yi.",
        "Ci pepinyer, bàyyil ndaw yi ay yoonu digg te lakk yi am tàcc yu xonq-ñuul yu wërsëg.",
        "Su feebar bi metti, fongisid bu kuwiwr mën na aar xob yu wér. Laajal ofisye bu ndimbalu mbay bi balaa."
      ],
      "urgencyReason": "Dafay tax garab yi sonn di jafe-jafe, te dina gën a baax su ñam ak ker yi baaxee."
    },
    "healthy": {
      "name": "Xobu kafe bu wér",
      "look": "Xob bu wér dafa lëndëm, wërsëg ak bopp bu ñuul, xaar bu dëgër te bokk, amul tàcc, pudar, pax wala tunel ci kaw walla ci suuf.",
      "actions": [
        "Gor garab yi te bàyyi ker gu woyof te wàññi toxu ngir xob yi wow ci gaaw.",
        "May garab yi sàmbu wala engrè bu yemu, rawatina nitrogène ak potasiyom.",
        "Seetal xob yi ak seen suuf bis bu nekk ba ñaar ayubés ngir fekk rust wala bët-bët bu xob ci jëkk."
      ]
    },
    "miner": {
      "name": "Bët-bët bu xobu kafe",
      "look": "Yoon yu weex-mboq yu dox di wër feeñ ci biir xob bi te di tàcc yu xonq-ñuul yu dee ci kaw. Su ngeen sëngee xob bi, ker bu yaatul bi ci kaw tàcc bi dafay tàggu te mën ngeen fekk ab ndaw bu ndaw bu leer ci biir. Weer yu metti dañuy tax xob yi di tooñ.",
      "tellApart": "Tàcc yu bët-bët yi mel nañu ni mbuq yu kayit ak ndaw ci biir te di tàggu su ñu sëngee, waaye tàcc bu xonq-ñuul bu mel ni bët wërsëg bu rafet la te du tàggu.",
      "actions": [
        "Sëng tàcc yu xonq-ñuul yi ngir wër ndaw yu dund, rawatina ci jamono ju wow.",
        "Aar sa nawle yu mag yu natiirel ni way yu ndaw ak sunguf ci bàyyi ker gu jaxasoo te bañ a def pëndëraas yu amul solo.",
        "Seetal garab yu ndaw yi ak pepinyer yi bu baax te dindi tàcc yi njëkk ci gaaw.",
        "Su ñu soxlaa pestisid, laajal ofisye bu ndimbalu mbay bi ban jumtukaay mooy yoon ak jàmm ci seen réew."
      ],
      "urgencyReason": "Weer yu metti day tax xob yi di tooñ te dootu am lekk, rawatina ci jamono ju wow ju tàng."
    },
    "phoma": {
      "name": "Tàcc bu xobu Phoma",
      "look": "Tàcc yu xonq-ñuul ba ñuul, ba 2 cm, ci xob yu magg, ak digg bu leer ak ewel bu ñuul. Bopp yu car yu ndaw dañuy ñuul te wow, tooñ yi mën nañu dee te doom yi di tooñ. Yaafus bi mën na tambali ci boppu xob wala ewel.",
      "tellApart": "Phoma it dafay rey bopp yu car yu ndaw ak tooñ ci tund yu sedd te am ngelaw, waaye tàcc bu xonq-ñuul bu mel ni bët day des ni tàcc yu wërsëg te du wowal bopp yu car.",
      "actions": [
        "Ji garab yu aar ngelaw ci bërëb yu am ngelaw. Yaafus bu ngelaw day yëgël fongus bi mu dugg.",
        "Gor te jeexal car yu wow ak doom yu wow, te gor ngir ngelaw wowal xob yi.",
        "May garab yi engrè bu yemu, rawatina nitrogène ak potasiyom.",
        "Ci jamono ju sedd te am ngelaw, pëndëraas fongisid bu kuwiwr balaa feebar bi feeñ. Laajal ofisye bu ndimbalu mbay bi ci jamono bi."
      ],
      "urgencyReason": "Ci tund yu sedd te am ngelaw mën na rey car ak tooñ te wàññi dund bi ci 15 ba 43 ci téeméer."
    },
    "rust": {
      "name": "Rustu xobu kafe",
      "look": "Tàcc yu ndaw yu weex-mboq feeñ nañu ci kaw xob bi. Ci suuf, tàcc bu nekk am pudar bu mboq ba soxor bu ñuul bu di nootu ci baaraamu loxo. Tàcc yu mag dañuy xonq ci digg te xob yi di tooñ ci gaaw. Dafay tambali ci xob yu suuf yu garab bi.",
      "tellApart": "Rust am pudar bu soxor ci suuf xob bi, waaye tàcc bu xonq-ñuul bu mel ni bët am wërsëg yu xonq-ñuul yu wow ak digg bu wërëm-weex te amul pudar.",
      "actions": [
        "Seetal suufu xob yu suuf yi yoon yu bari. Fekk ko ci jëkk mooy li gën a am solo.",
        "Gàddu xob yi ak car yi am tàcc yu soxor te lakk leen wala suul leen.",
        "Gor te wàññi ker gi ak toxu ngir ngelaw dox te xob yi gën a wow ci gaaw.",
        "May garab yi sàmbu wala engrè bu yemu. Garab yu naqari dañu leen di gën a dal.",
        "Pëndëraas fongisid bu kuwiwr ni kuwiwr idroksid ci kaw ak suufu xob yi ba kaw xob yi yu feebar ëppul 5 ci téeméer. Kuwiwr day aar xob yu wér waaye du wéral yu feebar. Laajal ofisye bu ndimbalu mbay bi ci jamono bi.",
        "Ngir jiyu bu bees, laajal ofisye bu ndimbalu mbay bi ci xeet yi dékkal rust ni Catimor wala Sarchimor."
      ],
      "urgencyReason": "Dafay law ci gaaw diggante garab yi ak tool yi, te wàññeku yi ci xeet yu mën a feebar mën nañu àgg 30 ba 80 ci téeméer."
    },
    "mites": {
      "name": "Mën na doon yaafus bu mit",
      "look": "Nataal bi mel na ni xobu kafe yu ñu tudde yaafus bu mit. Màndarga yu mel noonu mën nañu am yeneen sabab, kon loolu mooy lu mën a am.",
      "actions": [
        "Laajal ofisye bu ndimbalu mbay bi mu seet ñaari wet yu xob bi te dëggal sabab bi balaa ñu tànn safaan."
      ]
    },
    "weevil": {
      "name": "Mën na doon yaafus bu jaan bu lekk xob",
      "look": "Xob bi mel na ni nataal yu ñu tudde yaafus bu koko wala wivil. Foto bii mënul xam xeetu jaan bi.",
      "actions": [
        "Laajal ofisye bu ndimbalu mbay bi mu seet xob bi yaafus ak jaan yi ci garab bi balaa ñu tànn safaan."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Wër sticker bu KEPHIS ci sakoosu pepp bi.",
    "stepScratch": "Raxas sticker bi ngir feeñal kod bi.",
    "stepText": "Yónnee kod bi ci {shortCode}. Dafa free.",
    "result": "KEPHIS dina tontu ne pepp bi dëgg la am déedéet. Kod bu dëgg du won ne pepp bi dencu woon na bu baax.",
    "coverage": "Loolu day liggéey ci pepp bu ñu seetlu bu ñuy jaay ci sakoos. Garab yu ndaw yu pepinyer amul sticker ci lu ëpp, kon laajal ofisye bu tool bi ci ñoom.",
    "noContact": "Laajal ofisye bu tool bi ni ñuy seet ndax sakoosu pepp dëgg la."
  },
  "phoneGreeting": "Nanga def, Leaf Doctor mooy wax. Dama ngi ndimbalu ci garab yu kafe yu feebar, te mën ngeen wax ak man ci seen làkk. Lan ngeen gis ci xob yu kafe yi?"
});

export default woText;
