// Machine translation by Claude Sonnet 5.5, 2026-10-04. No native speaker has checked it yet.
// Generated by scripts/translations/importTranslations.ts. Edit a line here, or re-run the import.
import type { AdviceTranslation } from "../adviceText.ts";

const zuText = (): AdviceTranslation => ({
  "copy": {
    "headlineHealthy": "Amakhasi akho abukeka ephilile",
    "headlineSpray": "{name}: vikela amakhasi aphilile ubuye uhlanze",
    "headlinePrune": "{name}: hlanza uphinde unqume",
    "headlineMonitor": "{name}: qhubeka ubheka",
    "headlineAskOfficer": "{name}: cela isikhulu sakho sasensimini sihlole",
    "headlineNotSure": "I-app ayiqinisekile. Khombisa lawa makhasi esikhulwini sakho sasensimini",
    "headlineMightBe": "Kungaba ngu-{name}, kodwa akuqinisekisiwe. Khombisa isikhulu sasensimini",
    "headlineRetake": "Thatha izithombe ezicacile zamakhasi amaningi",
    "retakeDaylight": "Hamba ekukhanyeni kwemini, hhayi emthunzini onzima noma elangeni eliqondile.",
    "retakeSteady": "Bamba ifoni iqine kuze kube ikhasi libukeka licacile.",
    "retakeFillFrame": "Gcwalisa ifreyimu ngekhasi elilodwa.",
    "sendToOfficer": "Thumela lolu daba esikhulwini sakho sasensimini sekhoperethivu nge-SMS, noma ukhombise amakhasi uqobo.",
    "rainReason": "Kunethe imvula ezinsukwini ezingu-{n} kwezi-7 zokugcina eduze kwakho ({source}). Isimo sezulu esimanzi senza i-rust isakazeke ngokushesha.",
    "labelRate": "Sebenzisa inani elibhalwe kulebuli yomkhiqizo.",
    "elseBerryDisease": "Isifo sezithelo zikakhofi: bheka izithelo uthole amabala amnyama acwiliswe phakathi.",
    "elseBerryBorer": "Isilokazana esiboboza izithelo zikakhofi: funa imigodi emincane ezithelweni.",
    "elseWilt": "Ukubunga kukakhofi: amagatsha aphelele abunga futhi afe.",
    "elseNutrition": "Inhlabathi ebuthakathaka noma ukungondleki: ukuphuzi esihlahleni sonke.",
    "smsDecisionSpray": "Isinqumo: vikela amakhasi aphilile ngethusi ngenani elibhalwe kulebuli uhlanze. Hlola futhi ezinsukwini ezingu-{days}.",
    "smsDecisionPrune": "Isinqumo: nquma uhlanze. Hlola futhi ezinsukwini ezingu-{days}.",
    "smsDecisionMonitor": "Isinqumo: qhubeka ubheka. Hlola futhi ezinsukwini ezingu-{days}.",
    "smsDecisionCallOfficer": "Isinqumo: khombisa isikhulu sakho sasensimini."
  },
  "diseases": {
    "cercospora": {
      "name": "Ibala lehlo elinsundu",
      "look": "Amabala ayindilinga ansundu, ikakhulukazi ngaphezulu kwekhasi, anesikhungo esimpunga-mhlophe nendandatho ensundu emnyama, ngokuvamile nomzimba ophuzi ozungezile. Amabala abanzi ngo-5 kuya ku-15 mm futhi angahlangana abe amabala amakhulu afile. Izithelo zithola amabala amnyama acwilisiwe futhi zivuthwa msinyane kakhulu.",
      "tellApart": "Ibala lehlo elinsundu linamasongo ansundu omile nesikhungo esimpunga esiphaphathekile futhi alinaphawuda we-orange, kuyilapho i-rust inophawuda we-orange ngaphansi.",
      "actions": [
        "Ondla izihlahla kahle, ikakhulukazi ngenayitrojini nepotassium. Ukondla kahle kuvame ukulawula lesi sifo.",
        "Gcina umthunzi ophansi, lawula ukhula, unqume ukuze umoya ugeleze namakhasi omile.",
        "Ngemva kokunquma, thutha amakhasi nezithelo ulibhale kude noma ulishise. Ungazibeki zibe yinqwaba eduze kwezihlahla.",
        "Enkulisa, hlukanisa izithombo kude bese ushisa izithombo ezinamabala ansundu anamasongo.",
        "Uma kubi, umuthi wokubulala isikhunta onethusi ungavikela amakhasi aphilile. Buza kuqala isikhulu sakho sokweluleka ngezolimo."
      ],
      "urgencyReason": "Ikakhulukazi ibuthakathakisa izihlahla ezicindezelekile futhi ivame ukuthuthuka uma ukondla nomthunzi kulungisiwe."
    },
    "healthy": {
      "name": "Ikhasi likakhofi eliphilile",
      "look": "Ikhasi eliphilile liyakhazimula, liyi-oval futhi linenhloko ebukhali, liluhlaza okuvuthiwe okufanayo, alinamabala, uphawuda, imigodi noma izimbobo ngaphezulu noma ngaphansi.",
      "actions": [
        "Nquma futhi ugcine umthunzi ophansi nokhula luphansi ukuze amakhasi omiswe ngokushesha.",
        "Ondla izihlahla ngomquba noma umanyolo olinganiselayo, ikakhulukazi inayitrojini nepotassium.",
        "Hlola amakhasi nangaphansi kwawo njalo ngeviki noma emavikini amabili ukuze ubambe i-rust noma i-leaf miner kusenesikhathi."
      ]
    },
    "miner": {
      "name": "I-leaf miner kakhofi",
      "look": "Imizila ephuzi ebomvana ejikelezayo ivela ngaphakathi kwekhasi bese iba amabala afile ansundu angalingani ngaphezulu. Uma ugoba ikhasi, isikhumba esincane ngaphezulu kwebala siyaphindwa ucwebuke futhi ungathola umbungu omncane obonakalayo ngaphakathi. Ukuhlasela okukhulu kwenza amakhasi awe.",
      "tellApart": "Amabala e-miner ayizibhamuza ezinjengephepha ezinombungu ngaphakathi ezicwebuka lapho zigotshwa, kuyilapho ibala lehlo elinsundu liyindandatho ehlanzekile engacwebuki.",
      "actions": [
        "Goba amabala ansundu ukuze uthole imibungu ephilayo, ikakhulukazi ngesikhathi somoya omile.",
        "Vikela izitha zemvelo ezifana nezinyosi ezincane nezintuthwane ngokugcina umthunzi osingethwe nokugwema ukufafaza okungadingekile.",
        "Qaphela izihlahla ezincane nezikhungo zezithombo kahle futhi ususe amabala okuqala kusenesikhathi.",
        "Uma umuthi wezinambuzane udingeka, buza isikhulu sakho sokweluleka ngezolimo ukuthi yimuphi umkhiqizo ongaphansi komthetho futhi ophephile ezweni lakho."
      ],
      "urgencyReason": "Ukuhlasela okukhulu kubangela ukuwa kwamakhasi nokwehla kwesivuno, okubi kakhulu ezikhathini ezomile nezishisayo."
    },
    "phoma": {
      "name": "Ibala lekhasi le-Phoma",
      "look": "Amabala ansundu amnyama kuya kokumnyama abanzi ngokufika ku-2 cm emakhasini amadala, anesikhungo esikhanyayo nomphetho omnyama. Amathiphu amahlumela amancane aba mnyama futhi ayoma, izimbali zingafa, nezithelo ziyawa. Umonakalo ungaqala emphethweni noma esihlokweni sekhasi.",
      "tellApart": "I-Phoma ibuye ibulale amathiphu amahlumela amancane nezimbali ezindaweni eziphakeme ezibandayo nezinomoya, kuyilapho ibala lehlo elinsundu lihlala njengamabala anamasongo futhi alomisi amathiphu amahlumela.",
      "actions": [
        "Tshala izihlahla zokuvimba umoya ezindaweni ezinomoya. Umonakalo womoya uvumela isikhunta singene.",
        "Nquma futhi ubhubhise amahlumela omisiwe nezithelo ezifiphele, futhi unqume ukuze umoya womise amakhasi.",
        "Ondla izihlahla ngomanyolo olinganiselayo, ikakhulukazi inayitrojini nepotassium.",
        "Ezinkathini ezibandayo ezinomoya, fafaza umuthi wokubulala isikhunta onethusi ngaphambi kokuba isifo sivele. Buza isikhulu sakho sokweluleka ngezolimo ngesikhathi."
      ],
      "urgencyReason": "Ezindaweni eziphakeme ezibandayo nezinomoya ingabulala izimpande nezimbali futhi inciphise isivuno ngamaphesenti angu-15 kuya kwangu-43."
    },
    "rust": {
      "name": "I-rust yekhasi likakhofi",
      "look": "Amabala amancane aphuzi aphaphathekile abonakala ngaphezulu kwekhasi. Ngaphansi, ibala ngalinye linendawo yophawuda ophuzi kuya ku-orange omnyama ohlikihlwa emunweni wakho. Amabala amadala aba nsundu maphakathi futhi amakhasi awa msinyane. Ngokuvamile iqala emakhasini aphansi esihlahla.",
      "tellApart": "I-rust inophawuda we-orange ngaphansi kwekhasi, kuyilapho ibala lehlo elinsundu linamasongo ansundu omile nesikhungo esimpunga-mhlophe futhi alinaphawuda.",
      "actions": [
        "Hlola ngaphansi kwamakhasi aphansi kaningi. Ukuyibamba kusenesikhathi kubaluleke kakhulu.",
        "Khipha amakhasi namagatsha anamabala e-orange uwashise noma uwangcwabe.",
        "Nquma futhi unciphise umthunzi nokhula ukuze umoya ugeleze namakhasi omile ngokushesha.",
        "Ondla izihlahla ngomquba noma umanyolo olinganiselayo. Izihlahla ezibuthakathaka zishaywa kakhulu.",
        "Fafaza umuthi wokubulala isikhunta onethusi njenge-copper hydroxide ngaphezulu nangaphansi kwamakhasi kuyilapho ngaphansi kwamaphesenti angu-5 amakhasi egula. Ithusi livikela amakhasi aphilile kodwa akwelapha amakhasi agulayo. Buza isikhulu sakho sokweluleka ngezolimo ngesikhathi.",
        "Ekutshaleni okusha, buza isikhulu sakho sokweluleka ngezolimo ngezinhlobo ezimelana ne-rust ezifana nezinhlobo ze-Catimor noma ze-Sarchimor."
      ],
      "urgencyReason": "Isakazeka ngokushesha phakathi kwezihlahla nezinsimu, futhi ukulahlekelwa ezinhlobweni ezithambile kungafinyelela kumaphesenti angu-30 kuya kwangu-80."
    },
    "mites": {
      "name": "Umonakalo okungenzeka we-mite",
      "look": "Isithombe sifana namakhasi kakhofi alebulwe ngomonakalo wezibungu zamaqhuqhuva. Izimpawu ezifanayo zingaba nezinye izimbangela, ngakho lokhu kungafana.",
      "actions": [
        "Cela isikhulu sokweluleka ngezolimo sihlole zombili izinhlangothi zekhasi siqinisekise imbangela ngaphambi kokukhetha ukwelashwa."
      ]
    },
    "weevil": {
      "name": "Umonakalo okungenzeka wesilokazana esidla amakhasi",
      "look": "Ikhasi lifana nezithombe ezilebulwe ngomonakalo we-coco noma we-weevil. Lesi sithombe asikwazi ukuhlonza uhlobo lwenambuzane.",
      "actions": [
        "Cela isikhulu sokweluleka ngezolimo sihlole ikhasi elonakele nanoma yiziphi izinambuzane esitshalweni ngaphambi kokukhetha ukwelashwa."
      ]
    }
  },
  "seedCheck": {
    "stepSticker": "Funa isitikha se-KEPHIS kuphakethe lembewu.",
    "stepScratch": "Khuhla isitikha ukuze ubone ikhodi.",
    "stepText": "Thumela ikhodi ku-{shortCode}. Ikhululekile.",
    "result": "I-KEPHIS iphendula ukuthi imbewu iyiyangempela yini. Ikhodi yangempela ayiboniseli ukuthi imbewu igcinwe kahle.",
    "coverage": "Lokhu kusebenza kwimbewu eqinisekisiwe etshengiswa emaphaketheni. Izithombo zasenkulisa zivamise ukungabi nasitikha, ngakho buza isikhulu sakho sasensimini ngazo.",
    "noContact": "Buza isikhulu sakho sasensimini ukuthi ungahlola kanjani ukuthi iphakethe lembewu liyiyangempela yini."
  },
  "phoneGreeting": "Sawubona, nginguLeaf Doctor. Ngisiza ngezitshalo zikakhofi ezigulayo, futhi ungakhuluma nami ngolimi lwakho. Yini oyibonayo emakhasini akho kakhofi?"
});

export default zuText;
