import type { DiseaseCatalog } from "./types.ts";

export const DISEASES: DiseaseCatalog = {
  mites: {
    key: "mites",
    name: "Possible mite damage",
    look: "The image resembles coffee leaves labelled with mite damage. Similar marks can have other causes, so this is a possible match.",
    symptomWords: [],
    actions: ["Ask an extension officer to inspect both sides of the leaf and confirm the cause before choosing a treatment."],
    urgency: "low",
    sources: ["https://data.mendeley.com/datasets/c5yvn32dzg/2"],
  },
  weevil: {
    key: "weevil",
    name: "Possible leaf-chewing pest damage",
    look: "The leaf resembles images labelled as coco or weevil damage. This photo cannot identify the insect species.",
    symptomWords: [],
    actions: ["Ask an extension officer to inspect the damaged leaf and any insects on the plant before choosing a treatment."],
    urgency: "low",
    sources: ["https://zenodo.org/records/22756170"],
  },
  rust: {
    key: "rust",
    name: "Coffee leaf rust",
    look: "Small pale yellow spots show on the top of the leaf. Underneath, each spot has a patch of yellow to dark orange powder that rubs off on your finger. Old spots turn brown in the middle and the leaves drop early. It usually starts on the lower leaves of the tree.",
    tellApart: "Rust has orange powder on the underside of the leaf, while brown eye spot has dry brown rings with a grey-white centre and no powder.",
    symptomWords: [
      "orange", "orange powder", "powder", "powdery", "rust", "rusty", "yellow spots",
      "yellow patches", "underside", "under the leaf", "bottom of leaf", "leaves falling",
      "leaf drop", "defoliation", "dusty", "orange dust", "yellow orange",
      "spots turning brown", "lower leaves", "rubs off",
    ],
    conditions: "Spreads fastest in warm, wet, humid weather, with rain carrying the spores. It is worse on crowded, poorly pruned, poorly fed trees and on trees carrying heavy crops.",
    actions: [
      "Check the underside of lower leaves often. Catching it early matters most.",
      "Pick off and burn or bury leaves and branches with orange spots.",
      "Prune and thin shade and weeds so air moves and leaves dry faster.",
      "Feed the trees with manure or balanced fertilizer. Weak trees get hit harder.",
      "Spray a copper fungicide such as copper hydroxide on tops and undersides of leaves while under about 5 percent of leaves are sick. Copper protects healthy leaves but does not cure sick ones. Ask your extension officer about timing.",
      "For new planting, ask your extension officer about rust-resistant varieties such as Catimor or Sarchimor types.",
    ],
    urgency: "high",
    urgencyReason: "It spreads quickly between trees and farms, and losses on susceptible varieties can reach 30 to 80 percent.",
    sources: [
      "https://blog.plantwise.org/2022/03/17/coffee-leaf-rust-spotting-and-managing-hemileia-vastatrix/",
      "https://www3.ctahr.hawaii.edu/oc/freepubs/pdf/PD-118.pdf",
      "https://www.ncipmc.org/communications/pest-alerts/coffee-leaf-rust/",
    ],
  },
  cercospora: {
    key: "cercospora",
    name: "Brown eye spot",
    look: "Round brown spots, mostly on the top of the leaf, with a grey-white centre and a dark brown ring, often with a yellow halo. Spots are 5 to 15 mm wide and can join into big dead patches. Berries get dark sunken blotches and ripen too early.",
    tellApart: "Brown eye spot has dry brown rings with a pale grey centre and no orange powder, while rust has orange powder underneath.",
    symptomWords: [
      "brown spots", "brown eye", "eye spot", "eyespot", "ring", "rings", "halo",
      "yellow halo", "grey center", "grey centre", "gray center", "white center",
      "round spots", "circular spots", "dark ring", "target", "iron spot", "spots on top",
      "upper side", "blotch", "berry spots", "sunken spots", "cherries ripen early",
      "premature ripening", "brown rings",
    ],
    conditions: "Worse on weak, underfed trees low in nitrogen and potassium, on trees stressed by drought, full sun or weeds, and in crowded nurseries.",
    actions: [
      "Feed the trees well, especially nitrogen and potassium. Good feeding often controls this disease.",
      "Keep light shade, control weeds, and prune so air moves and leaves dry.",
      "After pruning, carry away or burn leaves and berries. Do not pile them against the trees.",
      "In the nursery, space seedlings apart and burn seedlings with ringed brown spots.",
      "If it is bad, a copper fungicide can protect healthy leaves. Ask your extension officer first.",
    ],
    urgency: "medium",
    urgencyReason: "It mainly weakens stressed trees and usually improves once feeding and shade are fixed.",
    sources: [
      "https://www3.ctahr.hawaii.edu/oc/freepubs/pdf/PD-41.pdf",
      "https://apps.lucidcentral.org/ppp/text/web_full/entities/coffee_browneye_spot_142.htm",
      "https://www.hawaiicoffeeed.com/cercospora.html",
    ],
  },
  miner: {
    key: "miner",
    name: "Coffee leaf miner",
    look: "Pale yellow winding trails appear inside the leaf and turn into uneven brown dead patches on top. If you bend the leaf, the thin top skin over the patch peels apart and you can find a tiny see-through grub inside. Heavy attacks make leaves fall.",
    tellApart: "Miner patches are papery blisters with a grub inside that peel apart when bent, while brown eye spot is a neat round ring that does not peel.",
    symptomWords: [
      "worm", "grub", "larva", "caterpillar", "insect", "tunnel", "trail", "trails", "mine",
      "mines", "winding", "blister", "papery", "peeling", "peels", "irregular patches",
      "dead patches", "pale yellow trails", "bug", "moth", "dry season", "bend leaf",
      "inside the leaf",
    ],
    conditions: "Worse in the dry season and hot weather. Heavy spraying that kills its natural enemies makes it worse.",
    actions: [
      "Bend brown patches to look for live grubs, especially in the dry season.",
      "Protect natural enemies such as small wasps and ants by keeping mixed shade and avoiding needless spraying.",
      "Watch young trees and nurseries closely and remove the first patches early.",
      "If an insecticide is needed, ask your extension officer which product is legal and safe in your country.",
    ],
    urgency: "medium",
    urgencyReason: "Heavy attacks cause leaf fall and lower yield, worst in dry hot spells.",
    sources: [
      "https://pmc.ncbi.nlm.nih.gov/articles/PMC8707027/",
      "https://www.hawaiicoffeeed.com/coffee-leaf-miner---nko.html",
      "https://plantix.net/en/library/plant-diseases/600367/coffee-leaf-miner/",
    ],
  },
  phoma: {
    key: "phoma",
    name: "Phoma leaf spot",
    look: "Dark brown to black spots up to 2 cm wide on older leaves, with a lighter centre and darker edge. The tips of young shoots turn black and dry out, flowers can die, and berries drop. Damage can start at the leaf tip or edge.",
    tellApart: "Phoma also kills the tips of young shoots and flowers in cold, windy highlands, while brown eye spot stays as ringed spots and does not dry out shoot tips.",
    symptomWords: [
      "dry shoots", "shoot tips", "tip dieback", "dieback", "black tips", "dark spots",
      "black spots", "large spots", "big spots", "cold", "wind", "windy", "high altitude",
      "highland", "flowers dying", "flower drop", "berries dropping", "mummified berries",
      "dry branches", "leaf tip", "tip blight",
    ],
    conditions: "Worse in cool, humid, windy highlands above about 900 m and under about 20 C, especially in long wet spells.",
    actions: [
      "Plant windbreaks in windy areas. Wind damage lets the fungus in.",
      "Prune off and destroy dried shoots and mummified berries, and prune so air can dry the leaves.",
      "Feed the trees with balanced fertilizer, especially nitrogen and potassium.",
      "In cold windy seasons, spray a copper fungicide before the disease appears. Ask your extension officer for timing.",
    ],
    urgency: "medium",
    urgencyReason: "In cold windy highlands it can kill shoots and flowers and cut yield by 15 to 43 percent.",
    sources: [
      "https://revistacultivar.com/articles/phoma-spot-or-ascochyta-spot-of-coffee",
      "https://roastopedia.com/phoma-leaf-spot/",
    ],
  },
  healthy: {
    key: "healthy",
    name: "Healthy coffee leaf",
    look: "A healthy leaf is shiny, oval and pointed, an even dark green, with no spots, powder, holes or tunnels on top or underneath.",
    symptomWords: [
      "dark green", "shiny", "glossy", "healthy", "no spots", "clean", "smooth",
      "even colour", "no powder", "no holes", "looks good", "nothing wrong",
    ],
    actions: [
      "Prune and keep light shade and weeds down so leaves dry quickly.",
      "Feed trees with manure or balanced fertilizer, especially nitrogen and potassium.",
      "Check leaves and their undersides every week or two to catch rust or leaf miner early.",
    ],
    urgency: "none",
    sources: [
      "https://www3.ctahr.hawaii.edu/oc/freepubs/pdf/PD-41.pdf",
      "https://www3.ctahr.hawaii.edu/oc/freepubs/pdf/PD-118.pdf",
    ],
  },
};
